### DISCUSSION TITLE
Invitation via blueprint

### DISCUSSION THREAD

**Discussion by holmesb** [goauthentik/authentik#10041] [General]
Hi,

Anyone successfully created an invitation by blueprint? I can create via api fine using:

```
curl -L -X POST 'https://authentik.example.com/api/v3/stages/invitation/invitations/' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer <my_bearer_token>' --data-raw '{
  "name": "testinvite",
  "expires": "2024-06-10T08:21:27Z",
  "fixed_data": {},
  "single_use": true,
  "flow": "124946a2-62ec-47d0-bf0d-39871bfc7e5b"
}'
```
but if I try the same params in a blueprint :
```
version: 1
metadata:
  name: "testinvite"
entries:
  - model: authentik_stages_invitation.invitation
    identifiers:
      attributes:
        managed: "testinvite"
    attrs:
      name: "testinvite"
      expires: "2024-06-10T08:21:27Z"
      single_use: true
      flow: "124946a2-62ec-47d0-bf0d-39871bfc7e5b"
      fixed_data: {}
```
the blueprints webui page shows "error". 
Is there any way to get more info when a blueprint fails to apply than just "error"? I've increased log level to debug, but still no reason is logged on either the worker or server. Nothing in webui --> Events --> Logs either. That flow UUID is obtained by a:
```
curl -L -X GET 'https://authentik.example.com/api/v3/flows/instances/my-flow-slug/' -H 'Accept: application/json' -H 'Authorization: Bearer '<my_bearer_token>'
```
(I know I can get UUID using a yaml key, but I just want the simplest working code atm)
Any ideas? Diagnosing is made more difficult by the fact exporting to blueprints is currently [broken](https://github.com/goauthentik/authentik/issues/9430). I can create other types of resources using blueprints fine.

Thanks
