### DISCUSSION TITLE
Authentik logs only show addresses beginning with 172 when used with traefik

### DISCUSSION THREAD

**Discussion by S0ulf3re** [goauthentik/authentik#10510] [Q&A]
I recently setup Authentik with Traefik. However, my logs are only showing addresses from internal docker containers instead of actual user IP addresses. 
![image](https://github.com/user-attachments/assets/05d445b2-d115-45ce-ad7f-fd249a75b7bc)

I think that it might be something wrong with my traefik file for authentik I don't believe that it is properly forwarding the X-Forwarded-For headers

```
http:
################################################################
# Services configuration
################################################################
  services:
    authentik:
        loadBalancer:
          servers:
            - url: http://authentik-server:9000
################################################################
# Middleware configuration
################################################################
  middlewares:
    redirect-https:
      redirectScheme: 
        scheme: https
        permanent: true
################################################################
# Routers configuration
################################################################
  routers:
#region authentik
    authentik-http:
      entrypoints: web
      rule: Host(`sso.example.com`)
      service: authentik
      middlewares: redirect-https
    authentik:
      entrypoints: websecure
      rule: Host(`sso.example.com`)
      service: authentik
      tls:
        certresolver: myresolver
#endregion
```

Is there something that I can configure to make sure that the proper addresses are given?

**Comment by S0ulf3re** [comment]
This seems to have been fixed a bit by setting in the traefik config:

```
entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
        - "172.0.0.0/8"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - "172.0.0.0/8"
```
