### DISCUSSION TITLE
Authentik Embedded Outposts - Kubernetes Helm Chart Setup

### DISCUSSION THREAD

**Discussion by plsnotracking** [goauthentik/authentik#10556] [Q&A]
Hi team,

Hope y'all are doing well.

I deployed a fresh install of Authentik using PostgreSQL, and Redis.

I was trying to setup a Proxy Auth using the embedded outposts. It's a local Kubernetes cluster.

I'm having issues with 2 things

1. I don't see a dedicated service running for outposts yet.
2. When trying to save this settings from the admin dashboard, System -> Outposts Integration -> Create -> Kubernetes-service connection, no matter what I put it shows a failure status (screenshot attached)
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/85667b4d-fa30-4a58-a6b3-836a98d8de51">
<img width="948" alt="image" src="https://github.com/user-attachments/assets/6781e397-df26-40da-a559-ac164f1fce11">

Any suggestions are welcomed, thanks.

**Comment by hydazz** [comment]
I too face this conundrum
I've tried setting the serviceaccount
```
        serviceAccount:
            serviceAccountSecret:
                enabled: true
            fullnameOverride: authentik-sa
```
and also added a valid kubeconfig pointing to the serviceaccount (not required apparently) with no luck
