### DISCUSSION TITLE
Is there any official solution to avoid "auth_via": "unauthenticated", "domain_url": "<POD IP>"

### DISCUSSION THREAD

**Discussion by abhishek-ch** [goauthentik/authentik#11232] [General]
I've deployed Authentik and Ingress in k3s (on Hetzner). While the website is accessible and I can log in, I'm facing an issue when creating an OIDC provider. After filling in the details, clicking the "Finish" button doesn't trigger any action. In the worker logs, I'm seeing the following errors:

```
{"auth_via": "unauthenticated", "domain_url": "POD_IP", "event": "/-/health/ready/", "host": "POD_IP:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 5757, "remote": "10.244.1.1", "request_id": "cc9da6f15daa45eb894cdde091940f17", "runtime": 143, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2024-09-05T15:36:03.017508", "user": "", "user_agent": "kube-probe/1.30"}
{"auth_via": "unauthenticated", "domain_url": "POD_IP", "event": "/-/health/live/", "host": "POD_IP:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 6148, "remote": "10.244.1.1", "request_id": "cb45d897626d4430b768782a84523a77", "runtime": 120, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2024-09-05T15:36:12.990887", "user": "", "user_agent": "kube-probe/1.30"}
```

Here's the relevant part of my `values.yaml` file:

```
authentik:
    secret_key: "<>"
    error_reporting:
        enabled: true
    postgresql:
        host: "NEON TECH URL"
        name: "authentik"
        user: "blabla"
        password: "<>"

server:
    ingress:
        ingressClassName: nginx
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-dns01-issuer"
        hosts:
            - authentik.mywebsite.com
        tls:
           - secretName: authentik-tls-secret
             hosts:
               - "*.mywebsite.com"

postgresql:
    enabled: false
    auth:
        password: "ThisIsNotASecurePassword"

redis:
    enabled: true
```

I've tried adding DNS configurations in CoreDNS and various other approaches, but nothing has worked so far. Is there an official solution to this problem, or should I consider switching to a different setup that might work better?
