### DISCUSSION TITLE
How do I fix short "Registration failed" message in registration flow?

### DISCUSSION THREAD

**Discussion by OddMagnet** [goauthentik/authentik#11925] [Q&A]
The Flow I want:

1. User opens invitation link
2. Enters Username, Name, Email, Password x2
3. Sets up WebAuthn
4. Gets send a confirmation email
5. Clicks the link in the email
6. Is activated and logged in

What I currently have works for this, but there is a small cosmetic problem, after setting up WebAuthn and before the screen shows that an email has been sent you can briefly see: **Registration failed**

This is how my enrollment looks:
<img width="1082" alt="enrollment-stage-bindings" src="https://github.com/user-attachments/assets/fda941f4-080d-4d84-a3ee-7f39174fa8e4">

No policies attached.

And here's the exported flow
```
context: {}
entries:
- attrs:
    authentication: none
    compatibility_mode: true
    denied_action: message_continue
    designation: enrollment
    layout: stacked
    name: my-domain Enrollment Invitation Friends
    policy_engine_mode: any
    title: You are invited to my-domain.com
  conditions: []
  identifiers:
    pk: a33b90be-c8f9-4527-a1da-a045b7d3090c
    slug: my-domain-enrollment-invitation-friends
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs:
    field_key: username
    label: Username
    name: default-source-enrollment-field-username
    order: 100
    placeholder: Username
    required: true
    type: username
  conditions: []
  identifiers:
    pk: cc3308ca-366e-48db-9294-3b2cb6f6ebfd
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: name
    initial_value: "try:\n    return user.name\nexcept:\n    return ''"
    initial_value_expression: true
    label: Name
    name: default-user-settings-field-name
    order: 201
    placeholder: Name
    required: true
    type: text
  conditions: []
  identifiers:
    pk: ed8375a2-682b-4dcd-baee-0f105477dccf
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: password_repeat
    label: Password (repeat)
    name: initial-setup-field-password-repeat
    order: 301
    placeholder: Password (repeat)
    required: true
    type: password
  conditions: []
  identifiers:
    pk: 4ef85caa-a41e-4d4c-a726-66f1808443b9
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: email
    initial_value: "try:\n    return user.email\nexcept:\n    return ''"
    initial_value_expression: true
    label: Email
    name: default-user-settings-field-email
    order: 202
    placeholder: Email
    required: true
    type: email
  conditions: []
  identifiers:
    pk: 8d4c9be0-f597-4988-b17c-014e625ee38b
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: password
    label: Password
    name: initial-setup-field-password
    order: 300
    placeholder: Password
    required: true
    type: password
  conditions: []
  identifiers:
    pk: 534874ab-d51f-4cc9-9274-a9565338642e
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    amount_digits: 0
    amount_lowercase: 0
    amount_symbols: 2
    amount_uppercase: 0
    check_have_i_been_pwned: true
    check_static_rules: true
    check_zxcvbn: true
    error_message: Password needs to be at least 12 characters with at least 2 Symbols.
    hibp_allowed_count: 0
    length_min: 12
    name: Custom Password Complexity Policy
    password_field: password
    symbol_charset: '!\"#$%&''()*+,-./:;<=>?@[]^_`{|}~'
    zxcvbn_score_threshold: 2
  conditions: []
  identifiers:
    pk: 6d2bd739-2115-48d1-8062-9439b54c7f4d
  model: authentik_policies_password.passwordpolicy
  permissions: []
  state: present
- attrs: {}
  conditions: []
  identifiers:
    name: Custom Enrollment Invitation
    pk: 0aa9acc4-c55f-49a0-b820-54fbe8de0acd
  model: authentik_stages_invitation.invitationstage
  permissions: []
  state: present
- attrs:
    create_users_as_inactive: true
    create_users_group: c50a95f8-6532-42f1-a6c5-41f4df7b3918
    user_creation_mode: create_when_required
    user_type: external
  conditions: []
  identifiers:
    name: Custom Enrollment Invitation Write (Friends)
    pk: b23e0db3-f3f1-40c2-92e4-5c93e4030dda
  model: authentik_stages_user_write.userwritestage
  permissions: []
  state: present
- attrs:
    geoip_binding: no_binding
    network_binding: no_binding
    remember_me_offset: seconds=0
    session_duration: seconds=0
  conditions: []
  identifiers:
    name: default-source-enrollment-login
    pk: 72602fe5-84bd-44f0-8543-f8e9c7b43186
  model: authentik_stages_user_login.userloginstage
  permissions: []
  state: present
- attrs:
    fields:
    - cc3308ca-366e-48db-9294-3b2cb6f6ebfd
    - ed8375a2-682b-4dcd-baee-0f105477dccf
    - 4ef85caa-a41e-4d4c-a726-66f1808443b9
    - 8d4c9be0-f597-4988-b17c-014e625ee38b
    - 534874ab-d51f-4cc9-9274-a9565338642e
    validation_policies:
    - 6d2bd739-2115-48d1-8062-9439b54c7f4d
  conditions: []
  identifiers:
    name: default-source-enrollment-prompt
    pk: 30ef5beb-c144-4666-a3ff-9c5e4b0174db
  model: authentik_stages_prompt.promptstage
  permissions: []
  state: present
- attrs:
    configure_flow: 685e613e-46d9-41bb-8e45-c2f21c8ebee4
    friendly_name: FaceID, TouchID, Windows Hello, ...
    resident_key_requirement: preferred
    user_verification: preferred
  conditions: []
  identifiers:
    name: default-authenticator-webauthn-setup
    pk: 6f145570-877f-41ba-8155-5a561b630db7
  model: authentik_stages_authenticator_webauthn.authenticatorwebauthnstage
  permissions: []
  state: present
- attrs:
    activate_user_on_success: true
    from_address: system@authentik.local
    host: localhost
    port: 25
    subject: Account Confirmation
    template: email/account_confirmation.html
    timeout: 10
    token_expiry: 30
    use_global_settings: true
  conditions: []
  identifiers:
    name: Custom Email Account Confirmation
    pk: d86ed835-35de-4a97-a4c5-e323ade79227
  model: authentik_stages_email.emailstage
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 10
    pk: cbdb7ac0-a1a3-497c-b3db-51be8c1be351
    stage: 0aa9acc4-c55f-49a0-b820-54fbe8de0acd
    target: a33b90be-c8f9-4527-a1da-a045b7d3090c
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 20
    pk: 9cf88be6-3da5-40f7-9a85-ecc6b7172bb2
    stage: 30ef5beb-c144-4666-a3ff-9c5e4b0174db
    target: a33b90be-c8f9-4527-a1da-a045b7d3090c
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 30
    pk: 19d16d26-fca7-4b73-996e-435a8876cf0a
    stage: b23e0db3-f3f1-40c2-92e4-5c93e4030dda
    target: a33b90be-c8f9-4527-a1da-a045b7d3090c
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 40
    pk: d2551a4e-1182-41fb-9968-536c80f657b1
    stage: 6f145570-877f-41ba-8155-5a561b630db7
    target: a33b90be-c8f9-4527-a1da-a045b7d3090c
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 50
    pk: d6be2535-8815-4749-813e-1bc3cb9aec5d
    stage: d86ed835-35de-4a97-a4c5-e323ade79227
    target: a33b90be-c8f9-4527-a1da-a045b7d3090c
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 60
    pk: a8e2692a-5888-4925-aa78-7582482a9870
    stage: 72602fe5-84bd-44f0-8543-f8e9c7b43186
    target: a33b90be-c8f9-4527-a1da-a045b7d3090c
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2024-11-05 12:08:15.670488+00:00
version: 1
```
