### DISCUSSION TITLE
The client identifier (client_id) is missing or invalid.

### DISCUSSION THREAD

**Discussion by adoyle-h** [goauthentik/authentik#13760] [Q&A]
I'm using Proxy Provider with Forward Auth (domain level).  And deploy the proxy container with docker compose.

```
services:
    authentik_proxy:
        image: ghcr.io/goauthentik/proxy
        ports:
            - 9000:9000
            - 9443:9443
        environment:
            AUTHENTIK_HOST: https://your-authentik.tld
            AUTHENTIK_INSECURE: "false"
            AUTHENTIK_TOKEN: token-generated-by-authentik
```

When open my website in browser, it redirects to Authentik and show "The client identifier (client_id) is missing or invalid.".

![2025-04-03_16 40 31@2x](https://github.com/user-attachments/assets/93013f2c-817c-402a-9285-9a51f675658a)

How to fix this issue?
