### DISCUSSION TITLE
Feature request: Allow a custom Postgres schema

### DISCUSSION THREAD

**Discussion by madflow** [goauthentik/authentik#14147] [Ideas]
Drive-By Feature request ;)

Keycloak supports a custom Postgres schema. This can be defined for example in the env variable `      KC_DB_SCHEMA`.

In this repo I found https://github.com/goauthentik/authentik/blob/ba686f6a935544279b9a0851d28e9200ba5df70b/authentik/root/settings.py#L133 - but setting this variable in der `docker compose` deployment, resulted in the application not starting properly.

**Comment by rissson** [comment]
> resulted in the application not starting properly

Please elaborate

**Reply by madflow** [reply]
I think I tried this:

```yml
  authentik:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.2.4}
    command: server
    environment:
        AUTHENTIK_POSTGRESQL__DEFAULT_SCHEMA: authentik
```

and when starting the stack `/if/flow/initial-setup/` was always a 404.

When I reverted the schema change and tried again, everything was peachy. YEMD.
