### DISCUSSION TITLE
Cannot pass client's real ip through nginx reverse proxy

### DISCUSSION THREAD

**Discussion by netsho** [goauthentik/authentik#14157] [Q&A] [answered]
Hello,

I need your help on how to enable the passing of the client's real ip to Authentik. Right now, the client IP is the IP of the nginx reverse proxy.

Authentik is running as a podman container, and is behind nginx reverse proxy container. Everything is working LAN only, no exposition to the public.

I already tried multiple solutions i found on the authentik documentation (TRUSTED_PROXY_CIDRS) and other issues pointing to the same problem (https://github.com/goauthentik/authentik/issues/7216, https://github.com/goauthentik/authentik/issues/7504, https://github.com/goauthentik/authentik/issues/7219), but i couldn't resolve it. Your help is much appreciated.
This is my Authentik podman-compose of the server: 
```
 image: ghcr.io/goauthentik/server:2025.2.4
    container_name: authentik_server
    networks:
      - nginx-proxy-network
    restart: unless-stopped
    command: server
    environment:
      PUID: 1000
      PGID: 1000
      AUTHENTIK_REDIS__HOST: authentik_redis
      AUTHENTIK_POSTGRESQL__HOST: authentik_db
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: "10.89.0.0/24,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" # Tried multiple values here, none worked
      VIRTUAL_HOST: authentik.homelab.com
      CERT_NAME: homelab
    volumes:
      - /etc/authentik/config/media:/media
      - /etc/authentik/config/custom-templates:/templates
    env_file:
      - .env
    depends_on:
      authentik_db:
        condition: service_healthy
      authentik_redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1536M
          cpus: "1"
    tmpfs:
      - /tmp    # Directs temporary files to memory instead of disk
```
I'm using jwilder nginx reverse proxy image which generates automatically the nginx configuration. NGINX and Authentik Server are in the same podman network (nginx-proxy-network). I have verified against the documentation (https://docs.goauthentik.io/docs/install-config/reverse-proxy), and i don't see anything missing.
```
# authentik.homelab-services.com/
upstream authentik.homelab-services.com {
    # Container: authentik_server
    #     networks:
    #         nginx-proxy-network (reachable)
    #     IPv4 address: 
    #     IPv6 address: (none usable)
    #     exposed ports (first ten): (none)
    #     default port: 80
    #     using port: 9000
    server 10.89.0.11:9000; # Authentik server ip adress in the podman network subnet
    keepalive 2;
}
server {
    server_name authentik.homelab-services.com;
    access_log /var/log/nginx/access.log vhost;
    http2 on;
    listen 443 ssl ;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_certificate /etc/nginx/certs/homelab-services.crt;
    ssl_certificate_key /etc/nginx/certs/homelab-services.key;
    set $sts_header "";
    if ($https) {
        set $sts_header "max-age=31536000";
    }
    add_header Strict-Transport-Security $sts_header always;
    location / {
        proxy_pass http://authentik.homelab-services.com;
        set $upstream_keepalive true;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade_keepalive;
    }
}
```
Podman network inspect nginx-proxy-network: 
```
"3b26bb2a3b387eb8e424b40a7cd8f5cbf8cb7e1e4b8b190ac6e6d66dac35f8c6": {
                    "name": "nginx-proxy",
                    "interfaces": {
                         "eth0": {
                              "subnets": [
                                   {
                                        "ipnet": "10.89.0.4/24",
                                        "gateway": "10.89.0.1"
                                   }
                              ]
                         }
                    }
               }
"b9ebe4ba2ba11275248463c786a4d1e539d45137ac7e659d445913bf9d2c52ac": {
                    "name": "authentik_server",
                    "interfaces": {
                         "eth0": {
                              "subnets": [
                                   {
                                        "ipnet": "10.89.0.11/24",
                                        "gateway": "10.89.0.1"
                                   }
                              ]
                         }
                    }
               }
```
![image](https://github.com/user-attachments/assets/34cb3226-2fb8-420b-80d0-bebeb16ba762)

I'll be happy to provide any more context/information.
Thank you in advance for your help.
