### DISCUSSION TITLE
SAML zabbix instructions

### DISCUSSION THREAD

**Discussion by bbrendon** [goauthentik/authentik#2183] [Show and tell]
The docs didn't work. This did. It took me many hours to figure this out, probably because this is my first real foray into SAML.

### Zabbix
![image](https://user-images.githubusercontent.com/6364477/151674877-20818780-ace7-4e2e-8611-08880f0dd560.png)

After that is setup, you'll have two options on the login screen. One for normal and a button below it for saml.

Also, create a user in zabbix called akadmin to make testing all this easier. The user in Authentik has to match the user in zabbix.

### Copy Certs to zabbix server
In Authentik Goto System -> Certificates
download the key and cert for "authentik Self-signed Certificate".

copy them to the directory below with the names below.  Notice the file size for idp.crt and sp.crt are the same, it's because they are the same :) . No idea if this is correct but it worked.

```
% ls -l /usr/share/zabbix/conf/certs
total 16
-rw-r--r-- 1 root root 1814 Jan 28 19:34 idp.crt
-rw-r--r-- 1 root root 1814 Jan 28 19:34 sp.crt
-rw-r--r-- 1 root root 3243 Jan 28 19:34 sp.key
%
```

### Authentik
Application -> Providers -> Create SAML Provider

![image](https://user-images.githubusercontent.com/6364477/151674970-439c527a-b0da-48c1-9c08-2cb8a7617d4f.png)

Applications -> Applications -> Create

![image](https://user-images.githubusercontent.com/6364477/151675038-23c5eb51-c52a-40a2-914b-7dd2fdaebcb8.png)

### Done
I hope I didn't miss anything. Good luck.

**Comment by TheBinaryLoop** [comment]
Hey @bbrendon, I did everything exactly as you wrote here, but I get the error

"Invalid array settings: idp_cert_or_fingerprint_not_found_and_required"

do you have any idea on how I can resolve that?

**Reply by bbrendon** [reply]
Sorry, I'm pretty rusty on all of this. Where is that error from.

**Reply by TheBinaryLoop** [reply]
Zabbix SAML Login Screen

**Reply by bbrendon** [reply]
This is what i have in my notes for that error. Not really sure what it means.

    https://www.zabbix.com/forum/zabbix-help/425857-saml-is-not-working-properly

    'strict' => true,
    'debug' => false,

**Reply by OliverKarger** [reply]
@TheBinaryLoop i was able to fix this Error by configuring this Environment Variable for the Zabbix Frontend

```
ZBX_SSO_SETTINGS: "{'baseurl': 'https://zabbix-docker.mydomain.com', 'use_proxy_headers': true, 'strict': false}"
```

Source: https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql

Here is a complete example of a working config for docker:

```yaml
environment:
      ZBX_SSO_SP_KEY: /usr/share/zabbix/conf/certs/sp.key
      ZBX_SSO_SP_CERT: /usr/share/zabbix/conf/certs/sp.crt
      ZBX_SSO_IDP_CERT: /usr/share/zabbix/conf/certs/idp.crt
      ZBX_SSO_SETTINGS: "{'baseurl': 'https://nms.your-url.de', 'use_proxy_headers': true, 'strict': false}"
volumes:
      - ../config/zabbix/sp.key:/usr/share/zabbix/conf/certs/sp.key
      - ../config/zabbix/sp.crt:/usr/share/zabbix/conf/certs/sp.crt
      - ../config/zabbix/sp.crt:/usr/share/zabbix/conf/certs/idp.crt

```
