### DISCUSSION TITLE
New custom CSS support is great

### DISCUSSION THREAD

**Discussion by sevmonster** [goauthentik/authentik#4831] [Show and tell]
Thanks to #4804, we now have custom CSS that can touch every part of the DOM. With that, I started making my authentik look more like the new default look for Nextcloud, which is centered around a 25px frosted glass blur. Sadly, I had to do some hacky workarounds since authentik uses hex color values instead of RGB, but the end result is visual parity with Nextcloud.

Background is by [David Groves on Unsplash](https://unsplash.com/photos/raXnREhb-uI). I have a cronjob to rotate the background for all my services every hour.

### authentik
![image](https://user-images.githubusercontent.com/16788697/222502487-6ee53526-225c-4094-852e-8475f462a28c.png)
![image](https://user-images.githubusercontent.com/16788697/222504901-09207216-c3a5-4228-8dbe-9dbec977ae1c.png)
### Nextcloud inspiration
![image](https://user-images.githubusercontent.com/16788697/222500368-3b08533d-9db0-4915-a58b-82bc49d44ad0.png)

## CSS
I hereby release the below stylesheet into the public domain.
```
/*** global ***/
:root {
  --ak-accent: #3A244A;
  --ak-flow-background: url(https://picsum.photos/1920/1080) !important;
  --pf-global--primary-color--100: #70468E;
  --pf-global--primary-color--200: #55356c;
  --pf-global--primary-color--400: var(--ak-accent);
}
/* set up ::before psuedo-elems for hex transparency
 *
 * NOTE:
 * this is necessary as var() returns tokens, not strings, so:
 *   --a: #deadbe;
 *   x: var(--a)ef;
 * becomes:
 *   x: #deadbe ef;
 *
 * to get around this we use psuedo-elems with opacity; easier and less verbose
 * to just define the selectors here again instead of duplicating properties
 *
 * CSS Color Module Level 5 is not ready yet and would prevent this nasty shit
 */
.pf-c-login__main,
.pf-c-login__footer .pf-c-list,
.pf-c-page__sidebar {
  background-color: transparent !important;
  backdrop-filter: blur(25px);
}
.pf-c-login__main::before,
.pf-c-login__footer .pf-c-list::before,
.pf-c-page__sidebar::before {
  content: "";
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
  opacity: 0.8;
}


/*** flows ***/
.pf-c-background-image {
  --pf-c-background-image--Filter: none;
}

.ak-login-container {
  /* fix #4830 */
  justify-content: initial;
}
.pf-c-login__header {
  margin-top: 10px;
}

/* give both the blur and color same radius */
.pf-c-login__main,
.pf-c-login__main::before {
  border-radius: 3px 3px 0 0;
}
.pf-c-login__footer .pf-c-list,
.pf-c-login__footer .pf-c-list::before {
  border-radius: 0 0 3px 3px;
}

.pf-c-login__main::before,
.pf-c-login__footer .pf-c-list::before {
  background-color: var(--pf-c-login__main--BackgroundColor);
}
.pf-c-login__footer {
  /* unset inverted colorscheme on footer since we're adding bg */
  --pf-global--Color--100: inherit;
  --pf-global--Color--200: inherit;
  --pf-global--BorderColor--100: inherit;
  --pf-global--primary-color--100: inherit;
  --pf-global--link--Color: inherit;
  --pf-global--link--Color--hover: inherit;
  --pf-global--BackgroundColor--100: inherit;
}

.pf-c-login__footer .pf-c-list {
    padding-top: var(--pf-c-login__footer--c-list--PaddingTop);
    padding-bottom: var(--pf-c-login__footer--c-list--PaddingTop);
}

@media (prefers-color-scheme: dark) {
  .pf-c-login__main::before,
  .pf-c-login__footer .pf-c-list::before {
    background-color: var(--ak-dark-background);
  }
}


/*** user interface ***/
.header input {
  border-bottom-color: var(--pf-global--primary-color--100);
}


/*** admin interface ***/
.pf-c-page__sidebar {
  backdrop-filter: blur(10px);
}
.pf-c-page__sidebar::before {
  background-color: var(--pf-global--BackgroundColor--dark-300);
}
@media (prefers-color-scheme: dark) {
  .pf-c-page__sidebar::before {
     background-color: var(--ak-dark-background-light);
   }
  .pf-c-nav {
     background-color: transparent;
  }
}
.pf-c-nav__link.pf-m-current::after,
.pf-c-nav__link.pf-m-current:hover::after,
.pf-c-nav__item.pf-m-current:not(.pf-m-expanded) .pf-c-nav__link::after {
  --pf-c-nav__link--m-current--after--BorderColor: var(--ak-accent) !important;
}
```

**Comment by almereyda** [comment]
As I am unable to stop any changed URL for the background image, would you like to reveal a little more, how you change it?

**Reply by sevmonster** [reply]
I'm not sure what you mean. I just override the flow background image unconditionally. If you're talking about changing the default non-flow background (used on generic error pages), you need to overwrite `/web/dist/assets/images/flow_background.jpg`. Of course your custom css *should* be included on most of the pages as well so I doubt you would see it much if at all.

**Comment by terafirmanz** [comment]
@sevmonster line one imports from your website is this required as I like the rounded corners but hesitate to import external code dynamically to my authentication system? If required can you confirm what parts so one could include them in this and not import them?

**Reply by sevmonster** [reply]
You could have just visited the page to see what was being imported...

**Reply by terafirmanz** [reply]
fair enough not sure why I didn't: clearly lots on the mind.

I see at this stage it's only pulling in the background image.

**Reply by sevmonster** [reply]
Actually, I have updated the OP since it was silly in hindsight to include it. I am making changes internally that would have broken the variable anyway (it no longer exists in my stylesheet)

**Comment by hooray4me** [comment]
If using docker images, is there something special I need to do to mount the custom.css? Do I have to build it again? I have mounted it into both server and worker... If I exec into each, it shows the file mounted correctly, but it is not applied. Any help would be greatly appreciated.

```
version: "3.4"

services:
  redis:
    image: docker.io/library/postgres:12-alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - apps
  server:
    image: ghcr.io/goauthentik/server:2023.10.5
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
      - ${PWD}/custom.css:/web/dist/custom.css
    env_file:
      - .env
    expose:
      - "9000"
      - "9443"
    networks:
      - apps
    depends_on:
      - redis
  worker:
    image: ghcr.io/goauthentik/server:2023.10.5
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
      - ${PWD}/custom.css:/web/dist/custom.css
    env_file:
      - .env
    networks:
      - apps
    depends_on:
      - redis
networks:
  apps:
    external: true
volumes:
  redis:
    driver: local
```

**Reply by terafirmanz** [reply]
If you exec into the container can you read the file or output its contents with cat command? You will likely find that Authentik containers are running as a user that does not have permission to read the file. Either change the containers to run as a different user or add the user to the files permissions.

**Reply by hooray4me** [reply]
So simple! I totally overlooked that! Thank you!

**Reply by sevmonster** [reply]
You only need it mounted in the server. The worker does not serve user facing pages.

**Reply by arpanghosh8453** [reply]
I am having the same issue, I checked and I can cat the file contents so it's mounted and readable by the container user (Authentik) but it's still not being applied. I have used the above CSS example file as contents. Any suggestions @terafirmanz ?

![image](https://github.com/goauthentik/authentik/assets/26424944/a149f12e-7557-4950-aac3-8a9ad4e660a7)

**Reply by terafirmanz** [reply]
@arpanghosh8453 I hate to ask the obvious questions but are you running the latest version that supports the custom css file?

Also in your browser open the dev tools and disable the cache on the network tab to make sure it is loading fresh. Then in that tab refresh the page and under css see if you are getting the file:
![image](https://github.com/goauthentik/authentik/assets/53923271/4a9a2804-169c-4101-a409-a930c21f6008)

**Reply by arpanghosh8453** [reply]
Thanks a lot for getting back to me @terafirmanz. I checked that for sure. I was so confused why it's not working. When I open the file from inside container, I see the contents, but when I open it from the browser inspect, I get that files contains a single default comment only. 

Then I realized it's Cloudflare who is serving the cached content and not refreshing it even if I do hard refresh on my end. Funny story but then I purged the cache, and everything was great!

 I even customized the configured source buttons to make them look professional :) I LOVE the new look 💯 

![image](https://github.com/goauthentik/authentik/assets/26424944/d3d06c25-d61d-4473-98b5-7a114d97d526)

![image](https://github.com/goauthentik/authentik/assets/26424944/b61820df-1760-404f-8670-8996b92a4168)

**Reply by Mrs-Feathers** [reply]
wow that looks beautiful. how did you get the source buttons like that? whatever image i put, i can't get it to be bigger than a small circle with text beside it

**Reply by arpanghosh8453** [reply]
@Mrs-Feathers  I have the following in my custom.css to override the default styling of source buttons. 

```css
.pf-c-button.pf-m-link {
    color: #fff;
    background-color: #282828;
    padding: 10px 20px 4px 20px;
    border-radius: 40px;
    border: 2px solid #f4ebeb;
  }

.pf-c-button.pf-m-link:hover {
    background-color: #444444;
  }
```

**Reply by GerardWoldendorp** [reply]
@arpanghosh8453 Could you maybe share your custom css with us? Yours look very good and simple

**Reply by arpanghosh8453** [reply]
@GerardWoldendorp Here you go - 

```css
/*** global ***/

.pf-c-background-image {
  --ak-flow-background: url(https://picsum.photos/1920/1080) !important;
}

:root {
    --ak-accent: #3A244A;
    --pf-global--primary-color--100: #70468E;
    --pf-global--primary-color--200: #55356c;
    --pf-global--primary-color--400: var(--ak-accent);
  }
  /* set up ::before psuedo-elems for hex transparency
   *
   * NOTE:
   * this is necessary as var() returns tokens, not strings, so:
   *   --a: #deadbe;
   *   x: var(--a)ef;
   * becomes:
   *   x: #deadbe ef;
   *
   * to get around this we use psuedo-elems with opacity; easier and less verbose
   * to just define the selectors here again instead of duplicating properties
   *
   * CSS Color Module Level 5 is not ready yet and would prevent this nasty shit
   */
  .pf-c-login__main,
  .pf-c-login__footer .pf-c-list,
  .pf-c-page__sidebar {
    background-color: transparent !important;
    backdrop-filter: blur(25px);
  }
  .pf-c-login__main::before,
  .pf-c-login__footer .pf-c-list::before,
  .pf-c-page__sidebar::before {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
    opacity: 0.8;
  }
  
  
  /*** flows ***/
  .pf-c-background-image {
    --pf-c-background-image--Filter: none;
  }

  .pf-c-button.pf-m-link {
    color: #fff;
    background-color: #282828;
    padding: 10px 20px 4px 20px;
    border-radius: 40px;
    border: 2px solid #f4ebeb;
  }

  .pf-c-login__main-footer-links-item {
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  }

  .pf-c-button.pf-m-link:hover {
    background-color: #444444;
  }

  .pf-c-button.pf-m-secondary {
    color: var(--pf-c-button--m-primary--Color);
    background-color: var(--pf-c-button--m-primary--BackgroundColor);
  }
  
  .pf-c-button.pf-m-secondary:hover {
    color: var(--pf-c-button--m-primary--hover--Color);
    background-color: var(--pf-c-button--m-primary--hover--BackgroundColor);
  }

  .separator::before, .separator::after {
    border-bottom: 1px solid rgb(255, 255, 255);
  }

  .ak-login-container {
    /* fix #4830 */
    justify-content: initial;
  }
  .pf-c-login__header {
    margin-top: 10px;
  }
  
  /* give both the blur and color same radius */
  .pf-c-login__main,
  .pf-c-login__main::before {
    border-radius: 15px 15px 15px 15px;
  }
  .pf-c-login__footer .pf-c-list,
  .pf-c-login__footer .pf-c-list::before {
    border-radius: 0 0 3px 3px;
  }
  
  .pf-c-login__main::before,
  .pf-c-login__footer .pf-c-list::before {
    background-color: var(--pf-c-login__main--BackgroundColor);
  }
  .pf-c-login__footer {
    /* unset inverted colorscheme on footer since we're adding bg */
    --pf-global--Color--100: inherit;
    --pf-global--Color--200: inherit;
    --pf-global--BorderColor--100: inherit;
    --pf-global--primary-color--100: inherit;
    --pf-global--link--Color: inherit;
    --pf-global--link--Color--hover: inherit;
    --pf-global--BackgroundColor--100: inherit;
    display: none; /* For removing footer with Powered by Authentik link */
  }
  
  .pf-c-login__footer .pf-c-list {
      padding-top: var(--pf-c-login__footer--c-list--PaddingTop);
      padding-bottom: var(--pf-c-login__footer--c-list--PaddingTop);
  }
  
  @media (prefers-color-scheme: dark) {
    .pf-c-login__main::before,
    .pf-c-login__footer .pf-c-list::before {
      background-color: var(--ak-dark-background);
    }
  }
  
  
  /*** user interface ***/
  .header input {
    border-bottom-color: var(--pf-global--primary-color--100);
  }
  
  
  /*** admin interface ***/
  .pf-c-page__sidebar {
    backdrop-filter: blur(10px);
  }
  .pf-c-page__sidebar::before {
    background-color: var(--pf-global--BackgroundColor--dark-300);
  }
  @media (prefers-color-scheme: dark) {
    .pf-c-page__sidebar::before {
       background-color: var(--ak-dark-background-light);
     }
    .pf-c-nav {
       background-color: transparent;
    }
  }
  .pf-c-nav__link.pf-m-current::after,
  .pf-c-nav__link.pf-m-current:hover::after,
  .pf-c-nav__item.pf-m-current:not(.pf-m-expanded) .pf-c-nav__link::after {
    --pf-c-nav__link--m-current--after--BorderColor: var(--ak-accent) !important;
  }
```

**Reply by masterwishx** [reply]
is it still Fine for latest version , or/and maybe you made some more cool changes ?

**Comment by hexxone** [comment]
Looks great! Thanks for sharing!

I also extended the concept a bit by customising the "User Library" view in a similar way:

![image](https://github.com/goauthentik/authentik/assets/5312542/636846a1-edeb-4331-bad0-db44fab35011)

E.g.:

```css

.pf-c-card,
.pf-c-expandable-section {
    backdrop-filter: blur(25px);
    border-radius: 7px 7px 7px 7px !important;
}

.pf-c-card {
    background-color: #35353535 !important;
}

ak-expand,
.pf-c-expandable-section {
    background-color: transparent !important;
}

.pf-c-expandable-section.pf-m-display-lg::after {
    top: 5px;
    bottom: 5px;
    border-radius: 7px 7px 7px 7px !important;
    transition: all 0.3s;
}

.pf-c-expandable-section.pf-m-expanded::after {
    box-shadow: 1px 0px 4px #06c;
}

.pf-c-expandable-section button {
    width: 100%;
}

.pf-c-sidebar__panel .pf-c-card {
    background-color: #1c1e21 !important; /** Fix for /if/admin/#/core/applications Sidebar **/
}

```
