### DISCUSSION TITLE
Using Docker socket proxy with Authentik worker and understanding docker.sock access requirements

### DISCUSSION THREAD

**Discussion by n0one42** [goauthentik/authentik#5417] [Q&A]
Hello everyone,

I have been setting up Authentik in my environment and noticed that the Authentik worker container requires direct access to the Docker socket by mounting `/var/run/docker.sock`. While this is a common practice, it can have some security implications, as the container gains extensive privileges on the host system.

To mitigate this risk, I would like to know if it's possible to use a Docker socket proxy, such as [tecnativa/docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy), with the Authentik worker container. This proxy would limit the Docker API access and provide better security. 

I have already set up a similar configuration for Traefik `command: --providers.docker.endpoint=tcp://traefik-socketproxy:2375` and Portainer `command: -H tcp://portainer-socketproxy:2375`. 
My Ansible task for setting up Authentik can be found here: 
[ansible-playbook-homelab - container_authentik.yml](https://github.com/n0one42/ansible-playbook-homelab/blob/main/roles/docker_composes/tasks/container_authentik.yml)

Additionally, I would like to understand why the Authentik worker requires access to the Docker socket. What specific features or functionality does it provide that necessitate this access?

I couldn't find any references to configuring a custom Docker socket or using a DOCKER_HOST environment variable in the Authentik documentation or source code. Could you please provide some guidance on whether it's possible to use a socket proxy with Authentik worker and, if so, how to configure it correctly?

I appreciate any help or suggestions you can provide on this topic. Thank you in advance for your time and support.

**Comment by BeryJu** [comment]
The docker socket bind is not required and can be removed as the compose file states. The reason why it's in there by default is to allow the creation for authentik managed outposts, where authentik creates the container and keeps it updated. 

There was another issue that I can't find right now that lists what access is required for this integration when using an API proxy

You can connect to a different docker API endpoint by creating an outpost integration in the admin interface under system, where you can specify tcp://my-server and then use that for outposts

**Reply by n0one42** [reply]
Many thanks for the fast response!

I created the outpost under Outpost → "Docker Service-Connection" and inserted tcp://authentik-socketproxy:2375. The full configuration is as follows:
```json
{
  "pk": "random-pk",
  "name": "authentik-socketproxy",
  "local": true,
  "component": "ak-service-connection-docker-form",
  "verbose_name": "Docker Service-Connection",
  "verbose_name_plural": "Docker Service-Connections",
  "meta_model_name": "authentik_outposts.dockerserviceconnection",
  "url": "tcp://authentik-socketproxy:2375",
  "tls_verification": null,
  "tls_authentication": null
}
```
I tried `local: true` and `local: false`. Only with `local: false` do I get an entry inside the socket proxy, but it gives:
```
172.27.0.3:34764 [30/Apr/2023:07:10:53.448] dockerfrontend dockerfrontend/<NOSRV> -1/-1/-1/-1/0 400 188 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>"
```
For testing purposes, I've granted the socket proxy full access permissions.

---
offtopic
Vielen Dank für die Hilfe! Ich bin beeindruckt, wie gut strukturiert alles aussieht. Es ist selten, so gut durchdachte Projekte zu sehen, weshalb ich Authentik gerne eine Chance gegenüber Keycloak geben möchte.

**Reply by 1298345095** [reply]
> Many thanks for the fast response!
> 
> I created the outpost under Outpost → "Docker Service-Connection" and inserted tcp://authentik-socketproxy:2375. The full configuration is as follows:
> 
> ```json
> {
>   "pk": "random-pk",
>   "name": "authentik-socketproxy",
>   "local": true,
>   "component": "ak-service-connection-docker-form",
>   "verbose_name": "Docker Service-Connection",
>   "verbose_name_plural": "Docker Service-Connections",
>   "meta_model_name": "authentik_outposts.dockerserviceconnection",
>   "url": "tcp://authentik-socketproxy:2375",
>   "tls_verification": null,
>   "tls_authentication": null
> }
> ```
> 
> I tried `local: true` and `local: false`. Only with `local: false` do I get an entry inside the socket proxy, but it gives:
> 
> ```
> 172.27.0.3:34764 [30/Apr/2023:07:10:53.448] dockerfrontend dockerfrontend/<NOSRV> -1/-1/-1/-1/0 400 188 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>"
> ```
> 
> For testing purposes, I've granted the socket proxy full access permissions.
> 
> offtopic Vielen Dank für die Hilfe! Ich bin beeindruckt, wie gut strukturiert alles aussieht. Es ist selten, so gut durchdachte Projekte zu sehen, weshalb ich Authentik gerne eine Chance gegenüber Keycloak geben möchte.

Can you tell me where can I fill this config? I can't find any blank to fill this json.

**Reply by itskagee** [reply]
> Can you tell me where can I fill this config? I can't find any blank to fill this json.

Settings > Outpost Integrations > Create [Docker Service-Connection]

**Comment by danielriddell21** [comment]
I got authentik to work without DOCKER_HOST binding and using http://docker-proxy:2375 and local: false.
I needed to set 
CONTAINERS=1
POST=1
IMAGES=1
INFO=1

**Reply by ross-schlegel** [reply]
Confirming this was the change that worked for me. I had to hit "Refresh" a couple times but the state eventually went from Unhealthy to showing a valid state.

**Reply by Jurrer** [reply]
Hello people also having this issue.
I just spent a day troubleshooting this problem only to find out that I have connected server container to proxy instead of a worker.
Don't be like me, check your containers and good luck.

**Reply by 1298345095** [reply]
Why Local Docker connection still be "healthy"? I have already commented "/var/run/docker.sock".

**Reply by itskagee** [reply]
Heads up for anyone coming across this later, you don't need POST=1 anymore.

Since POST access is security critical, I thought I'd mention this here.

**Reply by fREAST** [reply]
POST=1 is still required if you want Authentik to be able to automatically create and manage outposts.

**Reply by itskagee** [reply]
Ah, makes sense.

My deployment only uses the embedded outpost so POST wasn't needed there.

Thanks for the update!

**Comment by tecio-first** [comment]
DOC:
https://docs.goauthentik.io/add-secure-apps/outposts/integrations/docker/#permissions

translated back into a config with a up to date socket proxy:

```

authentik-socket-proxy:
    image: ghcr.io/wollomatic/socket-proxy:${SOCKET_PROXY_TAG:-1.11.0}
    container_name: authentik-socket-proxy
    restart: unless-stopped
    mem_limit: 64M
    user: "0:0"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    labels:
      - "diun.enable=false"
    command:
      - '-loglevel=info'
      - '-listenip=0.0.0.0'
      - '-allowfrom=authentik-worker'
      # Official Authentik Docker API Permissions: https://docs.goauthentik.io/add-secure-apps/outposts/integrations/docker/#permissions
      # System/Info: Docker version | Containers/Read: running containers | Images/Pull: pull images | Networks: outpost networking
      - '-allowGET=/version|/info|/_ping|/v1\..{1,2}/(containers/json|containers/.*/json|networks/json|networks/.*/json)'
      - '-allowHEAD=/_ping'
      # Containers/Create: new containers | Containers/Kill: cleanup during upgrades | Images/Pull: download images | Networks: create networks
      - '-allowPOST=/v1\..{1,2}/(images/create|containers/create|containers/.*/kill|networks/create)'
      # Containers/Remove: outpost removal | Networks: cleanup networks
      - '-allowDELETE=/v1\..{1,2}/(containers/.*|networks/.*)'
      - '-allowhealthcheck'
      - '-watchdoginterval=3600'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - authentik-proxynet
```

and the reference service of it:
```

worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2025.12.1}
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - FOWNER
    security_opt:
      - no-new-privileges
    labels:
      - "diun.enable=false"
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
      authentik-socket-proxy:
        condition: service_healthy
      server:
        condition: service_healthy
      openbao:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_LOG_LEVEL: ${AUTHENTIK_LOG_LEVEL:-warning}
      DOCKER_HOST: tcp://authentik-socket-proxy:2375
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./custom-templates:/templates
    tmpfs:
      - /tmp:noexec,nosuid,nodev
      - /media:noexec,nosuid,nodev
    healthcheck:
      test: ["CMD-SHELL", "ak healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - traefik-network
      - authentik-proxynet


```
edit 1(indentation is off)
edit 2 - allowGET=/version added
