### DISCUSSION TITLE
Can't get Grafana/Prometheus metrics to work

### DISCUSSION THREAD

**Discussion by EHRETic** [goauthentik/authentik#8205] [Q&A]
Hi there,

As I don't know much about Prometheus metrics, I'm struggling a bit to get Authentik Prometheus data source working in my grafana Instance.
One important thing to know, in my environement, all docker instances have a dedicated IP address (macvlan), so port mapping is not working as expected. They are also in the same subnet, so there is no firewall/routing between Grafana & Authentik IPs.

This i what I put to the data source configuration (IP is my authentik server instance - not the worker instance)

![image](https://github.com/goauthentik/authentik/assets/28634810/a3ab6cfa-9530-49a8-9373-86f63caba74c)

What I've noticed so far, if I comment the variable AUTHENTIK_LISTEN__METRICS (set to 9300), I get the following error:

![image](https://github.com/goauthentik/authentik/assets/28634810/bcf750e3-a165-439e-a409-4cee4c9a0b10)

If I make it active again, I get the following:

![image](https://github.com/goauthentik/authentik/assets/28634810/96d9c83d-6cc8-4860-97b6-04000cb18b8d)

So variable seems to make a difference and should be active to make Authentik listen to that port but either I'm doing something wrong or there is something not working as expected.

Thanks in advance for your help 😉

PS: Authentik server version is [2023.10.6](https://goauthentik.io/docs/releases/2023.10)

**Comment by BeryJu** [comment]
You need an instance of prometheus which will "scrape" the metrics from authentik and then you can add that prometheus server in grafana

**Reply by EHRETic** [reply]
Thanks a lot for this super quick reply! 😉👌

The need of an instance wasn't clear when you don't know anything. So, I'm already a step further and have a basic Promotheus container, but the scrape job doesn't seems to get any data. Maybe I need something else, here is the prometheus.yml:

```
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "authentik-test"
    static_configs:
      - targets: ["192.168.X.X:9300"]
```

And I see this in Prometheus GUI:

![image](https://github.com/goauthentik/authentik/assets/28634810/8b9e4f05-613b-4beb-ad45-9f17b5b30c56)

I might still miss something, would you know where?
