### DISCUSSION TITLE
Jenkins Real fail !

### DISCUSSION THREAD

**Discussion by tron4x** [goauthentik/authentik#8937] [Q&A]
Hello,

i have problems with jenkins and authentik.
redirection to jenkins site is false.

http://jenkins:8080/securityRealm/finishLogin?code=eef2c7c4bb6540afab4602a5ab6f7a4f&state=OTJmMzg2OWItMjQxMy00

I have create OAuth2/OpenID provider and application like this in the documentation:

https://docs.goauthentik.io/integrations/services/jenkins/

Is this a bug or maybe is it my false ?

Than you !

**Comment by tron4x** [comment]
I return to Authelia.
Authentik sucks !
ArgoCD, Jenkins and others don't work.
And this is completely wrong. The path must be absolute and not this nonsense:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: authentik-outpost
spec:
    rules:
        - host: app.company
          http:
              paths:
                  - path: /outpost.goauthentik.io
                    pathType: Prefix
                    backend:
                        # Or, to use an external Outpost, create an ExternalName service and reference that here.
                        # See https://kubernetes.io/docs/concepts/services-networking/service/#externalname
                        service:
                            name: ak-outpost-example-outpost
                            port:
                                number: 9000
```

And what should the service show ? because it doesn't exist ?

I'm pissed off. Immature software!
