### ISSUE TITLE
Authentik Workers are now have an unexpectedly high memory footprint

### ISSUE THREAD

**Issue by janosmiko** [goauthentik/authentik#10021]
**Describe the bug**
Previously I was using 2023.10 helm chart with 2023.8 images. Yesterday I upgraded Authentik to 2024.02 and I faced an issue with the workers constantly restarted in my cluster. I found that they were OOMKilled so I raised their memory limits but I still face this issue and I assume this is somehow unexpected.

**To Reproduce**
My helm values
```yaml
global:
  image:
    tag: 2024.4.2
  env:
    - name: AK_ADMIN_PASS
      value: blabla
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      value: blablabla
    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      value: blablabla
    - name: AUTHENTIK_FLOW_BACKGROUND_URL
      value: >-
        https://raw.githubusercontent.com/regbo/public-html/master/authentik/background.png
    - name: AUTHENTIK_BRAND_ICON_URL
      value: 'https://example.com/favicon-96x96.png'
    - name: AUTHENTIK_INJECT_CSS_URL_0
      value: >-
        https://raw.githubusercontent.com/regbo/public-html/master/authentik/input.css
    - name: AUTHENTIK_INJECT_CSS_URL_1
      value: >-
        https://rawcdn.githack.com/regbo/public-html/2561d77f76d55b9f91afa697f2570f6ed74e6b94/authentik/hide-branding.css
    - name: AUTHENTIK_REDIS__HOST
      value: authentik-redis-ha-haproxy
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-postgres-app
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          key: redis-password
          name: authentik-redis
server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - example.com
        secretName: example.com-tls
    hosts:
      - example.com
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 1536Mi
    limits:
      #cpu: null
      memory: 1536Mi
worker:
  replicas: 3
  resources:
    requests:
      cpu: 10m
      memory: 2048Mi
    limits:
      #cpu: null
      memory: 4096Mi
blueprints:
  configmaps:
    - authentik-blueprint
authentik:
  secret_key: blabla
  error_reporting:
    enabled: false

  postgresql:
    host: 'authentik-postgres-rw'
    name: "authentik"
    user: "authentik"
    port: 5432

postgresql:
  enabled: false
redis:
  enabled: false
```

And my blueprint's template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint
data:
  authentik-blueprint.yaml: |
    version: 1
    metadata:
      name: authentik-blueprint
    entries:
      - attrs:
          designation: authentication
          name: {{ .Values.branding.message }}
          slug: default-authentication-flow
          title: {{ .Values.branding.message }}
        id: default-authentication-flow
        identifiers:
          slug: default-authentication-flow
        model: authentik_flows.flow
        state: present
      - id: default-provider-authorization-explicit-consent
        identifiers:
          slug: default-provider-authorization-explicit-consent
        model: authentik_flows.flow
        state: present
      - attrs:
          slug: default-invalidation-flow
        id: default-invalidation-flow
        identifiers:
          slug: default-invalidation-flow
        model: authentik_flows.flow
        state: present
      - attrs:
          slug: default-user-settings-flow
        id: default-user-settings-flow
        identifiers:
          slug: default-user-settings-flow
        model: authentik_flows.flow
        state: present
      - attrs:
          branding_favicon: {{ .Values.branding.favicon}}
          branding_logo: {{ .Values.branding.logo }}
          branding_title: {{ .Values.branding.title }}
          default: true
          domain: authentik-default
          event_retention: days=365
          flow_authentication: !KeyOf default-authentication-flow
          flow_invalidation: !KeyOf default-invalidation-flow
          flow_user_settings: !KeyOf default-user-settings-flow
        id: authentik-default-tenant
        identifiers:
          domain: authentik-default
        model: authentik_tenants.tenant
        state: present
      - id: 'authentik default OAuth Mapping: OpenID ''openid'''
        identifiers:
          name: 'authentik default OAuth Mapping: OpenID ''openid'''
        model: authentik_providers_oauth2.scopemapping
        state: present
      - id: 'authentik default OAuth Mapping: OpenID ''email'''
        identifiers:
          name: 'authentik default OAuth Mapping: OpenID ''email'''
        model: authentik_providers_oauth2.scopemapping
        state: present
      - id: 'authentik default OAuth Mapping: OpenID ''profile'''
        identifiers:
          name: 'authentik default OAuth Mapping: OpenID ''profile'''
        model: authentik_providers_oauth2.scopemapping
        state: present
      - id: 'authentik default OAuth Mapping: Proxy outpost'
        identifiers:
          name: 'authentik default OAuth Mapping: Proxy outpost'
        model: authentik_providers_oauth2.scopemapping
        state: present
      - attrs:
          local: true
          name: Local Kubernetes Cluster
          verify_ssl: true
        id: Local Kubernetes Cluster
        identifiers:
          name: Local Kubernetes Cluster
        model: authentik_outposts.kubernetesserviceconnection
        state: present
      - attrs:
          name: authentik Self-signed Certificate
        id: authentik Self-signed Certificate
        identifiers:
          name: authentik Self-signed Certificate
        model: authentik_crypto.certificatekeypair
        state: present
      - attrs:
          name: authentik Admins
        id: authentik Admins
        identifiers:
          name: authentik Admins
        model: authentik_core.group
        state: present

    # OIDC
      - attrs:
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          authentication_flow: !KeyOf default-authentication-flow
          authorization_flow: !KeyOf default-provider-authorization-explicit-consent
          client_id: {{ .Values.example.oidc.clientId }}
          client_secret: {{ .Values.example.oidc.clientSecret }}
          client_type: confidential
          include_claims_in_id_token: true
          issuer_mode: per_provider
          name: example-oidc
          property_mappings:
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''openid'''
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''email'''
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''profile'''
          {{- if .Values.example.oidc.redirectUris }}
          redirect_uris: {{ .Values.example.oidc.redirectUris }}
          {{- end }}
          refresh_token_validity: days=30
          sub_mode: hashed_user_id
        conditions: []
        id: example-oidc-provider
        identifiers:
          name: example-oidc
        model: authentik_providers_oauth2.oauth2provider
        state: present
      - attrs:
          meta_launch_url: {{ .Values.example.metaLaunchUrl }}
          meta_icon: {{ .Values.example.metaIcon }}
          name: Example
          policy_engine_mode: any
          provider: !KeyOf example-oidc-provider
          slug: example
        id: example-app
        identifiers:
          name: Example
        model: authentik_core.application
        state: present

    # Harbor
      - attrs:
          meta_launch_url: {{ .Values.harbor.metaLaunchUrl }}
          meta_icon: {{ .Values.harbor.metaIcon }}
          name: Harbor
          policy_engine_mode: any
          slug: harbor
        id: harbor-app
        identifiers:
          name: Harbor
        model: authentik_core.application
        state: present

    # Gitea
      - attrs:
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          authentication_flow: !KeyOf default-authentication-flow
          authorization_flow: !KeyOf default-provider-authorization-explicit-consent
          client_id: {{ .Values.gitea.oidc.clientId }}
          client_secret: {{ .Values.gitea.oidc.clientSecret }}
          client_type: confidential
          include_claims_in_id_token: true
          issuer_mode: per_provider
          name: gitea-oidc
          property_mappings:
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''openid'''
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''email'''
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''profile'''
          {{- if .Values.gitea.oidc.redirectUris }}
          redirect_uris: {{ .Values.gitea.oidc.redirectUris }}
          {{- end }}
          refresh_token_validity: days=30
          sub_mode: hashed_user_id
        conditions: []
        id: gitea-oidc-provider
        identifiers:
          name: gitea-oidc
        model: authentik_providers_oauth2.oauth2provider
        state: present
      - attrs:
          meta_launch_url: {{ .Values.gitea.metaLaunchUrl }}
          meta_icon: {{ .Values.gitea.metaIcon }}
          name: Gitea
          policy_engine_mode: any
          provider: !KeyOf gitea-oidc-provider
          slug: gitea
        id: gitea-app
        identifiers:
          name: Gitea
        model: authentik_core.application
        state: present

    # Kubernetes
      - attrs:
          name: {{ .Values.kubernetes.domain | quote }}
          certificate_data: {{ .Values.kubernetes.certificateData | b64dec | quote }}
          key_data: {{ .Values.kubernetes.certificateKeyData | b64dec | quote }}
        id: {{ .Values.kubernetes.domain | quote }}
        identifiers:
          name: {{ .Values.kubernetes.domain | quote }}
        model: authentik_crypto.certificatekeypair
        state: present

      - attrs:
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          authentication_flow: !KeyOf default-authentication-flow
          authorization_flow: !KeyOf default-provider-authorization-explicit-consent
          client_id: {{ .Values.kubernetes.oidc.clientId }}
          client_secret: {{ .Values.kubernetes.oidc.clientSecret }}
          client_type: confidential
          include_claims_in_id_token: true
          issuer_mode: per_provider
          name: kubernetes-oidc
          property_mappings:
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''openid'''
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''email'''
            - !KeyOf 'authentik default OAuth Mapping: OpenID ''profile'''
          {{ if .Values.kubernetes.oidc.redirectUris }}
          redirect_uris: {{ .Values.kubernetes.oidc.redirectUris }}
          {{- end }}
          refresh_token_validity: days=30
          signing_key: !KeyOf {{ .Values.kubernetes.domain | quote }}
          sub_mode: hashed_user_id
        conditions: []
        id: kubernetes-oidc-provider
        identifiers:
          name: kubernetes-oidc
        model: authentik_providers_oauth2.oauth2provider
        state: present
      - attrs:
          meta_launch_url: {{ .Values.kubernetes.metaLaunchUrl }}
          meta_icon: {{ .Values.kubernetes.metaIcon }}
          name: Kubernetes
          policy_engine_mode: any
          provider: !KeyOf kubernetes-oidc-provider
          slug: kubernetes
        id: kubernetes-app
        identifiers:
          name: Kubernetes
        model: authentik_core.application
        state: present

    # LDAP
      - attrs:
          authorization_flow: !KeyOf default-authentication-flow
          base_dn: {{ .Values.ldap.baseDn }}
          bind_mode: direct
          certificate: !KeyOf authentik Self-signed Certificate
          gid_start_number: 4000
          name: ldap-provider
          search_group: !KeyOf authentik Admins
          search_mode: direct
          uid_start_number: 2000
        id: ldap-provider
        identifiers:
          name: ldap-provider
        model: authentik_providers_ldap.ldapprovider
        state: present
      - attrs:
          meta_launch_url: {{ .Values.ldap.metaLaunchUrl }}
          meta_icon: {{ .Values.ldap.metaIcon }}
          name: LDAP
          policy_engine_mode: any
          provider: !KeyOf ldap-provider
          slug: ldap
        id: ldap-app
        identifiers:
          name: ldap
        model: authentik_core.application
        state: present
      - attrs:
          config:
            authentik_host: {{ .Values.ldap.authentikHost }}
            authentik_host_browser: ''
            authentik_host_insecure: false
            container_image: null
            docker_labels: null
            docker_map_ports: true
            docker_network: null
            kubernetes_disabled_components: []
            kubernetes_image_pull_secrets: []
            kubernetes_ingress_annotations: {}
            kubernetes_ingress_secret_name: authentik-outpost-ldap-tls
            kubernetes_namespace: {{ .Values.ldap.namespace }}
            kubernetes_replicas: 1
            kubernetes_service_type: ClusterIP
            log_level: info
            object_naming_template: "ak-outpost-%(name)s"
            kubernetes_json_patches:
              deployment:
                - op: add
                  path: "/spec/template/spec/containers/0/resources"
                  value:
                    requests:
                      cpu: 20m
                      memory: 48Mi
                    limits:
                      memory: 48Mi
          name: ldap
          providers:
          - !KeyOf ldap-provider
          service_connection: !KeyOf Local Kubernetes Cluster
          type: ldap
        id: ldap-outpost
        identifiers:
          name: ldap
        model: authentik_outposts.outpost
        state: present

    # SSO
      {{- range $key, $value := .Values.sso }}
      - attrs:
          access_token_validity: hours=1
          authentication_flow: !KeyOf default-authentication-flow
          authorization_flow: !KeyOf default-provider-authorization-explicit-consent
          cookie_domain: {{ $value.cookieDomain }}
          external_host: {{ $value.externalHost }}
          intercept_header_auth: true
          internal_host_ssl_validation: true
          mode: forward_domain
          name: {{ $value.name }}
          property_mappings:
          - !KeyOf 'authentik default OAuth Mapping: Proxy outpost'
          - !KeyOf 'authentik default OAuth Mapping: OpenID ''openid'''
          - !KeyOf 'authentik default OAuth Mapping: OpenID ''email'''
          - !KeyOf 'authentik default OAuth Mapping: OpenID ''profile'''
          refresh_token_validity: days=30
        id: {{ $value.name }}-provider
        identifiers:
          name: {{ $value.name }}
        model: authentik_providers_proxy.proxyprovider
        state: present
      - attrs:
          {{- if $value.metaLaunchUrl }}
          meta_launch_url: {{ $value.metaLaunchUrl }}
          {{- end }}
          {{- if $value.metaIcon}}
          meta_icon: {{ $value.metaIcon }}
          {{- end }}
          name: {{ $value.name }}
          policy_engine_mode: any
          provider: !KeyOf {{ $value.name }}-provider
          slug: {{ $value.name }}
        id: {{ $value.name }}-app
        identifiers:
          name: {{ $value.name }}
        model: authentik_core.application
        state: present
      - attrs:
          config:
            authentik_host: {{ $value.authentikHost }}
            authentik_host_browser: ''
            authentik_host_insecure: false
            container_image: null
            docker_labels: null
            docker_map_ports: true
            docker_network: null
            kubernetes_disabled_components: []
            kubernetes_image_pull_secrets: []
            kubernetes_ingress_annotations: {{ toYaml $value.ingress.annotations | nindent 14 }}
            kubernetes_ingress_class_name: {{ $value.ingress.className }}
            kubernetes_ingress_secret_name: {{ $value.ingress.secretName }}
            kubernetes_namespace: {{ $value.namespace }}
            kubernetes_replicas: 1
            kubernetes_service_type: ClusterIP
            log_level: info
            object_naming_template: ak-outpost-%(name)s
          name: {{ $value.name }}
          providers:
          - !KeyOf {{ $value.name }}-provider
          service_connection: !KeyOf Local Kubernetes Cluster
          type: proxy
        id: {{ $value.name }}-outpost
        identifiers:
          name: {{ $value.name }}
        model: authentik_outposts.outpost
        state: present
      {{- end }}

```

**Expected behavior**
Have the same memory footprint as previously.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/693558/460be527-d604-468c-9db8-ca761f7fd5d8)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2
-   Deployment: helm 2024.2
