### ISSUE TITLE
Device code flow with `verification_uri` (user needs to input `user_code`): `405 Method Not Allowed`

### ISSUE THREAD

**Issue by otaconix** [goauthentik/authentik#10402]
**Describe the bug**
Completing a OAuth _device code flow_ using a pretty much empty _stage configration_ flow results in a `405 Method Not Allowed` status code.

**To Reproduce**
Flow used:
```yaml
context: {}
entries:
- attrs:
    authentication: require_authenticated
    denied_action: message_continue
    designation: stage_configuration
    layout: stacked
    name: default-device-authentication-flow
    policy_engine_mode: any
    title: Let's verify your device!
  conditions: []
  identifiers:
    pk: f4ea7033-0679-4dff-b679-3012ee1568bc
    slug: default-device-authentication-flow
  model: authentik_flows.flow
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2024-07-07 18:10:12.625786+00:00
version: 1
```

1. Request a device code flow (`POST` to https://authentik.invalid/application/o/device)
2. Open the `verification_uri`
3. If needed, authenticate
4. Enter the `user_code`

**Expected behavior**
Succesful completion of the device code flow.

** Actual behavior**
The request the web UI sends to the backend (a `POST` to `.../api/v3/flows/executor/name-of-device-code-flow/` with the `user_code` in the `code` field of the request body) gets a `405 Method Not Allowed` response.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/1059119/3933fe0d-bfe2-4ef5-bb20-1d31f439f35c)

**Logs**
No useful logs to be found.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.0
-   Deployment: docker-compose
