### ISSUE TITLE
Is there an option to skip authentication with Authentik if the request comes from a specific path?

### ISSUE THREAD

**Issue by FutureFlySpace** [goauthentik/authentik#10419]
**Describe your question:**

I use Uptime-Kuma to monitor my websites.
The dashboard and a few status pages are protected with Authentik.
However, certain status pages should not be protected so that they can be viewed publicly.
I have already tried a little with Traefik, but unfortunately that has not worked so far:
```yaml
http:
  routers:
    uptime-kuma-status:
      rule: "(Host(`uptime.example.com`) && Path(`/status/foo`))"
      entrypoints: "websecure"
      tls:
        certresolver: "letsEncrypt"
      service: "uptime-kuma"

    uptime-kuma:
      rule: "Host(`uptime.example.com`)"
      entrypoints: "websecure"
      tls:
        certresolver: "letsEncrypt"
      middlewares:
        - "authentik-auth"
      service: "uptime-kuma"

  services:
    uptime-kuma:
      loadBalancer:
        servers:
          - url: http://uptime-kuma:3001
```
With this configuration, `https://uptime.example.com/status/foo` remains empty.
But I don't see any error in the browser console or when loading the required things

My thought was to somehow configure Authentik or Traefik to recognize when requests come from a certain path and then allow them.
Is that even possible?
Are there other (better) options?

**Screenshots:**

![image](https://github.com/goauthentik/authentik/assets/62362688/5f5aafb0-575e-41e4-9f09-dca89d4af5a7)

**Version and Deployment:**

-   authentik version: 2024.6.0
-   Deployment: docker-compose

Thank you very much for your help :)
