### ISSUE TITLE
Getting 500 error on subpages

### ISSUE THREAD

**Issue by hycday** [goauthentik/authentik#10557]
**Describe your question/**
I use Caddy Docker Proxy.
I have an app (amerkurev/scrapper) that I want to protect behind a login.
I have setup Authentik and am able to login properly and access the app.
However, when I want to use the app, it calls a "subpage" (example: app is on app.domain.ltd, subpage is on app.domain.ltd/api?q=test) and I get a 500 on that.

**Relevant info**

**Screenshots**

**Logs**
I have no errors on docker logs of authentik
docker logs of scrapper gives me 500 error.. no more details
on frontend i get CORS issue ("strict-origin-when-cross-origin") on the subpage url

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: 

```
version: '3.3'

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      - caddy
      - network-overlay
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - caddy
      - network-overlay
    volumes:
      - ./redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.6.1}
    restart: unless-stopped
    container_name: authentik-server
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
    networks:
      - caddy
      - network-overlay
    labels:
      caddy: auth.domain.ltd
      caddy.reverse_proxy: "{{upstreams 9443}}"
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.tls_insecure_skip_verify:


  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.6.1}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    networks:
      - caddy
      - network-overlay
    depends_on:
      - postgresql
      - redis

volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  caddy:
    external: true
  network-overlay:
    external: true
```

**Additional context**
I am wondering, if there is a step to do to protect/allow whole subpages of an app or if this is done by default ? 
what i mean is : 
by protecting app.domain.ltd, once logged in, anything under app.domain.ltd/* is accessible or do i need to configure it?
