### ISSUE TITLE
Outpost containers reverting back to "created" status after running for a few hours.

### ISSUE THREAD

**Issue by MRobi1** [goauthentik/authentik#10614]
**Describe the bug**
I run multiple sites through 1 instance of Authentik. In my .env file I have `AUTHENTIK_TENANTS__ENABLED=true` as well as
`AUTHENTIK_OUTPOSTS__DISABLE_EMBEDDED_OUTPOST=true`. 

I have the outposts deployed through the docker-compose file
```
  authentik_proxy_mike:
      image: ghcr.io/goauthentik/proxy
      container_name: ak-outpost-mikeoutpost
      restart: unless-stopped
      # Optionally specify which networks the container should be
      # might be needed to reach the core authentik server
      # networks:
      #   - foo
      ports:
          - 1080:9000
          - 10443:9443
      environment:
          AUTHENTIK_HOST: https://authentik.myfqdn.com/
          AUTHENTIK_INSECURE: "false"
          AUTHENTIK_TOKEN: authentiktokengoeshere
          # Starting with 2021.9, you can optionally set this too
          # when authentik_host for internal communication doesn't match the public URL
          # AUTHENTIK_HOST_BROWSER: https://external-domain.tld
```
On initial start, everything is great. 
Container shows healthy.
![image](https://github.com/user-attachments/assets/3a225ab8-0ec3-4aad-b85d-2670e146b0fd)
Authentik can see and connect to the outposts
![image](https://github.com/user-attachments/assets/a95b72ef-ec1a-4cdd-91bc-31ec9a941cb8)

Some time later, usually after a few hours, I try to access one of the services I have running through the outpost and I get a 500 error.
I'll log back in to authentik and it will then show Not Available.
![image](https://github.com/user-attachments/assets/78ef476d-22be-4b37-a0d4-e9f0276b10ea)
Back in portainer, expecting to see an exited or unhealthy status, it instead shows "created" and there are absolutely no logs to speak of.
![image](https://github.com/user-attachments/assets/81fb6f8a-2f86-4fdb-80a5-4f8418f0cf7a)
![image](https://github.com/user-attachments/assets/ce5a328f-d6f3-46ad-9b13-24430f19375a)

You can see here that the container was running at 2:17pm, but at 5:08pm it now just shows "created".
Re-running docker compose up -d gives me an error saying the container name is already in use
![image](https://github.com/user-attachments/assets/7200feac-0ecb-4770-bc46-85bbb5231ce4)

 
**To Reproduce**
Add outposts to docker-compose.yml, docker-compose up -d, wait

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: docker-compose

**Additional information**
I updated to 2024.6.1 yesterday and first noticed this issue late last night. It's happened twice again today. This may be related to 2024.6.1 but I'm unsure.
