### ISSUE TITLE
AttributeError: property 'is_staff' of 'User' object has no setter

### ISSUE THREAD

**Issue by davrot** [goauthentik/authentik#10610]
**Describe the bug**
I tries to do this:

root@psintern:~/sso_test_server/authentik# docker exec -it authentikserver bash
authentik@authentikserver:/$ ak createsuperuser

[Then there is a python error and some tears... And it continues with...]

AttributeError: property 'is_staff' of 'User' object has no setter
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

[...]

**To Reproduce**
I am using this compose.yaml
```
services:
  authentikserver:
    image: "ghcr.io/goauthentik/server:2024.6.1"
    container_name: authentikserver
    hostname: authentikserver
    restart: always

    command: server

    volumes:
      - authentik_media:/media
      - authentik_custom_templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - 9000:9000
      - 9443:9443

    environment:
      AUTHENTIK_REDIS__HOST: authentikredis
      AUTHENTIK_POSTGRESQL__HOST: authentikpostgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${ROOT_PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_EMAIL__HOST: "overleafsmtpd"
      AUTHENTIK_EMAIL__PORT: "25"
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      # AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: "overleaf@neuro.uni-bremen.de"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    networks:
      - overleaf-network

  authentikworker:
    image: "ghcr.io/goauthentik/server:2024.6.1"
    container_name: authentikworker
    hostname: authentikworker
    restart: always

    command: worker

    volumes:
      - authentik_media:/media
      - authentik_custom_templates:/templates
      - authentik_certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      AUTHENTIK_REDIS__HOST: authentikredis
      AUTHENTIK_POSTGRESQL__HOST: authentikpostgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${ROOT_PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_EMAIL__HOST: "overleafsmtpd"
      AUTHENTIK_EMAIL__PORT: "25"
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      # AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: "overleaf@neuro.uni-bremen.de"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"

    networks:
      - overleaf-network

    user: root

volumes:
  authentik_media:
  authentik_custom_templates:
  authentik_certs:

networks:
  overleaf-network:
    external: true
```

**Logs**

```
root@psintern:~/sso_test_server/authentik# docker exec -it authentikserver bash
authentik@authentikserver:/$ ak createsuperuser
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832583.7763846, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832583.7768726, "count": 12}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1721832584.524723}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1721832584.5317307}
{"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1721832584.5332792}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1721832584.5333793}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1721832587.3291473, "version": "2024.6.1"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1721832587.3322828}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3335738, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3359554, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3372462, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.342664, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.344461, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3456492, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.34631, "path": "authentik.blueprints.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3475711, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3484943, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3505821, "path": "authentik.enterprise.providers.google_workspace.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3527076, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3538847, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3555033, "path": "authentik.stages.authenticator_webauthn.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3562744, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1721832587.3577156, "path": "authentik.enterprise.providers.microsoft_entra.settings"}
/ak-root/venv/lib/python3.12/site-packages/opencontainers/distribution/reggie/defaults.py:17: SyntaxWarning: invalid escape sequence '\('
  "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
{"domain_url": null, "event": "Loaded MMDB database", "file": "/geoip/GeoLite2-ASN.mmdb", "last_write": 1720729304.0, "level": "info", "logger": "authentik.events.context_processors.mmdb", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:48.541654"}
{"domain_url": null, "event": "Loaded MMDB database", "file": "/geoip/GeoLite2-City.mmdb", "last_write": 1720729303.0, "level": "info", "logger": "authentik.events.context_processors.mmdb", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:48.544011"}
{"app_name": "authentik.tenants", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.tenants.checks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.641749"}
{"app_name": "authentik.tenants", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.tenants.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.642515"}
{"app_name": "authentik.admin", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.admin.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.708845"}
{"app_name": "authentik.admin", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.admin.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.709465"}
{"app_name": "authentik.crypto", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.crypto.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.710817"}
{"app_name": "authentik.flows", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.flows.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.760148"}
{"app_name": "authentik.outposts", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.outposts.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.802740"}
{"app_name": "authentik.outposts", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.outposts.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.803979"}
{"app_name": "authentik.policies.reputation", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.policies.reputation.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.805259"}
{"app_name": "authentik.policies", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.policies.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.817023"}
{"app_name": "authentik.providers.proxy", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.proxy.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.817966"}
{"app_name": "authentik.providers.proxy", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.proxy.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.818605"}
{"app_name": "authentik.providers.scim", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.scim.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.821777"}
{"app_name": "authentik.providers.scim", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.scim.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.823355"}
{"app_name": "authentik.rbac", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.rbac.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.824818"}
{"app_name": "authentik.sources.ldap", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.ldap.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.835863"}
{"app_name": "authentik.sources.ldap", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.ldap.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.838804"}
/ak-root/venv/lib/python3.12/site-packages/facebook/__init__.py:99: SyntaxWarning: invalid escape sequence '\d'
  version_regex = re.compile("^\d\.\d{1,2}$")
{"app_name": "authentik.sources.oauth", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.oauth.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.852188"}
{"app_name": "authentik.sources.saml", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.saml.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.853017"}
{"app_name": "authentik.sources.scim", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.scim.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.853931"}
{"app_name": "authentik.stages.authenticator_duo", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.authenticator_duo.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.854830"}
{"app_name": "authentik.stages.authenticator_static", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.authenticator_static.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:50.855622"}
{"app_name": "authentik.stages.authenticator_webauthn", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.authenticator_webauthn.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.004328"}
{"app_name": "authentik.stages.email", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.email.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.004828"}
{"app_name": "authentik.core", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.core.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.007728"}
{"app_name": "authentik.core", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.core.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.007938"}
{"app_name": "authentik.enterprise", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.008664"}
{"app_name": "authentik.enterprise", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.009355"}
{"app_name": "authentik.enterprise.providers.google_workspace", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.providers.google_workspace.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.010484"}
{"app_name": "authentik.enterprise.providers.google_workspace", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.providers.google_workspace.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.011113"}
{"app_name": "authentik.enterprise.providers.microsoft_entra", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.providers.microsoft_entra.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.011947"}
{"app_name": "authentik.enterprise.providers.microsoft_entra", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.providers.microsoft_entra.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.012512"}
{"app_name": "authentik.enterprise.providers.rac", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.providers.rac.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.019292"}
{"app_name": "authentik.events", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.events.tasks", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.019841"}
{"app_name": "authentik.events", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.events.signals", "pid": 795, "schema_name": "public", "timestamp": "2024-07-24T14:49:51.020029"}
Username: admin
Email address: davrot@uni-bremen.de
Password: 
Password (again): 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 52, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 89, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 238, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
  File "/ak-root/venv/lib/python3.12/site-packages/django/contrib/auth/models.py", line 172, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/contrib/auth/models.py", line 153, in _create_user
    user = self.model(username=username, email=email, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 556, in __init__
    _setattr(self, prop, value)
AttributeError: property 'is_staff' of 'User' object has no setter
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: compose.yaml
