### ISSUE TITLE
2024.6.1 Regression: Blueprint reference !KeyOf throws error "Object does not exist"

### ISSUE THREAD

**Issue by Salvoxia** [goauthentik/authentik#10679]
**Describe the bug**
Creating resources using blueprints and referencing them using the `!KeyOf` YAML tag throws an "object does not exist" error when importing the blueprint in Authentik 2024.6.1.
This does not seem to affect all resources, but is reliably reproducable with an OAuth2 Property Mapping used during creation of an OAuth2 provider as well as when referencing a provider during creation of an Application.
The same blueprint runs fine with Authentik 2024.4.3.

**To Reproduce**

1. Create and save the following blueprint
  ```yaml
   # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
    name: MiniO
entries:
  - attrs:
      description: Returns Minio Policies based on User Group Membership
      expression: "if ak_is_group_member(request.user, name=\"Minio Admins\"):\n  return\
        \ {\n      \"policy\": \"consoleAdmin\"\n  }\nelif ak_is_group_member(request.user,\
        \ name=\"Minio Users\"):\n  return {\n      \"policy\": \"readwrite\"\n  }\n\
        return None"
      managed: null
      name: Minio OIDC Scope Mapping
      scope_name: minio
    id: minio-oidc-property-mapping
    identifiers:
      name: Minio OIDC Scope Mapping
    model: authentik_providers_oauth2.scopemapping
    state: present
  # OAuth Provider
  - attrs:
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      client_id: ${MINIO_IDENTITY_OPENID_CLIENT_ID}
      client_secret: ${MINIO_IDENTITY_OPENID_CLIENT_SECRET}
      client_type: confidential
      include_claims_in_id_token: true
      issuer_mode: per_provider
      property_mappings:
      - !KeyOf minio-oidc-property-mapping
      - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''email''']]
      - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''openid''']]
      - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''profile''']]
      redirect_uris: https://minio-console.local/oauth_callback
      refresh_token_validity: days=30
      sub_mode: hashed_user_id
    conditions: []
    identifiers:
      name: Minio OAuth2
    id: minio-provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
  # MiniO Application
  - attrs:
      name: MiniO
      policy_engine_mode: any
      provider: !KeyOf minio-provider
      slug: minio
    conditions: []
    identifiers:
      name: MiniO
    id: minio
    model: authentik_core.application
    state: present
  
   ```
3. Log in to Authentik Admin interface and go to `Flows and Stages -> Flows`
4. Click on `Import`, select the file the blueprint from above is stored in and hit `Import` in the `Import Flow` dialog
5. See an error message `[ErrorDetail(string='Invalid pk "017039ed-05b8-4aca-9673-1640f64502cd" - object does not exist.', code='does_not_exist')]}`

**Expected behavior**
The blueprint should import successfully and create the following resources:
  - OAuth2 Property Mapping called `Minio OIDC Scope Mapping`
  - OAuth2 Provider called `Minio OAuth2`
  - Application called `MiniO`

**Screenshots**
![image](https://github.com/user-attachments/assets/19d67f5d-3b6d-4455-a7c4-0c907f532582)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: helm

**Additional context**
A similar error can be produced when removing they `!KeyOf` reference to the `minio-oidc-property-mapping`property mapping from the Provider `property_mappings` definition in the blueprint:
```yaml
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
    name: MiniO
entries:
  - attrs:
      description: Returns Minio Policies based on User Group Membership
      expression: "if ak_is_group_member(request.user, name=\"Minio Admins\"):\n  return\
        \ {\n      \"policy\": \"consoleAdmin\"\n  }\nelif ak_is_group_member(request.user,\
        \ name=\"Minio Users\"):\n  return {\n      \"policy\": \"readwrite\"\n  }\n\
        return None"
      managed: null
      name: Minio OIDC Scope Mapping
      scope_name: minio
    id: minio-oidc-property-mapping
    identifiers:
      name: Minio OIDC Scope Mapping
    model: authentik_providers_oauth2.scopemapping
    state: present
  # OAuth Provider
  - attrs:
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      client_id: ${MINIO_IDENTITY_OPENID_CLIENT_ID}
      client_secret: ${MINIO_IDENTITY_OPENID_CLIENT_SECRET}
      client_type: confidential
      include_claims_in_id_token: true
      issuer_mode: per_provider
      property_mappings:
      - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''email''']]
      - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''openid''']]
      - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''profile''']]
      refresh_token_validity: days=30
      sub_mode: hashed_user_id
    conditions: []
    identifiers:
      name: Minio OAuth2
    id: minio-provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
  # MiniO Application
  - attrs:
      name: MiniO
      policy_engine_mode: any
      provider: !KeyOf minio-provider
      slug: minio
    conditions: []
    identifiers:
      name: MiniO
    id: minio
    model: authentik_core.application
    state: present
```
The error now references the provider primary key in the Application definition: `Entry invalid: Serializer errors {'provider': [ErrorDetail(string='Invalid pk "76" - object does not exist.', code='does_not_exist')]}`
![image](https://github.com/user-attachments/assets/8083548b-5afe-41d8-b614-2749bb37b6ab)
