### ISSUE TITLE
AzureAD groups saving after user login

### ISSUE THREAD

**Issue by nbragin4** [goauthentik/authentik#10980]
**Describe your question/**
I need to keep groups from AzureAD when user enrollment and keep them in sync every time when user logins via AzureAD social login, but doesn't find any information about groups syncing from upstream OIDC provider. Is there any relevant info about it? Thanks!

**Additional context**
AzureAD backend configured for getting groups from groups claim.
my current configuration for login with dex (argocd) looks like that:
```yaml
name: $oidc-credentials:name
issuer: $oidc-credentials:issuer
clientID: $oidc-credentials:client-id
clientSecret: $oidc-credentials:client-secret
requestedIDTokenClaims:
  groups:
      essential: true
requestedScopes:
  - openid
  - profile
  - email
```
with this config it successfully read groups from azure. how can i automatically create groups from upsteam oidc provider in authentik? (or map it with expression policy)
