### ISSUE TITLE
Forward Auth (Domain) not setting current Client ID for Authentication Flow

### ISSUE THREAD

**Issue by AngellusMortis** [goauthentik/authentik#11010]
**Describe the bug**

When the user is redirected as part of a forward auth (domain level) authentication flow, it is not detecting and setting the client ID for the source application correctly. It is leading to every application to be listed as the last one in the list alphabetically.

My assumption of what is happening:
I understand it is definitely because of the domain auth, each app/provider does not have a fixed URL location (Launch URL does not count). As a result, there is nothing for the Outpost to look up against to set the client ID.

**To Reproduce**

1. Set up Forward Level domain auth
2. Set up at least 2 applications using it that are on the same cookie domain as Authentik and are sibling subdomains to authentik
3. Try to login with each service
4. Notice all but one of the applications will have the incorrect app for "Login to continue to __"

**Expected behavior**

Correct Client ID should be set for domain level forward auth

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.3
-   Deployment: helm

I am running authentik inside of k8s. There is the default outpost that all providers are assigned to. Then for each application I am running on the cluster, I have a have forward auth (domain) provider providing auth. So, everything is setup like this:

auth.example.com -> authentik
app1.example.com -> app1
app2.example.com -> app2
etc.

Every application has a "Launch URL set". Every provider has Authentication URL set to `https://auth.example.com` and Cookie Domain set to `example.com`. There is a single outpost that handles every application with `authentik_host` set to `https://auth.example.com/`

Each app is set up with ingress-nginx with the following annotations (for authentik):
```
      nginx.ingress.kubernetes.io/auth-url: |-
          http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
      nginx.ingress.kubernetes.io/auth-signin: |-
          https://auth.wl.mort.is/outpost.goauthentik.io/start?rd=$scheme%3A%2F%2F$host$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
      nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
```

**Additional context**

I encountered [a similar issue](https://github.com/goauthentik/authentik/issues/1997) that turned out to (possibly?) just be a documentation issue. The documentation for ingress-nginx on the provider does not really update correctly if it is domain level. There is just a single comment about it:

```yml
metadata:
    annotations:
        # This should be the in-cluster DNS name for the authentik outpost service
        # as when the external URL is specified here, nginx will overwrite some crucial headers
        nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-example.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        # If you're using domain-level auth, use the authentication URL instead of the application URL
        nginx.ingress.kubernetes.io/auth-signin: |-
            https://app.company/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
```

Specifically:

```yml
        # If you're using domain-level auth, use the authentication URL instead of the application URL
        nginx.ingress.kubernetes.io/auth-signin: |-
            https://app.company/outpost.goauthentik.io/start?rd=$escaped_request_uri
```

I noticed that `rd` always seemed to be relative to the `auth-signin` URL. Meaning if you do `rd=/` for a domain level, it will redirect to Authentik, not the app since `/` on `https://app.company` is Authentik. So, the issue seems like the outpost for Domain Level forward auth cannot determine the source application by itself (my original assumption). Perhaps there is already another query parameter that can be passed to the outpost to make this work?
