### ISSUE TITLE
"Failed to get token from provider" - Grafana

### ISSUE THREAD

**Issue by yash2002vardhan** [goauthentik/authentik#11167]
I have authentik running on a separate server and I have a nginx proxy to access it. Now I am trying to integrate grafana into it, whereby I am running grafana on a separate server, for which I have a nginx proxy configured. When trying to login getting the following error:

"Login Failed
Failed to get token from provider"

How to solve the error ?

**Comment by rouke-broersma** [comment]
I have recently been getting this error, while I previously had a working integration with Grafana.

**Comment by BeryJu** [comment]
Could you provide more details about your setup, what providers/outposts/grafana configuration you are using? From my understanding it seems that you are using Grafana with forward authentication, which isn't recommended, as Grafana supports OIDC natively and should be configured like this: https://docs.goauthentik.io/integrations/services/grafana/

**Comment by rouke-broersma** [comment]
I have grafana connected with oidc. This turned out to be a dns issue, grafana was unable to contact authentik (while I was) resulting in grafana being unable to obtain the token. Forgot to circle back with that info.

**Comment by uwugression** [comment]
For me it was this error from the grafana container on k8s (kube-prometheus-stack):

```
level=error msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.token.exchange] tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

## 1. Quick insecure check/fix
to verify if you're having the same issue is to set this in `values.yaml`:
```yaml
grafana.ini:
  auth.generic_oauth:
    tls_skip_verify_insecure: true
```

## 2. Solution
via volume mounted configmap, so first create the configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ca
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: ...
```

Then use an init container to create a combined crt file. Grafana version for the initContainer should match your grafana version:
```yaml
    extraInitContainers:
      - name: setup-ca
        image: grafana/grafana:12.2.0
        command:
          - sh
          - -c
          - |
            cat /custom-ca/ca.crt > /ssl-shared/ca-certificates.crt
        volumeMounts:
          - name: custom-ca
            mountPath: /custom-ca
          - name: ssl-shared
            mountPath: /ssl-shared
    extraVolumeMounts:
      - name: ssl-shared
        mountPath: /etc/ssl/certs
    extraVolumes:
      - name: custom-ca
        configMap:
          name: configmap-ca
      - name: ssl-shared
        emptyDir: {}
```
