### ISSUE TITLE
Source icon color inverted in dark mode

### ISSUE THREAD

**Issue by larsl-net** [goauthentik/authentik#11387]
**Describe the bug**
When using an OAuth Source for login, the Icon of the provider gets inverted when using the dark mode.
In the screenshot, the GitLab icon is shown in blue instead of orange.

**To Reproduce**

1. Create a `OAuth source` under `Federation and Social login`
2. Add a icon ex. [GitLab Logo](https://images.ctfassets.net/xz1dnu24egyd/3JZABhkTjUT76LCIclV7sH/17a92be9bce78c2adcc43e23aabb7ca1/gitlab-logo-500.svg)
3. Add source to `Identification Stage`
4. See broken icon color on login page

**Expected behavior**
Icons are shown with original colors

**Screenshots**
Dark mode
![image](https://github.com/user-attachments/assets/b9efcf7b-b409-488d-b90f-5fcc1bc78e6c)

Light mode
![image](https://github.com/user-attachments/assets/2a0e323a-57e7-4556-8553-17242886c451)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose
-   Browser: Firefox and Brave

**Additional context**

**Comment by larsl-net** [comment]
I was able to build simple a workaround with the following custom CSS, which works for the source icons in the authentication flow and the user settings. Maybe there are more points where the colors are inverted, and this is only tested with version `2024.8.2`.

```css
/* User customisable */
@media (prefers-color-scheme: dark){
  body > ak-flow-executor > ak-locale-context > div.pf-c-page__drawer.style-scope.ak-flow-executor > div > div > div > div > div > div > div > ak-stage-identification > footer > ul > li > button > span > img,
  li.pf-c-data-list__item > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > img:nth-child(1) {
      filter: invert(0);
  }
}
```

**Comment by wegylexy** [comment]
```css
@media (prefers-color-scheme: dark) {
  .pf-c-login__main-footer-links-item img, .pf-c-login__main-footer-links-item .fas {
      filter: none;
  }
}
```
for `2025.6.1`

**Comment by functionaldude** [comment]
this fix stopped working with `2025.12.1` and the problem is back

**Comment by larsl-net** [comment]
Custom CSS is broken in 2025.12 based on #19556 

This CSS should theoretically work.
```css
@media (prefers-color-scheme: dark) {
  .pf-c-login__main-footer-links-item img,
  .pf-c-login__main-footer-links-item .fas,
  img.ak-stage-identification,
  .pf-c-button__icon.ak-stage-identification .fas.ak-stage-identification,
  .pf-c-data-list__cell img
  {
      filter: invert(0) !important;
  }
}
```

**Comment by functionaldude** [comment]
@larsl-net thank you for the suggestion! I just tried it out and it does not seem to work. My assumption is that the problem is shadow-dom related

**Comment by MaxValue** [comment]
The solution would be somewhat like

```css
ak-flow-executor::part(source-icon) {
  filter: unset !important;
}
```

though I am not sure how the [exportparts](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/exportparts) feature works exactly.

In any case this solution cannot work currently because the `source-icon` part is currently not exported.

**Comment by Mmx233** [comment]
It seems there have been some changes to adopted-style-sheet injection in 2025.12; brand CSS is no longer being injected into deep Shadow DOM elements.

**Comment by gabriel-brunet-cmm** [comment]
Had the same issue. This seems to currently work : 
```css
fieldset > button.pf-c-button.source-button > span.pf-c-button__icon.pf-m-start > img {
  filter: unset !important;
}
```

Though it would be nice if it was a toggle we could control.
