### ISSUE TITLE
Server fails to start with a django error

### ISSUE THREAD

**Issue by nchietala** [goauthentik/authentik#11382]
**Describe the bug**
When starting the server I see an error related the django settings, after which gunicorn dies (presumably django killed it) and the server exits.

**To Reproduce**
Use the following docker-compose.yml:
```yml
version: "3.7"

services:
  # postgresql and redis running in their own stack on the overlay network, ensure authentik database exists and is owned by authentik user

  server:
    image: ghcr.io/goauthentik/server:2024.8.1
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__DB: 0
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${SECRET_KEY}
      AUTHENTIK_LOG_LEVEL: warning
      
    volumes:
      - ${DATA_ROOT}/media:/media
      - ${DATA_ROOT}/custom-templates:/templates
      - ${DATA_ROOT}/csrf.py:/data/user_settings.py
    networks:
      - overlay
    ports:
      - "127.0.0.1:9000:9000"  # reverse-proxy through nginx for ssl termination
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  worker:
    image: ghcr.io/goauthentik/server:2024.8.1
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__DB: 0
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${SECRET_KEY}
      AUTHENTIK_LOG_LEVEL: warning
      
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_ROOT}/media:/media
      - ${DATA_ROOT}/certs:/certs
      - ${DATA_ROOT}/custom-templates:/templates
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

networks:
  overlay:
    external: true
```

**Logs**
```
2024-09-14 21:28:31 [info     ] waiting to acquire database lock
2024-09-14 21:28:31 [info     ] applying django migrations
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1726349313.7615798, "version": "2024.8.1"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1726349313.7652197}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7669296, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7689505, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7701383, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.772853, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.778146, "path": "authentik.stages.authenticator_webauthn.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.781322, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7825363, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7836971, "path": "authentik.enterprise.providers.google_workspace.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7869737, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7890306, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7916894, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7929146, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7940247, "path": "authentik.blueprints.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.795081, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.797362, "path": "authentik.enterprise.providers.microsoft_entra.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349313.7980378, "path": "data.user_settings"}
SystemCheckError: System check identified some issues:

ERRORS:
?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found . See the release notes for details.
{"error":"exit status 1","event":"gunicorn process died, restarting","level":"warning","logger":"authentik.router","timestamp":"2024-09-14T21:28:40Z"}
{"error":"exit status 1","event":"gunicorn failed to start, restarting","level":"error","logger":"authentik.router","timestamp":"2024-09-14T21:28:40Z"}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349321.304624, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1726349321.305387, "count": 15}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1726349322.7287772}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1726349322.7489085}
{"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1726349322.7509327}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1726349322.751076}
{"error":"authentik starting","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2024-09-14T21:28:44Z"}
```
**Version and Deployment**

-   authentik version: 2024.8.1
-   Deployment: docker swarm

**Additional context**
I also tried running it via `docker compose up` to see if it was the swarm's fault but I'm not sure if that actually creates standalone-style containers when docker is in swarm mode. Of course the log says it's an issue with the django settings and I can't see how that would be resolved by being standalone.
