### ISSUE TITLE
/application/o/authorize Not Found

### ISSUE THREAD

**Issue by aolvictim** [goauthentik/authentik#11611]
**Describe your question/**
Fresh install via Docker Compose, trying to create my first OAuth2 application. But the authorization endpoint `/application/o/authorizer/` always returns 404. All other endpoints work.

**Relevant info**
Here is my docker compose. All I changed was bind mount

```yaml
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./data/redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.3}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./data/media:/media
      - ./data/custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.2}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/media:/media
      - ./data/certs:/certs
      - ./data/custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
```

**Screenshots**
<img width="934" alt="Screenshot 2024-10-03 at 4 40 35 PM" src="https://github.com/user-attachments/assets/76e4fcdf-42ce-4590-bafc-1eda8670d36f">

**Logs**
```log
INF auth_via=unauthenticated domain_url=localhost event=/ host=localhost:8000 logger=authentik.asgi method=OPTIONS pid=9206 remote=10.0.0.2 request_id=894d8540cb1d4a32ad45870368e174a5 runtime=23 schema_name=public scheme=https status=302 timestamp=2024-10-03T23:27:29.670565 user= user_agent=
{"auth_via": "session", "domain_url": "*REDACTED*", "event": "/application/o/authorize?client_id=HaYUqSMHpdSvpNIvV3eiCSu2woqb43rapBHBHvfC&redirect_uri=https%3A%2F%2Foauthdebugger.com%2Fdebug&scope=offline_access%20email%20profile%20openid&response_type=token&response_mode=query&state=5q3db6txesp&nonce=m86bpgigvgn", "host": "*REDACTED*", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 9206, "remote": "10.0.100.1", "request_id": "a1a29fa292d74491b0bf12eea1a889b1", "runtime": 35, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2024-10-03T23:27:30.528850", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**
-   authentik version: 2024.8.3
-   Deployment: docker-compose,helm
