### ISSUE TITLE
ingress-nginx returns 500 for some applications

### ISSUE THREAD

**Issue by ImDevinC** [goauthentik/authentik#11690]
**Describe your question/**
I'm running inside Kubernetes with ingress-nginx as my controller. On some of my applications, nginx returns a 500 error instead of redirecting me to the authentik login. But on other applications, it works as expected. If I remove the authentik annotations on the applications that fail, I am able to load the application, but not login (since the routes are configured)

**Relevant info**
```
authentik host: authentik.collins.home
failing application host: overseerr.collins.home
succeeded application host: radarr.collins.home
```

I have configured all applications as forward auth and added the following annotations the the ingress controllers for each app (where the auth-signin url <app> is either `radarr` or `overseerr`)
```yaml
nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,authorization                                           
nginx.ingress.kubernetes.io/auth-signin: http://<app>.collins.home/outpost.goauthentik.io/start?rd=$escaped_request_uri                                                                                         
nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;                                                                                                                          
nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx 
```
The only real difference between these two apps is that radarr uses header authorization and overseer uses a cookie with a custom property mapping.
```python
from authentik.sources.plex.models import UserPlexSourceConnection
import json

connection = UserPlexSourceConnection.objects.filter(user=request.user).first()
if not connection:
    ak_logger.info("Overseer: No Plex connection found")
    return {}

base_url = "http://overseerr.mediaserver:5055"
end_point = "/api/v1/auth/plex"

headers = {
    "Content-Type": "application/json",
}

data = {
    "authToken": connection.plex_token
}

response = requests.post(base_url + end_point, headers=headers, data=json.dumps(data))

if response.status_code == 200:
    sid_value = response.cookies.get("connect.sid")
    cookie_obj = f"connect.sid={sid_value}"
    ak_logger.info("Overseer: Successfully authenticated with Plex token")
    return {
        "ak_proxy": {
            "user_attributes": {
                "additionalHeaders": {
                    "Cookie": cookie_obj
                }
            }
        }
    }
else:
    ak_logger.error(f"Overseer: The request failed with: {response.text}")
    return {}
```
If I look at trace logs for the authentik-server, I can see that the cookie object is properly attached.

When navigating to `http://radarr.collins.home`, if I follow the network request I can see an immediate 302 redirect to authentik. However if I do the same on `http://overseer.collins.home`, I get an immediate 500 error, with no attempt to redirect.

**Logs**
```
...
{"event":"tracing request to backend","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Accept-Language":["en-US,en;q=0.9"],"Cache-Control":["max-age=0"],"Connection":["close"],"Cookie":["connect.sid=<redacted>"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"],"X-Auth-Request-Redirect":["/"],"X-Forwarded-For":["10.244.0.1"],"X-Forwarded-Host":["overseerr.collins.home"],"X-Original-Method":["GET"],"X-Original-Url":["http://overseerr.collins.home/"],"X-Real-Ip":["10.244.0.1"],"X-Request-Id":["221e3a396c4b773ae3eb9aa35ffe33bf"],"X-Sent-From":["nginx-ingress-controller"]},"level":"trace","logger":"authentik.router","timestamp":"2024-10-15T16:48:31Z","url":"http://localhost:8000/outpost.goauthentik.io/auth/nginx"}
...
```

**Version and Deployment (please complete the following information):**
- kubernetes version: 1.31.1
- ingress-nginx version: 1.11.2
- authentik version: 2024.8.3
