### ISSUE TITLE
PostgreSQL Connection failed when deployed by docker-compose

### ISSUE THREAD

**Issue by AminSaqi** [goauthentik/authentik#1184]
**Describe the bug**
Going through [docs](https://goauthentik.io/docs/installation/docker-compose), I see postgres errors '' repeatedly in server container.

I've double-checked the db password in environment with 'docker-compose config' and I'm sure that the password is set correctly, and is identical for db and server containers.

**To Reproduce**
Follow the instruction in [docker-compose installation](https://goauthentik.io/docs/installation/docker-compose) page.

**Logs**
I see the following error repeatedly in 'docker logs' of the server container:

{"event": "PostgreSQL Connection failed, retrying... (FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1627328759.8335326}

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Hi, just tried to reproduce this with a fresh install and that starts up without issues. 

Did you run the commands in the Preparation segment to generate the `.env` file?

**Comment by AminSaqi** [comment]
Yes, and I double-checked them with 'docker-compose config'.

Tommorrow I'll send you my .env file here.

**Comment by AminSaqi** [comment]
This is content of .env file:

```
PG_PASS=wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
AUTHENTIK_SECRET_KEY=phiZai5toi1ieBea0einaiQu4poo2eepie3aigahta5lewex
```

And here is the resulted `docker-compose config` output:

```
networks:
  internal: {}
services:
  geoipupdate:
    environment:
      AUTHENTIK_SECRET_KEY: phiZai5toi1ieBea0einaiQu4poo2eepie3aigahta5lewex
      GEOIPUPDATE_EDITION_IDS: GeoLite2-City
      GEOIPUPDATE_FREQUENCY: '8'
      PG_PASS: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
    image: maxmindinc/geoipupdate:latest
    volumes:
    - geoip:/usr/share/GeoIP:rw
  postgresql:
    environment:
      AUTHENTIK_SECRET_KEY: phiZai5toi1ieBea0einaiQu4poo2eepie3aigahta5lewex
      PG_PASS: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
      POSTGRES_USER: authentik
    image: postgres:12-alpine
    networks:
      internal: null
    restart: unless-stopped
    volumes:
    - database:/var/lib/postgresql/data:rw
  redis:
    image: redis:alpine
    networks:
      internal: null
    restart: unless-stopped
  server:
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_SECRET_KEY: phiZai5toi1ieBea0einaiQu4poo2eepie3aigahta5lewex
      PG_PASS: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
    image: ghcr.io/goauthentik/server:2021.6.4
    networks:
      internal: null
    ports:
    - 0.0.0.0:9000:9000/tcp
    - 0.0.0.0:9443:9443/tcp
    restart: unless-stopped
    volumes:
    - /var/authentik/media:/media:rw
    - /var/authentik/custom-templates:/templates:rw
    - geoip:/geoip:rw
  worker:
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_SECRET_KEY: phiZai5toi1ieBea0einaiQu4poo2eepie3aigahta5lewex
      PG_PASS: wahquoh3co1kiejahj2Wee4ohhoVoh5ohz0
    image: ghcr.io/goauthentik/server:2021.6.4
    networks:
      internal: null
    restart: unless-stopped
    user: root
    volumes:
    - /var/authentik/backups:/backups:rw
    - /var/authentik/media:/media:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /var/authentik/custom-templates:/templates:rw
    - geoip:/geoip:rw
version: '3.2'
volumes:
  database:
    driver: local
  geoip:
    driver: local
```
