### ISSUE TITLE
Invalid Challenge and Missing Password for RADIUS Authentication Attempt

### ISSUE THREAD

**Issue by ebadfd** [goauthentik/authentik#11974]
**Describe your question**

When attempting to set up RADIUS authentication, I encounter an error indicating an "Invalid Challenge" and that the "Password is not set for ident+auth attempt." This is unusual since the password is already configured for the user, and login through the dashboard is successful.

**Relevant info**

following is my UNLEASHED configuration for the radius server

![image](https://github.com/user-attachments/assets/9d5c51db-a0ca-4e17-8bff-a48fd94eee3e)

But when I test this using UNLEASHED dashboard this seems to be functioning as expected 

![image](https://github.com/user-attachments/assets/b7ee9746-4d2e-4b54-b9f0-c9c936368cf7)

Where this fails is when i try to connect using wpa enterprise following is how the configuration looks for wpa

![image](https://github.com/user-attachments/assets/5aba287b-299d-453f-a6d6-dbe0aa8c2e0e)

And following is my nmconnection as well

```
[connection]
id=radius_test
uuid=a8fd8f45-53ea-48d4-a0d6-74e2b3868beb
type=wifi
interface-name=wlan0
timestamp=1731104786

[wifi]
mode=infrastructure
ssid=radius_test

[wifi-security]
auth-alg=open
key-mgmt=wpa-eap
psk=password

[802-1x]
eap=peap;
identity=akadmin
password=*******
phase2-auth=pap

[ipv4]
method=auto

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
```

Here is the configuration of the radius authentication flow

```yaml
context: {}
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: authentication
    layout: stacked
    name: radius-authentication
    policy_engine_mode: any
    title: radius-authentication
  conditions: []
  identifiers:
    pk: 575415d0-ee18-4b9e-bd73-525d07a5b537
    slug: radius-authentication
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs:
    case_insensitive_matching: true
    password_stage: 7279e313-a8f5-4f23-adef-f85064011f9f
    pretend_user_exists: true
    show_matched_user: true
    user_fields:
    - username
  conditions: []
  identifiers:
    name: radius-auth-identification
    pk: 27a3edd2-4e0b-40fd-8a0a-db43623b89c1
  model: authentik_stages_identification.identificationstage
  permissions: []
  state: present
- attrs:
    geoip_binding: bind_continent
    network_binding: bind_asn
    remember_me_offset: seconds=0
    session_duration: seconds=0
  conditions: []
  identifiers:
    name: radius-auth-login
    pk: 8f3ea389-7e7e-49ce-8027-e943c666a239
  model: authentik_stages_user_login.userloginstage
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 10
    pk: c98f70d3-6fd0-461f-a93a-00a87e3516c9
    stage: 27a3edd2-4e0b-40fd-8a0a-db43623b89c1
    target: 575415d0-ee18-4b9e-bd73-525d07a5b537
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 100
    pk: 3f77e928-a1a2-4868-8bc0-4a3c28bceff5
    stage: 8f3ea389-7e7e-49ce-8027-e943c666a239
    target: 575415d0-ee18-4b9e-bd73-525d07a5b537
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2024-11-09 09:50:41.788203+00:00
version: 1
```

**Screenshots**

**Logs**
```
[server]     | {"auth_via": "unauthenticated", "domain_url": "192.168.1.110", "errors": {"captcha_stage": ["This field may not be null."]}, "event": "f(ch): Invalid challenge", "host": "192.168.1.110:9000", "level": "warning", "logger": "authentik.flows.stage", "pid": 40, "request_id": "00c9e0cd82eb40119093db12eb73c194", "schema_name": "public", "stage": "radius-auth-identification", "stage_view": "authentik.stages.identification.stage.IdentificationStageView", "timestamp": "2024-11-09T09:46:52.303777"}
[server]     | {"auth_via": "unauthenticated", "domain_url": "192.168.1.110", "event": "/api/v3/flows/executor/radius-authentication/?query=goauthentik.io%252Foutpost%252Fradius%3Dtrue", "host": "192.168.1.110:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 40, "remote": "192.168.1.99", "request_id": "00c9e0cd82eb40119093db12eb73c194", "runtime": 94, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2024-11-09T09:46:52.306361", "user": "", "user_agent": "goauthentik.io/outpost/2024.10.1"}
[server]     | {"auth_via": "unauthenticated", "domain_url": "192.168.1.110", "event": "Password not set for ident+auth attempt", "host": "192.168.1.110:9000", "level": "warning", "logger": "authentik.flows.stage", "pid": 40, "request_id": "e1cd676941034e479d98642e31b577a2", "schema_name": "public", "stage": "radius-auth-identification", "stage_view": "authentik.stages.identification.stage.IdentificationStageView", "timestamp": "2024-11-09T09:46:52.366774"}
[server]     | {"action": "login_failed", "auth_via": "unauthenticated", "client_ip": "192.168.1.99", "context": {"http_request": {"args": {"goauthentik.io/outpost/radius": "true"}, "method": "POST", "path": "/api/v3/flows/executor/radius-authentication/", "request_id": "e1cd676941034e479d98642e31b577a2", "user_agent": "goauthentik.io/outpost/2024.10.1"}, "password": "********************", "stage": {"app": "authentik_stages_identification", "model_name": "identificationstage", "name": "radius-auth-identification", "pk": "27a3edd24e0b40fd8a0adb43623b89c1"}, "username": "akadmin"}, "domain_url": "192.168.1.110", "event": "Created Event", "host": "192.168.1.110:9000", "level": "info", "logger": "authentik.events.models", "pid": 40, "request_id": "e1cd676941034e479d98642e31b577a2", "schema_name": "public", "timestamp": "2024-11-09T09:46:52.785438", "user": {"email": "user@example.com", "pk": 6, "username": "akadmin"}}
[server]     | {"auth_via": "unauthenticated", "domain_url": "192.168.1.110", "event": "Task published", "host": "192.168.1.110:9000", "level": "info", "logger": "authentik.root.celery", "pid": 40, "request_id": "e1cd676941034e479d98642e31b577a2", "schema_name": "public", "task_id": "75b1d0abc4974ba68f862a078698a21a", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2024-11-09T09:46:52.807738"}
```

logs from the radius_outpost

```
[radius_outpost] | {"code":"Access-Request","error":"flow error non_field_errors: Failed to authenticate.","event":"failed to execute flow","level":"warning","logger":"authentik.outpost.radius","request":"bf5c55f1-478d-467f-b35f-a27445f86185","timestamp":"2024-11-09T09:47:07Z","username":"akadmin"}
[radius_outpost] | {"code":"Access-Request","event":"Radius Request","level":"info","logger":"authentik.outpost.radius","request":"52f5eb4f-328e-4616-a15e-c0f4c47696a3","timestamp":"2024-11-09T09:47:18Z"}
[radius_outpost] | {"code":"Access-Request","error":"flow error non_field_errors: Failed to authenticate.","event":"failed to execute flow","level":"warning","logger":"authentik.outpost.radius","request":"52f5eb4f-328e-4616-a15e-c0f4c47696a3","timestamp":"2024-11-09T09:47:19Z","username":"akadmin"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.1
-   Deployment: docker-compose

**Additional context**
