### ISSUE TITLE
Proxy Provider - Forward Auth (domain level) can't work on Non-443 ports

### ISSUE THREAD

**Issue by CHANTXU64** [goauthentik/authentik#12503]
**Describe the bug**
When using Traefik to reverse proxy applications with Authentik authentication, and having both 443 and 4443 ports open, accessing the application via port 4443 results in a page showing only the Authentik logo and the message “authentik Logo Not Found Go home Powered by authentik”. Other resources fail to load, and login is not possible. Port 443, however, works correctly for login and redirects.
```
authentik Logo
Not Found
Go home
Powered by authentik
```

**To Reproduce**

1. Treafik config:
```yaml
http:
  routers:
    router-whoami:
      entryPoints:
        - "web443"
        - "web4443"
      rule: "Host(`whoami.xxx.com`)"
      middlewares:
        - authentik
      service: authentik
    router-authentik:
      entryPoints:
        - "web443"
        - "web4443"
      rule: "Host(`auth.xxx.com`)"
      service: authentik
  middlewares:
    authentik:
      forwardAuth:
        address: http://172.16.0.100:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
  services:
    authentik:
      loadBalancer:
        servers:
          - url: http://172.16.0.100:9000
    whoami:
      loadBalancer:
        servers:
          - url: http://172.16.0.100:4001
```
2. Create Authentik Proxy Provider - Forward Auth (domain level):
Authentication URL: https://auth.xxx.com:443
Cookie domain: xxx.com
3. Create Applications
Name: Treafik
Set provider
4. Edit authentik Embedded Outpost
Select Treafik Application
Advanced settings - authentik_host: https://auth.xxx.com:443

**Expected behavior**
Port 4443 should behave the same as port 443, allowing normal login and proper resource loading.

**Screenshots**

**Logs**
docker-compose logs:
```log
Port 4443:
INF auth_via=unauthenticated domain_url=whoami.xxx.com event=/outpost.goauthentik.io/auth/traefik host=whoami.xxx.com:4443 logger=authentik.asgi method=GET pid=64548 remote=192.168.127.66 request_id=0e9d4e30757e4dbba6f68b117f610ad4 runtime=10 schema_name=public scheme=https status=404 timestamp=2024-12-27T09:24:16.910949 user= user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

Port 443:
INF event=/outpost.goauthentik.io/auth/traefik host=whoami.xxx.com logger=authentik.outpost.proxyv2.application method=GET name=Provider for Traefik remote=192.168.127.66 runtime=0.300 scheme=http size=0 status=0 timestamp=2024-12-27T09:24:23Z user=chantxu user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
```

**Version and Deployment (please complete the following information):**

-   authentik version: ghcr.io/goauthentik/server:2024.10.4
-   Deployment: docker-compose

**Additional context**

**Comment by CHANTXU64** [comment]
like #12492

**Comment by tarihub** [comment]
> like #12492

I have solved in NPM

**Comment by CHANTXU64** [comment]
Thank you. I tested with Nginx, and it works fine for authentication and login. However, after the first login, it cannot redirect back to the original URL.

I have now added a header modification plugin in Traefik to remove the port from the Host. After disabling Authentik authentication and opening `https://whoami.xxx.com:4443/`, I can see that the port is indeed removed from the Host header. After re-enabling Authentik authentication, the login works correctly, but after the first login, it redirects to `https://whoami.xxx.com/` instead of `https://whoami.xxx.com:4443/`.

I now have strong reason to believe that the issue lies with how Authentik is handling the Host header parsing.

**Comment by hanley-development** [comment]
I can connect to authentik using a non 443  entrypoint port , but once changing the application entrypoint Authentik just loops


```yaml
services:
  authentik_server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.0}
......Standard setup......
      ## HTTP Routers
       - "traefik.http.routers.authentik-external-server.rule=Host(`authentik.$EXTERNAL_DOMAIN`)"
       - "traefik.http.routers.authentik-external-server.entrypoints=http-external"
       - "traefik.http.routers.authentik-external-server.middlewares=authentik-external-server-redirect"
       - "traefik.http.middlewares.authentik-external-server-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.authentik-external-server-secure.rule=Host(`authentik.$EXTERNAL_DOMAIN`)"
       - "traefik.http.routers.authentik-external-server-secure.entrypoints=https-external"
       - "traefik.http.routers.authentik-external-server-secure.tls=true"
       - "traefik.http.routers.authentik-external-server-secure.tls.certresolver=cloudflare"
       ## HTTP-Services
       - "traefik.http.routers.authentik-external-server-secure.service=authentik-external-server-svc"
       - "traefik.http.routers.authentik-external-server.service=authentik-external-server-svc"
       - "traefik.http.services.authentik-external-server-svc.loadbalancer.server.scheme=https"
       - "traefik.http.services.authentik-external-server-svc.loadBalancer.server.port=9443"
         ## Middlewares
       - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
   
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
       proxy:
    ports:
      - 80:80
      - 443:443
      - 81:81 #http External
      - 444:444 #https External
    secrets:
      - cf_api_key
      - cf_api_email
    environment:
      CF_API_EMAIL_FILE: /run/secrets/cf_email
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_key
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.traefik-bypass.entrypoints=http"
      - "traefik.http.routers.traefik-bypass.rule=Host(`$TRAEFIK_HOST`) && ClientIP(`192.168.5.6`)"
      - "traefik.http.routers.traefik-bypass.middlewares=traefik-https-redirect"
      ## HTTP Routers Auth
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`$TRAEFIK_HOST`)"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      ## Middlewares
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      ## HTTPS Routers Auth Bypass
      - "traefik.http.routers.traefik-secure-bypass.entrypoints=https"
      - "traefik.http.routers.traefik-secure-bypass.rule=Host(`$TRAEFIK_HOST`) && ClientIP(`192.168.5.6`)"
      - "traefik.http.routers.traefik-secure-bypass.tls=true"
      - "traefik.http.routers.traefik-secure-bypass.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure-bypass.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.traefik-secure-bypass.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.traefik-secure-bypass.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure-bypass.service=api@internal"
      ## HTTPS Routers Auth MFA
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`$TRAEFIK_HOST`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[1].main=${AUTHENTIK_HOST_BROWSER}"
      - "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.${AUTHENTIK_HOST_BROWSER}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=middlewares-authentik@file"
      - "traefik.http.middlewares.crowdsec-root.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-root.plugin.crowdsec-bouncer.crowdseclapikey=$CROWDSEC_TRAEFIK_BOUNCER_API_KEY"
      - "traefik.http.middlewares.crowdsec-root.plugin.crowdsec-bouncer.crowdseclapischeme=http"
      - "traefik.http.middlewares.crowdsec-root.plugin.crowdsec-bouncer.crowdseclapihost=crowdsec:8080"

secrets:
   cf_api_key:
     file: /home/mhanl/docker/stacks/traefik/data/secrets/cf_api_key.secret
   cf_api_email:
     file: /home/mhanl/docker/stacks/traefik/data/secrets/cf_api_email.secret

networks:
  proxy:
    external: true

```

application:
```yaml
services:
  whoami-test:
    image: traefik/whoami
    container_name: whoami-test
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whoami-test.entrypoints=http-external"
      - "traefik.http.routers.whoami-test.rule=Host(`whoami-test.$EXTERNAL_DOMAIN`)"
      - "traefik.http.middlewares.whoami-test-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.whoami-test.middlewares=whoami-test-https-redirect"
      - "traefik.http.routers.whoami-test-secure.entrypoints=https-external"
      - "traefik.http.routers.whoami-test-secure.rule=Host(`whoami-test.$EXTERNAL_DOMAIN`)"
      - "traefik.http.routers.whoami-test-secure.tls=true"
      - "traefik.http.routers.whoami-test-secure.tls.certresolver=cloudflare"
      ## Middlewares
      - "traefik.http.routers.whoami-test-secure.middlewares=authentik-external@file"
      - "traefik.http.routers.whoami-test-secure.service=whoami-test"
      - "traefik.http.services.whoami-test.loadbalancer.server.port=80"
     
networks:
  proxy:
    external: true
 ```
 
 traefik config.yml using authentik proxy:
 ```yaml
    authentik-external:
      forwardAuth:
        address: http://authentik-external:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
         - X-authentik-username
         - X-authentik-groups
         - X-authentik-entitlements
         - X-authentik-email
         - X-authentik-name
         - X-authentik-uid
         - X-authentik-jwt
         - X-authentik-meta-jwks
         - X-authentik-meta-outpost
         - X-authentik-meta-provider
         - X-authentik-meta-app
         - X-authentik-meta-version
 ```
