### ISSUE TITLE
k8s outpost integration: _ in outpost name breaks deployment

### ISSUE THREAD

**Issue by RaicuRobert** [goauthentik/authentik#12568]
**Describe the bug**
When deploying an outpost in a k8s environment using blueprints via helm, the deployments, secrets and other components are not created.

**To Reproduce**

1. Create an outpost blueprint of the form
```yaml
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json

context: {}
entries:
  - model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        name: ldap-provider-blueprint
      required: true

  - attrs:
      type: ldap
      providers: 
        - !KeyOf ldap-provider
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, "Local Kubernetes Cluster"]]
      config:
        log_level: info
        authentik_host: http://authentik.example.com/ # Assume the host is correct
        refresh_interval: minutes=5
        kubernetes_replicas: 1
        kubernetes_namespace: authentik
        authentik_host_browser: ""
        object_naming_template: ak-outpost-%(name)s
        authentik_host_insecure: false
        kubernetes_json_patches: null
        kubernetes_service_type: ClusterIP
        kubernetes_ingress_class_name: null
        kubernetes_disabled_components: []
        kubernetes_ingress_annotations: {}
        kubernetes_ingress_secret_name: authentik-outpost-tls
    model: authentik_outposts.outpost
    id: ldap-outpost
    identifiers:
      name: ldap_outpost
    permissions: []
    conditions: []
    state: present

metadata:
  name: LDAP Outpost
version: 1
```

2. Add it to a config map
3. Register it in the helm file
4. Check for secrets and pods
5. Observe that there are no "ak-outpost-<<name>>" resources

**Expected behavior**
k8s deployment of the outpost should happen

**Screenshots**
Consider these two outpost the see logs:
- ldap_outpost: the one in the blueprint
- test: manually created (sorry for the naming)
![image](https://github.com/user-attachments/assets/96e282b5-00d4-490b-b383-f0a6742de32c)

**Logs**
The outpost created with the blueprint has no k8s resources deployed, even if it is has a service_connection to k8s
```
$ kubectl -n authentik get secrets
NAME                                            TYPE                       DATA   AGE
ak-outpost-test                                 Opaque                     4      74m
authentik-1735598614                            Opaque                     18     6d1h

$ kubectl -n authentik get pods
NAME                                           READY   STATUS    RESTARTS   AGE
ak-outpost-test-f99b75976-jkbjq                1/1     Running   0          78m
authentik-1735598614-redis-master-0            1/1     Running   0          6d1h
authentik-1735598614-server-576f96f7f5-2d2ln   1/1     Running   0          45h
authentik-1735598614-worker-6f5df697f9-x295q   1/1     Running   0          19h

$ kubectl -n authentik get deployments
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
ak-outpost-test               1/1     1            1           79m
authentik-1735598614-server   1/1     1            1           6d1h
authentik-1735598614-worker   1/1     1            1           6d1h
```

**Version and Deployment (please complete the following information):**

-   authentik version: v2024.12.1
-   Deployment: helm

**Additional context**
