### ISSUE TITLE
Postgres tries to connect to random Cloudflare IP

### ISSUE THREAD

**Issue by pamidur** [goauthentik/authentik#12605]
**Describe the bug**
Authentik-server won't start because it tries to connect to some random cloudflare ip instead of postgres pod

**To Reproduce**
Steps to reproduce the behaviour:
install on k3s with following values.yaml
```
authentik:
  log_level: info
  postgresql:
    host: "my-internal-db.svc.cluster.local"
    name: "authentik"

worker:
  replicas: 1
  envFrom: 
    - secretRef:
        name: authentik-pg-secret
    - secretRef:
        name: authentik-secret-key

server:
  replicas: 1
  envFrom: 
    - secretRef:
        name: authentik-pg-secret
    - secretRef:
        name: authentik-secret-key

```

**Note**
`my-internal-db.svc.cluster.local` is resolvable and pingable within the same namespace at 10.x.x.y
`2606:4700:3032::ac43:bd3b` is some random cloudflare address

**Expected behavior**
Authentik connects to another pod with postgres db at 10.x.x.y

**Logs**
```
{"event": "PostgreSQL connection failed, retrying... (connection is bad: connection to server at \"2606:4700:3032::ac43:bd3b\", port 5432 failed: Network is unreachable\n\tIs the server running on that host and accepting TCP/IP connections?)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1736388730.1291566}
{"error":"authentik starting","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-01-09T02:12:16Z"}
```

**Version and Deployment:**

-   authentik version: [2024.12.1]
-   Deployment: [helm]

**Additional context**
I have cloudflared in another namespace
