### ISSUE TITLE
Support redis sentinel

### ISSUE THREAD

**Issue by neumantm** [goauthentik/authentik#1285]
**Is your feature request related to a problem? Please describe.**
I would like to deploy authentik on kubernetes with a separately configured distributed redis setup.
Typically a distributed redis is setup using [redis sentinel](https://redis.io/topics/sentinel).
As far as I know authentik currently does not support redis sentinel.

**Describe the solution you'd like**
I'd like, that authentik allows configuring redis sentinels and uses them.

**Describe alternatives you've considered**
Using a non-distributed redis installation, but then the redis is not as fail-save.

**Additional context**
For the django part: The `django-redis` libary recently added support for this. [docs](https://github.com/jazzband/django-redis#use-the-sentinel-connection-factory)
Celery also has support. [docs](https://docs.celeryproject.org/en/latest/getting-started/backends-and-brokers/redis.html?highlight=sentinel#configuration)
The python `redis` libary, too. [docs](https://github.com/andymccurdy/redis-py#sentinel-support)
Same for `go-redis`. [docs](https://pkg.go.dev/github.com/go-redis/redis/v8#NewFailoverClient)

**Comment by ToshY** [comment]
This is still a desired feature 🤐

**Comment by ck3mp** [comment]
I require this too. For now I have deployed a HAProxy container with a service resource to auto pick the primary node and allow Authentik to write to Redis.

**Comment by kashalls** [comment]
Looking forward to having this implemented, it will be extremely helpful. I already started switching over from an other provider as this is another key feature I wanted (among other things).

**Comment by PKizzle** [comment]
@kashalls You might want to have a look at https://github.com/goauthentik/authentik/pull/7118 and test whether it works as expected

**Comment by kashalls** [comment]
> @kashalls You might want to have a look at #7118 and test whether it works as expected. A pre-built Docker image is linked as well.

What configuration changes do I need to do in order for sentinel support to be enabled?

**Comment by PKizzle** [comment]
I have fixed the issue. Please check again using the updated image on Docker Hub.

**Comment by cardboardpig** [comment]
does AUTHENTIK_REDIS__URL also work with the helm chart?

**Comment by kashalls** [comment]
> does AUTHENTIK_REDIS__URL also work with the helm chart?

Kind of. In it's current state, overriding the image and passing it as an env works.

**Comment by cardboardpig** [comment]
Perhaps I am doing something wrong?

```yaml
apiVersion: apps/v1
kind: Deployment
<snip>
      containers:
        - name: authentik
          image: "ghcr.io/goauthentik/server:2023.8.3"
          imagePullPolicy: "IfNotPresent"
          args: ["server"]
          envFrom:
            - secretRef:
                name: authentik
            - configMapRef:
                name: authentik
<snip>
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik
data:
<snip>
  AUTHENTIK_REDIS__URL: "redis+sentinel://redis.redis:26379/?db=0"
```

```json
{"event": "Redis Connection failed, retrying... (Error 111 connecting to localhost:6379. Connection refused.)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1698890681.8654897, "redis_url": "redis://:@localhost:6379/0"}
```

No other Redis variables are set/exist in the container via envFrom etc.
