### ISSUE TITLE
How to use app passwords

### ISSUE THREAD

**Issue by NickKatchur** [goauthentik/authentik#12916]
**Describe your question/**
How are users able to utilize passwords after creating them? There seems to be little to no documentation and no one knows how to use them #7488. A simple Authorization: Bearer <token> header does not work.

**Relevant info**
I'm trying to access a protection application domain.xxx/api, using an app password.

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.12.2]
-   Deployment: docker-compose

**Comment by rissson** [comment]
API tokens are strictly used for talking with the authentik API (stuff under `authentik.company/api/v3/`), and are used with a `Authorization: Bearer <token>` header.

App passwords can be used for OOB authentication to authentik, usually through a password stage, for instance for LDAP authentication, but also for m2m OIDC for instance.

**Comment by erictrometer** [comment]
I know this is a slightly older thread but do you min elaborating because whenever i try to use app passwords in my LDAP workflow I cannot authenticate against them. And like @NickKatchur I have found the doc to be very misleading on how to setup them up properly so they get queried during the auth process

**Comment by atol71** [comment]
Hi,
I have it working by generating app password in Directory > Token and App passwords. After this I added, in my case `ollama_token:<app_pasword>` into my user profiles Atributes. 
Create a property mapping in Customization > Property Mappings of type 'Scope Mapping' . In it one can have:

```
next(
    (f"Authorization: Bearer {user.attributes.get('ollama_token', '')}"),
    None
)
```

After this create App & Provider with provider type: Proxy Provider. Select: Single application, add your endpoint URL. In Advanced protocol settings add your newly created scope mapping into selected mappings. 
Bind into default Outpost and if you are using Traefik Proxy (or any other proxy) configure it:

```
http:
  middlewares:
    authentik-forwardauth:
      forwardAuth:
        address: "https://authentik.company.com/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version`

```

and in services:

```
http:
  routers:
    ollam-home-https:
      rule: "Host(`ollama.company.com`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik-forwardauth
      service: ollama
      tls: {}

  services:
    ollama:
      loadBalancer:
        servers:
          - url: "http://ollama:11434"
        passHostHeader: true
```

Really don't know how to fork into Directory > Token and App passwords and extract the token from that...
SH
