### ISSUE TITLE
AUTHENTIK_LISTEN__HTTPS=0.0.0.0:443 using macvlan: bind: permission denied

### ISSUE THREAD

**Issue by olifluous** [goauthentik/authentik#12990]
## **Describe your question**
Can I change my internal port to 80 and 443 on server when using macvlan?

I get the following error:
`authentik-server-1      | {"error":"listen tcp 0.0.0.0:443: bind: permission denied","event":"failed to listen (TLS)","level":"warning","logger":"authentik.router","timestamp":"2025-02-11T15:41:10Z"}`

## **Relevant info**
```
docker-compose -v
Docker Compose version v2.9.0-6413-g38f6acd

docker -v
Docker version 20.10.23, build 876964a
```

### partial from file: docker-compose.yml
```
# file: docker-compose.yml

services:
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    command: server
    
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    
    volumes:
      - ./media:/media
      - ./custom-templates:/templates

    env_file:
      - .env
    
    mac_address: ${mac_address}

    networks:
      frontend:
        ipv4_address: ${ipv4_address}
      backend: {}
    
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  frontend:
    name: frontend
    external: true
  backend:
    name: backend
    driver: bridge


secrets:
  postgres_password:
    file: ./postgres_password.txt
```

```
# file: .env

AUTHENTIK_TAG=latest
mac_address=aa:aa:aa:aa:aa:aa
ipv4_address=10.10.10.10
PG_USER=postgres_admin
PG_DB=authentik
PG_PASS=password123!
AUTHENTIK_SECRET_KEY=secretkey123!
#AUTHENTIK_LISTEN__HTTPS=10.10.10.10:443
#AUTHENTIK_LISTEN__HTTP=10.10.10.10:80
#AUTHENTIK_LISTEN__HTTPS=0.0.0.0:443
#AUTHENTIK_LISTEN__HTTP=0.0.0.0:80
```

Running Authentik using docker-compose with `server` in 2 networks:
- frontend (macvlan)
- backend (bridge)
the backend network also connects to `redis`, `worker` and `postgresql`.

Using Macvlan, I don't have to expose ports, so I deleted this from my compose file.
As the `Authentik server` uses Macvlan, I can expose port 443 and 80, so in the .env file, I add:
`AUTHENTIK_LISTEN__HTTPS:0.0.0.0:443`
`AUTHENTIK_LISTEN__HTTP:0.0.0.0:80`

I also tried to specify the macvlan IP address:
`AUTHENTIK_LISTEN__HTTPS:10.10.10.10:443`
`AUTHENTIK_LISTEN__HTTP:10.10.10.10:80`

However, I always get the following error:
`authentik-server-1      | {"error":"listen tcp 0.0.0.0:443: bind: permission denied","event":"failed to listen (TLS)","level":"warning","logger":"authentik.router","timestamp":"2025-02-11T15:41:10Z"}`

When removing`AUTHENTIK_LISTEN__HTTPS:10.10.10.10:443` and/or `AUTHENTIK_LISTEN__HTTP:0.0.0.0:80` from my .env file, the service starts up, bound to ports 9000 and 9443.

Is it possible to run the Authentik server on port 443 and 80?

**Version and Deployment (please complete the following information):**

-   authentik version: latest
-   Deployment: docker-compose
