### ISSUE TITLE
No web GUI access to authentik / behind Traefik v3 / Bad GW error 502

### ISSUE THREAD

**Issue by ThierryIT** [goauthentik/authentik#13185]
**Describe your question/**
I am trying to have access to the webGUI of Authentik 

**Logs**
Authentik server logs (using Portainer)

```
`ntime=171 schema_name=public scheme=http status=200 timestamp=2025-02-23T10:17:07.033265 user=ak-outpost-df960f7a9201492d9575e1904913d50a user_agent=goauthentik.io/outpost/2024.12.3

INF event=updating brand certificates logger=authentik.router.brand_tls timestamp=2025-02-23T10:17:07Z

INF auth_via=secret_key domain_url=0.0.0.0 event=/api/v3/core/brands/?page=1&page_size=100 host=0.0.0.0:9000 logger=authentik.asgi method=GET pid=70 remote=127.0.0.1 request_id=e6c95395413a4f7184fa8cf3c520fa9e runtime=75 schema_name=public scheme=http status=200 timestamp=2025-02-23T10:17:07.206184 user=ak-outpost-df960f7a9201492d9575e1904913d50a user_agent=goauthentik.io/outpost/2024.12.3

INF event=updating brand certificates logger=authentik.router.brand_tls timestamp=2025-02-23T10:18:05Z

INF auth_via=secret_key domain_url=0.0.0.0 event=/api/v3/core/brands/?page=1&page_size=100 host=0.0.0.0:9000 logger=authentik.asgi method=GET pid=69 remote=127.0.0.1 request_id=d27d45ce7baf460eb3090094ff52025e runtime=268 schema_name=public scheme=http status=200 timestamp=2025-02-23T10:18:05.583312 user=ak-outpost-df960f7a9201492d9575e1904913d50a user_agent=goauthentik.io/outpost/2024.12.3

`
```

docker compose file of Authentik:

```
`services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    container_name: authentik-postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - $BASE/authentik/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    user: "${UID}:${GID}"
    networks:
      - mynet

  redis:
    image: docker.io/library/redis:alpine
    container_name: authentik-redis
    command: -- save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    user: "${UID}:${GID}"
    volumes:
      - $BASE/authentik/redis/data:/data
    networks:
      - mynet
  server:
    image: ghcr.io/goauthentik/server:2024.12
    container_name: authentik-server
    restart: unless-stopped
    command: server
    user: "${UID}:${GID}"
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
    volumes:
      - $BASE/authentik/media:/media
      - $BASE/authentik/custom-templates:/templates

    labels:

      - "traefik.enable=true"
      - "traefik.docker.network=mynet"
      ## HTTP Routers
      - "traefik.http.routers.authentik.rule=Host(`authentik.mynet.org`)"
      - "traefik.http.routers.authentik.entrypoints=http-external"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.routers.authentik.tls.certresolver=cloudflare"
      ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)
      - "traefik.http.routers.authentik-outpost.rule=Host(`authentik.mynet.org`) || HostRegexp(`{subdomain:[a-z0-9-]+}.mynet.org`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-outpost.entrypoints=https-external"
      - "traefik.http.routers.authentik-outpost.tls=true"
      - "traefik.http.routers.authentik-outpost.tls.certresolver=cloudflare"
      ## HTTP Services
      - "traefik.http.routers.authentik.service=authentik"
      - "traefik.http.services.authentik.loadBalancer.server.port=9001"
      - "traefik.http.routers.authentik.entrypoints=http"
      - "traefik.http.routers.authentik.rule=Host(`authentik.mynet.org`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      
    depends_on:
      - postgresql
      - redis
    networks:
      - mynet
  worker:
    image: ghcr.io/goauthentik/server:2024.12
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
       - '--host=tcp://worker-docker-socket-proxy:2375'
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
    user: root
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - $BASE/authentik/media:/media
      - $BASE/authentik/certs:/certs
      - $BASE/authentik/custom-templates:/templates

    depends_on:
      - postgresql
      - redis
      - dockerproxy
    networks:
      - mynet
      - socket-worker
  dockerproxy:
    image: wollomatic/socket-proxy:1.5.5
    read_only: true
    container_name: worker-docker-socket-proxy
    restart: unless-stopped
    user: 65534:110 # change group 999 to docker gid
    mem_limit: 128M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - -loglevel=info # change to info in prod
      - -allowfrom=*
      - -listenip=0.0.0.0
      - -shutdowngracetime=5
      - -allowGET=/containers/.*
      - -watchdoginterval=600
      - -stoponwatchdog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-worker

  geoipupdate:
    image: maxmindinc/geoipupdate:v7.1
    container_name: geoipupdate
    restart: unless-stopped
    networks:
      - mynet
    volumes:
      - $BASE/authentik/geoip/data:/usr/share/GeoIP
    environment:
       GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS}
       GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY}
       GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
       GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      #- GEOIPUPDATE_VERBOSE=1 #for debugging shows output in "docker compose up" logs
volumes:
  geoip:
    driver: local
  database:
    driver: local
  redis:
    driver: local
networks:
  mynet:
     external: true
  socket-worker:
    driver: bridge
    internal: true   
```

Traefik dynamic file:

```
middlewares-authentik:
      forwardAuth:
        address: "http://authentik-server:9001/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```

-   authentik version: 2024.12
-   Deployment: docker compose

**Additional context**

I would like Authentik running on port 9001 (9000 is already taken by Portainer).
Through the log we can see that Authentik is listenning on port 9000 instead of 9001 ....

I have a Bad GW error 502

Thx
