### ISSUE TITLE
Uptime-kuma, authentik and traefik

### ISSUE THREAD

**Issue by ThierryIT** [goauthentik/authentik#13242]
**Describe your question/**

I would like Uptime-Kuma to be authenticated using authentik.

**Relevant info**

With the bad config I have done concerning this app, I still have external access to uptime-kuma without any authentication. I should be able to logiin with authentik.

**Screenshots**

Traefik dynamic file config:

```
middlewares-authentik:
      forwardAuth:
        address: "http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
```
routers:
    uptime-kuma:
      rule: "host(`uptime-kuma.domain.org`)"
      middlewares:
        - authentik
      priority: 10
      service: uptime-kuma
```
```
# service web
    uptime-kuma:
      loadBalancer:
        servers:
          - url: "http://192.168.XXX.XXX"
    authentik:
      loadBalancer:
        servers:
          - url: "http://autehntik-server:9000/outpost.goauthentik.io"
```

Authentik config (proxy)

```
- application:  
                  - name: uptime-kuma
                  - slug: uptime-kuma
                  - provider: provider for uptime-kuma
                  - Any

- Provider for uptime-kuma
                   - authorisation flux: default-provider-authorization-implicit ....
                   - Proxy
                   - external host: uptime-kuma.domain.org
                   - internal host: http://uptime-kuma:3001
                   - SSL validation

Authentification parameters:
                    - intercept the authentication header
                    - OIDC: Provider for uptime-kuma
  
advanced flux parameters:

                     - auth flux: default-authentication-flow
```
                                

-   authentik version:2024.12.3
-   Deployment: docker-compose,

Thx
