### ISSUE TITLE
Outpost returns 404 when serving endpoints under /auth/ prefix after changing authentik.web.path to /auth/

### ISSUE THREAD

**Issue by SaraAbdelhafeez** [goauthentik/authentik#13504]
**Describe the bug**
After changing the authentik.web.path value to /auth/, the outpost fails to serve its endpoints under /outpost.goauthentik.io. The outpost returns a 404 Not Found error when accessing /outpost.goauthentik.io/start or /outpost.goauthentik.io. This issue occurs even after updating the authentik server ingress to use the /auth/ prefix.

**To Reproduce**

1. Set authentik.web.path to /auth/ in the Helm values.
2. Deploy authentik using the Helm chart.
3. Create a provider, application, and update the outpost configuration to use the /auth/ prefix.
4. Attempt to access the outpost endpoints (e.g., /outpost.goauthentik.io/start or the protected app)

**Expected behavior**
The outpost should serve its endpoints under /outpost.goauthentik.io, and the protected app should redirect to the authentik login page.

**Actual Behavior**
500 Internal Server Error happens when i try to access the protected app

**Version and Deployment (please complete the following information):**
authentik Version: 2025.2.1
Kubernetes Version: v1.30.5
Helm Chart Version: authentik-2025.2.1
Ingress Controller: NGINX Ingress Controller

-   authentik version: 2025.2.1
-   Deployment: helm
-  Ingress Controller: NGINX Ingress Controller

**Relevant Configurations**
Outpost Configuration:
```
"config": {
    "authentik_host": "http://192.168.0.241/auth/"
```
Outpost Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
  name: ak-outpost-authentik-embedded-outpost
  namespace: authentik
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ak-outpost-authentik-embedded-outpost
            port:
              name: http
        path: /outpost.goauthentik.io
        pathType: Prefix
```

Protected App’s Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: http://192.168.0.241/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
  name: atun-web
  namespace: atun
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: atun-web
            port:
              number: 3000
        path: /
        pathType: Prefix
```
authentik Server Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-server
  namespace: authentik
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: authentik-server
            port:
              number: 80
        path: /auth/
        pathType: Prefix

```
