### ISSUE TITLE
Unable to start Authentik docker environment as expected

### ISSUE THREAD

**Issue by Power2All** [goauthentik/authentik#13613]
**Describe the bug**
Unable to start Authentik using Docker

**To Reproduce**
Deploying the server using docker compose.
It starts but then exits afterwards, even when cleanly starting.

**Expected behavior**
Running Authentik as expected.

**Screenshots**
N/A

**Logs**
```
DBG | event=Loaded config logger=authentik.lib.config timestamp=1742547473.5752518 file=/authentik/lib/default.yml 
DBG | event=Loaded environment variables logger=authentik.lib.config timestamp=1742547473.5768917 count=14 
INF | event=Starting authentik bootstrap logger=authentik.lib.config timestamp=1742547476.1032617 
INF | event=PostgreSQL connection successful logger=authentik.lib.config timestamp=1742547476.1668239 
INF | event=Redis Connection successful logger=authentik.lib.config timestamp=1742547476.172183 
INF | event=Finished authentik bootstrap logger=authentik.lib.config timestamp=1742547476.1728468 
INF | event=Booting authentik logger=authentik.lib.config timestamp=1742547484.367115 version=2025.2.2 
INF | event=Enabled authentik enterprise logger=authentik.lib.config timestamp=1742547484.3789308 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.383257 path=authentik.enterprise.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.3968723 path=authentik.events.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.404978 path=authentik.crypto.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4074433 path=authentik.admin.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4114923 path=authentik.sources.ldap.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4145901 path=authentik.enterprise.providers.google_workspace.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4174216 path=authentik.sources.kerberos.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.419393 path=authentik.blueprints.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.428943 path=authentik.stages.authenticator_webauthn.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.436263 path=authentik.sources.plex.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.445249 path=authentik.providers.scim.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4586492 path=authentik.sources.oauth.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4603324 path=authentik.stages.authenticator_totp.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4643738 path=authentik.outposts.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4700308 path=authentik.enterprise.providers.microsoft_entra.settings 
DBG | event=Loaded app settings logger=authentik.lib.config timestamp=1742547484.4712532 path=authentik.enterprise.settings 
INF | domain_url=null event=Loaded MMDB database file=/geoip/GeoLite2-ASN.mmdb last_write=1738185299 logger=authentik.events.context_processors.mmdb pid=8 schema_name=public timestamp=2025-03-21T08:58:07.750895 
INF | domain_url=null event=Loaded MMDB database file=/geoip/GeoLite2-City.mmdb last_write=1738185299 logger=authentik.events.context_processors.mmdb pid=8 schema_name=public timestamp=2025-03-21T08:58:07.755687 
INF | app_name=authentik.tenants domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.tenants.checks pid=8 schema_name=public timestamp=2025-03-21T08:58:18.515179 
INF | app_name=authentik.tenants domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.tenants.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:18.519331 
INF | app_name=authentik.admin domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.admin.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:18.617210 
INF | app_name=authentik.admin domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.admin.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:18.620370 
INF | app_name=authentik.crypto domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.crypto.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:18.625606 
INF | app_name=authentik.flows domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.flows.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:18.801692 
INF | app_name=authentik.outposts domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.outposts.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:18.976031 
INF | app_name=authentik.outposts domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.outposts.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:18.980569 
INF | app_name=authentik.policies.reputation domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.policies.reputation.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:18.984590 
INF | app_name=authentik.policies domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.policies.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.053875 
INF | app_name=authentik.providers.oauth2 domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.providers.oauth2.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.057238 
INF | app_name=authentik.providers.proxy domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.providers.proxy.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.060027 
INF | app_name=authentik.providers.proxy domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.providers.proxy.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.062096 
INF | app_name=authentik.providers.rac domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.providers.rac.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.081398 
INF | app_name=authentik.providers.scim domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.providers.scim.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.095862 
INF | app_name=authentik.providers.scim domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.providers.scim.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.103316 
INF | app_name=authentik.rbac domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.rbac.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.109890 
INF | app_name=authentik.sources.kerberos domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.kerberos.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.123064 
INF | app_name=authentik.sources.kerberos domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.kerberos.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.126579 
INF | app_name=authentik.sources.ldap domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.ldap.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.164418 
INF | app_name=authentik.sources.ldap domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.ldap.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.185526 
INF | app_name=authentik.sources.oauth domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.oauth.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.270190 
INF | app_name=authentik.sources.saml domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.saml.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.272981 
INF | app_name=authentik.sources.scim domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.sources.scim.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.276493 
INF | app_name=authentik.stages.authenticator_duo domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.authenticator_duo.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.279738 
INF | app_name=authentik.stages.authenticator_static domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.authenticator_static.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.282813 
INF | app_name=authentik.stages.authenticator_webauthn domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.authenticator_webauthn.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.539737 
INF | app_name=authentik.stages.email domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.email.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.540809 
INF | app_name=authentik.core domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.core.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.551600 
INF | app_name=authentik.core domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.core.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.552048 
INF | app_name=authentik.enterprise domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.554158 
INF | app_name=authentik.enterprise domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.556554 
INF | app_name=authentik.enterprise.providers.google_workspace domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.google_workspace.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.560214 
INF | app_name=authentik.enterprise.providers.google_workspace domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.google_workspace.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.561872 
INF | app_name=authentik.enterprise.providers.microsoft_entra domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.microsoft_entra.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.565052 
INF | app_name=authentik.enterprise.providers.microsoft_entra domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.microsoft_entra.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.566761 
INF | app_name=authentik.enterprise.providers.ssf domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.ssf.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.573209 
INF | app_name=authentik.enterprise.providers.ssf domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.ssf.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.579164 
INF | app_name=authentik.events domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.events.tasks pid=8 schema_name=public timestamp=2025-03-21T08:58:19.581383 
INF | app_name=authentik.events domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.events.signals pid=8 schema_name=public timestamp=2025-03-21T08:58:19.581768 

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[authenticator_webauthn]
    update_webauthn_mds

[blueprints]
    apply_blueprint
    blueprint_shell
    export_blueprint
    make_blueprint_schema

[channels]
    runworker

[contenttypes]
    remove_stale_contenttypes

[core]
    bootstrap_tasks
    build_source_docs
    change_user_type
    dev_server
    repair_permissions
    shell
    worker

[crypto]
    import_certificate

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    optimizemigration
    sendtestemail
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[django_tenants]
    all_tenants_command
    clone_tenant
    collectstatic_schemas
    create_missing_schemas
    create_tenant
    create_tenant_superuser
    delete_tenant
    migrate
    migrate_schemas
    rename_schema
    tenant_command

[drf_spectacular]
    spectacular

[email]
    test_email

[flows]
    benchmark

[guardian]
    clean_orphan_obj_perms

[kerberos]
    kerberos_check_connection
    kerberos_sync

[ldap]
    ldap_check_connection
    ldap_sync

[pgactivity]
    pgactivity

[pglock]
    pglock

[recovery]
    create_admin_group
    create_recovery_key

[rest_framework]
    generateschema

[scim]
    scim_sync

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver
```

**Version and Deployment (please complete the following information):**
-   authentik version: 2025.2.2
-   Deployment: Docker in Swarm mode (replicated to 1 in manager node)

**Additional context**
All works fine, just the Authentik server doesn't load as expected, with an "help" returning, see logs above.

**Docker Compose**
```
version: "3.8"

services:

  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: 'postgresql'
    hostname: 'postgresql'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik -U authentik"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - type: bind
        source: "**CENSORED**/postgresql_data"
        target: "/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "**CENSORED**"
      POSTGRES_USER: "authentik"
      POSTGRES_DB: "authentik"
    networks:
      - External-Network

  server:
    image: ghcr.io/goauthentik/server:latest
    container_name: 'server'
    hostname: 'server'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
      labels: (**CENSORED** for Traefik)
    environment:
      AUTHENTIK_SECRET_KEY: "**CENSORED**"
      AUTHENTIK_ERROR_REPORTING__ENABLED: 1
      AUTHENTIK_EMAIL__HOST: "**CENSORED**"
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: "**CENSORED**"
      AUTHENTIK_EMAIL__PASSWORD: "**CENSORED**"
      AUTHENTIK_EMAIL__USE_TLS: 1
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: "**CENSORED**"
      AUTHENTIK_POSTGRESQL__HOST: "system_authentik_postgresql"
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "**CENSORED**"
      AUTHENTIK_REDIS__HOST: "system_authentik_redis"
    volumes:
      - type: bind
        source: "**CENSORED**/media"
        target: "/media"
      - type: bind
        source: "**CENSORED**/templates"
        target: "/templates"
      - type: bind
        source: "**CENSORED**/certs"
        target: "/certs"
    networks:
      - External-Network

  redis:
    image: **CENSORED**
    command: "redis-server --save 60 1 --loglevel notice"
    build: redis
    container_name: 'redis'
    hostname: 'redis'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: "**CENSORED**/redis"
        target: "/data"
    networks:
      - External-Network

networks:
  External-Network:
    name: External-Network
    external: true
```
