### ISSUE TITLE
Oauth auth don't work with grafana on kubernetes

### ISSUE THREAD

**Issue by JulesPichon84** [goauthentik/authentik#13650]
**Describe the bug**

When I try to setup an Oauth authentification within Grafana which is deployed via Argcocd on my kubernetes cluster,  I get an redirect uri error. I tried to recreate a provider to the application but it doesn't change, it's the same error.

**To Reproduce**

Here is my values for Grafana:

```
# Grafana configuration
grafana:
  fullnameOverride: grafana
  assertNoLeakedSecrets: false
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: ...
    hosts:
      - "<some_url>"
    tls:
      - secretName: ...
        hosts:
          - "<some_url>"
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    server:
      root_url: "<some_url>"
    auth:
      signout_redirect_url: "https://authk.<some_url>/application/o/sup/end-session/"
      oauth_auto_login: true
    auth.generic_oauth:
      name: authentik
      enabled: true
      client_id: "<client_id>"
      client_secret: "<client_secret>"
      scopes: "openid profile email"
      auth_url: "https://authk.<some_url>/application/o/authorize/"
      token_url: "https://authk.<some_url>/application/o/token/"
      api_url: "https://authk.<some_url>/application/o/userinfo/"
      # Optionally map user groups to Grafana roles
      role_attribute_path: contains(groups, 'authentik Admins') && 'Admin'
```

**Expected behavior**

I except that the authentik Ouath Oidc be enable within my Grafana so I can disable login/password auth.

**Screenshots**

![Image](https://github.com/user-attachments/assets/424c3317-093c-4463-a87b-2f36547bff44)

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.2.2]
-   Deployment of Grafana: Argocd (with kube-prometheus-stack v69.8.0)
