### ISSUE TITLE
2FA confirmation fails for Russian (Cyrillic) usernames longer than 25 characters

### ISSUE THREAD

**Issue by Vladaffera** [goauthentik/authentik#13723]
**Describe the bug**  
When enabling 2FA (MFA), the confirmation code fails to deliver if the user's Cyrillic name exceeds 25 characters. The system crashes during email address validation with a `ValueError`.

**To Reproduce**  
1. Create a user with a >25-character Cyrillic name (e.g., "Иванов Владимир Сергеевич").  
2. Navigate to Security → Enable 2FA.  
3. Click "Send confirmation code".  
4. Error occurs: `ValueError: Invalid address; address parts cannot contain newlines`.  

**Expected behavior**  
2FA confirmation codes should be delivered successfully regardless of username length or script (Cyrillic/Latin).  

**Screenshots**  

![Image](https://github.com/user-attachments/assets/f8210e06-34c1-4bb2-bd9c-c0d5ee34d18a)

**Logs**  
```log
Traceback (most recent call last):
  File "/ak-noc/venv/lib/python32!/site-packages/django/core/mail/message.py", line 161, in sanitize_address
    raise ValueError('Invalid address; address parts cannot contain newlines.')
ValueError: Invalid address; address parts cannot contain newlines.
Logger: send_mail

Version
-   authentik version: [e.g. 2025.2.3]

**Comment by melizeche** [comment]
Related to #13649

**Comment by melizeche** [comment]
@Vladaffera at the moment I'm working on a fix for this

Can you test this patch to see if it solves the issue?

authentik Patch Installation instructions

<details>
  <summary>Instructions for docker-compose</summary>

  Add the following block to your `.env` file:

  ```shell
  AUTHENTIK_IMAGE=ghcr.io/goauthentik/dev-server
  AUTHENTIK_TAG=gh-6410d340d2071c26385d85fc1bb94c3319fd9937
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE=ghcr.io/goauthentik/dev-%(type)s:gh-%(build_hash)s
  ```

  Afterwards, run the upgrade commands from the latest release notes.
</details>
<details>
  <summary>Instructions for Kubernetes</summary>

  Add the following block to your `values.yml` file:

  ```yaml
  authentik:
      outposts:
          container_image_base: ghcr.io/goauthentik/dev-%(type)s:gh-%(build_hash)s
  global:
      image:
          repository: ghcr.io/goauthentik/dev-server
          tag: gh-6410d340d2071c26385d85fc1bb94c3319fd9937
  ```

  Afterwards, run the upgrade commands from the latest release notes.
</details>
