### ISSUE TITLE
FR: HTTPRoute support for Kubernetes integration

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#14070]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when things I want to use, don't support HTTPRoute.

**Describe the solution you'd like**
I would like to be able to use the included Kubernetes support to create proxied HTTPRoutes where it goes though Authentik proxy and then to app.

**Describe alternatives you've considered**
PR it myself, but now entirely sure how it should be approached.

**Additional context**

The idea is basically similar functionality as is currently possible with the included Kubernetes support for creating Ingresses automatically and then proxying the app though after auth and all.

**Comment by rissson** [comment]
https://github.com/goauthentik/authentik/pull/13272

**Comment by samip5** [comment]
> [#13272](https://github.com/goauthentik/authentik/pull/13272)

Does that mean it's waiting on testing ooor?

**Comment by rissson** [comment]
Oh yeah sorry I should've been a bit more explicit, no, it's still waiting on implementation

**Comment by samip5** [comment]
> Oh yeah sorry I should've been a bit more explicit, no, it's still waiting on implementation

So currently, what is the PR missing for it to be in a working condition?

**Comment by rissson** [comment]
I think mainly tests and documentation

**Comment by rissson** [comment]
@samip5 that PR is ready to go and we'll be publishing our first release candidate for 2025.4 in the following days. Would you be able to try that out? I'll open a separate PR for documentation, but the short of it is, in the outpost configuration:
1. Add `ingress` to the `kubernetes_disabled_components` list
2. Set `kubernetes_httproute_parent_refs` is a list that needs to be set to what would be in `httproute.spec.parentRefs`
3. Optionally set `kubernetes_httproute_annotations` if needed

**Comment by samip5** [comment]
@rissson What should the helm value for outpost be if testing an RC?

```
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
```

**Comment by rissson** [comment]
Just replace `%(version)s` with 2025.4.0-rc2

**Comment by samip5** [comment]
Just found out that the service account/related RBAC permissions that the chart currently does are not at all compatible with httproutes, but I also don't see any logs about them.

Where should I see something about those if I added proxy providers to the embedded outpost and specified the parentrefs?

For reference:
```
kubernetes_disabled_components:
  - deployment
  - secret
  - traefik middleware
  - ingress
error_reporting_environment: kryptonian-k8s
kubernetes_httproute_parent_refs:
  - name: envoy-internal
    namespace: networking
    sectionName: https
  - name: envoy-external
    namespace: networking
    sectionName: https
```


I don't see any httproutes being created by Authentik?
