### ISSUE TITLE
JellyFin OIDC Redirect URI Error

### ISSUE THREAD

**Issue by Ingener74** [goauthentik/authentik#14072]
**Describe the bug**
Authentik substitutes redirect_uri from https to http

**To Reproduce**

1. Setup JellyFin by instruction from https://docs.goauthentik.io/integrations/services/jellyfin/#oidc-configuration
2. Try to enter in JellyFin

**Expected behavior**
Normal enter in JellyFin throught Authentik

**Screenshots**
JellyFin provider in Authentik
<img width="1090" alt="Image" src="https://github.com/user-attachments/assets/9ea817f9-198c-49f2-bf3a-6d645e488eba" />

Redirect error 
<img width="824" alt="Image" src="https://github.com/user-attachments/assets/a8895027-3c3e-425b-8036-aa6cad23c14d" />

**Logs**

**Version and Deployment (please complete the following information):**
Authentik version 2025.2.4
Deployment: [docker-compose]

**Additional context**

**Comment by rissson** [comment]
I'm guessing your reverse proxy is not setting `X-Forwarded-Proto` and `X-Forwarded-Protocol` properly. Check out the Jellyfin documentation on how to do that https://jellyfin.org/docs/general/networking/nginx

**Comment by Ingener74** [comment]
I use Traefik and tried to set headers in it, but it didn't help.
```yaml
http:
  routers:
    jellyfin-https:
      entryPoints:
        - websecure
      service: jellyfin
      rule: Host(`jf.domain.com`)
      middlewares:
        - add-forward-headers  # add new middleware for headers
      tls:
        certResolver: letsencrypt
    jellyfin-http:
      entryPoints:
        - web
      middlewares:
        - redirect-https
      service: jellyfin
      rule: Host(`jf.domain.com`)
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://jf:8096
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    # new middleware for headers
    add-forward-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Protocol: "https"
          X-Forwarded-Host: "jf.domain.com"
```
