### ISSUE TITLE
Initial setup link `https://<host>/if/flow/initial-setup/`  or root `/` not found in 2025.2.4

### ISSUE THREAD

**Issue by chakraborty29** [goauthentik/authentik#14319]
**Describe the bug**
Unable to access root at `/` or initial-setup at `/if/flow/initial-setup`.

Related to https://github.com/goauthentik/authentik/issues/9584

**To Reproduce**
1. Follow the Kubernetes Helm Installation in docs
2. My Helm Values, Secrets & Traefik IngressRoute Below

<details>
<Summary>
  <strong>values.yaml</strong>
</Summary>

```
---
## Globally shared configuration for authentik components.
global:
  namespaceOverride: "authentik"

  # Number of old deployment ReplicaSets to retain. The rest will be garbage collected.
  revisionHistoryLimit: 10

  # Default image used by all authentik components. For GeoIP configuration, see the geoip values below.
  image:
    repository: ghcr.io/goauthentik/server
    tag: "2025.2.4"

  # -- Annotations for all deployed Deployments
  deploymentAnnotations:
    secrets.infisical.com/auto-reload: "true"

  # -- Deployment strategy for all deployed Deployments
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # -- Environment variables to pass to all deployed Deployments. Does not apply to GeoIP
  # See configuration options at https://goauthentik.io/docs/installation/configuration/
  # @default -- `[]` (See [values.yaml])
  env:
    - name: AUTHENTIK_POSTGRESQL__USER 
      valueFrom:
        secretKeyRef:
          name: authentik-pg-admin-credentials-secret 
          key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-pg-admin-credentials-secret 
          key: password
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__USER
      valueFrom:
        secretKeyRef:
          name: authentik-pg-admin-credentials-secret 
          key: username
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-pg-admin-credentials-secret 
          key: password
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-redis-admin-credentials-secret
          key: redis-password

  envFrom:
    - secretRef:
        name: authentik-env

  volumeMounts:
    - name: ssl-root-cert
      mountPath: /etc/ssl/certs/example
      readOnly: true

  volumes:
    - name: ssl-root-cert
      secret:
        secretName: example-internal-ca-key-pair
        items:
          - key: ca.crt
            path: ca.crt

## Authentik configuration
authentik:
  # -- Log level for server and worker
  log_level: debug
  # -- Secret key used for cookie singing and unique user IDs,
  # don't change this after the first install
  secret_key: ""
  events:
    context_processors:
      # -- Path for the GeoIP City database. If the file doesn't exist, GeoIP features are disabled.
      geoip: /geoip/GeoLite2-City.mmdb
      # -- Path for the GeoIP ASN database. If the file doesn't exist, GeoIP features are disabled.
      asn: /geoip/GeoLite2-ASN.mmdb
  web:
    # -- Relative path the authentik instance will be available at. Value _must_ contain both a leading and trailing slash.
    path: /
  email:
    # -- SMTP Server emails are sent from, fully optional
    host: "${DREAMHOST_SMTP_HOST}"
    # -- SMTP server port
    port: 587
    # -- SMTP credentials, when left empty, no authentication will be done
    username: "${DREAMHOST_SMTP_USERNAME}"
    # -- SMTP credentials, when left empty, no authentication will be done
    password: "${DREAMHOST_SMTP_PASSWORD}"
    # -- Use StartTLS. Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_tls: true
    # -- Use SSL. Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_ssl: false
    # -- Connection timeout
    timeout: 30
    # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
    from: "${DREAMHOST_SMTP_USERNAME}"
  outposts:
    # -- Template used for managed outposts. The following placeholders can be used
    # %(type)s - the type of the outpost
    # %(version)s - version of your authentik install
    # %(build_hash)s - only for beta versions, the build hash of the image
    container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

  postgresql:
    host: "${AUTHENTIK_POSTGRESQL__HOST}"

  redis:
    host: "${AUTHENTIK_REDIS__HOST}"


blueprints:
  # -- List of config maps to mount blueprints from.
  # Only keys in the configMap ending with `.yaml` will be discovered and applied.
  configMaps: []
  # -- List of secrets to mount blueprints from.
  # Only keys in the secret ending with `.yaml` will be discovered and applied.
  secrets: []


## authentik server
server:
  # -- authentik server name
  name: server

  # -- The number of server pods to run
  replicas: 3

  # Significantly increase resource limits incase as authentik workers were restarting
  # -- Resource limits and requests for the authentik server
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

## authentik worker
worker:
  # -- authentik worker name
  name: worker

  # -- The number of worker pods to run
  replicas: 3

  # Significantly increase resource limits as authentik workers were restarting
  # -- Resource limits and requests for the authentik worker
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  # Increased readinessProbe limits as Worker pods were constantly restarting
  readinessProbe:
    # -- Minimum consecutive failures for the [probe] to be considered failed after having succeeded
    failureThreshold: 10
    # -- Number of seconds after the container has started before [probe] is initiated
    initialDelaySeconds: 30
    # -- How often (in seconds) to perform the [probe]
    periodSeconds: 15
    # -- Minimum consecutive successes for the [probe] to be considered successful after having failed
    successThreshold: 1
    # -- Number of seconds after which the [probe] times out
    timeoutSeconds: 5

```
</details>

<details>
<Summary>
  <strong>Secrets</strong>
</Summary>

```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-env
  namespace: authentik
spec:
  hostAPI: https://infisical.prod.example.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ""
        envSlug: prod
        secretsPath: ""
        recursive: true
  managedKubeSecretReferences:
    - secretName: authentik-env
      secretNamespace: authentik
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL.Value }}"
          AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD.Value }}"
          AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN.Value }}"
          AUTHENTIK_POSTGRESQL__HOST: "{{ .AUTHENTIK_POSTGRESQL__HOST.Value }}"
          AUTHENTIK_POSTGRESQL__SSLROOTCERT: "{{ .SSLROOTCERT.Value }}"
          AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__HOST: "{{ .AUTHENTIK_POSTGRESQL__HOST.Value }}"
          AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__NAME: "{{ .AUTHENTIK_POSTGRESQL__NAME.Value }}"
          AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PORT: "{{ .AUTHENTIK_POSTGRESQL__PORT.Value }}"
          AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__SSLMODE: "{{ .AUTHENTIK_POSTGRESQL__SSLMODE.Value }}"
          AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__SSLROOTCERT: "{{ .SSLROOTCERT.Value }}"
          AUTHENTIK_REDIS__HOST: "{{ .AUTHENTIK_REDIS__HOST.Value }}"
          AUTHENTIK_REDIS__TLS: "{{ .AUTHENTIK_REDIS__TLS.Value }}"
          AUTHENTIK_REDIS__TLS_CA_CERT: "{{ .SSLROOTCERT.Value }}"
          AUTHENTIK_REDIS__TLS_REQS: "{{ .AUTHENTIK_REDIS__TLS_REQS.Value }}"
          AUTHENTIK_STORAGE__MEDIA__BACKEND: "{{ .AUTHENTIK_STORAGE__MEDIA__BACKEND.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__REGION: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__REGION.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT.Value }}/{{ .AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME.Value }}"
          DREAMHOST_SMTP_USERNAME: "{{ .DREAMHOST_SMTP_USERNAME.Value }}"
          DREAMHOST_SMTP_PASSWORD: "{{ .DREAMHOST_SMTP_PASSWORD.Value }}"
          DREAMHOST_SMTP_HOST: "{{ .DREAMHOST_SMTP_HOST.Value }}"

```
</details>

<details>
<Summary>
  <strong>Traefik IngressRoute</strong>
</Summary>

```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: authentik
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.prod.example.com`)
      kind: Rule
      priority: 10
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: authentik-server
          port: 443
    - match: Host(`*.prod.example.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: authentik
          port: 443
  tls:
    secretName: prod-example-tls
```
</details>

**Expected behavior**
Be able to reach either the initial setup or even the admin or login page.

**Screenshots**
Going to root `/`:

<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/7e4e9bf6-243b-4f72-ac53-ce2e01756239" />

Going to `/if/flows/initial-setup/`

<img width="1163" alt="Image" src="https://github.com/user-attachments/assets/1d507773-1914-47ee-972b-ce8e3a23b58a" />

**Logs**

<details>
<Summary>
  <strong>Server logs when I try to access `/if/flow/initial-setup/`:</strong>
</Summary>

```
{
  "auth_via": "unauthenticated", 
  "domain_url": "authentik.prod.example.com", 
  "event": "dropping exception", 
  "exc": "Http404('No Flow matches the given query.')",
  "host": "authentik.prod.example.com", 
  "level": "debug", 
  "logger": "authentik.lib.sentry", 
  "pid": 69, 
  "request_id": "af20849b614a4256bcf052a156f9eba0", 
  "schema_name": "public", 
  "timestamp": "2025-05-01T03:43:21.284659"
}
{
  "auth_via": "unauthenticated", 
  "domain_url": "authentik.prod.example.com", 
  "event": "/if/flow/initial-setup/", 
  "host": "authentik.prod.example.com", 
  "level": "info", 
  "logger": "authentik.asgi", 
  "method": "GET", 
  "pid": 69, 
  "remote": "10.42.4.0", 
  "request_id": "af20849b614a4256bcf052a156f9eba0", 
  "runtime": 62, 
  "schema_name": "public", 
  "scheme": "https", 
  "status": 404, 
  "timestamp": "2025-05-01T03:43:21.289613", 
  "user": "", 
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
}
```
</details>

<details>
<Summary>
  <strong>Server logs when I try to access the root `/` url</strong>
</Summary>

```
{
  "auth_via": "unauthenticated",
  "domain_url": "authentik.prod.example.com",
  "event": "dropping exception",
  "exc": "Http404()",
  "host": "authentik.prod.example.com",
  "level": "debug",
  "logger": "authentik.lib.sentry",
  "pid": 69,
  "request_id": "5a714080abf3485685bc7a64a3145a06",
  "schema_name": "public",
  "timestamp": "2025-05-01T04:57:27.233271"
}

{
  "auth_via": "unauthenticated",
  "domain_url": "authentik.prod.example.com",
  "event": "/flows/-/default/authentication/?next=/",
  "host": "authentik.prod.example.com",
  "level": "info",
  "logger": "authentik.asgi",
  "method": "GET",
  "pid": 69,
  "remote": "10.42.4.0",
  "request_id": "5a714080abf3485685bc7a64a3145a06",
  "runtime": 55,
  "schema_name": "public",
  "scheme": "https",
  "status": 404,
  "timestamp": "2025-05-01T04:57:27.238214",
  "user": "",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
}
```
</details>

<details>
<Summary>
  <strong>Related to #12186 - This is the output of the db table `authentik_flows_flow`</strong>
</Summary>

The output only has 3 flows. 
```
postgres@pg-authentik-1:/$ psql
psql (17.4 (Debian 17.4-1.pgdg110+2))
Type "help" for help.

postgres=# \l
                                                     List of databases
   Name    |       Owner        | Encoding | Locale Provider | Collate | Ctype | Locale | ICU Rules |   Access privileges   
-----------+--------------------+----------+-----------------+---------+-------+--------+-----------+-----------------------
 authentik | authentik-pg-admin | UTF8     | libc            | C       | C     |        |           | 
 postgres  | postgres           | UTF8     | libc            | C       | C     |        |           | 
 template0 | postgres           | UTF8     | libc            | C       | C     |        |           | =c/postgres          +
           |                    |          |                 |         |       |        |           | postgres=CTc/postgres
 template1 | postgres           | UTF8     | libc            | C       | C     |        |           | =c/postgres          +
           |                    |          |                 |         |       |        |           | postgres=CTc/postgres
(4 rows)

postgres=# \c authentik
You are now connected to database "authentik" as user "postgres".
authentik=# select * from authentik_flows_flow;

flow_uuid               |           name            |                      slug                       |     designation     |      policybindingmodel_ptr_id       |             title             | background | compatibility_mode | layout  |  denied_action   |    authentication     
--------------------------------------+---------------------------+-------------------------------------------------+---------------------+--------------------------------------+-------------------------------+------------+--------------------+---------+------------------+-----------------------
 5f211996-aa8a-4225-9053-570291f758f7 | Logged out of application | default-provider-invalidation-flow              | invalidation        | d26a58d7-f95c-4c9e-a05a-60abb9f76108 | You've logged out of %(app)s. |            | f                  | stacked | message_continue | none
 2d271993-4ea0-4a51-8262-878e341ffdc4 | Pre-Authentication        | default-source-pre-authentication               | stage_configuration | 52d63556-0be4-43ed-9193-4a0b8e85f4da | Pre-authentication            |            | f                  | stacked | message_continue | none
 e9bbe3c2-1446-420e-88f9-c74328c76770 | Authorize Application     | default-provider-authorization-implicit-consent | authorization       | bdcab40c-218e-421f-8a7e-981c3680c3fc | Redirecting to %(app)s        |            | f                  | stacked | message_continue | require_authenticated

```
</details>

<details>
<Summary>
  <strong>Worker Migration logs post initial migration</strong>
</Summary>

```
=== Starting migration
Operations to perform:
  Apply all migrations: auth, authentik_blueprints, authentik_brands, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_geoip, authentik_policies_password, authentik_policies_reputation, authentik_providers_google_workspace, authentik_providers_ldap, authentik_providers_microsoft_entra, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_rac, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_providers_ssf, authentik_rbac, authentik_sources_kerberos, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_sources_scim, authentik_stages_authenticator_duo, authentik_stages_authenticator_email, authentik_stages_authenticator_endpoint_gdtc, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_redirect, authentik_stages_source, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, sessions
Running migrations:
  No migrations to apply.
```
</details>

**Version and Deployment (please complete the following information):**

-   authentik version: 2025.2.4
-   Deployment: helm

**Additional context**
