### ISSUE TITLE
Possible to change internal UID and GID for authentik user?

### ISSUE THREAD

**Issue by stobbsm** [goauthentik/authentik#14625]
**Describe your question/**
I want to change the internal UID and GID of the container for the authentik user, from 1000:1000, to a < 1000 set.

**Relevant info**
Running with podman on alpine linux, on top of proxmox. Multiple containers are running in the same VM to better use resources, and the default alpine user has UID and GID of 1000, making running authentik a security risk.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2025.4.1
-   Deployment: podman via docker-compose plugin

**Additional context**
I can't find any docs about changing the internal UID:GID. Is this possible without rebuilding the container images myself?

**Comment by rissson** [comment]
have you tried simply running with other ids?

**Comment by sevmonster** [comment]
Currently, the `authentik` user is [hardcoded](https://github.com/goauthentik/authentik/blob/a8327101c675b4dc0b0201ff46bf7a028261b370/Dockerfile#L165). You can change the container UID/GID via the usual method (`docker run -u` or `user` key for Compose) and that will work, but there are some problems:
- This breaks [Docker socket and other permission fixes](https://github.com/goauthentik/authentik/blob/02072bda93dfc87956818df5e44facb73839d430/lifecycle/ak#L19) in-container for the `worker`
- In both server and worker, [various authentik files](https://github.com/goauthentik/authentik/blob/02072bda93dfc87956818df5e44facb73839d430/lifecycle/ak#L38) are still owned by the `authentik` user (UID 1000)

I don't know how much trouble the second item causes, but if you want to let authentik manage outposts itself via the Docker socket, the first item has to be resolved.

You can change the internal UID/GID and fix internal permissions by replacing the container entrypoint.

Example for Compose (set `UID` and `GID` in your `.env`):
```yaml
services:
  server:
    # ... 
    entrypoint:
      - /bin/sh
      - -c
      - |
        sed -i 's/:x:1000:1000:/:x:$UID:$GID:/' /etc/passwd
        sed -i 's/:x:1000:/:x:$GID:/' /etc/group
        chown authentik:authentik /authentik/.ssh /ak-root
        # must drop privs manually like ak does for worker
        exec chpst -u authentik:authentik env HOME=/authentik dumb-init -- ak server
    user: root
    # ...
  worker:
    # ...
    entrypoint:
      - /bin/sh
      - -c
      - |
        sed -i 's/:x:1000:1000:/:x:$UID:$GID:/' /etc/passwd
        sed -i 's/:x:1000:/:x:$GID:/' /etc/group
        chown authentik:authentik /authentik/.ssh /ak-root
        # ak handles priv drop for us
        exec dumb-init -- ak worker
    user: root
    # ...
```

Notes: 
- `root` user for both containers is required, and it will drop privs afterward.
- Make sure that you do not set `CMD` or `command` in your `docker run` or Compose file respectively, the entrypoint handles the arguments for `ak` for you.
- This is an ugly hack, and the main reason you would want to do it is for Docker socket access in the worker. Doing this for the server may not be necessary as only the worker cares about the socket or fixing permissions. I haven't looked far enough into it to know for sure. However, it is still a good idea to change the UID/GID to prevent sharing active UIDs with the host, of which you can do with Docker without the entrypoint hack.
