### ISSUE TITLE
Custom branding docker volume mount does not load (404)

### ISSUE THREAD

**Issue by tunloop** [goauthentik/authentik#14627]
**Describe the bug**

With custom branding images mounted in the docker container, the browser attempts to load the image but gets 404 from the server.

**Screenshots**

![Image](https://github.com/user-attachments/assets/77e11bd3-2826-4f50-9373-67bcbac84ba8)
![Image](https://github.com/user-attachments/assets/4cc88bad-196d-4da6-8d12-da063533380b)

**Logs**
Within the container:
```
authentik@09b71b38b63f:/$ ls -l /web/dist/assets/images/custom*
-rw-r--r-- 1 root root 224219 May 22 02:34 /web/dist/assets/images/customfavicon.png
-rw-r--r-- 1 root root 224219 May 22 02:34 /web/dist/assets/images/customlogo.png
authentik@09b71b38b63f:/$ ls -l /web/dist/assets/images/flow*
-rw-r--r-- 1 root root 694021 May 22 02:34 /web/dist/assets/images/flow_background.jpg
 ```

docker logs:
```
{"auth_via": "session", "domain_url": "domain", "event": "/web/dist/assets/images/customlogo.png", "host": "domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 41, "remote": "clientip", "request_id": "7c4cf7885e6f478997b439b05a3f9529", "runtime": 70, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2025-05-22T03:35:45.217460", "user": "akadmin", "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0"}
{"auth_via": "unauthenticated", "domain_url": "domain", "event": "/web/dist/assets/images/customlogo.png", "host": "domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 40, "remote": "clientip", "request_id": "3e22ff8d49904aaf85f6655cb8e5386c", "runtime": 11, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2025-05-22T03:35:45.851387", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0"}
{"auth_via": "unauthenticated", "domain_url": "domain", "event": "/web/dist/assets/images/customfavicon.png", "host": "domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 41, "remote": "clientip", "request_id": "d1d2bd8fb47240bfb2aa80a7d6d6caf7", "runtime": 5, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2025-05-22T03:35:46.101241", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0"}
 {"auth_via": "unauthenticated", "domain_url": "domain", "event": "/web/dist/assets/images/flow_background.jpg", "host": "domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 40, "remote": "clientip", "request_id": "6348875db5d1438c8ea2f82d45ec7459", "runtime": 10, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2025-05-22T03:35:46.149087", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0"}
```

**Version and Deployment (please complete the following information):**
- 
-   authentik version: 2025.4.0
-   Deployment: docker-compose

**Docker compose yaml**

```
---
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - /opt/.env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.4.0}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
      - ./branding/logo.png:/web/dist/assets/images/customlogo.png
      - ./branding/logo.png:/web/dist/assets/images/customfavicon.png
      - ./branding/background.jpg:/web/dist/assets/images/flow_background.jpg
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.4.0}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
    driver: local
  redis:
    driver: local
```
