### ISSUE TITLE
Grafana Login failed Failed to get token from provider

### ISSUE THREAD

**Issue by Akenjeru** [goauthentik/authentik#14695]
When I try to log in via Authentik to Grafana, it says "Login failed
Failed to get token from provider"

```
version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    ports:
      - 3005:3000
    restart: always
    volumes:
      - /home/grafana/data:/var/lib/grafana
    user: root
    labels:
      - "diun.enable=true"
      - "diun.metadata.container=Grafana"
    environment:
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "id"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "secret"
        GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.mydomain.com/application/o/authorize/"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.mydomain.com/application/o/token/"
        GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.mydomain.com/application/o/userinfo/"
        GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.mydomain.com/application/o/grafana/end-session/"
    # Optionally enable auto-login (bypasses Grafana login screen)
        GF_AUTH_OAUTH_AUTO_LOGIN: "true"
    # Optionally map user groups to Grafana roles
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
    # Required if Grafana is running behind a reverse proxy
        GF_SERVER_ROOT_URL: "https://grafana.mydomain.com"
```
