### ISSUE TITLE
Forward auth proxy returns malformed redirect URL

### ISSUE THREAD

**Issue by danhawkes** [goauthentik/authentik#1475]
Running a clean install of ~`2021.9.2` (with https://github.com/goauthentik/authentik/commit/27e04589c1a0c7ab93f0acf43d77fca88e938673), and using the built-in outpost and domain-level forward auth.

When visiting a protected ingress, the redirect includes scheme twice: `https://https://`. If I manually edit the URL in the browser, it works and I'm able to log in. 

This worked with the a manually deployed outpost in `2021.8.x`.

Any ideas what's wrong?

```bash
✗  http https://qb.example.com/
HTTP/1.1 307 Temporary Redirect
Location: https://https://auth.example.com/akprox/start
Set-Cookie: authentik_proxy=...; Path=/; Domain=example.com; Expires=Sun, 03 Oct 2021 14:57:22 GMT; Max-Age=604801
Vary: Accept-Encoding

<a href="https://https://auth.example.com/akprox/start">Temporary Redirect</a>.
```
This is the generated middleware:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ak-outpost-authentik-embedded-outpost
  namespace: authentik
spec:
  forwardAuth:
    address: http://ak-outpost-authentik-embedded-outpost.authentik:9000/akprox/auth/traefik
    authResponseHeaders:
    - Set-Cookie
    - X-Auth-Username
    - X-Auth-Groups
    - X-Forwarded-Email
    - X-Forwarded-Preferred-Username
    - X-Forwarded-User
    trustForwardHeader: true
```
And IngressRoute:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
spec:
  routes:
  - kind: Rule
    match: Host(`qb.example.com`)
    middlewares:
    - name: ak-outpost-authentik-embedded-outpost
      namespace: authentik
    services:
    - kind: Service
      name: qbittorrent-default
      namespace: default
      port: 8080
  tls:
    certResolver: cloudflare
    domains:
    - main: qb.example.com
```
