### ISSUE TITLE
[Q] Integration with Synapse

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1477]
**Describe your question/**
I'm trying to use Authentik as the provider for users to Synapse, but I'm not finding proper information on how I need to configure it in Authentik and then in Synapse?

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.2
 - Deployment: docker-compose via Ansible

**Comment by samip5** [comment]
Just for reference:

You need to create a oauth provider in Authentik and app for it, and map that to the provider.
The oauth provider needs to have openid and profile scopes selected.

Matrix Synapse needs to have this configuration in openidc_providers:
```
- idp_id: authentik
    idp_name: Authentik
    discover: true
    issuer: "https://authentik.example.com/application/o/example-applicatonslug/"
    client_id: "52611cbe0a8e16c458026d4f7b3c966cd0acd549"
    client_secret: "{{ matrix_openidc_providers_authentik_client_secret }}"
    scopes:
      - "openid"
      - "profile"
    user_mapping_provider:
      config:
        localpart_template: "{{ '{{ user.name }}' }}"
        display_name_template: "{{ '{{ user.name|capitalize }}' }}"
```
