### ISSUE TITLE
Set path for brand specific custom css instead of inline (eg for blueprints)

### ISSUE THREAD

**Issue by ojsef39** [goauthentik/authentik#15149]
**Is your feature request related to a problem? Please describe.**
Recently, it was changed how users are able to add custom css.
While i like it that its brand specific now, i dont like that you have to copy paste it into the field (or as inline in the blueprint).

Since im all in into Git Ops, this makes editing the custom.css hideous.

**Describe the solution you'd like**
It would be very nice if the field also supports paths additionally to the css file itself, so i can just mount my css into eg `/static/dist/custom-css/brand1.css` (probably somewhere else is more appropriate) and have it all nicely managed in my git repo :)

**Describe alternatives you've considered**
Yes i can just copy and paste the css into a new file to have it separate and syntax highlighting and so on, but above solution would be cooler imo.

**Additional context**

Thanks for reading and considering my suggestion :)

**Comment by BeryJu** [comment]
The recommended way to do this is via a blueprint which can be managed via GitOps. You can have a blueprint like this and mount it to `/blueprints/custom/brand.yaml`

```yaml
metadata:
  name: My Brand
version: 1
entries:
  - attrs:
      branding_custom_css: |
        * {
            color: pink
        }
    identifiers:
      domain: authentik-default
    model: authentik_brands.brand
```

We're not planning to add file support for custom CSS as this offers all the same configuration options without requiring file-system access to the authentik instance
