### ISSUE TITLE
Wrong display of multiple federated OIDC providers

### ISSUE THREAD

**Issue by Leandro4002** [goauthentik/authentik#15168]
**Describe the bug**
When a provider has 2 federated OIDC providers, they are not displayed as selected in the list on the web interface.

**To Reproduce**
Setup a default installation of authentik as explained here: https://docs.goauthentik.io/docs/install-config/install/docker-compose
```bash
wget https://goauthentik.io/docker-compose.yml
echo "PG_PASS=$(openssl rand -base64 36 | tr -d '\n')" >> .env
echo "AUTHENTIK_SECRET_KEY=$(openssl rand -base64 60 | tr -d '\n')" >> .env
docker compose pull
docker compose up -d
```
Then go to Customization > Blueprints and create a new internal blueprint with the name "test" and with this content:
```yaml
context: {}
version: 1
metadata:
  name: "Test blueprint with 2 providers and 2 applications"
entries:
- model: authentik_providers_oauth2.oauth2provider
  state: present
  identifiers:
    name: Provider for AAA
  id: aaa-provider
  attrs:
    access_code_validity: minutes=1
    access_token_validity: minutes=5
    authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
    invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
    client_id: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    client_type: public
    include_claims_in_id_token: true
    issuer_mode: per_provider
    redirect_uris:
      - url: "http://example.com"
        matching_mode: strict
    name: AAA
    refresh_token_validity: days=30
    signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
    sub_mode: hashed_user_id
    property_mappings:
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]
- model: authentik_core.application
  state: present
  identifiers:
    slug: aaa
  conditions: []
  attrs:
    name: AAA
    policy_engine_mode: any
    provider: !KeyOf aaa-provider
    slug: aaa
- model: authentik_providers_oauth2.oauth2provider
  state: present
  identifiers:
    name: Provider for BBB
  id: bbb-provider
  attrs:
    access_code_validity: minutes=1
    access_token_validity: minutes=5
    authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
    invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
    client_id: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    client_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    client_type: confidential
    include_claims_in_id_token: true
    issuer_mode: per_provider
    redirect_uris:
      - url: "http://example.com"
        matching_mode: strict
    name: BBB
    refresh_token_validity: days=30
    signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
    sub_mode: hashed_user_id
    property_mappings:
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
- model: authentik_core.application
  state: present
  identifiers:
    slug: bbb
  conditions: []
  attrs:
    name: BBB
    policy_engine_mode: any
    provider: !KeyOf bbb-provider
    slug: bbb
- model: authentik_providers_oauth2.oauth2provider
  state: present
  identifiers:
    name: Provider for CCC
  id: ccc-provider
  attrs:
    access_code_validity: minutes=1
    access_token_validity: minutes=5
    authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
    invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
    client_id: CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    client_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    client_type: confidential
    include_claims_in_id_token: true
    issuer_mode: per_provider
    redirect_uris:
      - url: "http://example.com"
        matching_mode: strict
    name: CCC
    refresh_token_validity: days=30
    signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
    sub_mode: hashed_user_id
    property_mappings:
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
      - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
    jwt_federation_providers:
      - !Find [authentik_providers_oauth2.oauth2provider, [name, Provider for AAA]]
      - !Find [authentik_providers_oauth2.oauth2provider, [name, Provider for BBB]]
- model: authentik_core.application
  state: present
  identifiers:
    slug: ccc
  conditions: []
  attrs:
    name: CCC
    policy_engine_mode: any
    provider: !KeyOf ccc-provider
    slug: ccc


```

It is a simple configuration with 3 providers : AAA, BBB and CCC. They each have an application with the same name. The CCC provider has the AAA and BBB providers configured as federated OIDC provider. Here is the relevant config line:
```yaml
    jwt_federation_providers:
      - !Find [authentik_providers_oauth2.oauth2provider, [name, Provider for AAA]]
      - !Find [authentik_providers_oauth2.oauth2provider, [name, Provider for BBB]]
```
Then on your blueprints list, find the blueprint "test" you've just created and apply it.
Now Go on Applications > Providers and edit the provider named "Provider for CCC". Go to "Machine to Machine authentication settings" and you'll see that no provider is selected. And that we cannot add one.
There is a javascript error on the console.

**Expected behavior**
The federated OIDC provider must appear on the select list on the web interface in the edit page of a provider.

**Screenshots**
![Image](https://github.com/user-attachments/assets/785d332f-f0cd-44ec-ac8e-f0e458d2068c)
![Image](https://github.com/user-attachments/assets/1365da98-1b85-4788-adf0-920a4e1493b6)

**Version and Deployment:**
-   authentik version: [e.g. 2025.6.2]
-   Deployment: Using docker compose
