### ISSUE TITLE
Expression Policy: 'ak_client_ip' is not defined

### ISSUE THREAD

**Issue by macmoritz** [goauthentik/authentik#15161]
**Describe the bug**
Using `ak_client_ip` in a expression policy as [documented](https://version-2025-6.goauthentik.io/docs/customize/policies/expression) throws a "is not defined error".

**To Reproduce**

1. Create expression policy
2. Use `ak_client_ip` in expression
3. Save
4. See error been thrown in event log

**Expected behavior**
Using `ak_client_ip` as [documented](https://version-2025-6.goauthentik.io/docs/customize/policies/expression).

**Logs**
Event log:
```
Traceback (most recent call last):
  File "my-expression", line 14, in <module>
  File "my-expression", line 4, in handler
builtins.NameError: name 'ak_client_ip' is not defined
```

**Version and Deployment (please complete the following information):**
-   authentik version: 2025.2.0
-   Deployment: helm

**Additional context**
In version 2025.2.4 it works, in 2025.6.2 the "is not defined" error came up.  
The linked docs did not change since Feb 19, the release of 2025.2.4 was on Apr 8.

**Comment by dewi-tik** [comment]
I've just tested `ak_client_ip` on 2025.6.2 and it's working as expected. Can you please share the expression policy that you're testing?

**Comment by macmoritz** [comment]
```python
from authentik.policies.reputation.models import Reputation

ak_logger.debug(f"reputation at threshold: triggered with ip: {ak_client_ip}; user: {request.user}")
reps = Reputation.objects.filter(ip=ak_client_ip, identifier=request.user.username)
[...]
```  
This is the start of the expression policy. In the event log there is the "Model updated" event, directly followed by "Policy exception" from the same object.  
Am I missing something like an import?

**Comment by dewi-tik** [comment]
`ak_client_ip` utilizes the [ipaddress python library](https://docs.python.org/3/library/ipaddress.html#module-ipaddress) and outputs in this form: `"IPv4Address('192.168.0.1')"`

What are you trying to achieve with the policy?

**Comment by macmoritz** [comment]
This policy should trigger if there is a reputation score below a certain threshold.
But there are other cases where we use `ak_client_ip`, which is not working after updating to 2025.6.2. Currently this blocks updating our production environment.

**Comment by benedikt-bartscher** [comment]
Same here, `ak_client_ip` seems not defined in some contexts

**Comment by dewi-tik** [comment]
`ak_client_ip` is not defined in some contexts such as those without HTTP_Requests, for example synchronization property mappings. 

@macmoritz Can you please give more information on where the policy is being used/applied?

**Comment by macmoritz** [comment]
`ak_client_ip` was used in a policy, which was intended to trigger a notification if a user has a reputation above a threshold.  
Interesting: The user is passed from the failed login to the policy execution, but not the ip address. Is there a reason, why the ip address is not passed through?

**Comment by rissson** [comment]
> `ak_client_ip` was used in a policy, which was intended to trigger a notification if a user has a reputation above a threshold. Interesting: The user is passed from the failed login to the policy execution, but not the ip address. Is there a reason, why the ip address is not passed through?

could you show how it's bound, and on which event specifically you get the error. Don't just tell us, show a screenshot of the event please.

**Comment by macmoritz** [comment]
Sorry I was just playing around in the ui but now I've started creating a blueprint for this:
```yaml
  ### Notifications
  - identifiers:
      name: bad-reputation-notification
    id: group-bad-reputation-notification
    model: authentik_core.group
    attrs:
      name: bad reputation notification
  - identifiers:
      name: reputation-at-threshold
    id: reputation-at-threshold
    model: authentik_policies_expression.expressionpolicy
    attrs:
      expression: |-
        from authentik.policies.reputation.models import Reputation
        from django.db.models import Sum
        # ak_client_ip is not defined in here

        if "event" not in request.context:
            return False

        ak_logger.debug(f"reputation at threshold: user: {request.user}")
        reps = Reputation.objects.filter(identifier=request.user.username)

        ak_logger.debug(f"reputation at threshold: found {len(reps)=} reputations with user {request.user}")

        if len(reps) == 0:
          return False

        rep = reps.aggregate(Sum('score'))['score__sum']
        ak_logger.debug(f"reputation : {rep=}")
        return rep == -5
  - identifiers:
      name: notify-bad-reputation
    id: notify-bad-reputation
    model: authentik_events.notificationrule
    attrs:
      destination_group: !KeyOf group-bad-reputation-notification
      transports: [!Find [authentik_events.notificationtransport, [name, default-email-transport]]]
  - identifiers:
      order: 0
      policy: !KeyOf reputation-at-threshold
      target: !KeyOf notify-bad-reputation
    model: authentik_policies.policybinding
    attrs:
      enabled: true
```  
  
This are the relevant event logs (sensitive data was removed or censored): 
![Image](https://github.com/user-attachments/assets/e8926946-a15a-49e9-b50b-caa5e3d80150)

As you can see the failed login has an user and an ip address, but only the username is passed to the policy. Therefor the `ak_client_ip` is not defined in the expression policy above.  
The main goal is to get notifications if an user exceedes a certain reputation. A check with ip and username would be better for more precise blocking.  
Is it possible to pass the ip through as already done with the user?  
I am open for any hints or tips!
