### ISSUE TITLE
Cannot pull ghcr.io/goauthentik/authentik (manifest unknown) on x86_64, other GHCR images work

### ISSUE THREAD

**Issue by begunfx** [goauthentik/authentik#15277]
**Describe the bug**
unable to pull ghcr.io/goauthentik/authentik:latest, 2025.6.2, 2024.10.0

The error is consistently Error response from daemon: manifest unknown.

sudo docker manifest inspect ghcr.io/goauthentik/authentik:latest also returns manifest unknown.

**To Reproduce**

Confirmed x86_64 architecture.

Updated Docker client to 24.0.2.

Cleared Docker cache (docker system prune -a).

Tested multiple Authentik tags.

-   authentik version: 2025.6.2
-   Deployment: docker-compose
-  Portainer Stack

Compose file:
```
services:
  authentik:
    # ORIGINAL: image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/authentik}:${AUTHENTIK_TAG:-2025.6}
    # MODIFIED FOR PORTAINER:
    image: ghcr.io/goauthentik/authentik:2025.6 # Or whatever the latest stable tag is
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_LISTEN__HTTP: 0.0.0.0:${AUTHENTIK_PORT_HTTP}
      AUTHENTIK_LISTEN__HTTPS: 0.0.0.0:${AUTHENTIK_PORT_HTTPS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ERROR_REPORTING__ENABLED:-true}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    # Comment out or remove the ports section
    # ports:
    #   - "${COMPOSE_PORT_HTTP:-9000}:${AUTHENTIK_PORT_HTTP}"
    #   - "${COMPOSE_PORT_HTTPS:-9443}:${AUTHENTIK_PORT_HTTPS}"
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -fskS http://localhost:${AUTHENTIK_PORT_HTTP}/ping/"]
      interval: 1m
      timeout: 3s
      retries: 5
    networks:
      - authentik_network
      - nginx_proxy_manager_default

  worker:
    # ORIGINAL: image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/authentik}:${AUTHENTIK_TAG:-2025.6}
    # MODIFIED FOR PORTAINER:
    image: ghcr.io/goauthentik/authentik:2025.6 # Or whatever the latest stable tag is
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ERROR_REPORTING__ENABLED:-true}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    depends_on:
      - postgres
      - redis
    networks:
      - authentik_network

  postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - authentik_network

  redis:
    image: docker.io/library/redis:7-alpine
    restart: unless-stopped
    networks:
      - authentik_network

networks:
  authentik_network:
    driver: bridge
  nginx_proxy_manager_default:
    external: true 

```
