### ISSUE TITLE
Persistent `Connection error, reconnecting....` prompt in GUI

### ISSUE THREAD

**Issue by cnocmpls** [goauthentik/authentik#15317]
Getting constant error pop-ups in Authentik GUI. In browser console log it shows as:
```
ws.ts:27 WebSocket connection to 'wss://authentik.domain/ws/client/' failed: 
connect @ ws.ts:27
d @ ws.ts:17
G @ index.entrypoint.ts:285
(anonymous) @ custom-element.ts:60
Le @ IQ5NWFN3.js:1
(anonymous) @ index.entrypoint.ts:264
ws.ts:27 WebSocket connection to 'wss://authentik.domain/ws/client/' failed: 
connect @ ws.ts:27
(anonymous) @ ws.ts:48
ws.ts:27 WebSocket connection to 'wss://authentik.domain/ws/client/' failed: 
connect @ ws.ts:27
(anonymous) @ ws.ts:48
ws.ts:27 WebSocket connection to 'wss://authentik.domain/ws/client/' failed: 
connect @ ws.ts:27
(anonymous) @ ws.ts:48
ws.ts:27 WebSocket connection to 'wss://authentik.domain/ws/client/' failed: 
connect @ ws.ts:27
(anonymous) @ ws.ts:48
```

To Reproduce

Deploy Authentik using docker-compose.
```
root@authentik:/opt/authentik# cat docker-compose.yml
---

services:
  postgresql:
    image: docker.io/library/postgres:17-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.6.3}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
#      AUTHENTIK_SSL__CERT_BUNDLE: /certs/letsencrypt-r10.crt
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
 #     - ./certs:/certs
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.6.3}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
  #    AUTHENTIK_SSL__CERT_BUNDLE: /certs/letsencrypt-r10.crt
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
    driver: local
  redis:
    driver: local
```

.env
```
AUTHENTIK_ERROR_REPORTING__ENABLED=false
AUTHENTIK_LOG_LEVEL=debug
PG_PASS=pg_pass
AUTHENTIK_SECRET_KEY=secret_key
```

Place the deployment behind a standard Nginx reverse proxy.
```
# /etc/nginx/sites-available/authentik.domain

# Upstream for the Authentik backend server.
upstream authentik {
    server 192.168.1.1:9000;
    keepalive 10;
}

# This map directive handles the "Connection" header.
# If the client requests a WebSocket upgrade, it passes "upgrade".
# For regular HTTP requests, it passes an empty value, which helps with keepalive.

map $http_upgrade $connection_upgrade_keepalive {
    default upgrade;
    ''      '';
}

# Server block to redirect HTTP to HTTPS.
server {
    listen 80;
    listen [::]:80;
    server_name authentik.domain;

    # Certbot-managed redirect to HTTPS.
    if ($host = authentik.domain) {
        return 301 https://$host$request_uri;
    }


}

# Main server block for handling all HTTPS traffic.
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name authentik.domain;


    # --- SSL Configuration ---
    ssl_protocols TLSv1.3;
    ssl_ciphers 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    # --- Main Proxy Location ---
    # This single location handles all requests and proxies them to Authentik.
    location / {
        # Proxy all requests to the authentik upstream server.
        proxy_pass http://authentik;
#        proxy_ssl_verify off;

        # Set proxy headers required by Authentik.
        proxy_set_header Host                   $http_host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;

        # Set headers for WebSocket support using the 'map' directive.
        proxy_http_version 1.1;
        proxy_set_header Upgrade                $http_upgrade;
        proxy_set_header Connection             $connection_upgrade_keepalive;
        
        # Recommended timeouts
#        proxy_connect_timeout 60s;
#        proxy_send_timeout 60s;
#        proxy_read_timeout 60s;
#        proxy_buffering off;
    }

    ssl_certificate /etc/letsencrypt/live/authentik.domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/authentik.domain/privkey.pem; # managed by Certbot
}
```

Navigate to the GUI(user or Admin)

A pop-up appears with message `Connection error, reconnecting....`

Expected behavior
The websocket connection should remain active and stable, allowing logs and task statuses to stream into the Admin UI in real-time without requiring a manual page refresh.

Screenshots

![Image](https://github.com/user-attachments/assets/42306d54-438e-4223-a67c-2f33ed97d97e)

Logs
Nginx error logs:
```
2025/06/30 15:05:44 [error] 2710725#2710725: *48819177 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 1.1.1.1, server: authentik.domain, request: "GET /ws/client/ HTTP/1.1", upstream: "http://192.168.1.1:9000/ws/client/", host: "authentik.domain"
```

I tried to use websocat on the authentik host to see if the error was persistent before nginx as well:
```
root@authentik:/opt/authentik# ./websocat --log-verbose  ws://localhost:9000/ws/client/
2025-06-30T07:21:17.311835Z ERROR websocat::scenario_executor::utils1: Upstream server's Upgrade: header is not `websocket`
```

The following is a standard Nginx reverse proxy configuration that reproduces this issue. Despite having the correct Upgrade and Connection headers for websocket proxying, the connection is not stable.
