### ISSUE TITLE
worker going unhealthy

### ISSUE THREAD

**Issue by RXWatcher** [goauthentik/authentik#1627]
**Describe the bug**
I'm seeing the worker go unhealthy and never recover. I have autoheal that will restart the container if unhealthy and it contstantly wants to restart the contaner.

My docker-compose:

```
  authentik_worker:
    image:  ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2021.9.8}
    # image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2021.9.2}
    restart: unless-stopped
    container_name: authentik_worker
    depends_on:
      - authentik_server
    command: worker
    env_file:
      - .env
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /backups and /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA_ROOT}/authentik/backups:/backups
      - ${APPDATA_ROOT}/authentik/media:/media
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_ROOT}/authentik/custom-templates:/templates
      - ${APPDATA_ROOT}/authentik/geoip:/geoip
    labels:
      autoheal: false
```

**To Reproduce**
Start a worker, wait a bit and check its health status

**Expected behavior**
That it not go unhealthy

**Screenshots**

![unhealthy](https://user-images.githubusercontent.com/14085001/137582674-1c86529c-85cf-47c9-8da9-6a6028e61a61.jpg)

**Logs**
```
rs28:docker $ docker logs -f authentik_worker
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1634373108.9413393, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1634373108.9417012, "count": 20}
{"event": "Bootstrap completed", "level": "info", "logger": "bootstrap", "command": "worker"}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1634373110.3922012, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1634373110.3924723, "count": 20}
{"event": "Error reporting is enabled", "level": "info", "logger": "authentik.root.settings", "timestamp": 1634373110.5746686, "env": "customer"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.root.settings", "timestamp": 1634373110.621284, "version": "2021.9.8"}

 -------------- celery@1a154f6730e5 v5.1.2 (sun-harmonics)
--- ***** -----
-- ******* ---- Linux-5.11.11-051111-generic-x86_64-with-glibc2.28 2021-10-16 10:31:52
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         authentik:0x7f940a71b4c0
- ** ---------- .> transport:   redis://redis:6379/1
- ** ---------- .> results:     redis://redis:6379/1
- *** --- * --- .> concurrency: {min=1, max=3} (prefork)
-- ******* ---- .> task events: ON
--- ***** -----
 -------------- [queues]
                .> authentik        exchange=authentik(direct) key=authentik
                .> authentik_events exchange=authentik_events(direct) key=authentik_events
                .> authentik_scheduled exchange=authentik_scheduled(direct) key=authentik_scheduled

{"event": "/usr/local/lib/python3.9/site-packages/celery/app/utils.py:204: CDeprecationWarning: \n    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in\n    version 6.0.0. Use the result_backend instead\n\n  deprecated.warn(description=f'The {setting!r} setting',\n", "level": "warning", "logger": "py.warnings", "timestamp": 1634373112.639841}
{"event": "Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.", "level": "warning", "logger": "celery.apps.worker", "timestamp": 1634373112.6413448}
{"event": "event doesn't exist yet or anymore", "event_uuid": "6c593ef448e2459dbbc11cce689ef5c8", "level": "warning", "logger": "authentik.events.tasks", "pid": 403, "timestamp": "2021-10-16T10:49:11.551708"}
{"event": "event doesn't exist yet or anymore", "event_uuid": "6c593ef448e2459dbbc11cce689ef5c8", "level": "warning", "logger": "authentik.events.tasks", "pid": 404, "timestamp": "2021-10-16T10:49:11.551692"}
{"event": "event doesn't exist yet or anymore", "event_uuid": "6c593ef448e2459dbbc11cce689ef5c8", "level": "warning", "logger": "authentik.events.tasks", "pid": 326, "timestamp": "2021-10-16T10:49:11.556123"}
{"event": "event doesn't exist yet or anymore", "event_uuid": "424f645aad234577a1550311e79ddbf3", "level": "warning", "logger": "authentik.events.tasks", "pid": 403, "timestamp": "2021-10-16T10:49:11.582936"}
{"event": "event doesn't exist yet or anymore", "event_uuid": "424f645aad234577a1550311e79ddbf3", "level": "warning", "logger": "authentik.events.tasks", "pid": 403, "timestamp": "2021-10-16T10:49:11.590810"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.8
 - Deployment: [e.g. docker-compose, helm]
docker-compose
**Additional context**
