### ISSUE TITLE
backup_database system task fails with password from docker secret file

### ISSUE THREAD

**Issue by klatka** [goauthentik/authentik#1828]
**Describe the bug**
backup_database system task: command pg_dump failed with password from docker secret file.

**To Reproduce**
1. Create secret files
2. Run docker-compose:
```
version: "3.8"

networks:
  traefik:
    external: true
  local:
    external: false
    driver: bridge

secrets:
  authentik_pg_pass:
    file: $SECRETSDIR/authentik_pg_pass
  authentik_secret_key:
    file: $SECRETSDIR/authentik_secret_key
  mail_auth_password:
    file: $SECRETSDIR/mail_auth_password

services:
  postgresql:
    container_name: authentik-pg
    image: postgres:12-alpine
    restart: unless-stopped
    networks:
      - local
    secrets:
      - authentik_pg_pass
    volumes:
      - $BASEDIR/authentik/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=/run/secrets/authentik_pg_pass
      - POSTGRES_USER=${PG_USER:-authentik}
      - POSTGRES_DB=${PG_DB:-authentik}
  redis:
    container_name: authentik-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - local
  server:
    container_name: authentik
    image: ${AUTHENTIK_IMAGE:-goauthentik.io/server}:${AUTHENTIK_TAG:-stable}
    restart: unless-stopped
    command: server
    networks:
      - local
      - traefik
    secrets:
      - authentik_pg_pass
      - authentik_secret_key
      - mail_auth_password
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: /run/secrets/authentik_secret_key
      AUTHENTIK_POSTGRESQL__HOST: authentik-pg
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: /run/secrets/authentik_pg_pass
      AUTHENTIK_EMAIL__PASSWORD: /run/secrets/mail_auth_password
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST: "mail.example.com"
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: "authentik@example.com"
      AUTHENTIK_EMAIL__USE_TLS: "true"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: "authentik@example.com"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    volumes:
      - $BASEDIR/authentik/media:/media
      - $BASEDIR/authentik/custom-templates:/templates
    #ports:
    #  - "0.0.0.0:9000:9000"
    #  - "0.0.0.0:9443:9443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik-rtr.entrypoints=https"
      - "traefik.http.routers.authentik-rtr.rule=Host(`auth.$DOMAIN`)"
      - "traefik.http.routers.authentik-rtr.tls=true"
      - "traefik.http.routers.authentik-rtr.middlewares=chain-base@file"
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadbalancer.server.port=9000"
  worker:
    container_name: authentik-worker
    image: ${AUTHENTIK_IMAGE:-goauthentik.io/server}:${AUTHENTIK_TAG:-stable}
    restart: unless-stopped
    command: worker
    networks:
      - local
      - dsocket
    secrets:
      - authentik_pg_pass
      - authentik_secret_key
      - mail_auth_password
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: /run/secrets/authentik_secret_key
      AUTHENTIK_POSTGRESQL__HOST: authentik-pg
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: /run/secrets/authentik_pg_pass
      AUTHENTIK_EMAIL__PASSWORD: /run/secrets/mail_auth_password
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST: "mail.example.com"
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: "authentik@example.com
      AUTHENTIK_EMAIL__USE_TLS: "true"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: "authentik@example.com"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # This is optional, and can be removed. If you remove this, the following will happen
      # - The permissions for the /backups and /media folders aren't fixed, so make sure they are 1000:1000
      # - The docker socket can't be accessed anymore
    user: root
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - $BASEDIR/authentik/custom-templates:/templates
```

**Expected behavior**
pg_dump is called with password from docker secret file and creates a database dump.

**Screenshots**

**Logs**
backup_database system task:
```
Traceback (most recent call last):
File "/authentik/core/tasks.py", line 82, in backup_database
management.call_command("dbbackup", quiet=True, stdout=out)
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
return command.execute(*args, **defaults)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.9/site-packages/dbbackup/utils.py", line 114, in wrapper
func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbbackup.py", line 66, in handle
self._save_new_backup(database)
File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbbackup.py", line 79, in _save_new_backup
outputfile = self.connector.create_dump()
File "/usr/local/lib/python3.9/site-packages/dbbackup/db/base.py", line 84, in create_dump
dump = self._create_dump()
File "/usr/local/lib/python3.9/site-packages/dbbackup/db/postgresql.py", line 50, in _create_dump
stdout, stderr = self.run_command(cmd, env=self.dump_env)
File "/usr/local/lib/python3.9/site-packages/dbbackup/db/base.py", line 157, in run_command
raise exceptions.CommandConnectorError(
Error running: pg_dump --dbname=postgresql://authentik:/run/secrets/authentik_pg_pass@authentik-pg:5432/authentik --clean
pg_dump: error: connection to server at "authentik" (172.23.0.6), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: docker-compose

**Additional context**
