### ISSUE TITLE
SAML POST binding turned into GET without body when user hasn't previously logged in to authentik

### ISSUE THREAD

**Issue by rucciva** [goauthentik/authentik#1873]
**Describe the bug**
When user first logged-in to SAML service provider (POST binding) without being previously logged-in to authentik, the request to POST Binding endpoint turned into GET without request body after user succesfully logged-in to authentik.

**To Reproduce**
1. Open new browser without existing session (such as new incognito tab)
2. Login to SAML Service Provider that use POST binding
3. Follow redirect and login to authentik
4. See error "The SAML request payload is missing"

**Expected behavior**
Successfully loged in to SAML Service Provider

**Screenshots**
<img width="857" alt="Screen Shot 2021-12-02 at 18 08 22" src="https://user-images.githubusercontent.com/4647473/144410984-29c86d1c-0bb7-4b12-aadb-a629a46efbeb.png">

**Logs**
```
{"event": "Bad Request: /application/saml/checkmarx/sso/binding/post/", "level": "warning", "logger": "django.request", "timestamp": 1638440408.3246837}
{"event": "/application/saml/checkmarx/sso/binding/post/", "host": "x.x.x.x", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "eb09b30b2e154b38bfd51fbc65ffbc97", "runtime": 1600, "scheme": "https", "size": 0.161, "status": 400, "timestamp": "2021-12-02T10:20:08.326311", "user": "user", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
@rucciva Can you check if this still happens with 2021.12.1-rc2?

**Comment by rucciva** [comment]
checked, it no longer happens. thank you very much

**Comment by rucciva** [comment]
but now login to service provider failed when user has already authenticated to authentik

**Comment by BeryJu** [comment]
Which service provider are you testing this with?

**Comment by rucciva** [comment]
Checkmarx and defectdojo

**Comment by BeryJu** [comment]
I'll try and replicate it with defectdojo, I was able to successfully login to https://github.com/BeryJu/saml-test-sp both after the initial authentik login and also while the user was already logged in.

Can you post your config for defectdojo?

**Comment by rucciva** [comment]
sure, here they are.

```
version: '3.7'
services:
  nginx:
    image: "defectdojo/defectdojo-nginx:2.4.1"
    depends_on:
      - uwsgi
    environment:
      NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}"
    volumes:
      - defectdojo_media:/usr/share/nginx/html/media
    ports:
      - target: 8080
        published: ${DD_PORT:-8080}
        protocol: tcp
        mode: host
  uwsgi:
    image: "defectdojo/defectdojo-django:2.4.1"
    depends_on:
      - mysql
    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', '/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_DJANGO_METRICS_ENABLED: "${DD_DJANGO_METRICS_ENABLED:-False}"
      DD_ALLOWED_HOSTS: "${DD_ALLOWED_HOSTS:-*}"
      DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:somepassword@mysql:3306/defectdojo}"
      DD_CELERY_BROKER_USER: "${DD_CELERY_BROKER_USER:-guest}"
      DD_CELERY_BROKER_PASSWORD: "${DD_CELERY_BROKER_USER:-guest}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
      DD_SITE_URL: "https://defectdojo.domain.tld"      
      DD_SAML2_ENABLED: "true"
      DD_SAML2_METADATA_AUTO_CONF_URL: "https://authentik.domain.tld/api/v3/providers/saml/16/metadata/?download"
      #      DD_SAML2_ASSERTION_URL: "https://DD_FQDN"
      DD_SAML2_ATTRIBUTES_MAPS_EMAIL: "Email"
      DD_SAML2_ATTRIBUTES_MAPS_USERNAME: "username"
      DD_SAML2_ATTRIBUTES_MAPS_FIRSTNAME: "First_Name"
      DD_SAML2_ATTRIBUTES_MAPS_LASTNAME: "Last_Name"
      DD_SAML2_CREATE_USER: "true"
      #      REQUESTS_CA_BUNDLE: "/app/cert/bundle.pem"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
        - "defectdojo_media:${DD_MEDIA_ROOT:-/app/media}"
        - "./bundle.pem:/app/cert/bundle.pem"
  celerybeat:
    image: "defectdojo/defectdojo-django:2.4.1"
    depends_on:
      - mysql
      - rabbitmq
    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', '/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:somepassword@mysql:3306/defectdojo}"
      DD_CELERY_BROKER_USER: "${DD_CELERY_BROKER_USER:-guest}"
      DD_CELERY_BROKER_PASSWORD: "${DD_CELERY_BROKER_USER:-guest}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
      DD_SITE_URL: "https://defectdojo.domain.tld"      
      DD_SAML2_ENABLED: "true"
      DD_SAML2_METADATA_AUTO_CONF_URL: "https://authentik.domain.tld/api/v3/providers/saml/16/metadata/?download"
      DD_SAML2_ASSERTION_URL: "https://DD_FQDN"
      DD_SAML2_ATTRIBUTES_MAPS_EMAIL: "email"
      DD_SAML2_ATTRIBUTES_MAPS_USERNAME: "username"
      DD_SAML2_ATTRIBUTES_MAPS_FIRSTNAME: "first_name"
      DD_SAML2_ATTRIBUTES_MAPS_LASTNAME: "last_name"      
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
  celeryworker:
    image: "defectdojo/defectdojo-django:2.4.1"
    depends_on:
      - mysql
      - rabbitmq
    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', '/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:somepassword@mysql:3306/defectdojo}"
      DD_CELERY_BROKER_USER: "${DD_CELERY_BROKER_USER:-guest}"
      DD_CELERY_BROKER_PASSWORD: "${DD_CELERY_BROKER_USER:-guest}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
      DD_SITE_URL: "https://defectdojo.domain.tld"      
      DD_SAML2_ENABLED: "true"
      DD_SAML2_METADATA_AUTO_CONF_URL: "https://authentik.domain.tld/api/v3/providers/saml/16/metadata/?download"
      DD_SAML2_ASSERTION_URL: "https://DD_FQDN"
      DD_SAML2_ATTRIBUTES_MAPS_EMAIL: "email"
      DD_SAML2_ATTRIBUTES_MAPS_USERNAME: "username"
      DD_SAML2_ATTRIBUTES_MAPS_FIRSTNAME: "first_name"
      DD_SAML2_ATTRIBUTES_MAPS_LASTNAME: "last_name"      
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
        - "defectdojo_media:${DD_MEDIA_ROOT:-/app/media}"
  initializer:
    image: "defectdojo/defectdojo-django:2.4.1"
    depends_on:
      - mysql
    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '--', '/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:somepassword@mysql:3306/defectdojo}"
      DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
      DD_ADMIN_MAIL: "${DD_ADMIN_USER:-admin@domain.tld}"
      DD_ADMIN_FIRST_NAME: "${DD_ADMIN_FIRST_NAME:-Admin}"
      DD_ADMIN_LAST_NAME: "${DD_ADMIN_LAST_NAME:-User}"
      DD_INITIALIZE: "${DD_INITIALIZE:-true}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
      DD_SAML2_ENABLED: "true"
      DD_SITE_URL: "https://defectdojo.domain.tld"
      DD_SAML2_METADATA_AUTO_CONF_URL: "https://authentik.domain.tld/api/v3/providers/saml/16/metadata/?download"
      DD_SAML2_ASSERTION_URL: "https://DD_FQDN"
      DD_SAML2_ATTRIBUTES_MAPS_EMAIL: "email"
      DD_SAML2_ATTRIBUTES_MAPS_USERNAME: "username"
      DD_SAML2_ATTRIBUTES_MAPS_FIRSTNAME: "first_name"
      DD_SAML2_ATTRIBUTES_MAPS_LASTNAME: "last_name"      
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
  mysql:
    image: mysql:5.7.36@sha256:7a3a7b7a29e6fbff433c339fc52245435fa2c308586481f2f92ab1df239d6a29
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:somepassword@mysql:3306/defectdojo}"
      MYSQL_USER: "${DD_DATABASE_USER:-defectdojo}"
      MYSQL_PASSWORD: "${DD_DATABASE_PASSWORD:-somepassword}"
      MYSQL_DATABASE: "${DD_DATABASE_NAME:-defectdojo}"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
       - defectdojo_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.9.10@sha256:0d862496f77a3bd377eb5de437411a4388885f0f0c2452291e97a85bc89df87a
    volumes:
       - defectdojo_rabbitmq:/var/lib/rabbitmq
volumes:
  defectdojo_data: {}
  defectdojo_media: {}
  defectdojo_rabbitmq: {}
```


<img width="1084" alt="Screen Shot 2021-12-05 at 21 32 28" src="https://user-images.githubusercontent.com/4647473/144751125-ef108f60-7af4-45c1-819c-f1d3cae5179f.png">
<img width="1093" alt="Screen Shot 2021-12-05 at 21 31 01" src="https://user-images.githubusercontent.com/4647473/144751132-affad964-999c-419c-b6c9-84c679992730.png">
