### ISSUE TITLE
Forward auth redirecting to authentik instead of app

### ISSUE THREAD

**Issue by rxbn** [goauthentik/authentik#1997]
**Describe the bug**
When I visit `app1.example.com`, which is behind domain level forward auth, authentik does the authentication but then redirects me to the authentik main page (app overview) instead of the application I originally wanted to visit.

**To Reproduce**
1. Go to URL of an app behind domain level forward auth
2. authentik does authentication
3. authentik redirects to start page instead of app URL

**Expected behavior**
Authentik should redirect the browser to the requested app and not to the start page.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.4
 - Deployment: helm

**Additional context**
Not additional context but I just wanted to say thank you for all the effort you put in this awesome application :)

Happy Holidays!

**Comment by rxbn** [comment]
Okay, I have researched a bit... The affected application is not hosted on the same server as authetik is. I pointed my forward auth middleware to the public domain of authentik. Maybe that's the issue?

When should a secondary outpost be used? Can I have a domain level forward auth and an application level forward auth with the same root domain?

**Comment by BeryJu** [comment]
If I remember correctly, you were using traefik, right? Because my test setup with traefik does this just as expected, using domain auth.
Could you try with the beta again? I haven't made any changes to the forward auth code since 12.4, but I did add some logging that would be helpful

**Comment by rxbn** [comment]
Yes, I'm using Traefik. I will try that tomorrow. But is the intention behind outposts to put them on all the servers where applications are using forward auth?

**Comment by BeryJu** [comment]
You can do either one, as long as the reverse proxy can reach it for forward auth; for most cases one outpost is enough per k8s cluster.

**Comment by rxbn** [comment]
Alright, but one of my apps is hosted on an external cloud vpc and I only notice the issue with that app.

**Comment by BeryJu** [comment]
It shouldnt make a difference with forward auth, but lets have a look at the logs first

**Comment by rxbn** [comment]
Sorry for the delay, I am currently using authentik 2021.12.5 and the issue persists. Should I enable debug logging for the embedded outpost?

**Comment by BeryJu** [comment]
Yeah just enable it for the main authentik instance and set it to trace

**Comment by rxbn** [comment]
Okay so I found the following:

When I try to access an application hosted on the same Kubernetes host as authentik, I get a log entry with the following contents:

```
{"event":"/akprox/auth/traefik","host":"app.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"192.168.1.48","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"1.843","size":68,"status":307,"timestamp":"2022-01-12T13:52:16Z","upstream":""}
```

When I access my externally hosted service, the "host" field is "auth.example.com" and not "external-app.example.com"

```
{"event":"/akprox/auth/traefik","host":"auth.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"172.70.162.20","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"1.469","size":68,"status":307,"timestamp":"2022-01-12T13:55:03Z","upstream":""}
```

**Comment by rxbn** [comment]
Here is the middleware I use on my external Traefik:

```yaml
---
http:
  middlewares:
    authentik-forward-auth:
      forwardAuth:
        address: https://auth.example.com/akprox/auth/traefik
        authResponseHeaders:
          - X-Auth-Username
          - X-Auth-Groups
          - X-Forwarded-Email
          - X-Forwarded-Preferred-Username
          - X-Forwarded-User
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
        trustForwardHeader: true
```

**Comment by BeryJu** [comment]
> Okay so I found the following:
> 
> When I try to access an application hosted on the same Kubernetes host as authentik, I get a log entry with the following contents (the redirect works here):
> 
> ```
> {"event":"/akprox/auth/traefik","host":"app.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"192.168.1.48","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"1.843","size":68,"status":307,"timestamp":"2022-01-12T13:52:16Z","upstream":""}
> ```
> 
> When I access my externally hosted service, the "host" field is "auth.example.com" and not "external-app.example.com"
> 
> ```
> {"event":"/akprox/auth/traefik","host":"auth.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"172.70.162.20","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"1.469","size":68,"status":307,"timestamp":"2022-01-12T13:55:03Z","upstream":""}
> ```

There should be some surrounding log lines, especially with the level set to trace. Can you post those too?

**Comment by rxbn** [comment]
When accessing "external-app.example.com":

```
{"event":"Redirecting to login","level":"debug","logger":"authentik.outpost.proxy.bundle","provider":"Traefik Forward Auth","timestamp":"2022-01-12T14:23:34Z","url":"https://auth.example.com/akprox/start"}
{"event":"/akprox/auth/traefik","host":"auth.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"162.158.114.140","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"0.509","size":68,"status":307,"timestamp":"2022-01-12T14:23:34Z","upstream":""}
{"event":"/akprox/start","host":"auth.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"192.168.1.48","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"3.027","size":300,"status":302,"timestamp":"2022-01-12T14:23:34Z","upstream":""}
{"event": "user not authenticated", "host": "auth.example.com", "level": "warning", "logger": "authentik.policies.views", "pid": 23, "request_id": "6a311ae86b354ef68a1b201cf14b83a2", "timestamp": "2022-01-12T14:23:34.425762"}
{"event": "/application/o/authorize/?client_id=NHLm0zoq6uBZm6QyBjIEArSKVSYgiJSpeqWVJ7T2&redirect_uri=https%3A%2F%2Fauth.example.com%2Fakprox%2Fcallback&response_type=code&scope=email+ak_proxy+openid+profile&state=eS%2BqNPHuBNpA2JRWtFrd4frLmcn01liAb1MXWecaD78", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "6a311ae86b354ef68a1b201cf14b83a2", "runtime": 17, "scheme": "https", "status": 302, "timestamp": "2022-01-12T14:23:34.427982", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/flows/-/default/authentication/?next=/application/o/authorize/%3Fclient_id%XXXX%26redirect_uri%3Dhttps%253A%252F%252Fauth.example.com%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Demail%2Bak_proxy%2Bopenid%2Bprofile%26state%3DeS%XXXX", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "fd46bbd4058f48e5a49c16c8af31aa4b", "runtime": 16, "scheme": "https", "status": 302, "timestamp": "2022-01-12T14:23:34.506158", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/if/flow/default-authentication-flow/?next=%2Fapplication%2Fo%2Fauthorize%2F%3Fclient_id%XXXX%26redirect_uri%3Dhttps%253A%252F%252Fauth.example.com%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Demail%2Bak_proxy%2Bopenid%2Bprofile%26state%3DeS%XXXX", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "0fe60bfc07f246f089273f7e6e4ee360", "runtime": 13, "scheme": "https", "status": 200, "timestamp": "2022-01-12T14:23:34.533420", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
```

When accessing "app.example.com":

```
{"event":"Redirecting to login","level":"debug","logger":"authentik.outpost.proxy.bundle","provider":"Traefik Forward Auth","timestamp":"2022-01-12T14:25:58Z","url":"https://auth.example.com/akprox/start"}
{"event":"/akprox/auth/traefik","host":"app.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"192.168.1.48","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"2.970","size":68,"status":307,"timestamp":"2022-01-12T14:25:58Z","upstream":""}
{"event":"/akprox/start","host":"auth.example.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Traefik Forward Auth","remote":"192.168.1.48","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","runtime":"2.285","size":300,"status":302,"timestamp":"2022-01-12T14:25:59Z","upstream":""}
{"event": "user not authenticated", "host": "auth.example.com", "level": "warning", "logger": "authentik.policies.views", "pid": 23, "request_id": "18bc0abe12d54c73a75d841f5d2b1df5", "timestamp": "2022-01-12T14:25:59.155685"}
{"event": "/application/o/authorize/?client_id=NHLm0zoq6uBZm6QyBjIEArSKVSYgiJSpeqWVJ7T2&redirect_uri=https%3A%2F%2Fauth.example.com%2Fakprox%2Fcallback&response_type=code&scope=email+ak_proxy+openid+profile&state=V%2BTvzktwyodZIveCXGEfrIgO916RMokigJFKl7wAW2I", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "18bc0abe12d54c73a75d841f5d2b1df5", "runtime": 21, "scheme": "https", "status": 302, "timestamp": "2022-01-12T14:25:59.158478", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/flows/-/default/authentication/?next=/application/o/authorize/%3Fclient_id%XXX%26redirect_uri%3Dhttps%253A%252F%252Fauth.example.com%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Demail%2Bak_proxy%2Bopenid%2Bprofile%26state%3DV%252BTvzktwyodZIveCXGEfrIgO916RMokigJFKl7wAW2I", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "b713ada3c1304c45afd9d03d33886ad7", "runtime": 12, "scheme": "https", "status": 302, "timestamp": "2022-01-12T14:25:59.178944", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/if/flow/default-authentication-flow/?next=%2Fapplication%2Fo%2Fauthorize%2F%3Fclient_id%XXX%26redirect_uri%3Dhttps%253A%252F%252Fauth.example.com%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Demail%2Bak_proxy%2Bopenid%2Bprofile%26state%3DV%252BTvzktwyodZIveCXGEfrIgO916RMokigJFKl7wAW2I", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "0caeed2521cb4101bac59be72471d536", "runtime": 14, "scheme": "https", "status": 200, "timestamp": "2022-01-12T14:25:59.201697", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "f(exec): Continuing existing plan", "flow_slug": "default-authentication-flow", "host": "auth.example.com", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 23, "request_id": "03e917020ca848bf9c652023fd9c3ee1", "timestamp": "2022-01-12T14:25:59.340968"}
{"current_stage": "<IdentificationStage: Stage default-authentication-identification>", "event": "f(exec): Current stage", "flow_slug": "default-authentication-flow", "host": "auth.example.com", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 23, "request_id": "03e917020ca848bf9c652023fd9c3ee1", "timestamp": "2022-01-12T14:25:59.342177"}
{"event": "f(exec): Passing GET", "flow_slug": "default-authentication-flow", "host": "auth.example.com", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 23, "request_id": "03e917020ca848bf9c652023fd9c3ee1", "stage": "<IdentificationStage: Stage default-authentication-identification>", "timestamp": "2022-01-12T14:25:59.343629", "view_class": "authentik.stages.identification.stage.IdentificationStageView"}
{"event": "/api/v3/core/tenants/current/", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "192.168.1.48", "request_id": "e563f92e140f4235af173d63b2b1ef1c", "runtime": 25, "scheme": "https", "status": 200, "timestamp": "2022-01-12T14:25:59.345995", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/api/v3/root/config/", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "e9664c44021e429288a4bd8313c67e97", "runtime": 35, "scheme": "https", "status": 200, "timestamp": "2022-01-12T14:25:59.355764", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/api/v3/flows/executor/default-authentication-flow/?query=next%3D%252Fapplication%252Fo%252Fauthorize%252F%253Fclient_id%XXX%2526redirect_uri%253Dhttps%25253A%25252F%25252Fauth.example.com%25252Fakprox%25252Fcallback%2526response_type%253Dcode%2526scope%253Demail%252Bak_proxy%252Bopenid%252Bprofile%2526state%253DV%XXX", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "192.168.1.48", "request_id": "03e917020ca848bf9c652023fd9c3ee1", "runtime": 41, "scheme": "https", "status": 200, "timestamp": "2022-01-12T14:25:59.357805", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"}
{"event": "/metrics/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "127.0.0.1", "request_id": "3375a7a3457445e68ed27f81433e3597", "runtime": 555, "scheme": "http", "status": 200, "timestamp": "2022-01-12T14:25:59.945732", "user": "", "user_agent": "Go-http-client/1.1"}
```

**Comment by BeryJu** [comment]
Fixed https://github.com/goauthentik/authentik/issues/2109

**Comment by rxbn** [comment]
Thank you so much for putting in so much effort!!

**Comment by rxbn** [comment]
Unfortunately, the error still persists. Even with 2022.1.2

**Comment by BeryJu** [comment]
Could you try with the latest version in master? I just started adding some tests and more logs since this breaks so often

**Comment by bcg62** [comment]
I am also seeing this on 2022.1.2

**Comment by bcg62** [comment]
Same with ghcr.io/goauthentik/dev-server@sha256:91fb3a5ff53e32bedf75240334db26ad32806168345404cfe7dd4a92abe44967 is there something I can grab to help troubleshoot?

**Comment by tavalin** [comment]
Just to add I'm experiencing the same issue with 2022.1.4.

**Comment by rxbn** [comment]
I was able to do a work around by deploying a separate outpost on my cloud vpc instance.

**Comment by Zolli** [comment]
I have the same issue, maybe somone can help me out. I try to describe my setup best as i can.

So i deploy authentik one of my local server using docker-compose. and i run an edge proxy on a digitalocean VPS that have traefikV2 installed standalone. The edge proxy and my local machin(s) connected trough VPN (tailscale if its matter).

I can also able to provide logs, currently the authentik server and the outpost is configured for debug logging.

Here is my traefik configurations:

authentik proxy:
```yaml
http:
  routers:
    authentik-router:
      rule: Host(`id.domain.tld`)
      service: local-authentik-service
      entryPoints:
        - https
      tls: {}
  services:
    local-authentik-service:
      loadBalancer:
        servers:
          - url: "http://TAILSCALE_IP:9000/"
```

authentik middleare:

```yaml
http:
  middlewares:
   authentik:
      forwardAuth:                                                                                                                                                                                      $
        address: "https://id.domain.tld/akprox/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```

```yaml
http:
  routers:
    uptimekuma-router-auth:
      rule: Host(`status.domain.tld`) && PathPrefix(`/akprox/`)
      priority: 15
      service: https://id.domain.tld/akprox
    uptimekuma-router:
      rule: Host(`status.id.tld`)
      service: local-uptimekuma-service
      priority: 10
      entryPoints:
        - https
      tls: {}
      middlewares:
        - authentik
  services:
    local-uptimekuma-service:
      loadBalancer:
        servers:
          - url: "http://TAILSCALE_IP:port/"
```

Authentik configuration:

Embedded outpost configuration:
```
log_level: debug
docker_labels: null
authentik_host: https://id.domain.tld/
docker_network: null
container_image: null
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: ""
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: false
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_disabled_components:
  - deployment
  - secret
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```

For the provider i configured the external host as: `https://status.domain.tld`

**Comment by BeryJu** [comment]
After some further debugging, this might be two individual issues. The actual redirect (authentik and app on the same domain, with domain auth) should be fixed by the commits above, please check with the gh-next build.

The other issue can happen if you have authentik on for example ak.x.y and your application(s) on foo.z.x.y, because authentik cannot create a cookie for the z.x.y domain as its not running on that domain. This is the RFC defined behaviour and this setup can only work if authentik (or at least the outpost) is configured to use anything.z.x.y

**Comment by Zolli** [comment]
@BeryJu i just pushed the dev-server:gh-next image and now i get a 404 when i try to access the application and this line in the logs:

`{"event": "Not Found: /akprox/auth/traefik", "level": "warning", "logger": "django.request", "timestamp": 1644972204.3644965}`

**Comment by BeryJu** [comment]
My bad @Zolli, I forgot to mention in the current beta, that path has changed to `/outpost.goauthentik.io/auth/traefik`, the docs will reflect this one this version is released.

**Comment by Zolli** [comment]
I not set the AUTHENTIK_COOKIE_DOMAIN cookie so i expect that the id.domain.tld is used for cookie domain and i use this url to access authentik as well, also the forward auth is use the same address

**Comment by BeryJu** [comment]
Oh you're using single-app forward auth? What is the external domain set to? @Zolli

**Comment by Zolli** [comment]
Yes, the external url is set to the app address (https://app.domain.tld)

**Comment by BeryJu** [comment]
Hmm, in that case it should just work; but I also feel like this issue is actually 2 or 3 separate things. Since the initial fix is in 22.2.1, I'd like to close this issue and open separate issues (based on reverse-proxy in use, and single-app or domain forward auth)

**Comment by maaft** [comment]
Got the same issue.

- authentik hosted under `authentik.mgmt.domain.org` in cluster1
- app.main.domain.org hosted on cluster2
- app ingress uses traefik forward auth

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: authentik
    namespace: traefik
spec:
    forwardAuth:
        address: https://authentik.mgmt.domain.org/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
            - X-authentik-username
            - X-authentik-groups
            - X-authentik-email
            - X-authentik-name
            - X-authentik-uid
            - X-authentik-jwt
            - X-authentik-meta-jwks
            - X-authentik-meta-outpost
            - X-authentik-meta-provider
            - X-authentik-meta-app
            - X-authentik-meta-version
```
Authentik config:
- app with "single-app" proxy provider pointing to `app.main.domain.org`
- provider activated in embedded outpost

When visiting "app.main.domain.org":

```
{
	"Message": "no app for hostname",
	"Host": "authentik.mgmt.domain.org",
	"Detail": "Check the outpost settings and make sure 'authentik.mgmt.domain.org' is included."
}
```

What to do now?

 @BeryJu you mentioned a "separate" issue - where can I find it?

**Comment by BeryJu** [comment]
You'll want to use the in-cluster service for the `forwardAuth.address`, as when using the external address the headers required will be overwritten

**Comment by maaft** [comment]
You mean the in-cluster service for my **embedded** outpost?

![image](https://user-images.githubusercontent.com/2518993/209130215-7f96ceae-ba2a-4d89-b356-bd9a6e6b1d61.png)

What ist the incluster address of that outpost?

Or: Do I need to configure another outpost for my 2nd cluster? E.g. `authentik.main.domain.org` -> points to 1st cluster's separate outpost.

**Comment by BeryJu** [comment]
Oh my bad, I didn't see that you have two clusters, but in this case it would be easiest to have an outpost in cluster2 and reference that via in-cluster service

The outpost tries to figure out which application to authenticate for by looking at the `Host` header, and with the external URL specified as you have it, traefik will overwrite that header and lead to the error above

**Comment by maaft** [comment]
Ah, alright. So I need to deploy another outpost in my 2nd cluster. I guess there are some docs on how to connect external cluster outposts? Will look it up asap!

**Comment by maaft** [comment]
okay, I created another outpost on my external cluster with the provided helm chart.

- When adding the proxy provider, the outpost created a new ingress for "app.main.domain.org".
- The TLS certificate was missing, so I created one.
- When opening "app.main.domain.org", I get a 500 error now

Here's my middleware config:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: authentik
    namespace: traefik
spec:
    forwardAuth:
        address: ak-outpost-main-outpost.authentik.svc.cluster.local/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
            - X-authentik-username
            - X-authentik-groups
            - X-authentik-email
            - X-authentik-name
            - X-authentik-uid
            - X-authentik-jwt
            - X-authentik-meta-jwks
            - X-authentik-meta-outpost
            - X-authentik-meta-provider
            - X-authentik-meta-app
            - X-authentik-meta-version
```
