### ISSUE TITLE
How to allow access for specific source IPs without authentication using forward auth proxy provider?

### ISSUE THREAD

**Issue by rperpe** [goauthentik/authentik#2029]
**Describe your question/**
I'd like to publish some semi-confidential services internally without authentication (but if they get accessed from external auth is required).
Is it possible to allow access for specific source IP addresses without authentication using authentik's forward auth proxy provider?

**Relevant infos**
Using Traefik as reverse proxy with authentik's single application forward auth proxy providers. So authentik would have to always return HTTP status 200 to Traefik's forward auth middleware if source IP is an internal one.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.4
 - Deployment: docker-compose

**Additional context**
Found something in the docs regarding IP address comparison but didn't understand how to compare to source IP and how integrate this in proxy providers.

**Comment by BeryJu** [comment]
In authentik itself you can currently only do IP Reputation, but that would still require a login. I'm a bit torn whether to include this or not, imo this should be done by your reverse proxy and not authentik, but it also wouldn't be hard to add.

**Comment by rperpe** [comment]
Didn't find a solution for Nginx Proxy Manager (NPM) to achieve this. But it looks like Traefik makes this possible. Will check.

**Comment by rperpe** [comment]
Was able to configure the desired in Traefik:
```
http:
  routers:
    service:
      rule: "Host(`service.mydomain.tld`)"
      tls:
        certResolver: letsencrypt
      middlewares:
      - authentik-forwardauth@file
      priority: 10
      service: "service"

    service-without-forward-auth:
      rule: "Host(`service.mydomain.tld`) && ( ClientIP(`10.62.8.0/24`) || ClientIP(`10.62.12.0/24`) || ClientIP(`10.62.16.0/24`) || ClientIP(`10.36.12.11`) )"
      tls:
        certResolver: letsencrypt
      priority: 15
      service: "service"

    service-akprox:
      rule: "Host(`service.mydomain.tld`) && PathPrefix(`/akprox/`)"
      tls:
        certResolver: letsencrypt
      priority: 20
      service: "authentik-forwardauth-proxy@file"

  services:
    service:
      loadBalancer:
        servers:
          - url: "http://svliman.apps.mydomain.tld:8081/"
```

Nevertheless some source IP comparison would be very helpful within the flows to e.g. skip second factor prompt when users access. Is this possible?
