### ISSUE TITLE
fresh install with helm of authentik-5.2.1 has misconfigured Ingress

### ISSUE THREAD

**Issue by steschuser** [goauthentik/authentik#2390]
Ingress in microk8 cluster will try to open https 443 port, but has no secret
Backend for service "authentik" specifies an invalid port TLS configuration did not define a secret name

**To Reproduce**
1. Get helm chart version 5.2.1 / image 2021.12.5
2. Use values.yml
```
replicas: 1

worker:
  replicas: 1

image:
  repository: ghcr.io/goauthentik/server
  tag: 2021.12.5
  pullPolicy: IfNotPresent
  pullSecrets: []

initContainers: {}

additionalContainers: {}

ingress:
  enabled: true
  ingressClassName: ""
  annotations: {}
  labels: {}
  hosts:
    - host: authentik.systems
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts: []
      secretName: ""

authentik:
  log_level: info
  secret_key: "*"
  geoip: /geoip/GeoLite2-City.mmdb
  avatars: gravatar
  email:
    host: ""
    port: 587
    username: ""
    password: ""
    use_tls: false
    use_ssl: false
    timeout: 30
    from: ""
  outposts:
    container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
  error_reporting:
    enabled: false
    environment: "k8s"
    send_pii: false
  postgresql:
    host: '{{ .Release.Name }}-postgresql'
    name: "authentik"
    user: "authentik"
    password: "*"
    port: 5432
    s3_backup:
      access_key: ""
      secret_key: ""
      bucket: ""
      region: ""
      host: ""
      location: ""
      insecure_skip_verify: false
  redis:
    host: '{{ .Release.Name }}-redis-master'
    password: "*"

env: {}

envFrom: []

envValueFrom: {}

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: http
  protocol: TCP
  labels: {}
  annotations: {}

volumes: []

volumeMounts: []

affinity: {}

nodeSelector: {}

resources:
  server: {}
  worker: {}

livenessProbe:
  enabled: true
  httpGet:
    path: /-/health/live/
    port: http
  initialDelaySeconds: 50
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /-/health/ready/
    port: http
  initialDelaySeconds: 50
  periodSeconds: 10

serviceAccount:
  create: true

prometheus:
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 3s
  rules:
    create: false

geoip:
  enabled: false
  accountId: ""
  licenseKey: ""
  editionIds: "GeoLite2-City"
  image: maxmindinc/geoipupdate:v4.8
  updateInterval: 8

postgresql:
  enabled: true
  postgresqlUsername: "authentik"
  postgresqlPassword: "*"
  postgresqlDatabase: "authentik"
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
```
Ingress will not come up, will try to open https port 443
Backend for service "authentik" specifies an invalid port TLS configuration did not define a secret name
