### ISSUE TITLE
[docker & traefik] Port 9000 (http) actually needed?

### ISSUE THREAD

**Issue by hexxone** [goauthentik/authentik#2482]
**Describe your question/**
Hi there, I have just set-up authentik using docker-compose and added my traefik config.
Its working like a charm so far; - nice job!

However, I have been wondering if exposing the http-port '9000' is actually needed?
If it's just for redirecting to Https, Traefik can take care of this.
But it doesn't seem like authentik is actually listening on that port?
I'm just getting a blank `404 page not found` there, even though traefik seems to work.

Please correct me if I have missed something in the docs ^^

**Relevant infos**
traefik config on "server":
```
    labels:
      traefik.enable: "true"
      # http -> service
      traefik.http.routers.authentik-unsecure.entrypoints: web
      traefik.http.routers.authentik-unsecure.rule: Host(`auth.${HOST}`)
      traefik.http.routers.authentik-unsecure.middlewares: limit@docker,error-pages@docker
      traefik.http.routers.authentik-unsecure.service: authentik-unsecure
      traefik.http.services.authentik-unsecure.loadbalancer.server.port: 9000
      # Helper
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https 
      # https -> service
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.rule: Host(`auth.${HOST}`)
      traefik.http.routers.authentik.middlewares: sslheader,limit@docker,error-pages@docker
      traefik.http.routers.authentik.tls.certresolver: cfresolver
      traefik.http.routers.authentik.service: authentik
      traefik.http.services.authentik.loadbalancer.server.port: 9443
      traefik.http.services.authentik.loadbalancer.server.scheme: https
      traefik.http.services.authentik.loadbalancer.passhostheader: true
```

**Version and Deployment (please complete the following information):**
 - authentik version: docker/stable
 - Deployment: slightly customized docker-compose

-----------------------
**Unrelated**

I also found a small error in the [passwordless-login](https://goauthentik.io/docs/flow/stages/password/#passwordless-login) example:
` Cannot resolve keyword 'active' into field. Choices are: confirmed, created_on, credential_id, id, last_used_on, name, public_key, rp_id, sign_count, user, user_id `

Seems like "active" is not available for WebAuthn hardware-devices?
I assume When deactivating a device now, it now gets actually deleted?
Anyways, removing `active=True` did the trick. -->
```
from authentik.stages.authenticator_webauthn.models import WebAuthnDevice
return WebAuthnDevice.objects.filter(user=request.user).exists()
```

Cheers.
