### ISSUE TITLE
Local Docker connection, worker can't query Authentik API (403 Forbidden)

### ISSUE THREAD

**Issue by Chifilly** [goauthentik/authentik#3087]
**Describe the bug**
Just want to preface this by saying I'm still not 100% sure how everything works and the flow of the Docker integration, so bare with me if I get an assumption incorrect.

From what I understand, the Docker integration works (in a basic sense) as follows:

1. The `worker` lets the `server` know it has the Docker socket
2. Authentik sets up the outpost in its behind-the-scenes 🌈magic
3. The outpost(/worker?) then queries for all the outposts/proxies/whatevertheyare it needs to create through Docker (?)
4. ... that's as far as I can get

What happens instead is the `authentik Embedded Outpost` Health and Version is on `Not available`, there's a `Warning: authentik Domain is not configured, authentication will not work.` message under it, and when checking the logs for the server, it's spammed every 3 seconds by something (I'm assuming the worker) trying to connect to `/api/v3/outposts/instances/` and getting `403 Forbidden` back (exact logs with `debug` level output below). The Docker integration seems to be fine, as `Local Docker connection` shows its version under `State` and has a green tick. If I go directly to my url at that location I get what (I assume) is expected:

```json
{
  "pagination": {
    "next": 0,
    "previous": 0,
    "count": 1,
    "current": 1,
    "total_pages": 1,
    "start_index": 1,
    "end_index": 1
  },
  "results": [{
    "pk": "f312adc6-9c72-4aee-8613-3d49a5cd5bfc",
    "name": "authentik Embedded Outpost",
    "type": "proxy",
    "providers": [],
    "providers_obj": [],
    "service_connection": "74df6d1a-07f1-461e-9298-fd23d8cf477d",
    "service_connection_obj": {
      "pk": "74df6d1a-07f1-461e-9298-fd23d8cf477d",
      "name": "Local Docker connection",
      "local": true,
      "component": "ak-service-connection-docker-form",
      "verbose_name": "Docker Service-Connection",
      "verbose_name_plural": "Docker Service-Connections",
      "meta_model_name": "authentik_outposts.dockerserviceconnection"
    },
    "token_identifier": "ak-outpost-f312adc6-9c72-4aee-8613-3d49a5cd5bfc-api",
    "config": {
      "log_level": "debug",
      "docker_labels": null,
      "authentik_host": "",
      "docker_network": null,
      "container_image": null,
      "docker_map_ports": true,
      "kubernetes_replicas": 1,
      "kubernetes_namespace": "default",
      "authentik_host_browser": "",
      "object_naming_template": "ak-outpost-%(name)s",
      "authentik_host_insecure": false,
      "kubernetes_service_type": "ClusterIP",
      "kubernetes_image_pull_secrets": [],
      "kubernetes_disabled_components": ["deployment", "secret"],
      "kubernetes_ingress_annotations": {},
      "kubernetes_ingress_secret_name": "authentik-outpost-tls"
    },
    "managed": "goauthentik.io/outposts/embedded"
  }]
}
```

I've been trying to get this working for the last 2 days now and it just won't. I have OAuth2 fully working for Portainer and Grafana, but now I just want to get `forwardauth` with Traefik working. I've done so much Googling and I can't find anyone that has the same or similar issue, and I can't tell at all whether it's a configuration issue or not.

**To Reproduce**
Some basic info: All the containers are on a bridge network by default, so they can talk to each other via the Docker bridge.

My compose file is as follows:

```yaml
x-common:
  image: &common-image ghcr.io/goauthentik/server:latest
  environment:
    &common-environment
    AUTHENTIK_SECRET_KEY: file:///run/secrets/AUTHENTIK_SECRET_KEY

    AUTHENTIK_REDIS__HOST: redis

    AUTHENTIK_POSTGRESQL__HOST: postgres
    AUTHENTIK_POSTGRESQL__USER: file:///run/secrets/POSTGRES_USER
    AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/POSTGRES_PASSWORD
    AUTHENTIK_POSTGRESQL__NAME: file:///run/secrets/POSTGRES_DATABASE

    AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    AUTHENTIK_LOG_LEVEL: debug
  volumes:
    - &common-volumes-media ./volumes/authentik/data/media:/media
    - &common-volumes-templates ./volumes/authentik/custom-templates:/templates
  secrets:
    &common-secrets
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DATABASE
    - AUTHENTIK_SECRET_KEY
  depends_on:
    &common-depends_on
    - postgres
    - redis

services:
  authentik-server:
    container_name: authentik-server
    image: *common-image
    command: server
    depends_on: *common-depends_on
    environment:
      <<: *common-environment
    volumes:
      - *common-volumes-media
      - *common-volumes-templates
    secrets: *common-secrets
    restart: unless-stopped

    labels:
      traefik.enable: true

      traefik.http.routers.authentik.rule: Host(`auth.${DOMAIN}`)
      traefik.http.routers.authentik.entrypoints: https
      traefik.http.routers.authentik.priority: 1
      traefik.http.routers.authentik.service: authentik
      traefik.http.services.authentik.loadbalancer.server.port: 9000

  authentik-worker:
    container_name: authentik-worker
    image: *common-image
    command: worker
    depends_on: *common-depends_on
    environment:
      <<: *common-environment
    user: root
    volumes:
      - *common-volumes-media
      - *common-volumes-templates
      - ./volumes/authentik/data/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: *common-secrets
    restart: unless-stopped
```

I've also tried many other configurations and couldn't get them to work, but even with just a basic _nearly_ vanilla server and worker, it doesn't work.

**Expected behavior**
I expect that the worker or outposts or whatever does the connecting to be able to connect so it can set up the proxies or whatever it needs automagically for the apps assigned to the `authentik Embedded Outpost`.

**Logs**
```
{"auth_via": "api_token", "event": "/api/v3/outposts/instances/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25, "remote": "127.0.0.1", "request_id": "51cb26865b144d08adc91cd107513e8e", "runtime": 10, "scheme": "http", "status": 403, "timestamp": "2022-06-14T03:08:29.567149", "user": "", "user_agent": "goauthentik.io/outpost/2022.6.2"}
{"event": "Forbidden: /api/v3/outposts/instances/", "level": "warning", "logger": "django.request", "timestamp": 1655176109.567589}
{"error":"403 Forbidden","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-14T03:08:29Z"}
```

with a few 
```
{"event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25, "remote": "127.0.0.1", "request_id": "378ef0d6f3d345fa96674d065cdc5011", "runtime": 15, "scheme": "http", "status": 204, "timestamp": "2022-06-14T03:08:26.824605", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
```
scattered in every now-and-then.

**Version and Deployment:**
 - authentik version: `2022.6.2`
 - Deployment: docker-compose (docker version `20.10.17, build 100c701`, compose version `2.6.0`)

**Comment by BeryJu** [comment]
So the embedded outpost has nothing to do with the docker connection, since the embedded outpost runs in-process in the server container. This error is most likely caused by the `managed_reconcile` System task not running. This has been recently changed to be triggered on worker start (in addition to a timer) instead of on worker start. The task should still show up in your System tasks list in the Admin interface, where you can re-trigger it

**Comment by Chifilly** [comment]
I thought the Embedded Outpost updated automatically due to the Local Docker connection since that's its integration, or am I wrong? (I've see that people can have automatic deployment of outposts and things because it's a "managed" outpost).

---

Anyway, I just checked, and it has been run, and shows `Successful` with a green tick, with `Successfully updated managed models.` as the message and last run time as `05:40:00` (the container start time being `04:48:41`). However, there are 2 tasks that have status `Unknown` which are `notification_cleanup` (which I doubt is relevant) and `outpost_token_ensurer` with the message `Task has not been run yet.` but the last run time being `08:22:19` which doesn't make sense to me?

Manually running `managed_reconcile` didn't fix the issue, and neither did `outpost_token_ensurer`, the same logs are still happening with no new logs on the server.

Checking the worker logs, these are all the logs that happen after running `managed_reconcile`

```
{"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "task_id": "03b0a7a8-3e50-47c6-8fc9-d10206cda78b", "task_name": "managed_reconcile", "timestamp": "2022-06-14T08:22:53.736294"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "CryptoManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:53.744511"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "OutpostManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:53.744774"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "task_id": "8b23a27c-c4ca-47b7-a3ca-09c50bd93099", "task_name": "authentik.outposts.tasks.outpost_post_save", "timestamp": "2022-06-14T08:22:53.756090"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "ScopeMappingManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:53.801470"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "ProxyScopeMappingManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:53.889957"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "SAMLProviderManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:53.900957"}
{"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 5552, "request_id": "task-8b23a27cc4ca47b7a3ca09c50bd93099", "task_id": "8b23a27c-c4ca-47b7-a3ca-09c50bd93099", "task_name": "outpost_post_save", "timestamp": "2022-06-14T08:22:53.918144"}
{"event": "Trigger reconcile for outpost", "instance": "<Outpost: Outpost authentik Embedded Outpost>", "level": "debug", "logger": "authentik.outposts.tasks", "pid": 5552, "request_id": "task-8b23a27cc4ca47b7a3ca09c50bd93099", "timestamp": "2022-06-14T08:22:53.924687"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 5552, "request_id": "task-8b23a27cc4ca47b7a3ca09c50bd93099", "task_id": "ad8beebf-6739-4ce5-80c7-21d24c2e03ab", "task_name": "authentik.outposts.tasks.outpost_controller", "timestamp": "2022-06-14T08:22:53.929701"}
{"event": "triggering outpost update from outpostmodel/outpost", "instance": "<Outpost: Outpost authentik Embedded Outpost>", "level": "debug", "logger": "authentik.outposts.tasks", "pid": 5552, "request_id": "task-8b23a27cc4ca47b7a3ca09c50bd93099", "timestamp": "2022-06-14T08:22:53.929994"}
{"event": "Updated service account's permissions", "level": "debug", "logger": "authentik.outposts.models", "obj_perms": "<QuerySet [<UserObjectPermission: Outpost authentik Embedded Outpost | ak-outpost-f312adc69c724aee86133d49a5cd5bfc | view_outpost>]>", "perms": "<QuerySet [<Permission: authentik_events | Event | Can add Event>]>", "pid": 5552, "request_id": "task-8b23a27cc4ca47b7a3ca09c50bd93099", "timestamp": "2022-06-14T08:22:53.990022"}
{"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 5552, "request_id": "task-8b23a27cc4ca47b7a3ca09c50bd93099", "state": "SUCCESS", "task_id": "8b23a27c-c4ca-47b7-a3ca-09c50bd93099", "task_name": "outpost_post_save", "timestamp": "2022-06-14T08:22:53.997073"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "LDAPProviderManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:54.000691"}
{"event": "Reconciling managed objects", "level": "debug", "logger": "authentik.managed.manager", "manager": "CoreManager", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "timestamp": "2022-06-14T08:22:54.166827"}
{"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 5540, "request_id": "task-03b0a7a83e5047c68fc9d10206cda78b", "state": "SUCCESS", "task_id": "03b0a7a8-3e50-47c6-8fc9-d10206cda78b", "task_name": "managed_reconcile", "timestamp": "2022-06-14T08:22:54.179958"}
{"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 5554, "request_id": "task-ad8beebf67394ce580c721d24c2e03ab", "task_id": "ad8beebf-6739-4ce5-80c7-21d24c2e03ab", "task_name": "outpost_controller", "timestamp": "2022-06-14T08:22:54.249742"}
{"event": "Getting outpost from DB", "level": "debug", "logger": "authentik.outposts.tasks", "pid": 5554, "request_id": "task-ad8beebf67394ce580c721d24c2e03ab", "timestamp": "2022-06-14T08:22:54.256104"}
{"event": "---------------Outpost Controller logs starting----------------", "level": "debug", "logger": "authentik.outposts.tasks", "pid": 5554, "request_id": "task-ad8beebf67394ce580c721d24c2e03ab", "timestamp": "2022-06-14T08:22:54.258761"}
{"event": "-----------------Outpost Controller logs end-------------------", "level": "debug", "logger": "authentik.outposts.tasks", "pid": 5554, "request_id": "task-ad8beebf67394ce580c721d24c2e03ab", "timestamp": "2022-06-14T08:22:54.258903"}
{"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 5554, "request_id": "task-ad8beebf67394ce580c721d24c2e03ab", "state": "SUCCESS", "task_id": "ad8beebf-6739-4ce5-80c7-21d24c2e03ab", "task_name": "outpost_controller", "timestamp": "2022-06-14T08:22:54.261080"}
```

and I don't know if it's relevant, but these are the logs after running `outpost_token_ensurer`

```
{"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 5585, "request_id": "task-7c6bf0dfc8734283a6b101eebc3c832e", "task_id": "7c6bf0df-c873-4283-a6b1-01eebc3c832e", "task_name": "outpost_token_ensurer", "timestamp": "2022-06-14T08:25:22.011543"}
{"event": "Updated service account's permissions", "level": "debug", "logger": "authentik.outposts.models", "obj_perms": "<QuerySet [<UserObjectPermission: Outpost authentik Embedded Outpost | ak-outpost-f312adc69c724aee86133d49a5cd5bfc | view_outpost>]>", "perms": "<QuerySet [<Permission: authentik_events | Event | Can add Event>]>", "pid": 5585, "request_id": "task-7c6bf0dfc8734283a6b101eebc3c832e", "timestamp": "2022-06-14T08:25:22.071785"}
{"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 5585, "request_id": "task-7c6bf0dfc8734283a6b101eebc3c832e", "state": "SUCCESS", "task_id": "7c6bf0df-c873-4283-a6b1-01eebc3c832e", "task_name": "outpost_token_ensurer", "timestamp": "2022-06-14T08:25:22.078301"}
```

**Comment by BeryJu** [comment]
The embedded outpost is the same code as the regular outpost code, except its executed from the main process in the main containers, but I get the confusion from the integrations. When the embedded outpost has the docker integration selected, it actually does nothing, because there's nothing to do. The outpost already runs in the container. This is only useful for Kubernetes deployments, where the outpost controller does other things, instead of just running the actual outpost container

---

The `Task has not been run yet` with a time is also confusing, this is caused by the code on startup pre-saving the task info into redis so that it shows up in the list, but it doesn't null out the time, so thats just a cosmetic issue.

---

The logs are from the server, and all outposts connect to the core server. The requests are going to `localhost:8000` since thats where the django app runs, while the go-proxy runs on port 9000 (the go-proxy is a long story, basically it serves static files, proxies to django, but also runs the embedded outpost)

**Comment by Chifilly** [comment]
Yep, you're exactly right! Putting the values directly in the compose file fixed the issue.

However, now I have an issue where I go to my app URL which is forwarded to Authentik as you'd expect for forwardauth, it authenticates me and then sends me back to the app URL like this `https://app.domain.tld/outpost.goauthentik.io/callback?code=[long code]`, but obviously `outpost.goauthentik.io` doesn't exist for the app so I get a 404. Do I need more configuration? The provider is set to `Forward auth (single application)`.

Also, forgive my ignorance again, but is the outpost controller supposed to make new containers for routing the apps? I currently have 1 app assigned to the embedded outpost but no new containers (I really don't know how any of this works). I've seen in multiple places the managed outpost is supposed to create new outposts with the correct Traefik labels on it for routing correctly. You say the embedded outpost would do nothing for my setup, so does that mean I need to make my outposts manually?

These are the labels I have for my app (my Authentik compose is exactly the same as above still)
```yaml
traefik.enable: true
traefik.http.routers.app.rule: HOST(`app.${DOMAIN}`)
traefik.http.routers.app.entrypoints: https
traefik.http.routers.app.middlewares: authentik@docker
```

---

Also, if I create a new outpost manually with the same settings as the embedded one and assign that the provider, it takes me to `https://auth.domain.tld/outpost.goauthentik.io/auth/traefik` and I get the following
```json
{
  "Message": "no app for hostname",
  "Host": "auth.domain.tld",
  "Detail": "Check the outpost settings and make sure 'auth.domain.tld' is included."
}
```

which I see is referenced in issue #2180, however I clearly don't understand how outposts work (especially the embedded one and managed outposts) or I'm misinterpreting because I don't feel like this should all be so manual from what I've heard about the Docker integration, which is one of the reasons I chose to use Authentik over Authelia after trying it (it was way too manual and I like automation).

This is all making me feel really stupid 😆 but I'm stubborn and I've been fighting this for 2 days so I'll see it through

**Comment by BeryJu** [comment]
> However, now I have an issue where I go to my app URL which is forwarded to Authentik as you'd expect for forwardauth, it authenticates me and then sends me back to the app URL like this `https://app.domain.tld/outpost.goauthentik.io/callback?code=[long code]`, but obviously `outpost.goauthentik.io` doesn't exist for the app so I get a 404. Do I need more configuration? The provider is set to `Forward auth (single application)`.

`/outpost.goauthentik.io` needs to be routed to the outpost (in thise case with the embedded outpost, the core authentik server. You can add a Rule something like
```
PathPrefix(`/outpost.goauthentik.io/`)
```
to the core server, see https://goauthentik.io/docs/providers/proxy/forward_auth#traefik

> Also, forgive my ignorance again, but is the outpost controller supposed to make new containers for routing the apps? I currently have 1 app assigned to the embedded outpost but no new containers (I really don't know how any of this works). I've seen in multiple places the managed outpost is supposed to create new outposts with the correct Traefik labels on it for routing correctly. You say the embedded outpost would do nothing for my setup, so does that mean I need to make my outposts manually?

A single outpost handles any amount of applications, so no, you only need a single Outpost instance (and again special case with the embedded outpost, as that doesn't need a separate container, and is included in the server). The managed outposts which *can* optionally be created, are docker containers managed by authentik, and those would indeed also have automatically configured traefik labels.
You can use a managed outpost for your setup, the advantage of that is that it auto-manages the labels, the disadvantage of it is adding one more component and container that is separate, where things can go wrong (i.e. connection between outpost & core, etc)


> These are the labels I have for my app (my Authentik compose is exactly the same as above still)
> 
> ```yaml
> traefik.enable: true
> traefik.http.routers.app.rule: HOST(`app.${DOMAIN}`)
> traefik.http.routers.app.entrypoints: https
> traefik.http.routers.app.middlewares: authentik@docker
> ```

with this it should work

```yaml
traefik.http.routers.app.rule: HOST(`app.${DOMAIN}`) || PathPrefix(`/outpost.goauthentik.io/`)
```

> 
> Also, if I create a new outpost manually with the same settings as the embedded one and assign that the provider, it takes me to `https://auth.domain.tld/outpost.goauthentik.io/auth/traefik` and I get the following
> 
> ```json
> {
>   "Message": "no app for hostname",
>   "Host": "auth.domain.tld",
>   "Detail": "Check the outpost settings and make sure 'auth.domain.tld' is included."
> }
> ```
> 

That's because `authentik.domain/outpost.goauthentik.io` will always point to the embedded outpost, and because the outposts figure out which app you're trying to authenticate via the Host header, and so since your application probably has a different domain, there's no response for `authentik.domain`

**Comment by Chifilly** [comment]
Okay, I'm getting somewhere, but either I don't fully understand or I missed something.

Now what happens is different depending on whether I'm logged in already.

If I'm logged into Authentik I end up at `https://auth.domain.tld/outpost.goauthentik.io/auth/traefik` and get the following JSON
```json
{
  "message": "NotFound"
}
```

If I'm not logged in, I get the same result, however this time I'm at `https://app.domain.tld/outpost.goauthentik.io/start` instead

My Authentik server labels (I have a separate subdomain for the dashboard now so I don't end up confusing myself)
```yaml
traefik.enable: true

traefik.http.routers.authentik-dashboard.rule: Host(`authentik.${DOMAIN}`)
traefik.http.routers.authentik-dashboard.entrypoints: https
traefik.http.routers.authentik-dashboard.service: authentik-dashboard
traefik.http.services.authentik-dashboard.loadbalancer.server.port: 9000

traefik.http.routers.authentik.rule: Host(`auth.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
traefik.http.routers.authentik.entrypoints: https
traefik.http.routers.authentik.priority: 1
traefik.http.routers.authentik.service: authentik
traefik.http.services.authentik.loadbalancer.server.port: 9000

traefik.http.middlewares.authentik.forwardauth.address: http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
```

My app labels
```yaml
traefik.enable: true

traefik.http.routers.sonarr.rule: HOST(`app.${DOMAIN}`) || PathPrefix(`/outpost.goauthentik.io/`)
traefik.http.routers.sonarr.entrypoints: https
traefik.http.routers.sonarr.middlewares: authentik@docker
```

The Embedded Outpost config
```yaml
log_level: debug
docker_labels: null
authentik_host: https://auth.domain.tld
docker_network: null
container_image: null
docker_map_ports: false
authentik_host_browser: ""
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: false
```

And the Embedded Outpost is set to my app provider, that the provider is set to Forward auth (single application) still with `https://app.domain.tld` as the External host

**Comment by amatheo** [comment]
Same issue and same setup as yours.
Keep getting back a `
{
  "message": "NotFound"
}
` response with same URL behavior as yours if logged in or not.

**Comment by Chifilly** [comment]
I just noticed that if I use ```Host(`auth.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)``` on the server, then I get the `NotFound` JSON as said before, but OAuth also breaks with a `404`. If I change it to ```Host(`auth.${DOMAIN}`) || PathPrefix(`/outpost.goauthentik.io/`)``` then I get a `Bad Gateway` on the forwardauth route, but OAuth works again.

**Comment by Chifilly** [comment]
OKAY! I eventually figured it out! Took me a while, but I got there (worked on this on-and-off for a while). This is how I set it up in full;

- An `Application` created in Authentik with the settings for my application
- A `Proxy Provider` in `Providers` set to `Forward auth (single application)` with the app URL in `External host`
- Setting the labels on my Authentik Server instance to the following:
```yaml
traefik.enable: true

# * Dashboard/OAuth route
traefik.http.routers.authentik-api.rule: Host(`authentik.${DOMAIN}`) || Host(`auth.${DOMAIN}`) # I have 2 separate sub-domains here just so I can split authentication and dashboard URLs, but it's not necessary. It was just to avoid my own confusion
traefik.http.routers.authentik-api.entrypoints: https
traefik.http.routers.authentik-api.priority: 1
traefik.http.routers.authentik-api.service: authentik-api
traefik.http.services.authentik-api.loadbalancer.server.port: 9000

# * Forward Auth route
traefik.http.routers.authentik-forward-auth.rule: HostRegexp(`${DOMAIN}`, `{subdomain:[a-z]+}.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
traefik.http.routers.authentik-forward-auth.entrypoints: https
traefik.http.routers.authentik-forward-auth.service: authentik-forward-auth
traefik.http.services.authentik-forward-auth.loadbalancer.server.port: 9000

# * Middleware
# replace authentik-server with whatever the service name for your Authentik server is
traefik.http.middlewares.authentik-forward-auth.forwardauth.address: http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
traefik.http.middlewares.authentik-forward-auth.forwardauth.trustForwardHeader: true
traefik.http.middlewares.authentik-forward-auth.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
```
- And labels on my application to the following:
```yaml
traefik.enable: true

traefik.http.routers.app.rule: HOST(`app.${DOMAIN}`)
traefik.http.routers.app.entrypoints: https
traefik.http.routers.app.middlewares: authentik-forward-auth@docker
```

This will allow me to have any number of applications use forward auth, because I used ``traefik.http.routers.authentik-forward-auth.rule: HostRegexp(`${DOMAIN}`, `{subdomain:[a-z]+}.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)``, but still allow me to use `Forward auth (single application)` for per-application authentication, without having to make loads of Traefik rules for each application, because this will route the base domain and all subdomains that have a path prefix of `/outpost.goauthentik.io/` to Authentik. It will technically work without the ``HostRegexp(`${DOMAIN}`, `{subdomain:[a-z]+}.${DOMAIN}`)`` part, but I just wanted to be safe and be explicit about the TLD.

I don't know if this is the optimal way or if there's an easier way, but I find this pretty simple, and the only way I could get it to work with a _lot_ of trial and error. Every example I could find on forward auth with Traefik didn't work, so I'm glad I could piece together a load of documentation and slowly understand how stuff works to come up with this solution.

Now I just need #2719 to be fixed and I have Authentik fully set up for my use-case.
