### ISSUE TITLE
Can anyone write a full tutorial about how to deploy authentik with traefik as a proxy provider in docker

### ISSUE THREAD

**Issue by basicallynewbie** [goauthentik/authentik#3092]
**Describe your question/**
 I'm a newbie trying to use authentik as a SSO provider.I can't find enough tutorials about authentik in internet.So I have to ask for help here.I have successfully deployed authentik server and worker but not the outpost.And I'm confused by outpost,why it uses the same ports used in the server,does it mean that they only need one to exist,but I do need the token from server,or they are actually sharing the same ports,but docker reported errors.And where the label io.goauthentik.outpost-uuid coming from.And the most confusing label traefik.http.services.ak-outpost-<outpost-name>-service.loadbalancer.healthcheck.port: "9300",all I can find is the description in the Outpost-Overview-Metrics,without it properlly setuped the outpost cortainer keeps reporting unhealth.And I followed Proxy Provider-Forward auth-Traefik build the docker-compose,a new cortainer named ak-outpost-traefik cortainer shows up,I'm very confused.
 I'll just post my docker-compose.yml and traefik.yml,so you can find where I'm wrong.And I'm using portainer,the port 9000 has been used,so authentik will take the port 9080.
docker-compose.yml
```
version: '3.4'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/me/docker/portainer/data/:/data
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    volumes:
      - /home/me/docker/duckdns/config:/config
    environment:
    DUCKDNS_TOKEN: mytoken
    SUBDOMAINS: subdomain1,subdomain2,subdomain3,subdomain4,subdomain5
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
    DUCKDNS_TOKEN: mytoken
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /home/me/docker/traefik:/etc/traefik:ro
      - /home/me/docker/traefik/config.yml:/config.yml:ro
      - /home/me/docker/traefik/certs:/etc/traefik/certs
      - /home/me/docker/traefik/logs:/etc/traefik/logs
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.entrypoints=web'
      - 'traefik.http.routers.traefik.rule=Host(`subdomain1.duckdns.org`)'
      - 'traefik.http.routers.traefik-secure.entrypoints=websecure'
      - 'traefik.http.routers.traefik-secure.rule=Host(`subdomain1.duckdns.org`)'
      - 'traefik.http.routers.traefik-secure.service=api@internal'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.raefik-secure.tls.certresolver=production'
      - 'traefik.http.routers.traefik.middlewares=https-redirect'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
  postgresql:
    container_name: postgres
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /home/me/docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${my database password}
      - POSTGRES_USER=${PG_USER:-authentik}
      - POSTGRES_DB=${PG_DB:-authentik}
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.6.2}
    container_name: authentik-server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
    volumes:
      - /home/me/docker/media:/media
      - /home/me/docker/templates:/templates
    env_file:
      - /home/me/docker/.env:/.env
    ports:
      - "9080:9000"
      - "9443:9443"
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.6.2}
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: ip
      AUTHENTIK_POSTGRESQL__HOST: ip
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    user: root
    volumes:
      - /home/me/docker/media:/media
      - /home/me/docker/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/me/docker/templates:/templates
    env_file:
      - /home/me/docker/.env:/.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authentik.entrypoints=web'
      - 'traefik.http.routers.authentik.rule=Host(`subdomain2.duckdns.org`)'
      - 'traefik.http.routers.authentik-secure.entrypoints=websecure'
      - 'traefik.http.routers.authentik-secure.rule=Host(`subdomain2.duckdns.org`)'
      - 'traefik.http.routers.authentik-secure.tls=true'
      - 'traefik.http.routers.authentik-secure.tls.certresolver=production'
      - 'traefik.http.routers.authentik.middlewares=https-redirect'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
  authentik-proxy:
        image: ghcr.io/goauthentik/proxy
        ports:
            - 9081:9000
            - 9444:9443
        environment:
            AUTHENTIK_HOST: https://subdomain2.duckdns.org
            AUTHENTIK_INSECURE: "false"
            AUTHENTIK_TOKEN: token-generated-by-authentik
        labels:
            traefik.enable: true
            traefik.port: 9081
            traefik.http.routers.authentik.rule: Host(`subdomain2.duckdns.org`) && PathPrefix(`/outpost.goauthentik.io/`)
            traefik.http.middlewares.authentik.forwardauth.address: http://ip:9080/outpost.goauthentik.io/auth/traefik
            traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
            traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
        restart: unless-stopped
  ak-outpost-traefik:
        image: ghcr.io/goauthentik/proxy:2022.6.2
        ports:
            - 9082:9000
            - 9445:9443
        environment:
            AUTHENTIK_HOST: https://subdomain2.duckdns.org
            AUTHENTIK_INSECURE: "false"
            AUTHENTIK_TOKEN: token-generated-by-authentik
        labels:
            traefik.enable: true
            traefik.http.services.ak-outpost-traefik-service.loadbalancer.server.port: 9082
            traefik.http.services.ak-outpost-traefik-service.loadbalancer.healthcheck.port: 9300
            traefik.http.routers.authentik.rule: Host(`subdomain2.duckdns.org`) && PathPrefix(`/outpost.goauthentik.io/`)
            traefik.http.routers.ak-outpost-traefik-router.service: ak-outpost-traefik-service
            traefik.http.routers.ak-outpost-traefik-router.tls: true
            traefik.http.services.ak-outpost-traefik-service.loadbalancer.healthcheck.path: /outpost.goauthentik.io/ping
        restart: unless-stopped
   heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    ports:
      - 180:80
    volumes:
      - /home/me/docker/heimdall/config:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.heimdall.entrypoints=web'
      - 'traefik.http.routers.heimdall.rule=Host(`subdomain3.duckdns.org`)'
      - 'traefik.http.routers.heimdall-secure.entrypoints=websecure'
      - 'traefik.http.routers.heimdall-secure.rule=Host(`subdomain3.duckdns.org`)'
      - 'traefik.http.routers.heimdall-secure.tls=true'
      - 'traefik.http.routers.heimdall-secure.tls.certresolver=production'
      - 'traefik.http.routers.heimdall.middlewares=https-redirect'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.services.heimdall.loadbalancer.server.port=180'
```

traefik.yml
```
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: DEBUG
  filePath: /etc/traefik/logs/traefik.log
accessLog:
  filePath: /etc/traefik/logs/traefik-access.log
api:
  dashboard: true
  debug: true
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
certificatesResolvers:
   staging:
     acme:
       email: myemail
       storage: /etc/traefik/certs/acme.json
       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
       dnsChallenge:
          provider: duckdns
   production:
     acme:
       email: myemail
       storage: /etc/traefik/certs/acme.json
       caServer: "https://acme-v02.api.letsencrypt.org/directory"
       dnsChallenge:
          provider: duckdns
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /config.yml
    directory: /etc/traefik
    watch: true
```

**Version and Deployment (please complete the following information):**
 - authentik version: [2022.6.2]
 - Deployment: [docker-compose]

**Additional context**
That's what the outpost reported:
Connecting to localhost:9300 (127.0.0.1:9300) wget: can't connect to remote host (127.0.0.1): Connection refused
