### ISSUE TITLE
How to access proxied application through Postman

### ISSUE THREAD

**Issue by stratosgear** [goauthentik/authentik#3229]
**Describe your question/**
I am trying to protect an API server (Fastapi).

I have (I think) successfully setup an Application and a Proxy Provider.

With this setup, if I try to access the docs page of the API server at: `my.domain/backend_v1/docs`, if I am not logged in (or I have my cookies cleared) I get challenged by Authentik, and once I provide my user name and password then I am redirected to the API docs page.

The issue is that I do not know what is the process to hit the API server from Postman (or from another service), if I want to hit directly the API endpoints. 

What kind of credentials do I have to use?  I have created a service account but it is not clear to me how it can be used.

**Relevant infos**
Latest version of all libraries used.  Running on Arch linux.  No other issues with my setup

docker-compose services (only relevant services):

```
...
...
    cots-traefik:
        image: traefik:v2.8
        command: --api.insecure=true --providers.docker
        ports:
            - published: 80
              target: 80
            - published: 8080
              target: 8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            traefik.enable: "true"
            traefik.http.routers.cots-traefik.rule: Host(`my.domain`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            traefik.http.routers.cots-traefik.service: api@internal
            traefik.http.services.cots-traefik.loadbalancer.server.port: "80"

    ak-server:
        image: ghcr.io/goauthentik/server:2022.7.1
        restart: unless-stopped
        command: server
        environment:
            AUTHENTIK_REDIS__HOST: cots-redis
            AUTHENTIK_POSTGRESQL__HOST: cots-db
            AUTHENTIK_POSTGRESQL__USER: postgres
            AUTHENTIK_POSTGRESQL__NAME: myapp
            AUTHENTIK_POSTGRESQL__PASSWORD: postgres
            AUTHENTIK_SECRET_KEY: dwfweyq6fRsb2vJfweffw8vvuNJgdasdau2Ek36gArreGMcz
            AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
            # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
            # WORKERS: 2
        volumes:
            - ./dockerdata/authentik/media:/media
            - ./dockerdata/authentik/custom-templates:/templates
        ports:
        - "0.0.0.0:${AUTHENTIK_PORT_HTTP:-9000}:9000"
        - "0.0.0.0:${AUTHENTIK_PORT_HTTPS:-9443}:9443"
        labels:
            traefik.enable: "true"
            traefik.http.routers.authentik.rule: (Host(`sso.my.domain`) && PathPrefix(`/outpost.goauthentik.io/`) || Host(`sso.my.domain`))
            traefik.http.services.ak-server.loadbalancer.server.port: "9000"
            traefik.http.middlewares.authentik.forwardauth.address: http://ak-server:9000/outpost.goauthentik.io/auth/traefik
            traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
            traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
            traefik.http.routers.authentik.priority: 1
    ak-worker:
        image: ghcr.io/goauthentik/server:2022.7.1
        restart: unless-stopped
        command: worker
        environment:
            AUTHENTIK_REDIS__HOST: cots-redis
            AUTHENTIK_POSTGRESQL__HOST: cots-db
            AUTHENTIK_POSTGRESQL__USER: postgres
            AUTHENTIK_POSTGRESQL__NAME: myapp
            AUTHENTIK_POSTGRESQL__PASSWORD: postgres
            AUTHENTIK_SECRET_KEY: dwfweyq6fRsb2vJfweffw8vvuNJgdasdau2Ek36gArreGMcz
            AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
        # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
        # This is optional, and can be removed. If you remove this, the following will happen
        # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
        # - The docker socket can't be accessed anymore
        # user: root
        volumes:
            - ./dockerdata/authentik/media:/media
            - ./dockerdata/authentik/certs:/certs
            - /var/run/docker.sock:/var/run/docker.sock
            - ./dockerdata/authentik/custom-templates:/templates
...
...
```

**Screenshots**

Application Settings:

![application](https://user-images.githubusercontent.com/193463/177654279-cdd3a2f9-c01e-488c-9d70-0d0e185c6452.png)

Provider Settings:

![provider](https://user-images.githubusercontent.com/193463/177654317-f2cd9ccb-ac7d-44b4-a29a-e5faef855d42.png)

Outpost settings:

![outpost](https://user-images.githubusercontent.com/193463/177654368-39e5833a-c13e-4efc-bec3-ce3085bea050.png)

From postman the available Authentication options are the following:

![postman_auth_options](https://user-images.githubusercontent.com/193463/177654644-dcb522e4-4e6c-4753-a2c7-04df85713242.png)

**Logs**
Not sure what logs I should provide here.

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2022.7.1]
 - Deployment: docker-compose

**Additional context**
