### ISSUE TITLE
404 error when using traefik

### ISSUE THREAD

**Issue by LP0101** [goauthentik/authentik#3305]
**Describe your question/**
I'm trying to use single application forward auth along with Traefuk to protect some docker containers. However, upon going to `app,domain.tld`, I get redirected to `/outpost.goauthentik.io/start`, and the page shows a 404 error

**Relevant infos**
Traefik configuation:

file provider:
```
http:
  middlewares:
    authentik:
      forwardAuth:
        address: https://auth.domain.tld/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```

Labels on my app:
`traefik.enable: true`
`traefik.http.routers.prowlarr.entryPoints: https`
`traefik.http.routers.prowlarr.middlewares: authentik@file`

**Screenshots**
![image](https://user-images.githubusercontent.com/16864921/180620072-5a2c1d6f-f10b-4894-86b3-1f174ba7b734.png)

**Logs**
Docker logs for Authentik:
```
{"event":"/outpost.goauthentik.io/auth/traefik","host":"prowlarr.popesco.io","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Prowlarr","remote":"192.168.100.39","runtime":"0.337","scheme":"https","size":0,"status":0,"timestamp":"2022-07-23T15:27:43-04:00","upstream":"","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2021.8.5]
 - Deployment: Docker/Unraid

**Additional context**
The same configured app/provider works with an nginx reverse proxy, trying to see what I'm doing wrong when it comes to traefik
