### ISSUE TITLE
Unable to send email using default-recovery-flow

### ISSUE THREAD

**Issue by joshuaavalon** [goauthentik/authentik#3438]
**Describe the bug**
I upgrade from 2022.7.3 to 2022.8.1. Then, I imported `default-recovery-flow` from example.

I try to send recovery email but I got an blank page instead (see screenshot).

**To Reproduce**
1. Enter username
2. Click forget password

**Expected behavior**
Send recovery email

**Screenshots**
![image](https://user-images.githubusercontent.com/7152420/185174273-7af1c67b-34a0-4f6e-b12b-0d483f2590cd.png)

**Logs**
```json
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/default-authentication-flow/?query=next%3D%252F", "host": "", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 18, "remote": "162.158.179.254", "request_id": "0ea5032f8af7459d991e82590c85bde8", "runtime": 42, "scheme": "https", "status": 302, "timestamp": "2022-08-17T15:08:23.128190", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/default-authentication-flow/?query=next%3D%252F", "host": "", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 18, "remote": "162.158.179.254", "request_id": "3ec7539e8d2c4e0fbda8ade9e699086c", "runtime": 46, "scheme": "https", "status": 200, "timestamp": "2022-08-17T15:08:23.426521", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/if/flow/default-recovery-flow/", "host": "", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "162.158.179.254", "request_id": "e17b1c33652e4bb58c1074d3a51ffdf9", "runtime": 35, "scheme": "https", "status": 200, "timestamp": "2022-08-17T15:08:28.369792", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "f(exec): Found existing plan for other flow, deleting plan", "flow_slug": "default-recovery-flow", "host": "", "level": "warning", "logger": "authentik.flows.views.executor", "other_flow": "63f90d9dd06642b08542554b447ba27b", "pid": 17, "request_id": "0a728cd1bc86486d8a5620c29ee9e722", "timestamp": "2022-08-17T15:08:28.753796"}
{"auth_via": "unauthenticated", "event": "/api/v3/core/tenants/current/", "host": "", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 18, "remote": "162.158.179.254", "request_id": "0b57c2245f6b472c8e04078960566bf2", "runtime": 48, "scheme": "https", "status": 200, "timestamp": "2022-08-17T15:08:28.768857", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/api/v3/root/config/", "host": "", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 18, "remote": "162.158.179.254", "request_id": "13aaedfe7c1a44a68db795df1190db2b", "runtime": 45, "scheme": "https", "status": 200, "timestamp": "2022-08-17T15:08:28.774270", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/default-recovery-flow/?query=", "host": "", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "162.158.179.254", "request_id": "0a728cd1bc86486d8a5620c29ee9e722", "runtime": 146, "scheme": "https", "status": 200, "timestamp": "2022-08-17T15:08:28.864668", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "HEAD", "pid": 18, "remote": "127.0.0.1", "request_id": "e5834fd3f7ef4d258c1d20abed0a099a", "runtime": 22, "scheme": "http", "status": 204, "timestamp": "2022-08-17T15:08:36.424462", "user": "", "user_agent": "goauthentik.io lifecycle Healthcheck"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.1
 - Deployment:
```yaml
version: "3"

services:
  server:
    image: ghcr.io/goauthentik/server:2022.8.1
    container_name: authentik_server
    restart: always
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
  worker:
    image: ghcr.io/goauthentik/server:2022.8.1
    container_name: authentik_worker
    restart: always
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
    user: root
    volumes:
      - ./media:/media
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: authentik_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
```

```
AUTHENTIK_ERROR_REPORTING__ENABLED=false
AUTHENTIK_DISABLE_STARTUP_ANALYTICS=true
AUTHENTIK_SECRET_KEY=xxx

AUTHENTIK_EMAIL__HOST=smtp.sendgrid.net
AUTHENTIK_EMAIL__PORT=25
AUTHENTIK_EMAIL__USERNAME=apikey
AUTHENTIK_EMAIL__PASSWORD=xxx
AUTHENTIK_EMAIL__USE_TLS=true
AUTHENTIK_EMAIL__USE_SSL=false
AUTHENTIK_EMAIL__TIMEOUT=10
AUTHENTIK_EMAIL__FROM=xxx

AUTHENTIK_POSTGRESQL__HOST=xxx
AUTHENTIK_POSTGRESQL__USER=xxx
AUTHENTIK_POSTGRESQL__NAME=xxx
AUTHENTIK_POSTGRESQL__PASSWORD=xxx

```

**Additional context**

I have notice `/static/dist/flow/PromptStage-0640e10a.js` is missing (404) from Chrome Developer console. May be this is the problem?
