### ISSUE TITLE
Adding certificates through certs directory

### ISSUE THREAD

**Issue by ToshY** [goauthentik/authentik#3489]
**Describe your question/**
It's unclear for me on what directory structure is acceptable in order for authentik to show new certificates in the UI. According to the [docs](https://goauthentik.io/docs/core/certificates#external-certificates), binding host directory containing certificates to the `/certs` directory inside container should be enough.

Docker compose (partial):
```yaml
services:
  authentik-server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_SERVER_IMAGE_VERSION}
    <<: *restart-stopped
    command: server
    <<: *authentik-environment
    volumes:
      - media:/media
      - geoip:/geoip
      - ~/certs/dump:/certs
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.priority: 50
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.service: authentik
      traefik.http.routers.authentik.rule: Host(`authentik.${APP_DOMAIN}`, `www.authentik.${APP_DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9-]+}.${APP_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.services.authentik.loadbalancer.server.port: 9000
    networks:
      - authentik
      - proxy

  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_SERVER_IMAGE_VERSION}
    <<: *restart-stopped
    user: root
    command: worker
    <<: *authentik-environment
    volumes:
      - media:/media
      - geoip:/geoip
      - ~/certs/dump:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - authentik
```

The `~/certs/dump` has the following structure:

```
~/certs/dump/
|___ private/
|___ example.com/
     |___ fullchain.pem
     |___ privkey.pem
```

So binding `~/certs/dump:/certs` correctly gives me both `fullchain.pem` and `privkey.pem` inside of `/certs/example.com/` .

> Files are checked every 5 minutes, and will trigger an Outpost refresh if the files differ.

After waiting over 20 minutes, I still don't see anything when I click the refresh button under "System" > "Certificates". 

My question is: am I doing something wrong or is this a bug?

**Relevant infos**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/31921460/187094839-3d33bf4d-6c4d-4c84-a784-c64bc91c5996.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: docker compose v2.10.0

**Additional context**
N/A
