### ISSUE TITLE
authentik-proxy from external server location using traefik

### ISSUE THREAD

**Issue by BoW2EviL** [goauthentik/authentik#3498]
**Describe your question/**
can the traefik fwd auth examples in the testing-setups be used for remote server locations or internal locations only? 

**Relevant infos**
I have followed the docker based install using authentik as the main proxy (no nginx caddy traefik etc) and everything is now working as i was hoping it would for all the containers on server A.... server B runs traefik and i was hoping to secure it using the example  outpost-proxy from the testing-setup. ie ghcr.io/goauthentik/proxy. but i cant seem to get it to locate the external authentik host from server A. 
am i going about this the right way? or should i be using something like thomseddon/traefik-forward-auth instead? or should server B have a clone or sync of authentik server from server A? 
```
  authentik-proxy:
      image: ghcr.io/goauthentik/proxy
      container_name: authentik-proxy
      environment:
          AUTHENTIK_LOG_LEVEL: trace
          AUTHENTIK_HOST: https://auth0.$DOMAINNAME1 <<points at server A
          AUTHENTIK_INSECURE: "false"
          AUTHENTIK_TOKEN: secret
          AUTHENTIK_HOST_BROWSER: https://auth0.$DOMAINNAME1 <<points at server A
      labels:
        - "traefik.http.routers.rtr.rule=Host(`sso1.$DOMAINNAME1`) || PathPrefix(`/outpost.goauthentik.io/`)" << 
        - "traefik.http.routers.rtr.middlewares=chain-authentik@file"
        - "traefik.http.routers.rtr.service=svc"
        - "traefik.http.services.svc.loadbalancer.server.port=9000"
        - "traefik.port=9000"
```

**Logs**
"error":"403 Forbidden","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller"

**Version and Deployment:**
 - authentik version: 2022.8.2
 - Deployment: docker-compose

**BTW** i love this app thanks for all the hard work. so far this seems to blow all other competition away.
