### ISSUE TITLE
Authentik should work without an env file

### ISSUE THREAD

**Issue by toxic0berliner** [goauthentik/authentik#3547]
I'm trying to setup authentik but I would like my single entrypoint to be traefik. 
As such, I would need the authentik web ui to be available through traefik, but somehow all I get is 404 errors.

Traefik is setup to monitor the docker provider where I launch traefik and enabled is on by default, here is my compose file : 
<details>
    <summary>compose</summary>

```
version: "3"
services:
  traefik:
    container_name: traefik
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    hostname: traefik
    image: traefik:2.6
    labels:
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 8080:8080/tcp
    restart: always
    volumes:
      - traefik-config:/etc/traefik
      - traefik-log:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE_VOLUMES}/${STACKNAME}/traefik/acme.json:/acme.json
    networks:
      traefiknet:
        aliases: 
          - traefik
  authentik-postgresql:
    container_name: authentik-postgresql
    hostname: authentik-postgresql
    image: postgres:12-alpine
    restart: unless-stopped
    labels:
      traefik.enable: false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      traefiknet:
        aliases: 
          - authentik-postgresql
    volumes:
      - authentik-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS:?database password required}
      - POSTGRES_USER=${PG_USER:-authentik}
      - POSTGRES_DB=${PG_DB:-authentik}
  authentik-redis:
    container_name: authentik-redis
    hostname: authentik-redis
    image: redis:alpine
    restart: unless-stopped
    labels:
      traefik.enable: false
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      traefiknet:
        aliases: 
          - authentik-redis
  authentik:
    container_name: authentik
    hostname: authentik
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.8.2}
    restart: unless-stopped
    labels:
      traefik.http.routers.authentik.rule: HostRegexp(`auth.example.com`)
      traefik.http.services.authentik.loadbalancer.server.port: 9000
      subdomain: authentik
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ERROR_REPORTING__ENABLED}
      # WORKERS: 2
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      AUTHENTIK_AUTHENTIK__GEOIP: ${AUTHENTIK_AUTHENTIK__GEOIP}
      AUTHENTIK_PORT_HTTP: ${AUTHENTIK_PORT_HTTP}
      AUTHENTIK_PORT_HTTPS: ${AUTHENTIK_PORT_HTTPS}
      DOMAIN: ${DOMAIN}
    volumes:
      - authentik-media:/media
      - authentik-custom-templates:/templates
      - authentik-geoip:/geoip
    ports:
    #  - "0.0.0.0:${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "0.0.0.0:${AUTHENTIK_PORT_HTTPS:-9443}:9443"
    networks:
      traefiknet:
        aliases: 
          - authentik
  authentik-worker:
    container_name: authentik-worker
    hostname: authentik-worker
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.8.2}
    restart: unless-stopped
    labels:
      traefik.enable: false
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    user: root
    volumes:
      - authentik-media:/media
      - authentik-certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-custom-templates:/templates
      - authentik-geoip:/geoip
    networks:
      traefiknet:
        aliases: 
          - authentik-worker
  authentik-geoipupdate:
    container_name: authentik-geoipupdate
    hostname: authentik-geoipupdate
    image: "maxmindinc/geoipupdate:latest"
    labels:
      traefik.enable: false
    volumes:
      - "authentik-geoip:/usr/share/GeoIP"
    environment:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      GEOIPUPDATE_FREQUENCY: "8"
    networks:
      traefiknet:
        aliases: 
          - authentik-geoipupdate
volumes:
  traefik-config:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/traefik/etc-traefik
  traefik-log:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/traefik/log
  authentik-media:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/authentik/media
  authentik-custom-templates:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/authentik/custom-templates
  authentik-db:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/authentik/db
  authentik-geoip:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/authentik/geoip
  authentik-certs:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/authentik/certs
 networks:
  traefiknet:
    name: traefiknet
    driver: bridge
    external: true
```
</details>

When I browse to https://auth.example.com/if/flow/initial-setup/ I get this: 
![image](https://user-images.githubusercontent.com/10488124/188739439-0feb238b-a483-48bf-9302-b0f3acae4b10.png)

I once got it working but it was by bypassing the traefik proxy by calling the host IP directly on port 9000, can't remember what I had in the DOMAIN env var at the time, but even now I'm only getting 404 using https://myip:9443/if/flow/initial-setup/

All I see now in the logs is this: 
```
############## when using auth.example.com ################
{"auth_via": "unauthenticated", "event": "/if/flow/initial-setup/", "host": "auth.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 33, "remote": "10.10.10.30", "request_id": "bd8cce93ca31480fa292347073187f39", "runtime": 19, "scheme": "https", "status": 404, "timestamp": "2022-09-06T21:20:26.006735", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"event": "Not Found: /if/flow/initial-setup/", "level": "warning", "logger": "django.request", "timestamp": 1662499226.0074883}
############## when using IP ###############
{"auth_via": "unauthenticated", "event": "/if/flow/initial-setup/", "host": "10.10.10.10:9443", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 32, "remote": "10.10.10.30", "request_id": "62428d81e6e14f4597cdbb18956d82a9", "runtime": 30, "scheme": "https", "status": 404, "timestamp": "2022-09-06T21:17:59.644027", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"event": "Not Found: /if/flow/initial-setup/", "level": "warning", "logger": "django.request", "timestamp": 1662499079.6559505}
```

Any idea ? I'm guessing authentik is not trusting traefik as proxy in front of itself but I see it nowhere in the logs nor do I find any hint on how to tell authentik to trust traefik as it is a reverse-proxy in front of it and handeling TLS and certs instead of authentik...

**Comment by toxic0berliner** [comment]
Ok, I found my problem is actually that I do not pass the .env file. So even if all env variables are passed through in the compose definition of the service itself, something inside the container relies on the env file actually being present and containing at least some vars even if I did not investigate which.

In fact, I am using portainer to depoy the stack and I have other services that require other env vars, so right now authentik seems working but it's started with more env vars than what it actually needs because I had to pass "stack.env" in portainer which is actually an env file for the whole portainer stack...

I am renaming the issue, I believe authentik should be able to work without an env file as long as all vars are properly passed.

If someone can look into it, maybe a quick first step is to build the env file on container startup if none is present and fill it with the current env variables, maybe even spit out an error if some mandatory var is missing...

**Comment by ToshY** [comment]
@toxic0berliner While the `docker-compose.yml` from the Authentik documentation has a `env_file` entry, it's definitely not necessary. My best guess would be that you are missing environment variables being passed to either server/worker.

I can give you an example of my own (partial) compose file, working with Traefik.

```yaml
version: '3.9'

x-restart: &restart-stopped
  restart: unless-stopped

x-authentik-environment: &authentik-environment
  environment:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
    AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN}
    AUTHENTIK_COOKIE_DOMAIN: ${AUTHENTIK_COOKIE_DOMAIN}
    AUTHENTIK_REDIS__HOST: ${REDIS_HOST}
    AUTHENTIK_REDIS__PASSWORD: ${REDIS_PASSWORD}
    AUTHENTIK_POSTGRESQL__HOST: ${POSTGRES_HOST}
    AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DATABASE}
    AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
    AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
    AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ERROR_REPORTING__ENABLED}
    AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
    AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
    AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
    AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
    AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
    AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    AUTHENTIK_INSECURE: ${AUTHENTIK_INSECURE}
    GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
    GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
    GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS}
    GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY}

services:
  authentik-server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_SERVER_IMAGE_VERSION}
    <<: *restart-stopped
    command: server
    <<: *authentik-environment
    volumes:
      - media:/media
      - geoip:/geoip
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.priority: 50
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.service: authentik
      traefik.http.routers.authentik.rule: Host(`authentik.${APP_DOMAIN}`, `www.authentik.${APP_DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9-]+}.${APP_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.services.authentik.loadbalancer.server.port: 9000
    networks:
      - authentik
      - proxy # traefik (external) network

  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_SERVER_IMAGE_VERSION}
    <<: *restart-stopped
    user: root
    command: worker
    <<: *authentik-environment
    volumes:
      - media:/media
      - geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - authentik
```

> Note: this will setup Authentik with specified default password defined by `${AUTHENTIK_BOOTSTRAP_PASSWORD}` so you can skip the initial flow setup and login with `akadmin` username.
