### ISSUE TITLE
How to edit email templates and create new custom templates?

### ISSUE THREAD

**Issue by jayknyn** [goauthentik/authentik#3814]
**Describe your question**
I'd like to edit the default `Account Confirmation` email template as right now the html is all left justified and the confirmation link isn't contained to a fixed width resulting in an extra wide email :) How can I edit this default template and also create a new custom template? I realize that once I have a custom template I can mount it into the container but I'm not sure of the format of this template (syntax and flle type).

**Relevant infos**
<details>
  <summary>Authentik docker-compose.yml</summary>
  
  ```yml
version: '3.7'

networks:
  ingress:
    external: true

  authentik:
    internal: true

services:
  authentik:
    container_name: ${SERVICE_NAME}-app
    image: ${AUTHENTIK_IMAGE}:${AUTHENTIK_TAG}
    depends_on: [db, cache, authentik-worker]
    command: server
    env_file: [.env]
    environment:
      AUTHENTIK_POSTGRESQL__USER: ${DB_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${DB_NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${DB_PASSWORD}
      # WORKERS: 2
    networks: [authentik, ingress]
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=le
      - traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}
      - traefik.http.routers.${SERVICE_NAME}.middlewares=sslheader
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_PORT}
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.scheme=http
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.passhostheader=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https

    volumes:
      - ./media:/media # mkdir, then sudo chown 1000:1000 media templates backups certs
      - ./templates:/templates
      # - ./geoip:/geoip

  authentik-worker:
    container_name: ${SERVICE_NAME}-worker
    image: ${AUTHENTIK_IMAGE}:${AUTHENTIK_TAG}
    depends_on: [db, cache]
    command: worker
    env_file: [.env]
    environment:
      AUTHENTIK_POSTGRESQL__USER: ${DB_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${DB_NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${DB_PASSWORD}
    networks: [authentik]
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    # user:root is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /backups and /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    user: root
    volumes:
      - ./backups:/backups
      - ./media:/media
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates:/templates
      # - ./geoip:/geoip

  # geoipupdate:
  #   container_name: ${SERVICE_NAME}-geoip
  #   image: 'maxmindinc/geoipupdate:latest'
  #   volumes:
  #     - './geoip:/usr/share/GeoIP'
  #   environment:
  #     GEOIPUPDATE_EDITION_IDS: 'GeoLite2-City'
  #     GEOIPUPDATE_FREQUENCY: '8'
  #   env_file:
  #     - .env

  db:
    container_name: ${SERVICE_NAME}-db
    image: postgres:${DB_VERSION}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks: [authentik]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    restart: unless-stopped
    volumes: [./db:/var/lib/postgresql/data]

  cache:
    container_name: ${SERVICE_NAME}-cache
    image: redis:${CACHE_VERSION}
    networks: [authentik]
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    restart: unless-stopped
    volumes: [./cache:/data]
  ```
</details>

<details>
  <summary>.env</summary>
  
  ```
INTERNAL_NETWORK=authentik
EXTERNAL_NETWORK=ingress
SERVICE_NAME=authentik
SERVICE_PORT=9000
DOMAIN=authtest.domain.tld
DB_VERSION=14.5-alpine
DB_NAME=authentik
DB_USER=authentik
DB_PASSWORD=SECRET
CACHE_VERSION=7.0.4-alpine

AUTHENTIK_IMAGE=beryju/authentik
AUTHENTIK_TAG=2022.8
AUTHENTIK_REDIS__HOST=cache
AUTHENTIK_POSTGRESQL__HOST=db
# generate with `openssl rand -hex 50`, don't change after first install
AUTHENTIK_SECRET_KEY=SECRET
# debug, info (default), warning, error, trace
AUTHENTIK_LOG_LEVEL=debug
AUTHENTIK_DISABLE_UPDATE_CHECK=true
AUTHENTIK_ERROR_REPORTING__ENABLED=false
# none, gravatar, <url>
AUTHENTIK_AVATARS=none
AUTHENTIK_EMAIL__HOST=smtp.sendgrid.net
AUTHENTIK_EMAIL__PORT=25
# (don't add quotation marks to you password)
AUTHENTIK_EMAIL__USERNAME=apikey
AUTHENTIK_EMAIL__PASSWORD=SECRET
AUTHENTIK_EMAIL__USE_TLS=true
AUTHENTIK_EMAIL__USE_SSL=false
AUTHENTIK_EMAIL__TIMEOUT=30
AUTHENTIK_EMAIL__FROM=auth@domain.tld
  ```
</details>

**Screenshots**

![Screen Shot 2022-10-18 at 8 51 27 PM](https://user-images.githubusercontent.com/45739598/196572148-a9806586-e1db-492d-ac07-1980767ffc30.png)

**Logs**
N/A

**Version and Deployment:**
 - authentik version: 2022.8.2
 - Deployment: docker-compose
