### ISSUE TITLE
User write stage: "Group" property not showing correct value in UI

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#3998]
**Describe the bug**
Consider the following blueprint:
```
version: 1
metadata:
  name: Default - enrollment user write stage
context:
  create_users_as_inactive: false
  user_path_template: ""
  group_name: new-users
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Group ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_core.group
  id: default-enrollment-user-write-group
  identifiers:
    name: !Context group_name
  attrs:
    is_superuser: false
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_stages_user_write.userwritestage
  id: default-enrollment-user-write-stage
  identifiers:
    name: default-enrollment-user-write-stage
  attrs:
    create_users_group: !KeyOf default-enrollment-user-write-group
    create_users_as_inactive: !Context create_users_as_inactive
    user_path_template: !Context user_path_template

````
**EDIT**:
Upon further investigation I _think_ this may be just a UI bug? 

What happened is:
1. I used the above blueprint to create the enrollment user write stage and user group
2.  Verified they have been created and that the "Group" property has not been set in the UI.
3. Created a new user with an enrollment flow (wihch uses the user write stage created by the blueprint)
4. Verified the newly created user has been assigned to the group created by the blueprint.

That combined with the fact that the "Group" property gets set sometimes (see Additional context), I think this may be a UI bug. However, I am not 100% sure so I will be keeping the title as is.

**EDIT 2**:
Ok. I think this is officially an UI bug. See video:

https://user-images.githubusercontent.com/36302090/201553767-c713e706-cef9-4de4-81ec-f190a777a031.mp4

**To Reproduce**
1. Add the blueprint to authentik and apply it
6. Confirm the group "new-users" has been created
7. Confirm the stage "default-enrollment-user-write-stage" has been created
8. Click on the stage "edit" button
9. Confirm the "Group" property has **not** been populated by the blueprint

**Expected behavior**
Blueprint should create both the stage and and the group and should pre-fill the "Group" property of the write stage with the newly created group.

**Screenshots**
![image](https://user-images.githubusercontent.com/36302090/201545500-495fa1e4-76b1-4e48-8145-7b86eea0d3fb.png)

**Logs**
N/A - no errors/exceptions shown

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.1 and gh-main (build hash: [ee6dc45](https://github.com/goauthentik/authentik/commit/ee6dc45a307fb0302754e331978dfd66aac01f62))
 - Deployment: docker-compose

**Additional context**
I think this may be a race condition of some sort as I managed to make it set the group once by repeatedly deleting the stage and group and re-applying the blueprint.
