### ISSUE TITLE
event=Secret key missing after update docker-compose

### ISSUE THREAD

**Issue by Vladimir-Va** [goauthentik/authentik#4171]
**Describe your question/**
Update from 2022.10.2 to 2022.11.3
Container server and worker go to cycle reboot
`INF event=Secret key missing, check https://goauthentik.io/docs/installation/.`
find https://github.com/goauthentik/authentik/issues/3386
Add to compose
```
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    environment:
      - AUTHENTIK_REDIS__TLS=true
```
and to .env
`AUTHENTIK_REDIS__TLS=true`

Nothing changed. I ask for help, I've been trying to figure it out for 3 days, without changes.

**Logs**
`INF event=Secret key missing, check https://goauthentik.io/docs/installation/.`

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: docker-compose
