### ISSUE TITLE
Authentik not showing intial user signup

### ISSUE THREAD

**Issue by amitavaghosh1** [goauthentik/authentik#4183]
**Describe the bug**

When I tried to access, `localhost:9000` or `http://localhost:9000/if/flow/initial-setup/` It redirects to `http://localhost:9000/flows/-/default/authentication/?next=/` And shows a webpage saying. `Not Found`

**To Reproduce**
1. docker prune exsisting volumes and images. `docker container prune; docker image prune; docker volume prune`
2. set the authentik secret, db username password in .env
3. do docker-compose up 
4. access the http://localhost:9000/if/flow/initial-setup/

**Expected behavior**
Show the default signup page

**Screenshots**

**Logs**
```
server_1      | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "HEAD", "pid": 23, "remote": "127.0.0.1", "request_id": "0b05a58a3f5a49d3a2bcfe3954dfe6c5", "runtime": 14, "scheme": "http", "status": 204, "timestamp": "2022-12-08T08:02:33.468877", "user": "", "user_agent": "goauthentik.io lifecycle Healthcheck"}
server_1      | {"auth_via": "unauthenticated", "event": "/if/flow/initial-setup/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "172.26.0.1", "request_id": "afd7146497974f449b397caa9345dc76", "runtime": 29, "scheme": "http", "status": 404, "timestamp": "2022-12-08T08:02:39.818211", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"}
server_1      | {"event": "Not Found: /if/flow/initial-setup/", "level": "warning", "logger": "django.request", "timestamp": 1670486559.8202548}
server_1      | {"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "127.0.0.1", "request_id": "0c48202ee11d4c269aa179b84b40aa6a", "runtime": 17, "scheme": "http", "status": 204, "timestamp": "2022-12-08T08:02:43.120408", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: [2022.11.1]
 - Deployment: [docker-compose]

**Additional context**

Also there is no documentation on what is `Configuration Stages`. The documentation is so bad, its so difficult to understand as a begineer.

ANyway, here is the. docker compose I am using

```yaml
---
version: '3.4'

services:
  postgresql:
    image: postgres:13-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS:-authentik}
      - POSTGRES_USER=${PG_USER:-authentik_dev_user}
      - POSTGRES_DB=${PG_DB:-authentik_dev}
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    ports:
      - "6379:6379"
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.11.1}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik_dev_user}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik_dev}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:-authentik}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "0.0.0.0:${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "0.0.0.0:${AUTHENTIK_PORT_HTTPS:-9443}:9443"
  # worker:
    # image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.11.1}
    # restart: unless-stopped
    # command: worker
    # environment:
      # AUTHENTIK_REDIS__HOST: redis
      # AUTHENTIK_POSTGRESQL__HOST: postgresql
      # AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik_dev_user}
      # AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik_dev}
      # AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:-authentik}
    # user: root
    # volumes:
      # - ./media:/media
      # - ./certs:/certs
      # - /var/run/docker.sock:/var/run/docker.sock
      # - ./custom-templates:/templates
    # env_file:
      # - .env
  # geoipupdate:
    # image: "maxmindinc/geoipupdate:latest"
    # volumes:
      # - "geoip:/usr/share/GeoIP"
    # environment:
      # GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      # GEOIPUPDATE_FREQUENCY: "8"
    # env_file:
      # - .env

volumes:
  database:
    driver: local
  # geoip:
    # driver: local

```
