### ISSUE TITLE
ForwardAuth using Traefik in a kubernetes cluster

### ISSUE THREAD

**Issue by rebebop** [goauthentik/authentik#4261]
**Describe your question/**
Hi,
I'm using `authentik` with `traefik` v2 in a k3s cluster. I have followed all the steps from the documentation and I'm trying to access a service using ForwardAuth.
- I have created a middleware for Traefik and applied it to the ingress route of the service.
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.domain.tld`)
      kind: Rule
      services:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80
      middlewares:
        - name: middleware-authentik
          namespace: traefik
      priority: 10
    - kind: Rule
      match: "Host(`longhorn.domain.tld`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: "ak-outpost-authentik-embedded-outpost"
          port: 9000
  tls:
    secretName: domain-tld-tls
```
- I have created an applicaton in authentik, with a proxy provider and I am using the default outpost.

Now when I am trying to access the application it shows me the following error:
```
{
	"Message": "no app for hostname",
	"Host": "authentik.domain.tld",
	"Detail": "Check the outpost settings and make sure 'authentik.domain.tld' is included."
}
```
I only have a single cluster and authentik is running at `authentik.domain.tld`. 

**Logs**
```
{"event":"no app for hostname","host":"authentik.domain.tld","level":"warning","logger":"authentik.outpost.proxyv2","timestamp":"2022-12-22T12:50:30Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: helm

**Comment by BeryJu** [comment]
The middleware should point to an in-cluster service and not the public authentik FQDN

**Comment by rebebop** [comment]
I have set it to the following now:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middleware-authentik
  namespace: traefik
spec:
  forwardAuth:
    address: http://ak-outpost-authentik-embedded-outpost:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
      - X-authentik-jwt
      - X-authentik-meta-jwks
      - X-authentik-meta-outpost
      - X-authentik-meta-provider
      - X-authentik-meta-app
      - X-authentik-meta-version
  ```
  But now I'm getting a `500`
