### ISSUE TITLE
Cannot reach to the admin signup page in authentik

### ISSUE THREAD

**Issue by amitavaghosh1** [goauthentik/authentik#4288]
**Describe your question/**
I ran a `docker-compose down`, cleaned up all volumes using `docker volume prune`. And booted up the server, with `docker-compose up`

And as I try to access  `localhost:9000` it redirects me to `"/flows/-/default/authentication/?next=/` and says Not found. I cleared the caches in browser as well.

**Relevant infos**
```
---
version: '3.4'

services:
  postgresql:
    image: postgres:13-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS:-authentik}
      - POSTGRES_USER=${PG_USER:-authentik_dev_user}
      - POSTGRES_DB=${PG_DB:-authentik_dev}
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    ports:
      - "6379:6379"
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.11.1}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik_dev_user}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik_dev}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:-authentik}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "0.0.0.0:${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "0.0.0.0:${AUTHENTIK_PORT_HTTPS:-9443}:9443"
  # worker:
    # image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.11.1}
    # restart: unless-stopped
    # command: worker
    # environment:
      # AUTHENTIK_REDIS__HOST: redis
      # AUTHENTIK_POSTGRESQL__HOST: postgresql
      # AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik_dev_user}
      # AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik_dev}
      # AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:-authentik}
    # user: root
    # volumes:
      # - ./media:/media
      # - ./certs:/certs
      # - /var/run/docker.sock:/var/run/docker.sock
      # - ./custom-templates:/templates
    # env_file:
      # - .env
  # geoipupdate:
    # image: "maxmindinc/geoipupdate:latest"
    # volumes:
      # - "geoip:/usr/share/GeoIP"
    # environment:
      # GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      # GEOIPUPDATE_FREQUENCY: "8"
    # env_file:
      # - .env

volumes:
  database:
    driver: local
  # geoip:
    # driver: local
```

**Screenshots**
![image](https://user-images.githubusercontent.com/71380768/209525377-70f589ce-1e38-4d0c-b434-9cf081ef06b9.png)

**Logs**
authentik-server-1      | {"auth_via": "unauthenticated", "event": "/flows/-/default/authentication/?next=/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "remote": "172.19.0.1", "request_id": "93fe1cf907b24a23b845bd27658263ae", "runtime": 20, "scheme": "http", "status": 404, "timestamp": "2022-12-26T08:27:14.130454", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}

**Version and Deployment:**
 - authentik version: [e.g. 2022.11.1]
 - Deployment: docker-compose,

**Additional context**

**Comment by BeryJu** [comment]
Just like you asked in https://github.com/goauthentik/authentik/issues/4183, the worker container needs to be running as it creates all the default objects in the database

**Comment by amitavaghosh1** [comment]
I ran the

**Comment by secnigma** [comment]
For future googlers who stumbles upon here, here's what worked for me. 

For me, the fix was to [follow the step mentioned in this comment](https://github.com/goauthentik/authentik/issues/8489#issuecomment-1951464350).

Added 

```yml
AUTHENTIK_REDIS__DB: 1
```

environment variable to both Authentik server and authentik worker service and restarted authentik via composer.

Example docker compose file:

```yml
---

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.4.2}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__DB: 1
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.4.2}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__DB: 1
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

volumes:
  database:
    driver: local
  redis:
    driver: local
    ```
