### ISSUE TITLE
Output proxy crash when start

### ISSUE THREAD

**Issue by vnStrawHat** [goauthentik/authentik#4642]
**Describe the bug**
Output proxy crash panic: runtime error: index out of range [0] with length 0 when start

**To Reproduce**
1. Start Authentik Host with compose file: https://goauthentik.io/docker-compose.yml
2. Create new Services Account
3. Create new Token (Intent - API Token)
4. Start Output Proxy via docker compose
```yaml
version: "3.5"

services:
    authentik_proxy:
        image: ghcr.io/goauthentik/proxy:2023.1.2
        # Optionally specify which networks the container should be
        # might be needed to reach the core authentik server
        networks:
           - authentik_stack
        #ports:
        #     - 9090:9000
        #     - 9443:9443
        environment:
            AUTHENTIK_HOST: http://authentik-server:9000
            AUTHENTIK_INSECURE: "true"
            AUTHENTIK_TOKEN: Up0AgJ4u5qJEsZHEsJVFO4WdpiuFNOq05dtYoraj6etgLs3Ot2WDA8DIQpNz
            AUTHENTIK_DEBUG: "true"
            AUTHENTIK_HOST_BROWSER: "https://sso-proxy.kfc.lab"

networks:
  authentik_stack:
    external: true
    name: authentik_stack
```

**Expected behavior**
Output Proxy success Integration with Authentik Host

**Screenshots**
Crash
![image](https://user-images.githubusercontent.com/4435695/217497197-a6c18d8c-443e-4719-ae40-06c79f37199c.png)

**Logs**
```
[+] Running 1/0
 ⠿ Container outpost-authentik_proxy-1  Created                                                                                  0.0s
Attaching to outpost-authentik_proxy-1
outpost-authentik_proxy-1  | {"event":"Loaded config from environment","level":"debug","timestamp":"2023-02-08T09:46:44Z"}
outpost-authentik_proxy-1  | timestamp="2023-02-08T09:46:44Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
outpost-authentik_proxy-1  | panic: runtime error: index out of range [0] with length 0
outpost-authentik_proxy-1  | 
outpost-authentik_proxy-1  | goroutine 1 [running]:
outpost-authentik_proxy-1  | goauthentik.io/internal/outpost/ak.NewAPIController({{0xc00003a03f, 0x4}, {0x0, 0x0}, 0x0, {0xc00003a046, 0x15}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
outpost-authentik_proxy-1  |    /go/src/goauthentik.io/internal/outpost/ak/api.go:76 +0xe27
outpost-authentik_proxy-1  | main.main()
outpost-authentik_proxy-1  |    /go/src/goauthentik.io/cmd/proxy/main.go:66 +0x470
outpost-authentik_proxy-1 exited with code 2

```

**Version and Deployment (please complete the following information):**
- Authentik Host docker compose with version 2023.1.2:
```yaml
---
version: '3.4'

services:
  postgresql:
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS:?database password required}
      - POSTGRES_USER=${PG_USER:-authentik}
      - POSTGRES_DB=${PG_DB:-authentik}
    env_file:
      - .env
    networks:
      - stack
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - stack

  authentik-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.1.2}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      HTTP_nginx: "http://192.168.219.7:9090"
      HTTPS_nginx: "http://192.168.219.7:9090"
      NO_nginx: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,*.ssi.com.vn"
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "127.0.0.1:${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "127.0.0.1:${AUTHENTIK_PORT_HTTPS:-9443}:9443"
    networks:
      - nginx
      - stack

  authentik-worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.1.2}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - ./media:/media
      - ./certs:/certs
      #- /var/run/docker.sock:/var/run/docker.sock
      - ./custom-templates:/templates
    env_file:
      - .env
    networks:
      - stack

volumes:
  database:
    driver: local

networks:
  nginx:
    external: true
    name: nginx
  stack:
    driver: bridge
```
**Additional context**
try to curl http://authentik-server:9000/api/v3/outposts/instances/ to and got response:
```json
{"pagination":{"next":0,"previous":0,"count":0,"current":1,"total_pages":1,"start_index":0,"end_index":0},"results":[]}
```
```curl
curl -vvv --header "Authorization: Bearer Up0AgJ4u5qJEsZHEsJVFO4WdpiuFNOq05dtYoraj6etgLs3Ot2WDA8DIQpNz" "http://authentik-server:9000/api/v3/outposts/instances/"
*   Trying 172.20.0.2:9000...
* Connected to authentik-server (172.20.0.2) port 9000 (#0)
> GET /api/v3/outposts/instances/ HTTP/1.1
> Host: authentik-server:9000
> User-Agent: curl/7.87.0
> Accept: */*
> Authorization: Bearer Up0AgJ4u5qJEsZHEsJVFO4WdpiuFNOq05dtYoraj6etgLs3Ot2WDA8DIQpNz
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Allow: GET, POST, HEAD, OPTIONS
< Content-Length: 119
< Content-Type: application/json
< Date: Wed, 08 Feb 2023 09:37:28 GMT
< Referrer-Policy: same-origin
< Vary: Accept-Encoding
< Vary: Cookie
< X-Authentik-Id: 64977bf1f3a341fc8115ca3506669694
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Powered-By: authentik
< 
* Connection #0 to host authentik-server left intact
{"pagination":{"next":0,"previous":0,"count":0,"current":1,"total_pages":1,"start_index":0,"end_index":0},"results":[]}
```
