### ISSUE TITLE
Helm: Adding volume and volumeMount for media folder

### ISSUE THREAD

**Issue by mkshb** [goauthentik/authentik#5042]
**Describe the bug**
A volume added in values.yaml is included in the deployment as EmptyDir.

**To Reproduce**

1. Add volume and volumemount to values.yaml
```
volumes:
  - name: media
    persistentVolumeClaim:
    claimName: authentik-media
    namespace: authentik

volumeMounts:
  - mountPath: /media
    name: media
```
2. Upgrade helm chart

`helm upgrade --install authentik authentik/authentik -f values.yaml -n authentik`

**Expected behavior**
A volume + mount of the PVC authentik-media under /media in the server pod.

**Screenshots**
Result inside deployment:
```
    spec:
      volumes:
        - name: media
          emptyDir: {}
      containers:
        - name: authentik
          image: ghcr.io/goauthentik/server:2023.3.1
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: helm

**Comment by BeryJu** [comment]
The values snippet you posted looks slightly incorrect, it should be (note the indent, and I don't think the `namespace` attribute is supported there

```yaml
volumes:
  - name: media
    persistentVolumeClaim:
      claimName: authentik-media
```
