### ISSUE TITLE
"Failed to proxy to backend"

### ISSUE THREAD

**Issue by Jdavid77** [goauthentik/authentik#5059]
**Describe the bug**
Since upgrading to the latest version , i've been getting this error:

`{"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2023-03-23T17:38:43Z"}`

And it makes authentik restart continuously and the pod gets shutdown everytime.

**To Reproduce**
1. Uprade authentik to the latest version.

My Current helm configuration is as follows:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: idp
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2023.3.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.3.1
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    ingress:
      enabled: true
      annotations:
      hosts:
        - host: authentik.${SECRET_DOMAIN}
          paths:
            - path: /
      tls:
        - hosts:
            - authentik.${SECRET_DOMAIN}
    worker:
      replicas: 2
    # Password in clear text because this is a random test instance
    authentik:
      secret_key: ${AUTHENTIK_SECRET}
      log_level: debug
      error_reporting:
        enabled: false
      avatars: none
      postgresql:
        # Should be present on the secret created by the postgres operator
        host: ${POSTGRES_HOST}
        name: ${POSTGRES_DB}
        user: ${POSTGRES_USER}
      email:
        # -- SMTP Server emails are sent from, fully optional
        host: "${SMTP_MAIL_SERVER}"
        port: 587
        # -- SMTP credentials, when left empty, not authentication will be done
        username: "${SMTP_MAIL_USERNAME}"
        # -- SMTP credentials, when left empty, not authentication will be done
        password: "${SMTP_MAIL_PASSWORD}"
        # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
        use_tls: true
        # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
        use_ssl: false
        # -- Connection timeout
        timeout: 30
        # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
        from: ${SMTP_FROM}

    postgresql:
      enabled: false

    redis:
      enabled: true
      persistence:
        enabled: false
      auth:
        enabled: false
    prometheus:
      serviceMonitor:
        create: false
      rules:
        create: false
    livenessProbe:
      # -- enables or disables the livenessProbe
      enabled: true
      httpGet:
        # -- liveness probe url path
        path: /-/health/live/
        port: http
      initialDelaySeconds: 60
      periodSeconds: 15
    readinessProbe:
      enabled: true
      httpGet:
        path: /-/health/ready/
        port: http
      initialDelaySeconds: 60
      periodSeconds: 15
  valuesFrom:
    - kind: Secret
      name: postgres-outputs
      targetPath: authentik.postgresql.password
      valuesKey: authentik_password
```

P.S - Usings SOPS for variable substitution

**Expected behavior**

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: helm chart version 2023.3.1

**Additional context**
Zero clue how to procede with this error it never happened before, all our previous updates have been smooth
