### ISSUE TITLE
Unable to use User Enrollment Portals or Password Self Resets

### ISSUE THREAD

**Issue by war3zlod3r** [goauthentik/authentik#5199]
**Describe the bug**
Unable to create new users via enrollment link or enrollment page or self reset passwords, the page just hangs up after submitting and doesn't go further but shows the spinning wheel. 

**To Reproduce**
1. Go to sign up or click enrollment invite and attempt to fill out the form.
2. Also occurs when you click the password reset link and attempt to submit new password.
3. In both the screen shows the spinning wheel animation but it just goes forever.

**Expected behavior**
To be able to enroll or self reset passwords.

**Screenshots**
https://media.discordapp.net/attachments/1093584727946051664/1093585046209843263/image.png

https://cdn.discordapp.com/attachments/1093584727946051664/1093584728076079185/image.png

**Version and Deployment (please complete the following information):**
 - authentik version: [2023.3.1]
 - Deployment: [docker-compose]

**Additional context**
I've also noticed the fields on the enrollment page appear to be duplicated somehow see second screenshot.

**Comment by war3zlod3r** [comment]
Seems almost like the front end doesn't have write permission on the database? Not sure what could cause this...

**Comment by strazto** [comment]
Having the same issue, also see @war3zlod3r 's discussion of same issue on discord:
 https://discord.com/channels/809154715984199690/1093584727946051664/1093584727946051664 
 
 @war3zlod3r did you have any luck with this? Did downgrading authentik to `2023.2.x` work?

**Comment by strazto** [comment]
I've been able to isolate the fault a little more

Imagine we have a flow with a prompt stage that does "everything" ie

```yaml
first-prompt-stage:
   type: prompt
   fields:
     - Username
     - Name
     - Email
     - Password
     - Repeat Password
user-write-stage:
   type: user-write
```

Our client would hang on submitting the prompt and going to the next stage. 

Initially I wondered if this was due to an issue with the next stage (User write), so I added a stage before that to confirm, but the behaviour persisted. 


```yaml

first-prompt-stage:
   type: prompt
   fields:
     - Username
     - Name
     - Email
     - Password
     - Repeat Password
# still hangs on first-prompt-stage

dummy-consent-stage:
   type: consent
user-write-stage:
   type: user-write
```

Because I was only observing this behaviour on usename + pword enrolment, as well as password reset, (but not on SSO enrolment which doesn't have a password prompt stage), I hypothesized it's due to the password prompt fields, so I separated them out into their own stage
 
```yaml
first-prompt-stage:
   type: prompt
   fields:
     - Username
     - Name
     - Email
     
 # No longer hangs on first-prompt-stage, now hangs after second prompt-stage
second-prompt-stage:
   type: prompt
   fields:
     - Password
     - Repeat Password
user-write-stage:
   type: user-write
```

This caused the hang to occur only on the stage with the passwords.

Having done that, I then took note of #6019 , which attributes a similar bug to LDAP Source writeback. 

By following the steps of #6019 , and disabling LDAP source writeback, I no longer experience hangs on password prompts.
