### ISSUE TITLE
How to set an externalIP address for an Outpost when using LoadBalencer in Kubernetes

### ISSUE THREAD

**Issue by eloebl** [goauthentik/authentik#5205]
**Describe your question/**
I am using kubernetes_service_type as LoadBalencer for the LDAP Outpost, and would like to set the external IP for the loadbalancer. I don't see a way to do that in the outpost configuration

**Relevant infos**
Kubernetes v1.26.3+k3s1

**Screenshots**
![image](https://user-images.githubusercontent.com/309719/230669585-cfc28deb-e0cb-4ea4-a0a2-5542e312fa15.png)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: helm

**Comment by cathelijne** [comment]
The best (and official) answer is of course that you can deploy the outpost manually by following [the docs](https://version-2023-3.goauthentik.io/docs/outposts/manual-deploy-kubernetes).

However, I am lazy, and I prefer Authentik doing most of the work ;) So I ended up creating the outpost with the default settings, and manually created a _second_ service with a different name with type loadbalancer.
The service uses the tailscale IP that I also use for my ingress. I used a [metallb annotation](https://metallb.universe.tf/usage/#ip-address-sharing) to enable sharing of the loadbalancer IP. I don't know if the standard k3s LB supports multiple loadbalancer IP's out of the box, if at all, so make sure you check beforehand!

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "tailscale"
  labels:
    app.kubernetes.io/instance: ldap
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: authentik-ldap-loadbalancer
    app.kubernetes.io/version: 2023.3.1
    goauthentik.io/outpost-name: ldap
    goauthentik.io/outpost-type: ldap
  name: authentik-ldap-loadbalancer
  namespace: authentik
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 3389
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: 6636
  selector:
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-outpost-ldap
    goauthentik.io/outpost-name: ldap
    goauthentik.io/outpost-type: ldap
  type: LoadBalancer
  loadBalancerIP: 100.101.102.103
  ```

**Comment by BeryJu** [comment]
there currently isn't a way to set externalIP on a service via authentik, however you can manually set the attribute on the service that is created by authentik and authentik won't remove it

**Comment by eloebl** [comment]
> there currently isn't a way to set externalIP on a service via authentik, however you can manually set the attribute on the service that is created by authentik and authentik won't remove it

I did try at the service, but it was getting rest on me which was frustrating :)

**Comment by eloebl** [comment]
@cathelijne Thank you for the reply, this is brilliant!

**Comment by CygnusHyoga** [comment]
Hi! I've encounter the same problem trying to deploy Radius. As feature request, it is possible to add extra variables, for example like "kubernetes_service_annotations" and "kubernetes_service_loadBalancerIP" on outpost config?

Thanks!

**Comment by BeryJu** [comment]
This is possible using the `kubernetes_json_patches` option: https://docs.goauthentik.io/docs/outposts/#configuration

An example of that would be 
```yaml
# deployment:
#   - op: add
#     path: "/spec/template/spec/containers/0/resources"
#     value:
#       requests:
#         cpu: 2000m
#         memory: 2000Mi
#       limits:
#         cpu: 4000m
#         memory: 8000Mi
```

**Comment by evanreichard** [comment]
Outposts -> Edit -> Advanced Settings

```yaml
# excerpt
kubernetes_json_patches:
  service:
    - op: add
      path: /spec/loadBalancerIP
      value: 10.0.50.10
```
