### ISSUE TITLE
Blueprints list stuck loading when custom blueprint added via Web UI

### ISSUE THREAD

**Issue by cskwrd** [goauthentik/authentik#5295]
See #5036 and #5112

**Additional context**
#5041 Doesn't resolve the issue.

Current version: 2023.4.1

~~For what it's worth, the name doesn't seem to be taken from the blueprint either.
I am using the helm chart, the name of my blueprint as display in the list is `mounted/<config map name>/<config map key>`.~~

**Comment by cskwrd** [comment]
I opened #5296 to stop the bleeding. The underlying issue of missing metadata still needs a resolution.

**Comment by cskwrd** [comment]
I have poked around at this a bit more and noticed that in my case the blueprint had a syntax issue. After fixing that it appears as though the blueprint is imported correctly from the config map (the strange name has been fixed as well).

However, manually creating a blueprint of type `Internal` (I didn't test the others) still suffers from the problem.

Example blueprint:
```yaml
version: 1
metadata:
  labels:
    blueprints.goauthentik.io/description: Test Blueprint Description via label metadata
  name: Test Blueprint Name via metadata
entries:
  - model: authentik_core.user
    identifiers:
      pk: 1
    attrs:
      username: nimdaka
      name: John
    state: present
```
