### ISSUE TITLE
Authentik Server Container stops responding to http requests

### ISSUE THREAD

**Issue by Divinii** [goauthentik/authentik#5320]
**Describe the bug**
Authentik Server stops responding to http requests frequently and then recovers without the pod restarting. Manually restarting the Pod also resoves the issue temporarily.

**To Reproduce**
1. Open Authentik Dashboard or any other site repeatetly
2. Authentik sometimes stops responding to http requests with Traefik showing 404 not found

**Expected behavior**
Web UI responds normally without being down

**Screenshots**
Kubernetes Events:
![image](https://user-images.githubusercontent.com/37466196/233114343-3cb41465-35d0-4a5e-9b97-68a26d96585c.png)

**Logs**
Authentik-Server Pod (There was one Unhealthy warning by kube healthchecks about 30s before i pulled these logs with loglevel debug)
```
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "acd61fe8e5144e04a31dcede18752fe6", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:19:50.518732", "user": "", "user_agent": "kube-probe/1.24"}
--
Thu, Apr 20 2023 12:19:50 pm | {"auth_via": "unauthenticated", "event": "/application/o/authorize/?client_id=dABOs9QGk4sg0nK7HGLxy5dtf5iRMFIRMi4uMGsk&redirect_uri=https%3A%2F%2Foctoprint.divini.at%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=email+ak_proxy+openid+profile&state=xrBB7-lIGMIWL6aNWvnrjPF56H4zmSInUXSJtEVXRaI", "host": "authentik.mackner.net", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.255.255.250", "request_id": "effb60e65f1b4885a301a67b28cf888a", "runtime": 21, "scheme": "https", "status": 302, "timestamp": "2023-04-20T10:19:50.574658", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"}
Thu, Apr 20 2023 12:19:54 pm | {"event":"/sockjs/545/wp23wyzl/xhr_streaming?t=1681983306783","host":"octoprint.divini.at","level":"info","logger":"authentik.outpost.proxyv2.application","method":"POST","name":"Proxy Octoprint","remote":"10.255.255.250","runtime":"2686870.867","scheme":"http","size":134065,"status":200,"timestamp":"2023-04-20T10:19:54Z","user":"Divini","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"}
Thu, Apr 20 2023 12:20:00 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "10.200.10.84", "request_id": "e5eb76068b0446ecb4a1e2c6d27f0816", "runtime": 14, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:00.519701", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:20:02 pm | {"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "127.0.0.1", "request_id": "d443eb9dde6747d8a421f74c0862a884", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:02.385928", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
Thu, Apr 20 2023 12:20:11 pm | {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2023-04-20T10:20:11Z"}
Thu, Apr 20 2023 12:20:11 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "10.200.10.84", "request_id": "5e0b9cf74c6248a4af88b5194f95a520", "runtime": 1034, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:11.540274", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:20:20 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "10.200.10.84", "request_id": "c43a3398ff8e492288d75fa7a795c14e", "runtime": 16, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:20.522992", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:20:30 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "900ad89323b54de0b62bf0c3d422143b", "runtime": 15, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:30.520923", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:20:32 pm | {"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "127.0.0.1", "request_id": "709f7e00b0394daab3d9068b2e4f94cf", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:32.385646", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
Thu, Apr 20 2023 12:20:41 pm | {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2023-04-20T10:20:41Z"}
Thu, Apr 20 2023 12:20:41 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "6ae9ab41214045798888f24cedda03e2", "runtime": 1019, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:41.525105", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:20:50 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "ac80a7e0862b407d8386e240fe8e186f", "runtime": 14, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:20:50.519836", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:21:00 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "10.200.10.84", "request_id": "231598e53f2243ea86bfcba38592be0b", "runtime": 15, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:00.520904", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:21:02 pm | {"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "127.0.0.1", "request_id": "588fea6074eb4287a709ae221954d28e", "runtime": 12, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:02.384500", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
Thu, Apr 20 2023 12:21:03 pm | {"event":"Running periodical tasks","level":"debug","logger":"authentik.outpost.ak-api-controller","timer":"cache-timeout","timestamp":"2023-04-20T10:21:03Z"}
Thu, Apr 20 2023 12:21:03 pm | {"event":"Running interval update","level":"debug","logger":"authentik.outpost.ak-api-controller","loop":"interval-updater","timestamp":"2023-04-20T10:21:03Z"}
Thu, Apr 20 2023 12:21:03 pm | {"auth_via": "unauthenticated", "event": "Task published", "host": "localhost:8000", "level": "info", "logger": "authentik.root.celery", "pid": 19691, "request_id": "2518475b936c469ca62dcc8c2e50fa2f", "task_id": "65037297-7a69-4879-b58b-ed237fbe9b36", "task_name": "authentik.providers.scim.tasks.scim_signal_direct", "timestamp": "2023-04-20T10:21:03.219186"}
Thu, Apr 20 2023 12:21:03 pm | {"auth_via": "secret_key", "event": "/api/v3/outposts/instances/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "127.0.0.1", "request_id": "2518475b936c469ca62dcc8c2e50fa2f", "runtime": 142, "scheme": "http", "status": 200, "timestamp": "2023-04-20T10:21:03.316907", "user": "ak-outpost-a314886ac4544378ad108dceb358bb94", "user_agent": "goauthentik.io/outpost/2023.4.1"}
Thu, Apr 20 2023 12:21:03 pm | {"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"authentik Embedded Outpost","timestamp":"2023-04-20T10:21:03Z"}
Thu, Apr 20 2023 12:21:03 pm | {"event":"Managed outpost, not setting global log level","level":"debug","logger":"authentik.outpost","timestamp":"2023-04-20T10:21:03Z"}
Thu, Apr 20 2023 12:21:03 pm | {"auth_via": "unauthenticated", "event": "Task published", "host": "localhost:8000", "level": "info", "logger": "authentik.root.celery", "pid": 19691, "request_id": "0c10438275b44aada3ad2558d37bc2fd", "task_id": "ee1d8959-b487-4bc0-aab0-5a72d5ce36bb", "task_name": "authentik.providers.scim.tasks.scim_signal_direct", "timestamp": "2023-04-20T10:21:03.364084"}
Thu, Apr 20 2023 12:21:04 pm | {"auth_via": "secret_key", "event": "/api/v3/outposts/proxy/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "127.0.0.1", "request_id": "0c10438275b44aada3ad2558d37bc2fd", "runtime": 732, "scheme": "http", "status": 200, "timestamp": "2023-04-20T10:21:04.053340", "user": "ak-outpost-a314886ac4544378ad108dceb358bb94", "user_agent": "goauthentik.io/outpost/2023.4.1"}
Thu, Apr 20 2023 12:21:04 pm | {"event":"Swapped maps","level":"debug","logger":"authentik.outpost.proxyv2","timestamp":"2023-04-20T10:21:04Z"}
Thu, Apr 20 2023 12:21:04 pm | {"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2023-04-20T10:21:04Z"}
Thu, Apr 20 2023 12:21:04 pm | {"auth_via": "unauthenticated", "event": "Task published", "host": "localhost:8000", "level": "info", "logger": "authentik.root.celery", "pid": 19691, "request_id": "9664dce35fcf4daab0b0edcd1469af88", "task_id": "1aa477d0-f607-4f21-93be-12a38b1da186", "task_name": "authentik.providers.scim.tasks.scim_signal_direct", "timestamp": "2023-04-20T10:21:04.161811"}
Thu, Apr 20 2023 12:21:04 pm | {"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "127.0.0.1", "request_id": "9664dce35fcf4daab0b0edcd1469af88", "runtime": 51, "scheme": "http", "status": 200, "timestamp": "2023-04-20T10:21:04.168872", "user": "ak-outpost-a314886ac4544378ad108dceb358bb94", "user_agent": "goauthentik.io/outpost/2023.4.1"}
Thu, Apr 20 2023 12:21:10 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "0362eadc02a74e448388ee642a8b6c90", "runtime": 15, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:10.521618", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:21:20 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "56718b1c96cf47ceab4f92fb7e3c90ba", "runtime": 15, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:20.521090", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:21:30 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "0716a30d80f14fc1a9412db6358dd12a", "runtime": 14, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:30.520149", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:21:32 pm | {"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "127.0.0.1", "request_id": "053b22d0c3c54661bd557fb4a759a687", "runtime": 12, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:32.384868", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
Thu, Apr 20 2023 12:21:41 pm | {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2023-04-20T10:21:41Z"}
Thu, Apr 20 2023 12:21:41 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "0e80f3163ec842aaacb4a65f235a22b8", "runtime": 1021, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:41.527086", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:21:50 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "fd59a94d4bee446ca910a89508364d10", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:21:50.518309", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:22:00 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "10.200.10.84", "request_id": "80342559a4024a03b7d8155a4c2bacd2", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:22:00.518893", "user": "", "user_agent": "kube-probe/1.24"}
Thu, Apr 20 2023 12:22:02 pm | {"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19158, "remote": "127.0.0.1", "request_id": "ea27fd7a849f48da95c79a4808de9c96", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:22:02.385534", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
Thu, Apr 20 2023 12:22:03 pm | {"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2023-04-20T10:22:03Z"}
Thu, Apr 20 2023 12:22:03 pm | {"auth_via": "unauthenticated", "event": "Task published", "host": "localhost:8000", "level": "info", "logger": "authentik.root.celery", "pid": 19691, "request_id": "50e004b686814139bfddd57f901b461f", "task_id": "09126ade-57ba-49e1-89a7-a7a1927e6913", "task_name": "authentik.providers.scim.tasks.scim_signal_direct", "timestamp": "2023-04-20T10:22:03.111297"}
Thu, Apr 20 2023 12:22:03 pm | {"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "127.0.0.1", "request_id": "50e004b686814139bfddd57f901b461f", "runtime": 57, "scheme": "http", "status": 200, "timestamp": "2023-04-20T10:22:03.119098", "user": "ak-outpost-a314886ac4544378ad108dceb358bb94", "user_agent": "goauthentik.io/outpost/2023.4.1"}
Thu, Apr 20 2023 12:22:10 pm | {"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.233.102.148:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19691, "remote": "10.200.10.84", "request_id": "7d937c513ee442199891450ba3092ac4", "runtime": 23, "scheme": "http", "status": 204, "timestamp": "2023-04-20T10:22:10.533652", "user": "", "user_agent": "kube-probe/1.24"}
```

**Version and Deployment:**
 - authentik version: 2023.4.1
 - Deployment: helm
 - Kubernetes Version: v1.24.10

**Additional context**
Helm Values:
```
additionalContainers: {}
affinity: {}
authentik:
  avatars: gravatar,initials
  email:
    from: authentik@mackner.net
    host: mail.mackner.net
    password: mysupersecretpassword
    port: 587
    timeout: 30
    use_ssl: false
    use_tls: true
    username: authentik@mackner.net
  error_reporting:
    enabled: false
    environment: k8s
    send_pii: false
  geoip: /geoip/GeoLite2-City.mmdb
  log_level: DEBUG
  outposts:
    container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
  postgresql:
    host: '{{ .Release.Name }}-postgresql'
    name: authentik
    password: mysupersecretpassword
    port: 5432
    user: authentik
  redis:
    host: '{{ .Release.Name }}-redis-master'
    password: ''
  secret_key: mysupersecretsecret
blueprints: []
env: {}
envFrom: []
envValueFrom: {}
geoip:
  accountId: ''
  editionIds: GeoLite2-City
  enabled: false
  image: maxmindinc/geoipupdate:v4.8
  licenseKey: ''
  updateInterval: 8
image:
  digest: ''
  pullPolicy: IfNotPresent
  pullSecrets: []
  repository: ghcr.io/goauthentik/server
  tag: 2023.4.1
ingress:
  annotations: {}
  enabled: true
  hosts:
    - host: authentik.mackner.net
      paths:
        - path: /
          pathType: Prefix
  ingressClassName: traefik-dmz
  labels: {}
  tls: []
initContainers:
  volume-permissions:
    command:
      - sh
      - '-c'
      - chown -R 1000:1000 /media
    image: busybox
    name: volume-permissions
    volumeMounts:
      - mountPath: /media
        name: media
livenessProbe:
  enabled: true
  httpGet:
    path: /-/health/live/
    port: http
  initialDelaySeconds: 50
  periodSeconds: 10
nodeSelector: {}
podAnnotations: {}
postgresql:
  enabled: true
  image:
    tag: 11.19.0-debian-11-r4
  postgresqlDatabase: authentik
  postgresqlMaxConnections: 500
  postgresqlUsername: authentik
  postgresqlPassword: mysupersecretpassword
priorityClassName: null
prometheus:
  rules:
    create: false
    labels: {}
  serviceMonitor:
    create: false
    interval: 30s
    labels: {}
    scrapeTimeout: 3s
readinessProbe:
  enabled: true
  httpGet:
    path: /-/health/ready/
    port: http
  initialDelaySeconds: 50
  periodSeconds: 10
redis:
  architecture: standalone
  auth:
    enabled: false
  enabled: true
  image:
    tag: 6.2.10-debian-11-r13
replicas: 1
resources:
  server: {}
  worker: {}
securityContext: {}
service:
  annotations: {}
  enabled: true
  labels: {}
  name: http
  port: 80
  protocol: TCP
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
tolerations: []
volumeMounts:
  - mountPath: /media
    name: media
volumes:
  - name: media
    nfs:
      path: /path/to/nfs/volume
      server: NFS Server IP
worker:
  priorityClassName: null
  replicas: 1
  securityContext: {}
global:
  cattle:
    clusterId: c-m-n5gxpw9t
    systemProjectId: p-zlwtg
```
