### ISSUE TITLE
How to use @goauthentik/api

### ISSUE THREAD

**Issue by heoyongun** [goauthentik/authentik#5326]
**Describe your question/**
How to use @goauthentik/api

**Relevant infos**
node v18
"@goauthentik/api": "^2023.4.1-1681807546",
"node-fetch": "^3.3.1"

**Screenshots**
Working

```
import { Configuration, CoreApi } from '@goauthentik/api';

async function listAllInstalledApps() {
    const config = new Configuration({
        basePath: 'http://localhost:9000/api/v3/',
        apiKey: 'Bearer AExoNXrzP6xJ44039xOE110CJhqMlUBWX3Ts8cJj6IUos0sWFbzsKOQw85x8'
    });

    const coreApi = new CoreApi(config);

    try {
        const response = await coreApi.coreApplicationsList();
        console.log('모든 설치된 앱 목록:');
        response.results.forEach(app => {
               //console.log
        });
    } catch (error) {
        console.error('API 요청 중 오류가 발생했습니다:', error);
    }
}

listAllInstalledApps();
```

Not Working
```
import { Configuration, CoreApi } from '@goauthentik/api';

async function listAllInstalledApps() {
    const config = new Configuration({
        basePath: 'http://localhost:9000/api/v3/',
        username: 'akadmin',
        password: '#test1234'
    });

    const coreApi = new CoreApi(config);

    try {
        const response = await coreApi.coreApplicationsList();
        console.log('모든 설치된 앱 목록:');
        response.results.forEach(app => {
               //console.log
        });
    } catch (error) {
        console.error('API 요청 중 오류가 발생했습니다:', error);
    }
}

listAllInstalledApps();```


**Additional context**

I want to use the API with a username and password.
Currently, the test was successful only when using the API by issuing an apiKey from the admin console.
How should I write this?

**Comment by BeryJu** [comment]
There isn't a way to access the API with just a username and password, see https://goauthentik.io/developer-docs/api/#authentication

You could do username/password via a Flow, see https://goauthentik.io/developer-docs/api/flow-executor

**Comment by heoyongun** [comment]
> 사용자 이름과 비밀번호만으로 API에 액세스할 수 있는 방법은 없습니다. [https://goauthentik.io/developer-docs/api/#authentication 을 참조하세요.](https://goauthentik.io/developer-docs/api/#authentication)
> 
> 흐름을 통해 사용자 이름/암호를 사용할 수 있습니다. [https://goauthentik.io/developer-docs/api/flow-executor 를 참조하세요.](https://goauthentik.io/developer-docs/api/flow-executor)

this is my code.
If you run the following code, "Authentication failed" is output.
Can you help me figure out what went wrong?

```
import { Configuration, CoreApi } from '@goauthentik/api';
import axios from 'axios';

const API_BASE = 'http://localhost:9000/api/v3';
const FLOW_SLUG = 'default-authentication-flow';

async function main() {
    // Create axios instance to store cookies
    const axiosInstance = axios.create({
        baseURL: API_BASE,
        withCredentials: true,
    });

    try {
        // 1. Start the flow
        const startResponse = await axiosInstance.get(`/flows/executor/${FLOW_SLUG}/`);
        const stage = startResponse.data;

        // 2. Send authentication information
        const authData = {
            component: stage.component, // stage.component is "ak-stage-identification"
            uid_field: 'akadmin',
            password: '1234qwer',
        };
        const authResponse = await axiosInstance.post(`/flows/executor/${FLOW_SLUG}/`, authData);

        // Check authentication response data
        console.log('Authentication response data:', authResponse.data);

        // 3. Check success
        // authResponse.data.component is 'ak-stage-identification'....why not return "xak-flow-redirect"
        if (authResponse.data.component === 'xak-flow-redirect') {
            console.log('Authentication successful'); 
        } else {
            console.log('Authentication failed');
            return;
        }

        // 4. Set Configuration for API usage
        const authToken = authResponse.headers['set-cookie'].find(cookie => cookie.startsWith('authentik_token'));
        const apiConfig = new Configuration({
            basePath: API_BASE,
            apiKey: `Token ${authToken.split('=')[1].split(';')[0]}`,
        });

        // 5. Call coreApplicationsList method
        const coreApi = new CoreApi(apiConfig);
        const applications = await coreApi.coreApplicationsList();
        console.log('Application list:', applications.data);
    } catch (error) {
        console.error('Error occurred:', error);
    }
}

main();
```

**Comment by BeryJu** [comment]
@heoyongun can you show the config of the flow that you're using? For this to work you need to configure a password stage within the identification stage, as by default that is two separate requests

**Comment by heoyongun** [comment]
> @heoyongun can you show the config of the flow that you're using? For this to work you need to configure a password stage within the identification stage, as by default that is two separate requests

Not the flow I wrote.
You're using a default flow.
It looks like this

![스크린샷 2023-04-22 11-39-40](https://user-images.githubusercontent.com/6076067/233757828-def1b68d-1fe0-4845-b3b6-005a2ade275c.png)
![스크린샷 2023-04-22 11-39-54](https://user-images.githubusercontent.com/6076067/233757845-986658bd-6037-4236-8c04-cf97647d69a6.png)


**default-authentication-flow.yaml**
```
context: {}
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: authentication
    layout: stacked
    name: Welcome to authentik!
    policy_engine_mode: any
    title: Welcome to authentik!
  conditions: []
  id: null
  identifiers:
    pk: e02f509d-9697-475a-b0cd-8c89f4bb1043
    slug: default-authentication-flow
  model: authentik_flows.flow
  state: present
- attrs:
    backends:
    - authentik.core.auth.InbuiltBackend
    - authentik.sources.ldap.auth.LDAPBackend
    - authentik.core.auth.TokenBackend
    configure_flow: e303f6d8-289b-4ca8-b21e-b133fc14785b
    failed_attempts_before_cancel: 5
  conditions: []
  id: null
  identifiers:
    name: default-authentication-password
    pk: f59f132c-5a8e-4d2f-be1d-87cd6475d64e
  model: authentik_stages_password.passwordstage
  state: present
- attrs:
    session_duration: seconds=0
  conditions: []
  id: null
  identifiers:
    name: default-authentication-login
    pk: b95b8d5c-35f9-405d-a6d5-63dd5276750d
  model: authentik_stages_user_login.userloginstage
  state: present
- attrs:
    device_classes:
    - static
    - totp
    - webauthn
    - duo
    - sms
    last_auth_threshold: seconds=0
    not_configured_action: skip
    webauthn_user_verification: preferred
  conditions: []
  id: null
  identifiers:
    name: default-authentication-mfa-validation
    pk: 6138207e-0679-4ebf-b9d6-ca059bce008e
  model: authentik_stages_authenticator_validate.authenticatorvalidatestage
  state: present
- attrs:
    case_insensitive_matching: true
    show_matched_user: true
    user_fields:
    - email
    - username
  conditions: []
  id: null
  identifiers:
    name: default-authentication-identification
    pk: f6b32e4f-5498-4d78-b95c-ee97d5f7a419
  model: authentik_stages_identification.identificationstage
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  id: null
  identifiers:
    order: 10
    pk: a194a85c-fad7-4e1d-b4fb-25f7748ca6a0
    stage: f6b32e4f-5498-4d78-b95c-ee97d5f7a419
    target: e02f509d-9697-475a-b0cd-8c89f4bb1043
  model: authentik_flows.flowstagebinding
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  id: null
  identifiers:
    order: 20
    pk: 545a2e92-b46a-46cd-8e8b-02867ba48139
    stage: f59f132c-5a8e-4d2f-be1d-87cd6475d64e
    target: e02f509d-9697-475a-b0cd-8c89f4bb1043
  model: authentik_flows.flowstagebinding
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  id: null
  identifiers:
    order: 30
    pk: d6287889-6d6d-42f0-8b02-cbf88a55dcd8
    stage: 6138207e-0679-4ebf-b9d6-ca059bce008e
    target: e02f509d-9697-475a-b0cd-8c89f4bb1043
  model: authentik_flows.flowstagebinding
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  id: null
  identifiers:
    order: 100
    pk: 252b06de-faa1-4935-9753-292e0f359ec1
    stage: b95b8d5c-35f9-405d-a6d5-63dd5276750d
    target: e02f509d-9697-475a-b0cd-8c89f4bb1043
  model: authentik_flows.flowstagebinding
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2023-04-22 02:36:43.559687+00:00
version: 1

```
