### ISSUE TITLE
Forward auth with Traefik seems to expect wierd URL

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#5374]
**Describe the bug**
Authentik seems to expect some wierd URL as the redirect_uri when coming from the outpost, so it's not working with the autogenerated config examples for traefik.

**To Reproduce**

1. Create a forward auth app, app-level
2. Deploy outpost that's binded to that app/provider combo externally (eg not managed by Authentik)
3. Try to get Traefik working with forward auth
4. See that the redirect is not correct

**Expected behavior**
I would have expected the redirect_uri to be correct.

**Screenshots**

**Logs**

```
{"auth_via": "session", "event": "/application/o/authorize/?client_id=6SteJ8ZxeTQy0Ned64993uYXI8vKfPuXjNwH0pPA&redirect_uri=https%3A%2F%2Fdh.example.com%2Foutpost.goauthentik.io%2Fcallback&response_type=code&scope=profile+ak_proxy+email+openid&state=LE4cyEKC-bwJwgNNM0xxrHCA95_-7S_gesesAYe0KWk", "host": "id.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 8820, "remote": "2001:14ba:16e5:faaf:f9b7:eda0:ecb7:baf0", "request_id": "b07aa84fda374943a0e85a860183a838", "runtime": 37, "scheme": "https", "status": 400, "timestamp": "2023-04-25T15:40:46.464072", "user": "akadmin", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0"}
{"event":"tracing request to backend","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":["authentik_csrf=nbB67g9PeycBjsWyDfH6jOgspw9SjHbo; authentik_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJ4ZGlteDhieW04ZDM2Z3lvOTFmcWxpcWI0ODR2M2dkaSIsImlzcyI6ImF1dGhlbnRpayIsInN1YiI6IjYxMjQ2YmQ1MzE2NDlmNTY5NTZiZWU2NGUxZDc5NTYwYTJjYzVlMmE0MGY2NDAxOTk3ODM1YTE0MDE2OGNkZDMiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJhY3IiOiJnb2F1dGhlbnRpay5pby9jb3JlL2RlZmF1bHQifQ.7FWwuzBjSgVGIAwGawfAqt3slFWSnfypiq7egTkSTCE"],"Sec-Ch-Ua":["\"Chromium\";v=\"108\", \"Opera\";v=\"94\", \"Not)A;Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0"],"X-Forwarded-For":["2001:14ba:16e5:faaf:f9b7:eda0:ecb7:baf0"],"X-Forwarded-Host":["id.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Forwarded-Scheme":["https"],"X-Real-Ip":["2001:14ba:16e5:faaf:f9b7:eda0:ecb7:baf0"],"X-Request-Id":["809cfd4bed0d9c27a8ac7b2b1d3ece45"],"X-Scheme":["https"]},"level":"trace","logger":"authentik.router","timestamp":"2023-04-25T15:43:07Z","url":"http://localhost:8000/application/o/authorize/?client_id=6SteJ8ZxeTQy0Ned64993uYXI8vKfPuXjNwH0pPA&redirect_uri=https%3A%2F%2Fdh.example.com%2Foutpost.goauthentik.io%2Fcallback&response_type=code&scope=profile+ak_proxy+email+openid&state=kAiCLqylnrKrObxmeZblAWCyGaa6a1h-mo5CTqskA-g"}
{"auth_via": "session", "event": "Invalid redirect uri (regex comparison)", "expected": ["https://dh.example.com/outpost.goauthentik.io/callback\\?X-authentik-auth-callback=true", "https://dh.example.com\\?X-authentik-auth-callback=true"], "host": "id.example.com", "level": "warning", "logger": "authentik.providers.oauth2.views.authorize", "pid": 8820, "redirect_uri": "https://dh.example.com/outpost.goauthentik.io/callback", "request_id": "41adcf09b35b4b65b08174b0ce4adc3d", "timestamp": "2023-04-25T15:43:07.983708"}
{"auth_via": "session", "event": "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).", "host": "id.example.com", "level": "warning", "logger": "authentik.providers.oauth2.views.authorize", "pid": 8820, "request_id": "41adcf09b35b4b65b08174b0ce4adc3d", "timestamp": "2023-04-25T15:43:07.984443"}
```

**Version and Deployment**

-   authentik version: 2023.4.1
-   Deployment: Authentik via Helm and external outpost via docker-compose

**Additional context**

Docker-compose:
```yaml
---
version: '3.7'
services:
  ak:
   image: ghcr.io/goauthentik/proxy
   container_name: ak
   restart: unless-stopped
   environment:
     AUTHENTIK_HOST: https://id.example.com
     AUTHENTIK_INSECURE: "false"
     AUTHENTIK_TOKEN: <snip>
     AUTHENTIK_DEBUG: "true"
   ports:
     - 172.19.0.1:9000:9000
     - 172.19.0.1:9443:9443
   networks:
     - default
     - traefik_proxy
   labels:
     traefik.enable: true
     traefik.port: 9000
     traefik.http.routers.authentik.rule: Host(`dh.example.com`) && PathPrefix(`/outpost.goauthentik.io/`)
     # `authentik-proxy` refers to the service name in the compose file.
     traefik.http.middlewares.authentik.forwardauth.address: http://172.19.0.1:9000/outpost.goauthentik.io/auth/traefik
     traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
     traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
  index:
    container_name: index
    image: samip537/fancyindex-darktheme:latest
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /var/www/html:/share
    environment:
      - PUID=112
      - GUID=100
      - CONTAINER_TIMEZONE=Europe/Helsinki
      - DISABLE_AUTH=true
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.index-rtr.entrypoints=https
      - traefik.http.routers.index-rtr.rule=Host("dh.example.com")
      - traefik.http.routers.index-rtr.priority=20
      - traefik.http.routers.index-rtr.tls.certresolver=zerossl
      ## Middlewares
      - traefik.http.routers.index-rtr.middlewares=authentik@docker
      ## HTTP Services
      - traefik.http.routers.index-rtr.service=index-svc
      - traefik.http.services.index-svc.loadbalancer.server.port=80

```
