### ISSUE TITLE
JWT in Proxy Provider not valid

### ISSUE THREAD

**Issue by Nefkens** [goauthentik/authentik#5447]
**Describe the bug**
JWT for Proxy provider is not valid (and large)

**To Reproduce**

Create Proxy Provider. Without cert.

Create Ingress
```
 #ingress grafana
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://authentik-1682534179.default.svc.cluster.local:80/outpost.goauthentik.io/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://domain.nl/outpost.goauthentik.io/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-authentik-username,X-authentik-jwt,X-authentik-meta-jwks"
    nginx.ingress.kubernetes.io/auth-snippet: "proxy_set_header X-Forwarded-Host $http_host;"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - domain.nl
    secretName: domain.nl-tls
  rules:
    - host: domain.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 1234
```

helm chart:
```
authentik:
  log_level: trace
```

When i get the JWT from the log (header), https://jwt.io gives:  invalid signature

I cannot paste the JWT here since it contains my e-mail adres. 

Also the JWT is "large" and contains all the scopes. Even double since key ak_proxy containts a copy of the scope

**Expected behavior**
A valid JWT

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.4.1]
-   Deployment: [helm]

**Additional context**

In this comment, is explained why RS256 is used in Proxy Provider mode
https://github.com/goauthentik/authentik/issues/3909#issuecomment-1397065921

In this comment, is explained RS256 is calculated based on the client secret. Only does the proxy does not have a client secret.
https://github.com/goauthentik/authentik/issues/4824#issuecomment-1451675304

What secret is used?

My use case is auth for grafana with auth.JWT. So my next challange is to tell grafana to validate the JWT with a pem file:
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/
