### ISSUE TITLE
Is there a way to load test data in docker?

### ISSUE THREAD

**Issue by CyborTronik** [goauthentik/authentik#5700]
Context:
I write an app (experiment with Spring boot service). For security I need an auth service. Ideally is to reuse an existing solution like Authentik. During the development phase I do write integration and system tests. Which means I need to run the auth service during those tests. For that a docker-compose was configured which looks to be fine for now.

Question:
Can I configure (or automate) authentik, so during docker start it would load few test users and an app credentials that I can use in tests?

Thanks

**Comment by BeryJu** [comment]
You can do that with blueprints, see https://goauthentik.io/developer-docs/blueprints/

for example the blueprint I use for some testing users:

```yaml
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: local - dev users & groups
  labels:
    blueprints.goauthentik.io/instantiate: "false"
entries:
  - model: authentik_core.group
    identifiers:
      name: Department foo
    id: group_foo
  - model: authentik_core.group
    identifiers:
      name: Department bar
    id: group_bar
  - model: authentik_core.group
    identifiers:
      name: Department baz
    id: group_baz
  - model: authentik_core.user
    identifiers:
      attributes:
        managed: "user1"
    attrs:
      username: user1
      name: user1
      groups:
        - !KeyOf group_foo
  - model: authentik_core.user
    identifiers:
      attributes:
        managed: "user2"
    attrs:
      username: user2
      name: user2
      groups:
        - !KeyOf group_bar
        - !KeyOf group_foo
  - model: authentik_core.user
    identifiers:
      attributes:
        managed: "user3"
    attrs:
      username: user3
      name: user3
      groups:
        - !KeyOf group_baz
        - !KeyOf group_bar

```
