### ISSUE TITLE
Weird behavior using Docker Networks

### ISSUE THREAD

**Issue by zolero** [goauthentik/authentik#5880]
Currently I've been struggling for hours now finding out finding our what's wrong with my Authentik setup. And as far as I have reached my investigations, this is a common issue: #2180 #4383, #3637, #5059, #2719, #3087, 

Basic docker setup:

```yml
---
version: "3.8"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
    networks:
      - network
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - network
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.5.3}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./templates:/templates
    env_file:
      - .env
    ports:
      - "9000:9000"
    expose:
      - 9000
    depends_on:
      - postgresql
      - redis
    networks:
      - network # Even defining network with just an basic setup sometimes failes.
#      - nginx-proxy <--- Fails as well
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.5.3}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
    networks:
      - network
volumes:
  database:
    driver: local
  redis:
    driver: local
networks:
  network:
    name: ${DOCKER_STACK}-network
#  nginx-proxy: <--- One extra network it fails everyhing
#    external: true
#    name: nginx-proxy
 ```

Whenever I deploy a fresh installation using networks, it succeeds and I can access the host. Although when I add an network to the server it instantly disconnects the worker and sometimes I just logout out of nowhere. Now when I try to setup a Authentik with a proxy server it fails and returns me an 403 error.

Please help,

```yml
  networks:
      - nginx-proxy
```

```yml
networks:
  network:
    name: ${DOCKER_STACK}-network
#  nginx-proxy: <--- One extra network it fails everyhing
#    external: true
#    name: nginx-proxy
```
