### ISSUE TITLE
Error while applying blueprints

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#5890]
**Describe the bug**
All my blueprints with BlueprintInstances are failing to apply.

**To Reproduce**

1. Create a blueprint template
2. Create a blueprint containing a BlueprintInstance
3. Check Admin -> System Tasks

**Expected behavior**
Blueprints get applied.

**Screenshots**
---

**Logs**
```
Never call result.get() within a task! See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment: helm

**Additional context**
---

**Comment by benedikt-bartscher** [comment]
The blueprints actually get applied, it's just the System Task which fails. Introduced in https://github.com/goauthentik/authentik/pull/5703

**Comment by cskwrd** [comment]
I am not seeing my blueprints applied when getting this error.

```
version: 1
entries:
  - model: authentik_blueprints.blueprintinstance
    identifiers:
      path: default/flow-oobe.yaml
    attrs:
      enabled: false
    state: present
```

This should disable the OOBE but doesn't on 2023.10.1 helm chart
