### ISSUE TITLE
"Warning: authentik Domain is not configured, authentication will not work. " on Fresh deploy

### ISSUE THREAD

**Issue by Harnish** [goauthentik/authentik#5916]
**Describe the bug**
I do a clean helm install with values file (scrubbed):

values.yaml
```
authentik:
    secret_key: "randomlygeneratedsecret"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: false
    postgresql:
        password: "samesecretforbothvalues"

ingress:
    enabled: true
    hosts:
        - host: authentik.mydomain.rocks
          paths:
              - path: "/"
                pathType: Prefix
postgresql:
    enabled: true
    postgresqlPassword: "samesecretforbothvalues"
redis:
    enabled: true
```
Deploy with helm
```
helm upgrade --install authentik authentik/authentik -f values.yaml
```

**To Reproduce**

1. go to https://authentik.mydomain.rocks/if/flow/initial-setup/
2. Setup the akadmin account
3. Go to the Admin Interface
4. Click Applications->Providers
5. Click Create
6. Select Proxy Provider
7. Set name: bob, set "Authentication flow" to the default and set "Authorization flow"
8. Set External host: https://bob.mydomain.rocks and set internal host: http://bob.k3s.local
9. Click Finish
10. Get error "CSRF Failed: Origin checking failed - https://authentik.mydomain.rocks does not match any trusted origins."

**Expected behavior**
It should save the config.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment: helm
-
