### ISSUE TITLE
OAuth2 token created via secondary tenant has default tenant as issuer

### ISSUE THREAD

**Issue by joriskt** [goauthentik/authentik#6419]
## Describe the bug
When Authentik is deployed with multiple tenants, e.g. `primary.tld` and `secondary.tld`, and an Outpost is configured to authenticate users via **any non-primary tenant**, the generated OAuth2 token still has `primary.tld` as the `iss` (issuer) field on the token. **This results in the Outpost rejecting it:**
```
warning error=oidc: id token issued by a different provider, expected "https://login.secondary.tld/application/o/myapp/" got "https://login.primary.tld/application/o/myapp/" event=failed to redeem code logger=authentik.outpost.proxyv2.application name=myapp-provider timestamp=2023-07-29T07:57:39Z
```
The result is that the user cannot access the application at all, as the Outpost keeps returning `400 Bad Request`.

## To Reproduce
For clarity, this setup assumes two distinct domain names and two distinct machines. For reproducing this bug you almost certainly do not need to *actually* do this.

### Authentik config
Assuming this runs on "the primary machine".

- Deploy Authentik.
  - Default settings unless mentioned otherwise.
  - Make sure it is accessible via `login.primary.tld` and `login.secondary.tld`.
- Create a Tenant, `primary.tld`, and set it as default.
- Create a Tenant, `secondary.tld`.
- Create a Provider:
  - Type: `Proxy Provider`
  - Name: `myapp-provider`
  - Authorization flow: `default-provider-authorization-implicit-consent`
  - Kind of proxy: `Forward auth (single application)`
  - **External host: `myapp.secondary.tld`**
- Create an Application:
  - Name: `MyApp`
  - Slug: (auto)
  - Provider: `myapp-provider` that you created
- Create an `Outpost`:
  - Name: `myapp-outpost`
  - Type: `Proxy`
  - Applications: `MyApp`

### Outpost config
Assuming this runs on "the secondary machine".

- Install the independent Authentik Outpost, in this example using `docker-compose`:
```
version: "3.8"

services:
  outpost:
    image: ghcr.io/goauthentik/proxy
    container_name: "authentik-outpost"
    # Host networking because our fake app is running on the host and not in a container. The outpost uses port tcp/9000.
    network_mode: "host"
    environment:
      AUTHENTIK_HOST: https://login.secondary.tld
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: your-outpost-token
    restart: always
```
- Please make sure you inserted your `login.secondary.tld` and `your-outpost-token` in the above config.

### Forward proxy config
Still on the secondary machine. We will be using Caddy in this example.

- Install `caddy` and configure like so (which matches [the manual](https://goauthentik.io/docs/providers/proxy/server_caddy)):
```
myapp.secondary.tld {
        # Outpost traffic is routed to the outpost
        reverse_proxy /outpost.goauthentik.io/* http://localhost:9000

        # Forward authentication to outpost
        forward_auth http://localhost:9000 {
                uri /outpost.goauthentik.io/auth/caddy

                copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
        }

        # Forward authenticated traffic to our fake app.
        reverse_proxy http://localhost:30002
}

# OUR FAKE APP:
http://localhost:30002 {
        respond "Hi, I'm an app!"
}
```

### Reproducing
- Navigate to `myapp.secondary.tld`.
- The outpost will redirect you to `login.secondary.tld`.
- You log in.
- Authentik redirects you back to `myapp.secondary.tld`.
- You see a blank screen.
  - Using your browsers network inspector, you can see the request returned `400 Bad Request`.
- Checking the Outpost logs, you can find the following error:
```
warning error=oidc: id token issued by a different provider, expected "https://login.secondary.tld/application/o/myapp/" got "https://login.primary.tld/application/o/myapp/" event=failed to redeem code logger=authentik.outpost.proxyv2.application name=foundry-proxy-provider timestamp=2023-07-29T07:57:39Z
```

## Expected behavior
Considering that the user logged in via `login.secondary.tld`, it would be only natural to expect that the `iss` field of the OAuth2 token is set to `login.secondary.tld`. This would fix the problem.

## Screenshots
\-

## Logs
From the Authentik Proxy (`ghcr.io/goauthentik/proxy`) container:
```
warning error=oidc: id token issued by a different provider, expected "https://login.secondary.tld/application/o/myapp/" got "https://login.primary.tld/application/o/myapp/" event=failed to redeem code logger=authentik.outpost.proxyv2.application name=foundry-proxy-provider timestamp=2023-07-29T07:57:39Z
```

## Version and Deployment

-   authentik version: `2023.6.1`
-   Deployment: `docker-compose`

## Additional context
\-

**Comment by joriskt** [comment]
With some help from @BeryJu, we found the issue was this part of the **outpost configuration:**
```
    environment:
      AUTHENTIK_HOST: https://login.secondary.tld  # <-- secondary
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: your-outpost-token
```

Instead, it should have been this:
```
    environment:
      AUTHENTIK_HOST: https://login.primary.tld  # <-- should be primary
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: your-outpost-token
      AUTHENTIK_BROWSER_HOST: https://login.secondary.tld  # <-- new, should be secondary
```

Thanks. Closing this issue.
