### ISSUE TITLE
 Forward Proxy not working if host_browswer env var does not match host env var in 2023.6.1

### ISSUE THREAD

**Issue by jmdilly** [goauthentik/authentik#6476]
When AUTHENTIK_HOST does not match AUTHENTIK_HOST_BROWSER, forward authentication failed.

Was in issue #4715. Seems still broken.

**To Reproduce**

Create a proxy outpost with different AUTHENTIK_HOST and AUTHENTIK_HOST_BROWSER and use it in forward auth.

docker-compose example : 
```
  outpost_proxy_app:
        image: ghcr.io/goauthentik/proxy:2023.6.1
        environment:
            AUTHENTIK_HOST: https://authentik.local
            AUTHENTIK_INSECURE: "false"
            AUTHENTIK_TOKEN: XXX
            AUTHENTIK_HOST_BROWSER: https://auth.public.tld
```

My provider is forward auth (single application).

**Expected behavior**
Should be able to authenticate.

**Logs**
{"error":"oidc: id token issued by a different provider, expected \"https://authentik.local/application/o/app/\" got \"https://auth.public.tld/application/o/app/\"","event":"failed to redeem code","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"App","timestamp":"2023-08-04T21:12:21Z"}

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.1
-   Deployment: docker-compose
-   Reverse proxy: Traefik 2.10
