### ISSUE TITLE
Authentik gets stuck in redirect loop when using newly created application with proxy provider

### ISSUE THREAD

**Issue by miversen33** [goauthentik/authentik#6540]
**Describe the bug**
This was discussed a bit in the Application Reverse Proxy Issues thread on the discord but I will do my best to relay the info here as well.

On a fresh install, when I create a new proxy provider for an application (in my example I am using sonarr, though the endpoint is irrelevant), Authentik cannot seem to find the application after setting it up. Pictures are worth a thousand words, so here is a handful to show what I am seeing.

Proxy Provider setup
![Proxy Provider setup](https://github.com/goauthentik/authentik/assets/2640668/1053dfc2-5e68-4207-90e0-b6d20b1828e6)

Example application setup
![Example application setup](https://github.com/goauthentik/authentik/assets/2640668/2f4f62d2-7a48-491d-b971-b681b4028639)

Authentik Embedded Outpost
![Authentik Embedded Outpost](https://github.com/goauthentik/authentik/assets/2640668/2f8879a2-2a51-400a-8ae9-ab1ba289d6bc)

Authentik Outpost Configuration
```yaml
log_level: info
docker_labels: null
authentik_host: https://auth.iserver.me
docker_network: null
container_image: null
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: ""
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: false
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_ingress_class_name: null
kubernetes_disabled_components:
  - deployment
  - secret
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```

User application page
![User application page](https://github.com/goauthentik/authentik/assets/2640668/c5a59820-c9a5-4117-963f-1a624a61e306)

Firefox dying of redirect loop
![Firefox dying of redirect loop](https://github.com/goauthentik/authentik/assets/2640668/462e0b1d-67d6-4ed7-aa0a-b729b5d4d71b)

Round and round it goes
![Round and round it goes](https://github.com/goauthentik/authentik/assets/2640668/2c2f8d41-b9ac-4357-bfaf-5a5a5ad0e136)

**To Reproduce**

1. Setup new fresh installation of authentik with docker compose
2. Create new proxy provider with `default-authentication-flow` as the authentication flow and `default-provider-authorization-explicit-consent` as the authorization flow (though I tried with **implicit** and got the same result)
3. Setup external and internal host as requested
4. Create an application that uses the Provider
5. Add the application to the embedded outpost (are we supposed to set that to use the `local docker connection` integration?? I tried both but don't really know the "correct" way to use that).
6. Go to application page
7. See death

**Expected behavior**
I would expect the application to properly load when selected. I assume I am doing something wrong but I was unable to find any documentation/examples on how to setup applications/providers. There seems to be quite a bit of assumed knowledge in the docs. Note, previously I was experiencing an authentik 404 when selecting an application. I am unable to recreate this issue now, though I feel like I haven't changed my configuration so 🤷‍♂️

**Logs**
Output of docker-compose logs or kubectl logs respectively
[authentik-server-logs.gz](https://github.com/goauthentik/authentik/files/12340164/authentik-server-logs.gz)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.1
-   Deployment: docker-compose

**Additional context**
I am noticing that after I setup the basic proxy provider, that any request that come to the base domain (in this case, `iserver.me`) are being consumed by it at the listed endpoint (so `iserver.me/sonarr`). That screams misconfiguration to me but I have no idea what I am doing wrong :(

I will provide whatever information is needed, thanks in advanced!
