### ISSUE TITLE
Authentik's DB Migration fails when the DB is deployed outside of K8S

### ISSUE THREAD

**Issue by headstack** [goauthentik/authentik#6712]
**Describe the bug**
I have Authentik deployed to **K8S** with **PostgreSQL 15** previously deployed to **AWS RDS**. I mean I wasn't using PostgreSQL lower than 15 version previously as well as PostgreSQL deployed on kubernetes. When I set a new version for K8S chart as **2023.8.1** or **2023.8.0** `the server and worker does not start`. They are failing in loop instead. When I saw the server logs it was saying the connection to Redis and PostgreSQL was successful, but when **Django migration** task had started, I got an error with python stack trace.

**To Reproduce**
1. Deploy DB on VM or on RDS with PostgreSQL 15.
2. Deploy K8S Chart version 2023.6.3 with PostgreSQL disabled. I have the following configuration of PostgreSQL in my values.yaml:
```
postgresql:
  enabled: false
```
4. After server will get up and running successfully, deploy a new Chart Version 2023.8.0 or 2023.8.1.
5. See container logs. There's no a need to set AUTHENTIK_LOG_LEVEL=debug. The result will be the same as well as with info.
```
kubectl logs -n authentik authentik-server
```

**Expected behavior**
I've expected there won't be such error and Authentik starts without issues. But he tried to migrate PGSQL managed outside of K8S and got an error.

**Screenshots**
`N/A`

**Logs**
```
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1693467034.768935, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1693467034.7695396, "count": 57}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1693467034.7697883}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1693467034.8131988}
{"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1693467034.8159707}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1693467034.8159988}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1693467035.0098276, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1693467035.0103948, "count": 57}
2023-08-31 07:30:35 [info     ] applying django migrations
2023-08-31 07:30:35 [info     ] waiting to acquire database lock
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/lifecycle/migrate.py", line 95, in <module>
    execute_from_command_line(["", "migrate"])
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/authentik/root/settings.py", line 356, in <module>
    _ERROR_REPORTING = CONFIG.get_bool("error_reporting.enabled", False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/config.py", line 226, in get_bool
    return str(self.get(path, default)).lower() == "true"
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/config.py", line 213, in get
    attr: Attr = get_path_from_dict(root, path, sep=sep, default=Attr(default))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/config.py", line 30, in get_path_from_dict
    if root and comp in root:
                ^^^^^^^^^^^^
TypeError: argument of type 'Attr' is not iterable
```

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.8.0, 2023.8.1]
-   Deployment: [kustomize + helm]

**Additional context**
`N/A`

**Comment by BeryJu** [comment]
Can you post your full helm values file? I think the error is caused by something in there and the error isn't directly related to postgres

**Comment by headstack** [comment]
Yes, I can!

**helm.yaml:**

```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: authentik
name: authentik
repo: https://charts.goauthentik.io
version: 2023.8.1
releaseName: authentik
namespace: authentik
valuesFile: helm_values.yaml
includeCRDs: true
```

**helm_values.yaml:**

```
tolerations:
  - key: "on_demand"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: userlabels/environment
              operator: In
              values:
                - value
            - key: userlabels/intent
              operator: In
              values:
                - value

image:
  pullPolicy: "IfNotPresent"

livenessProbe:
  enabled: true
  httpGet:
    path: "/-/health/live/"
    port: "http"
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false
  ingressClassName: ingress
  tls:
    - hosts:
        - some.host.domain
  hosts:
    - host: some.host.domain
      paths:
        - path: "/"
          pathType: Prefix

authentik:
  error_reporting:
    enabled: false
  disable_startup_analytics: true
  geoip: "/geoip/GeoLite2-City.mmdb"
  log_level: "info"
  outposts:
    container_image_base: "ghcr.io/goauthentik/%(type)s:%(version)s"
  autoscaling:
    server:
      enabled: true
      maxReplicas: 3
      minReplicas: 2
      targetCPUUtilizationPercentage: 50
    worker:
      enabled: true
      maxReplicas: 3
      minReplicas: 2
      targetCPUUtilizationPercentage: 80

postgresql:
  enabled: false

redis:
  enabled: true
```

I also override all the Authentik variables via AWS Secrets Manager and k8s operator ExternalSecrets that is mounted to worker and server pods. Below you could see the values that my Authentik instance use. P.S. it worked with the version I migrate from.

```
    AUTHENTIK_POSTGRESQL__HOST                                    = tostring(module.rds_instance.instance_address)
    AUTHENTIK_POSTGRESQL__NAME                                    = "authentik"
    AUTHENTIK_POSTGRESQL__PORT                                    = 5432
    AUTHENTIK_POSTGRESQL__USER                                    = "authentikrds"
    AUTHENTIK_POSTGRESQL__PASSWORD                                = tostring(random_password.rds_password.result)
    AUTHENTIK_POSTGRESQL__SSLMODE                                 = "verify-ca"
    AUTHENTIK_POSTGRESQL__SSLROOTCERT                             = "/certs/aws_rds/cacerts.pem"
    AUTHENTIK_SECRET_KEY                                          = tostring(random_password.authentik_coockie_signin.result)
    AUTHENTIK_AUTOSCALING__SERVER__ENABLED                        = true
    AUTHENTIK_AUTOSCALING__SERVER__MAXREPLICAS                    = 3
    AUTHENTIK_AUTOSCALING__SERVER__MINREPLICAS                    = 1
    AUTHENTIK_AUTOSCALING__SERVER__TARGETCPUUTILIZATIONPERCENTAGE = 50
    AUTHENTIK_AUTOSCALING__WORKER__ENABLED                        = true
    AUTHENTIK_AUTOSCALING__WORKER__MAXREPLICAS                    = 3
    AUTHENTIK_AUTOSCALING__WORKER__MINREPLICAS                    = 1
    AUTHENTIK_AUTOSCALING__WORKER__TARGETCPUUTILIZATIONPERCENTAGE = 80
    AUTHENTIK_EMAIL__PORT                                         = 587
    AUTHENTIK_EMAIL__TIMEOUT                                      = 30
    AUTHENTIK_EMAIL__USE_SSL                                      = false
    AUTHENTIK_EMAIL__USE_TLS                                      = false
    AUTHENTIK_ERROR_REPORTING                                     = false
    AUTHENTIK_DISABLE_STARTUP_ANALYTICS                           = true
    AUTHENTIK_GEOIP                                               = "/geoip/GeoLite2-City.mmdb"
    AUTHENTIK_LOG_LEVEL                                           = "debug"
    AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE                      = "ghcr.io/goauthentik/%(type)s:%(version)s"
    AUTHENTIK_REDIS__HOST                                         = "authentik-redis-master"
    AUTHENTIK_DEFAULT_USER_CHANGE_NAME                            = false
    AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL                           = false
    AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME                        = false
    AUTHENTIK_GDPR_COMPLIANCE                                     = true
    AUTHENTIK_DEFAULT_TOKEN_LENGTH                                = 60

    AUTHENTIK_BOOTSTRAP_PASSWORD = tostring(random_password.authentik_bootstrap_admin_password.result)
    AUTHENTIK_BOOTSTRAP_TOKEN    = tostring(random_password.authentik_bootstrap_admin_token.result)
    AUTHENTIK_BOOTSTRAP_EMAIL    = "email@stage.com"

    AUTHENTIK_FREEIPA_SYNC_USER_NAME     = "uid=authentik-stage,cn=users,cn=accounts,dc=eqvilent,dc=com"
    AUTHENTIK_FREEIPA_SYNC_USER_PASSWORD = tostring(random_password.authentik_freeipa_sync_user_password.result)
```

**Comment by headstack** [comment]
Yes, I can!

**helm.yaml:**

```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: authentik
name: authentik
repo: https://charts.goauthentik.io
version: 2023.8.1
releaseName: authentik
namespace: authentik
valuesFile: helm_values.yaml
includeCRDs: true
```

**helm_values.yaml:**

```
tolerations:
  - key: "on_demand"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: userlabels/environment
              operator: In
              values:
                - value
            - key: userlabels/intent
              operator: In
              values:
                - value

image:
  pullPolicy: "IfNotPresent"

livenessProbe:
  enabled: true
  httpGet:
    path: "/-/health/live/"
    port: "http"
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false
  ingressClassName: ingress
  tls:
    - hosts:
        - some.host.domain
  hosts:
    - host: some.host.domain
      paths:
        - path: "/"
          pathType: Prefix

authentik:
  error_reporting:
    enabled: false
  disable_startup_analytics: true
  geoip: "/geoip/GeoLite2-City.mmdb"
  log_level: "info"
  outposts:
    container_image_base: "ghcr.io/goauthentik/%(type)s:%(version)s"
  autoscaling:
    server:
      enabled: true
      maxReplicas: 3
      minReplicas: 2
      targetCPUUtilizationPercentage: 50
    worker:
      enabled: true
      maxReplicas: 3
      minReplicas: 2
      targetCPUUtilizationPercentage: 80

postgresql:
  enabled: false

redis:
  enabled: true
```

I also override all the Authentik variables via AWS Secrets Manager and k8s operator ExternalSecrets that is mounted to worker and server pods. Below you could see the values that my Authentik instance use. P.S. it worked with the version I migrate from.

```
    AUTHENTIK_POSTGRESQL__HOST                                    = tostring(module.rds_instance.instance_address)
    AUTHENTIK_POSTGRESQL__NAME                                    = "authentik"
    AUTHENTIK_POSTGRESQL__PORT                                    = 5432
    AUTHENTIK_POSTGRESQL__USER                                    = "authentikrds"
    AUTHENTIK_POSTGRESQL__PASSWORD                                = tostring(random_password.rds_password.result)
    AUTHENTIK_POSTGRESQL__SSLMODE                                 = "verify-ca"
    AUTHENTIK_POSTGRESQL__SSLROOTCERT                             = "/certs/aws_rds/cacerts.pem"
    AUTHENTIK_SECRET_KEY                                          = tostring(random_password.authentik_coockie_signin.result)
    AUTHENTIK_AUTOSCALING__SERVER__ENABLED                        = true
    AUTHENTIK_AUTOSCALING__SERVER__MAXREPLICAS                    = 3
    AUTHENTIK_AUTOSCALING__SERVER__MINREPLICAS                    = 1
    AUTHENTIK_AUTOSCALING__SERVER__TARGETCPUUTILIZATIONPERCENTAGE = 50
    AUTHENTIK_AUTOSCALING__WORKER__ENABLED                        = true
    AUTHENTIK_AUTOSCALING__WORKER__MAXREPLICAS                    = 3
    AUTHENTIK_AUTOSCALING__WORKER__MINREPLICAS                    = 1
    AUTHENTIK_AUTOSCALING__WORKER__TARGETCPUUTILIZATIONPERCENTAGE = 80
    AUTHENTIK_EMAIL__PORT                                         = 587
    AUTHENTIK_EMAIL__TIMEOUT                                      = 30
    AUTHENTIK_EMAIL__USE_SSL                                      = false
    AUTHENTIK_EMAIL__USE_TLS                                      = false
    AUTHENTIK_ERROR_REPORTING                                     = false
    AUTHENTIK_DISABLE_STARTUP_ANALYTICS                           = true
    AUTHENTIK_GEOIP                                               = "/geoip/GeoLite2-City.mmdb"
    AUTHENTIK_LOG_LEVEL                                           = "debug"
    AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE                      = "ghcr.io/goauthentik/%(type)s:%(version)s"
    AUTHENTIK_REDIS__HOST                                         = "authentik-redis-master"
    AUTHENTIK_DEFAULT_USER_CHANGE_NAME                            = false
    AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL                           = false
    AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME                        = false
    AUTHENTIK_GDPR_COMPLIANCE                                     = true
    AUTHENTIK_DEFAULT_TOKEN_LENGTH                                = 60

    AUTHENTIK_BOOTSTRAP_PASSWORD = tostring(random_password.authentik_bootstrap_admin_password.result)
    AUTHENTIK_BOOTSTRAP_TOKEN    = tostring(random_password.authentik_bootstrap_admin_token.result)
    AUTHENTIK_BOOTSTRAP_EMAIL    = "email@host.domain"

    AUTHENTIK_FREEIPA_SYNC_USER_NAME     = "uid=authentik,cn=users,cn=accounts,dc=host,dc=domain"
    AUTHENTIK_FREEIPA_SYNC_USER_PASSWORD = tostring(random_password.authentik_freeipa_sync_user_password.result)
```
