### ISSUE TITLE
Use embedded proxy outpost externally?

### ISSUE THREAD

**Issue by joachimtingvold** [goauthentik/authentik#6749]
**Describe your question/**
I'm currently using Authentik together with Traefik in a docker environment with the embedded proxy outpost. For internal things (proxied by Traefik), everything works without issues. However, when I try to expand this setup to allow for external reverse-proxies to use forwardauth towards the existing Authentik/Traefik setup, I run into problems (or at least I can't figure out how to get it to work).

A few details of the setup;
- docker1 running traefik1, authentik1, whoami1
- docker2 running traefik2 and whoami2
- docker1 and docker2 are completely separated (network and geographically, i.e. they reach each other via Internet)
- traefik1 reverse-proxies for traefik1.domain.tld, login.domain.tld (authentik1) and whoami1.domain.tld
- traefik2 reverse-proxies for traefik2.domain.tld and whoami2.domain.tld
- authentik1 running embedded proxy outpost

The current status is that requests to traefik1 & whoami1 works fine, but requests to traefik2 & whoami2 is not properly working;

- Open browser in incognito mode (i.e. all cookies/site data removed). Log in to `https://login.domain.tld` manually/beforehand (but can also be done during the flow -- it does not affect the outcome).

- Request to `https://whoami2.domain.tld` is successfully redirected (which results in HTTP 302 response):
`https://login.domain.tld/application/o/authorize/?client_id=xxx&redirect_uri=https%3A%2F%2Fwhoami2.domain.tld%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=profile+openid+email+ak_proxy&state=xxx`

 - Authorization (implicit consent) is done (HTTP 200 OK);
`https://login.domain.tld/if/flow/default-provider-authorization-implicit-consent/?client_id=xxx&redirect_uri=https%3A%2F%2Fwhoami2.domain.tld%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=profile+openid+email+ak_proxy&state=xxx`

 - API query is done (HTTP 200 OK);
`https://login.domain.tld/api/v3/flows/executor/default-provider-authorization-implicit-consent/?query=client_id%3Dxxx%26redirect_uri%3Dhttps%253A%252F%252Fwhoami2.domain.tld%252Foutpost.goauthentik.io%252Fcallback%253FX-authentik-auth-callback%253Dtrue%26response_type%3Dcode%26scope%3Dprofile%2Bopenid%2Bemail%2Bak_proxy%26state%3Dxxx`

 - Callback is done (HTTP 404 Not found);
`https://whoami2.domain.tld/outpost.goauthentik.io/callback?X-authentik-auth-callback=true&code=xxx&state=xxx`

The latest redirect results in 404 Not found, and the browser URL is at that point as depicted in the last step above. If I refresh the site, I still get the 404 Not found. The browser does the following requests, in this order, for every time I refresh (which differs from the initial attempt, probably due to cookies/headers already being set or similar);

1. 404 Not found;
`https://whoami2.domain.tld/outpost.goauthentik.io/callback?X-authentik-auth-callback=true&code=xxx&state=xxx`

2. 302 Temp redirect;
`https://login.domain.tld/application/o/authorize/?client_id=xxx&redirect_uri=https%3A%2F%2Fwhoami2.domain.tld%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=profile+openid+email+ak_proxy&state=xxx`

3. 302 Temp redirect;
`https://login.domain.tld/flows/-/default/authentication/?next=/application/o/authorize/%3Fclient_id%3Dxxx%26redirect_uri%3Dhttps%253A%252F%252Fwhoami2.domain.tld%252Foutpost.goauthentik.io%252Fcallback%253FX-authentik-auth-callback%253Dtrue%26response_type%3Dcode%26scope%3Dprofile%2Bopenid%2Bemail%2Bak_proxy%26state%3Dxxx`

4. 200 OK;
`https://login.domain.tld/if/flow/default-authentication-flow/?next=%2Fapplication%2Fo%2Fauthorize%2F%3Fclient_id%3Dxxx%26redirect_uri%3Dhttps%253A%252F%252Fwhoami2.domain.tld%252Foutpost.goauthentik.io%252Fcallback%253FX-authentik-auth-callback%253Dtrue%26response_type%3Dcode%26scope%3Dprofile%2Bopenid%2Bemail%2Bak_proxy%26state%3Dxxx`

If I attempt to visit `https://whoami2.domain.tld` at this point, I still end up at the same spot with 404 Not found. However, if I just add a single letter to the URL at this point and hit enter, it suddenly works.

Change;
`https://whoami2.domain.tld/outpost.goauthentik.io/callback?X-authentik-auth-callback=true&code=xxx&state=xxx`

to;
`https://whoami2.domain.tld/outpost.gooauthentik.io/callback?X-authentik-auth-callback=true&code=xxx&state=xxx`

(adding a second "o" to "goauthentik")

This results in the browser not receiving the initial 404 Not found, but rather the following;

1. 302 Temp redirect;
`https://whoami2.domain.tld/outpost.gooauthentik.io/callback?X-authentik-auth-callback=true&code=xxx&state=xxx`

2. 200 OK;
`https://whoami2.domain.tld/`

Every new refresh results in 200 OK, and everything seems to work.

**Relevant infos**
<details>
<summary>docker-compose.yml on docker1</summary>
<br>

```
version: '2.1'

services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: "traefik:latest"
    restart: ${RESTART}
    environment:
      TZ: ${TZ}
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_BASE}/traefik:/etc/traefik
      - /srv/letsencrypt/webssl:/certs:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: Host(`traefik1.${DOMAIN_NAME}`)
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: authentik@docker
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik-auth.entrypoints: websecure
      traefik.http.routers.traefik-auth.rule: Host(`traefik1.${DOMAIN_NAME}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.traefik-auth.tls: true
      traefik.http.routers.traefik-auth.service: authentik-server-web

  whoami:
    container_name: whoami
    hostname: whoami
    image: traefik/whoami:latest
    restart: ${RESTART}
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami1.${DOMAIN_NAME}`)
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.middlewares: authentik@docker
      traefik.http.routers.whoami-auth.entrypoints: websecure
      traefik.http.routers.whoami-auth.rule: Host(`whoami1.${DOMAIN_NAME}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.whoami-auth.tls: true
      traefik.http.routers.whoami-auth.service: authentik-server-web

  authentik-server:
    container_name: authentik-server
    hostname: authentik-server.local
    image: ghcr.io/goauthentik/server:latest
    restart: ${RESTART}
    depends_on:
      - authentik-sql
      - authentik-redis
      - authentik-geoip
    command: server
    environment:
      TZ: UTC
    env_file:
      - .env
    expose:
      - 9000
      - 9443
    volumes:
      - ${CONFIG_BASE}/authentik/media:/media
      - ${CONFIG_BASE}/authentik/templates:/templates
      - ${CONFIG_BASE}/authentik-geoip:/geoip
    labels:
      traefik.enable: true
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.rule: Host(`${AUTHENTIK_HOST}`)
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.service: authentik-server-web
      traefik.http.services.authentik-server-web.loadbalancer.server.port: 9443
      traefik.http.services.authentik-server-web.loadbalancer.server.scheme: https
      traefik.http.middlewares.authentik.forwardauth.address: https://authentik-server:9443/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.tls.insecureSkipVerify: true
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

  authentik-worker:
    container_name: authentik-worker
    hostname: authentik-worker.local
    image: ghcr.io/goauthentik/server:latest
    restart: ${RESTART}
    depends_on:
      - authentik-sql
      - authentik-redis
      - authentik-geoip
    command: worker
    environment:
      TZ: UTC
    env_file:
      - .env
    user: root
    volumes:
      - ${CONFIG_BASE}/authentik/media:/media
      - ${CONFIG_BASE}/authentik/certs:/certs
      - ${CONFIG_BASE}/authentik/templates:/templates
      - ${CONFIG_BASE}/authentik-geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock:ro

  authentik-sql:
    container_name: authentik-sql
    hostname: authentik-sql
    image: postgres:12-alpine
    restart: ${RESTART}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${AUTHENTIK_POSTGRESQL__USER}
      POSTGRES_DB: ${AUTHENTIK_POSTGRESQL__NAME}
      POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
    volumes:
      - ${CONFIG_BASE}/authentik-sql/postgres:/var/lib/postgresql/data

  authentik-redis:
    container_name: authentik-redis
    hostname: authentik-redis
    image: redis:alpine
    restart: ${RESTART}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

  authentik-geoip:
    container_name: authentik-geoip
    hostname: authentik-geoip
    image: "maxmindinc/geoipupdate:latest"
    restart: ${RESTART}
    environment:
      TZ: ${TZ}
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
    volumes:
      - ${CONFIG_BASE}/authentik-geoip:/usr/share/GeoIP

networks:
  default:
    external: true
    name: docker1

```

</details>

<details>
<summary>.env file on docker1</summary>
<br>

```
TZ=Europe/Oslo
RESTART=unless-stopped
DOMAIN_NAME=domain.tld
RESOLV_CONF=/srv/docker/docker1/dns/data/resolv.conf
CONFIG_BASE=/srv/docker/docker1/web/data
AUTHENTIK_HOST=login.${DOMAIN_NAME}
AUTHENTIK_HOST_BROWSER=${AUTHENTIK_HOST}
AUTHENTIK_PORT_HTTP=9000
AUTHENTIK_PORT_HTTPS=9443
AUTHENTIK_GEOIP=/geoip/GeoLite2-City.mmdb
AUTHENTIK_AUTHENTIK__GEOIP=/geoip/GeoLite2-City.mmdb
AUTHENTIK_EMAIL__HOST=smtp.${DOMAIN_NAME}
AUTHENTIK_EMAIL__PORT=587
AUTHENTIK_EMAIL__USE_TLS=true
AUTHENTIK_EMAIL__USE_SSL=false
AUTHENTIK_EMAIL__TIMEOUT=10
AUTHENTIK_EMAIL__FROM="${AUTHENTIK_HOST} <noreply@${DOMAIN_NAME}>"
AUTHENTIK_ERROR_REPORTING__ENABLED=false
AUTHENTIK_LOG_LEVEL=debug
AUTHENTIK_POSTGRESQL__HOST=authentik-sql
AUTHENTIK_POSTGRESQL__USER=authentik
AUTHENTIK_POSTGRESQL__NAME=authentik
AUTHENTIK_POSTGRESQL__PASSWORD=secret
AUTHENTIK_REDIS__HOST=authentik-redis
AUTHENTIK_SECRET_KEY=secret
GEOIPUPDATE_ACCOUNT_ID=12345
GEOIPUPDATE_LICENSE_KEY=secret

```

</details>

<details>
<summary>docker-compose.yml on docker2</summary>
<br>

```
version: '2.1'

services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: "traefik:latest"
    restart: ${RESTART}
    environment:
      TZ: ${TZ}
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_BASE}/traefik:/etc/traefik
      - /srv/letsencrypt/webssl:/certs:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: Host(`traefik2.${DOMAIN_NAME}`)
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: authentik@docker
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik-auth.entrypoints: websecure
      traefik.http.routers.traefik-auth.rule: Host(`traefik2.${DOMAIN_NAME}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.traefik-auth.tls: true
      traefik.http.routers.traefik-auth.service: login.domain.tld@file
      traefik.http.middlewares.authentik.forwardauth.address: https://login.domain.tld/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

  whoami:
    container_name: whoami
    hostname: whoami
    image: traefik/whoami:latest
    restart: ${RESTART}
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami2.${DOMAIN_NAME}`)
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.middlewares: authentik@docker
      traefik.http.routers.whoami-auth.entrypoints: websecure
      traefik.http.routers.whoami-auth.rule: Host(`whoami2.${DOMAIN_NAME}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.whoami-auth.tls: true
      traefik.http.routers.whoami-auth.service: login.domain.tld@file

networks:
  default:
    external: true
    name: authdns3

```

</details>

<details>
<summary>.env file on docker2</summary>
<br>

```
TZ=Europe/Oslo
RESTART=unless-stopped
DOMAIN_NAME=domain.tld
RESOLV_CONF=/srv/docker/docker2/dns/data/resolv.conf
CONFIG_BASE=/srv/docker/docker2/web/data

```

</details>

<details>
<summary>traefik service on docker2</summary>
<br>

```
http:
  services:
    login.domain.tld:
      loadBalancer:
        servers:
          - url: https://login.domain.tld

```

</details>

<details>
<summary>traefik entrypoints on docker1</summary>
<br>

```
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - "<public-ipv6-address>" # docker2/traefik2.domain.tld
        - "<public-ipv4-address>" # docker2/traefik2.domain.tld
  traefik:
    address: :8080

```

</details>

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**
-   authentik version: 2023.8.2
-   Deployment: docker-compose

**Additional context**
N/A
