### ISSUE TITLE
forwardAuth traefik app specific not working when using more than one app

### ISSUE THREAD

**Issue by RogerSik** [goauthentik/authentik#6961]
**Describe your question/**
When using forwardAuth in traefik it is working fine with one app. But when im adding a second app following error message I get on the apps in browser:

```
{
    "Message": "no app for hostname",
    "Host": "login.example.org",
    "Detail": "Check the outpost settings and make sure 'login.example.org' is included."
}
```

I try it with the embedded proxy and with an own added proxy outpust. With both it is working fine with only one assigned app. But with more than 2 it makes problems. I followed the authentik docs. 

**Relevant infos**
Using Authentik 2023.8 in Kubernets (K3S) with helm installed traefik and authentik official helm charts.

**Screenshots**

![23_22-00-55](https://github.com/goauthentik/authentik/assets/165814/3fbd7952-d62f-47cc-b3d0-eab198ae21f2)

Feel free to ask for more informations Im little confused after long troubleshooting. I anonymized my domain with example.org in this issue here (but is nothing really to hide it).

authentik IngressRoute (i also tried it with integrated ingress setup from authentik helm chart same result)
```
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`login.example.org`)
      priority: 10
      services:
        - name: authentik
          port: 80
  tls:
    certResolver: letsencrypt
    domains:
      - main: example.org
        sans:
          - "*.example.org"
```
paperless app specific forwardAuth (calibreweb same only with calibre-test.example.org as domain)
```
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-forwardauth
  namespace: paperless
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless-test.example.org`)
      kind: Rule
      services:
        - name: paperless
          port: 8000
      priority: 10
      middlewares:
        - name: authentik
          namespace: authentik
    - kind: Rule
      match: "Host(`paperless-test.example.org`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-proxy-forwardauth-app
          namespace: authentik
          port: 9000
  tls:
    certResolver: letsencrypt
    domains:
      - main: example.org
        sans:
          - "*.example.org"

```

authentik traefik middleware
```
# https://goauthentik.io/docs/providers/proxy/server_traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentik
  namespace: authentik
spec:
  forwardAuth:
    address: https://login.example.org/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
      - X-authentik-jwt
      - X-authentik-meta-jwks
      - X-authentik-meta-outpost
      - X-authentik-meta-provider
      - X-authentik-meta-app
      - X-authentik-meta-version
```

Note there that i tried here as address following:

* https://login.example.org/outpost.goauthentik.io/auth/traefik 
* http://ak-outpost-authentik-embedded-outpost:9000
* http://ak-outpost-proxy-forwardauth-app:9000 (own created outpost)

but everywhere same result.

**Comment by RogerSik** [comment]
Its was really simple. After i set traefik and authentik on DEBUG level I saw that traefik has problems to reach the internal service because of my "hostnetwork: true" on traefik. Nslookup was failing. 

After setting the traefik helm values:
```
  values:
    deployment:
      dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
```

it works fine for me.
