### ISSUE TITLE
allow a custom outpost port mapping override via outpost config

### ISSUE THREAD

**Issue by ayushin** [goauthentik/authentik#7373]
I would like to be able to provide custom ports mapping to an outpost so that the mapping is not done via 0.0.0.0

It would be great to have an option for `docker_ports` dict to override the generic `docker_map_ports`

https://github.com/goauthentik/authentik/blob/99f44ea805bc4fcd1bc1c43100d4bcd57606d979/authentik/outposts/controllers/docker.py#L206

**Comment by M-Davies** [comment]
@BeryJu Unfortunately, even if you specify a network, it will still listien on all mappings. This outpost config:
```yml
log_level: info
docker_labels: null
authentik_host: https://<OMITTED>/
docker_network: homelab
container_image: null
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: ""
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: false
kubernetes_json_patches: null
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_ingress_class_name: null
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```
...creates a container that is not bound to that docker network:
```
$ docker ps -a | grep 636
5404d77fa66e   ghcr.io/goauthentik/ldap:2024.2.2                    "/ldap"                  8 weeks ago      Up 2 days (healthy)         9300/tcp, 0.0.0.0:389->3389/tcp, :::389->3389/tcp, 0.0.0.0:636->6636/tcp, :::636->6636/tcp                                                                                                               ak-outpost-authentik-ldap-outpost
```
