### ISSUE TITLE
Manual/Integrated Outpost: error="undefined response type"

### ISSUE THREAD

**Issue by ggianfran** [goauthentik/authentik#7624]
**Describe the bug**

When trying to set up a LDAP outpost using the docker integration i keep getting this error on the outpost container:
`level=error event="Failed to fetch outpost configuration, retrying in 3 seconds" error="undefined response type" logger=authentik.outpost.ak-api-controller`

I have also tried to set up an integrated Proxy outpost and a manual LDAP outpost (using docker-compose) with the same results. No errors are being logged on the authentik server.
Setting `authentik_host_insecure` to either `true` or `false` does not seem to have an effect on this behaviour.

The created outpost container is added to the same docker network as the authentik server and I can ping the authentik server from within the container. 

I have also tried to set the `authentik_host` to the container name and with `authentik_host_insecure: true` . This resulted in the same error on the outpost container side, but the authentik server now gives the following error:
```
ERR event=Invalid HTTP_HOST header: 'authentik_server'. The domain name provided is not valid according to RFC 1034/1035. exception=[{"exc_type":"DisallowedHost","exc_value":"Invalid HTTP_HOST header: 'authentik_server'. The domain name provided is not valid according to RFC 1034/1035.","frames":[{"filename":"/ak-root/venv/lib/python3.11/site-packages/django/core/handlers/exception.py","line":"","lineno":55,"locals":{"exc":"'DisallowedHost(\"Invalid HTTP_HOST header: \\'authentik_server\\'. The domain name pr'+49","get_response":"<authentik.core.middleware.RequestIDMiddleware object at 0x7f3c45a81990>","request":"<ASGIRequest: GET '/api/v3/outposts/instances/'>"},"name":"inner"},{"filename":"/authentik/core/middleware.py","line":"","lineno":59,"locals":{"request":"<ASGIRequest: GET '/api/v3/outposts/instances/'>","request_id":"4eedf10687c542e6836ed36f2876e896","self":"<authentik.core.middleware.RequestIDMiddleware object at 0x7f3c45a81990>"},"name":"__call__"},{"filename":"/ak-root/venv/lib/python3.11/site-packages/django/http/request.py","line":"","lineno":150,"locals":{"allowed_hosts":"['*']","domain":"","host":"authentik_server","msg":"\"Invalid HTTP_HOST header: 'authentik_server'. The domain name provided is not va\"+31","port":"","self":"<ASGIRequest: GET '/api/v3/outposts/instances/'>"},"name":"get_host"}],"is_cause":false,"syntax_error":null}] logger=django.security.DisallowedHost timestamp=1700396804.6573462
```

When setting  `authentik_host` to the container name and running with  `authentik_host_insecure: false` I get the following error on the outpost container:
```
ERR error=Get "https://authentik_server/api/v3/outposts/instances/": tls: failed to verify certificate: x509: certificate signed by unknown authority event=Failed to fetch outpost configuration, retrying in 3 seconds logger=authentik.outpost.ak-api-controller timestamp=2023-11-19T12:35:57Z
```

**To Reproduce**

1. Create outpost with Local Docker connection of type LDAP
2. Using following outpost configuration:
```
authentik_host: https://auth.domain.tld/
authentik_host_insecure: true
authentik_host_browser: ""
log_level: debug
object_naming_template: ak-outpost-%(name)s
container_image: null
docker_network: proxy_network
docker_map_ports: true
docker_labels: null
kubernetes_replicas: 1
kubernetes_namespace: default
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
kubernetes_ingress_class_name: null
kubernetes_service_type: ClusterIP
kubernetes_disabled_components: []
kubernetes_image_pull_secrets: []
kubernetes_json_patches: null
```
3. Created docker container outputs: `level=error event="Failed to fetch outpost configuration, retrying in 3 seconds" error="undefined response type" logger=authentik.outpost.ak-api-controller`

**Expected behavior**
Outpost showing green health status

**Logs**
Logs of created outpost container:
```
DBG event=Loaded config path=inbuilt-default timestamp=2023-11-19T12:11:14Z
DBG event=Loaded config from environment timestamp=2023-11-19T12:11:14Z
INF event=not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it. logger=authentik.go_debugger timestamp=2023-11-19T12:11:14Z
ERR error=undefined response type event=Failed to fetch outpost configuration, retrying in 3 seconds logger=authentik.outpost.ak-api-controller timestamp=2023-11-19T12:11:14Z
ERR error=undefined response type event=Failed to fetch outpost configuration, retrying in 3 seconds logger=authentik.outpost.ak-api-controller timestamp=2023-11-19T12:11:17Z
ERR error=undefined response type event=Failed to fetch outpost configuration, retrying in 3 seconds logger=authentik.outpost.ak-api-controller timestamp=2023-11-19T12:11:20Z
```

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.10.3](https://goauthentik.io/docs/releases/2023.10)
-   Deployment: docker-compose, using traefik as reverse proxy

**Additional context**

Authentik env:
```
PUID=1000
PGID=1000
TZ=Europe/Amsterdam
DOMAIN=domain.tld 

POSTGRES_DB=/run/secrets/authentik_postgresql_db
POSTGRES_USER=/run/secrets/authentik_postgresql_user
POSTGRES_PASSWORD=/run/secrets/authentik_postgresql_password

AUTHENTIK_REDIS__HOST=redis

AUTHENTIK_POSTGRESQL__HOST=authentik_postgres
AUTHENTIK_POSTGRESQL__NAME=$POSTGRES_DB
AUTHENTIK_POSTGRESQL__USER=$POSTGRES_USER
AUTHENTIK_POSTGRESQL__PASSWORD=$POSTGRES_PASSWORD

AUTHENTIK_ERROR_REPORTING__ENABLED="false"
AUTHENTIK_SECRET_KEY=/run/secrets/authentik_secret_key
AUTHENTIK_COOKIE_DOMAIN=$DOMAIN

AUTHENTIK_LISTEN__HTTP=0.0.0.0:80
AUTHENTIK_LISTEN__HTTPS=0.0.0.0:443
AUTHENTIK_LISTEN__LDAP=0.0.0.0:389
AUTHENTIK_LISTEN__LDAPS=0.0.0.0:636
```

Docker compose for the server and worker:
```
authentik_server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik_server
    restart: unless-stopped
    command: server
    networks:
      - proxy_network
    depends_on:
      - authentik_postgres
      - authentik_redis
    user: "1000:1000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$DOCKERDIR/authentik/data/media:/media"
      - "$DOCKERDIR/authentik/data/custom-templates:/templates"
      - "$DOCKERDIR/authentik/data/geoip:/geoip"
    env_file:
      - .env
    secrets:
      - authentik_postgresql_db
      - authentik_postgresql_user
      - authentik_postgresql_password
      - authentik_notifier_smtp_password
      - authentik_secret_key
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authentik-rtr.rule=Host(`auth.$DOMAIN`)"
      - "traefik.http.routers.authentik-rtr.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr.tls=true"
      - "traefik.http.routers.authentik-rtr.tls.certresolver=letsencrypt"
      ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)  
      - "traefik.http.routers.authentik-rtr-outpost.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.$DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-rtr-outpost.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr-outpost.tls=true"
      - "traefik.http.routers.authentik-rtr-outpost.tls.certresolver=letsencrypt"
      ## HTTP Services
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadBalancer.server.port=80"


  authentik_worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik_worker
    restart: unless-stopped
    command: worker
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$DOCKERDIR/authentik/data/custom-templates:/templates"
      - "$DOCKERDIR/authentik/data/media:/media"
      - "$DOCKERDIR/authentik/data/certs:/certs"
      - "$DOCKERDIR/authentik/data/geoip/data:/geoip"
    user: root
    secrets:
      - authentik_postgresql_db
      - authentik_postgresql_user
      - authentik_postgresql_password
      - authentik_notifier_smtp_password
      - authentik_secret_key
    env_file:
      - .env
    depends_on:
      - authentik_postgres
      - authentik_redis
 ```
