### ISSUE TITLE
default-authentication-flow sidebar layout misaligned on small screens

### ISSUE THREAD

**Issue by Corban-Lee** [goauthentik/authentik#7735]
**Describe the bug**
The sidebar left and sidebar right styles are misaligned under the default-authentication-flow so that on smaller screens (including all mobile devices), the top of the sidebar is cut off, and there is no background to the bottom of the sidebar.

**To Reproduce**

1. Go to flows
2. Click on default-authentication-flow > edit
3. Scroll down to Appearance Settings
4. Set layout to sidebar left or sidebar right
5. Logout and view the flow.

**Expected behavior**
The sidebar background spans the height of the page, is behind all elements of the sidebar, and any off screen elements are reachable via scrolling.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/77944149/c2ba545d-d058-42ee-b812-5404e55e0f96)

**Logs**
N/a because this is a stylesheet issue

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.4
-   Deployment: docker-compose

**Solution**
Update the sidebar element at `.pf-c-login.sidebar_left.ak-flow-executor .ak-login-container.ak-flow-executor, .pf-c-login.sidebar_right.ak-flow-executor .ak-login-container.ak-flow-executor` 
Change the style to use:
```
height: fit-content;
min-height: 100vh;
```

**Comment by Corban-Lee** [comment]
Apologies in advance for botching the terminology, I know this affects any flow where this can be changed, but I'm new to Authentik so I'm unsure what this layout part's parent is called.

**Comment by asifbacchus** [comment]
Incorporating previously suggested changes, would be nice to see:

```css
ak-flow-executor {
    height: 100%;
    overflow: auto;
    position: fixed;
    width: 100%;
}

.pf-c-login.sidebar_left .ak-login-container,
.pf-c-login.sidebar_right .ak-login-container {
    height: 100%;
    min-height: 100vh;
}
```

Changes to the `ak-flow-executor` would resolve an annoyance where the page scrolls a little-bit on the downside despite everything being `100vh` tall. Currently, the parent (`ak-flow-executor`) is `inline` and thus, peeks out at the bottom. Or, at least, this is my experience.

Currently, these changes an be applied in `custom.css`, but having them as defaults would be awesome.
