### ISSUE TITLE
Make https listener (9443) optional

### ISSUE THREAD

**Issue by MarcelCoding** [goauthentik/authentik#7836]
**Is your feature request related to a problem? Please describe.**
If you are deploying authentik using a reverse proxy, there is no point in having a https listener running ad the revers epoxy is taking care of all https related things.

**Describe the solution you'd like**
Two posible solutions:
- Add an option to disable the https layer.
- Make the https listen address nullable. 

**Describe alternatives you've considered**
Just ignoring the additional port. But thats not that clean.

**Comment by Fredouye** [comment]
Hi

this is not a "solution" to your request, but as I'm using authentik behind a Traefik reverse proxy, I use this in the `docker-compose.override.yml` :

```yaml
services:
  server:
    networks:
      - authentik
      - traefik
    ports: !reset []
    labels:
      traefik.enable: "true"
      [...]
```

Using this, no authentik port is exposed on the Docker host.
