### ISSUE TITLE
Custom React App Forward Auth Proxy Provider JWT kubernetes nginx ingress 

### ISSUE THREAD

**Issue by mwx23** [goauthentik/authentik#7973]
**Describe your question/**

I'd like to receive the Authentik headers `X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid` in a custom React app deployed at `app.domain.tld` as a static site in an nginx container deployed within kubernetes that talks to `api.domain.tld`.

My goal is to use Authentik as SSO and have the app pass the `Authoization: Bearer $JWT` to the `api.domain.tld` endpoint.

**Relevant infos**
I've deployed Authentik  at `auth.domain.tld`.

My app is deployed at `app.domain.tld` and my API at `api.domain.tld`.

The API part isn't so much an issue at the moment as I can't get my app to receive the Authentik headers.

I've created an Application for the App.

I've created a Forward Auth Provider. What I'm confused about here is do I create a new Outpost or use the Embedded one. 

The documentation seems to say I should create a new Ingress myself (outside of Authentik), however if I create a new Outpost it sets up the Ingress for me and I can add Nginx annotations but I end up getting 500 errors from the backend.

Forward Auth Proxy Provider:
  External Host: https://app.domain.tld

This is an example Ingress that I've tried to piece together from various other issues:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost-app
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-authentik-embedded-outpost.production.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://app.domain.tld/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      auth_request_set $authentik_username $upstream_http_x_authentik_username;
      auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
      auth_request_set $authentik_email $upstream_http_x_authentik_email;
      auth_request_set $authentik_name $upstream_http_x_authentik_name;
      auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
      proxy_set_header X-authentik-username $authentik_username;
      proxy_set_header X-authentik-groups $authentik_groups;
      proxy_set_header X-authentik-email $authentik_email;
      proxy_set_header X-authentik-name $authentik_name;
      proxy_set_header X-authentik-uid $authentik_uid;
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header       Set-Cookie $auth_cookie;
spec:
  rules:
    - host: app.domain.tld
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-authentik-embedded-outpost
                port:
                  number: 9000
  #          - path: /
  #            pathType: Prefix
  #            backend:
  #              service:
  #                name: app
  #                port:
  #                  name: http
  tls:
    - hosts:
        - app.domain.tld
      secretName: tls-app-domain-tld
```

I've tried adding the nginx snippets to the Embedded and a new Outpost but neither work.

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.4
-   Deployment: helm

**Additional context**
