### ISSUE TITLE
authentik will not recognize/import/utilize valid letsencrypt cert key pair.

### ISSUE THREAD

**Issue by sudoshi** [goauthentik/authentik#7984]
Latest version of authentik does not properly import and utilize letsencrypt SSL certs even after explicitly following the documenation:

**To Reproduce**

Use certbot to create valid cert key pair.  Navigate to /etc/letsencrypt/live/yoursite.com
Find:
privkey.pem
chain.pem
cert.pem
fullchain.pem

In docker compose:

```
 worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.5}
    container_name: authentik-worker
    restart: always
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - /etc/letsencrypt/live/yoursite.com:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
```

**Expected behavior**

Upon docker compose down and docker compose up -d, authentik should recognize the valid cert key pair and import/utilize for the FQDN instead of its own self-signed cert.

**Screenshots**
![Screenshot 2023-12-23 at 10 44 21 PM](https://github.com/goauthentik/authentik/assets/100962480/83e9e2ae-cf9f-4274-ab0f-52416e8fc956)

![Screenshot 2023-12-23 at 10 44 41 PM](https://github.com/goauthentik/authentik/assets/100962480/f92bb205-420f-4ea0-8974-30041e1a7b8e)

Manual import attempted per documentation (https://goauthentik.io/docs/core/certificates#external-certificates)
**Logs**
```
sudo docker exec -it authentik-worker /bin/bash
root@6b8fe71bb74f:/# cd certs
root@6b8fe71bb74f:/certs# ls
cert2.pem  fullchain2.pem  privkey2.pem
root@6b8fe71bb74f:/certs# ak import_certificate --certificate /certs/fullchain2.pem --private-key /certs/privkey2.pem --name sandbox
/ak-root/venv/bin/python: No module named manage
root@6b8fe71bb74f:/certs# cd ..
root@6b8fe71bb74f:/# ak import_certificate --certificate /certs/fullchain2.pem --private-key /certs/privkey2.pem --name sandbox
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389169.3249285, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389169.3251684, "count": 7}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1102977, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1110342, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1114812, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.112339, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1135135, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1147192, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1154933, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1158755, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1162565, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.117577, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1203036, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1703389171.120431, "version": "2023.10.5"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1703389171.1212518}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703389171.1215167, "path": "authentik.enterprise.settings"}
{"event": "Loaded GeoIP database", "last_write": 1703165606.0, "level": "info", "logger": "authentik.events.geo", "pid": 154, "timestamp": "2023-12-24T03:39:31.886890"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 154, "task_id": "51018223518d481c999ad4fa8ca6fb0b", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-12-24T03:39:32.675991"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 154, "task_id": "a5bf9295eec0482081c088e7aaa0f8f0", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-12-24T03:39:32.677396"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 154, "task_id": "5f7783944a09435391e02294903203af", "task_name": "authentik.outposts.tasks.outpost_post_save", "timestamp": "2023-12-24T03:39:33.206668"}
root@6b8fe71bb74f:/#
```
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5]
-   Deployment: docker-compose

**Additional context**
I have authentik running with letsencrypt certificates on another development box with no issues, and I followed the exact same instructions.  So I am flumoxed.

**Comment by Lilneo786** [comment]
Modify Authentik Configuration: To utilize the imported certificate and key, you must edit the Authentik configuration. 

Refer to the Authentik documentation or configuration files for TLS/HTTPS settings options. You will need to specify the file paths for the imported certificate and private key, along with other relevant settings.

Restart Authentik: Once you have made the necessary configuration changes, restart the Authentik service or container. This will ensure that Authentik can utilize the imported certificate and key for secure connections.

**Comment by sudoshi** [comment]
> Modify Authentik Configuration: To utilize the imported certificate and key, you must edit the Authentik configuration.
> 
> Refer to the Authentik documentation or configuration files for TLS/HTTPS settings options. You will need to specify the file paths for the imported certificate and private key, along with other relevant settings.
> 
> Restart Authentik: Once you have made the necessary configuration changes, restart the Authentik service or container. This will ensure that Authentik can utilize the imported certificate and key for secure connections.

Not useful at all.  I have done all the above numerous times.

**Comment by mablerf** [comment]
I'm having similar problem. I found a work around that I'm not a fan of, but if it works it works. In the volumes I added mounting the archive folder as well so letsencrypts sym links exist in the container.

```
volumes:
- /etc/letsencrypt/live/yoursite.com:/certs/yoursite.com
- /etc/letsencrypt/archive/yoursite.com:/archive/yoursite.com
```

Given that there's documentation about setting up a certbot container to generate the certificates, I honestly expected the auto discovery of certificates to account for the way certbot sets up the files/paths/links. This does end up successfully discovering the certificate with private key for yoursite.com, but it also makes clutter entries for cert and chain. (according to the documentation it should group everything in the yoursite.com directory together.

This also causes a huge pain in the ass as far as the Outpost Integrations -> Local Docker connection. Apparently that requires the worker container to have user: root, but if you have that in the compose the container gets stuck in a never ending "can't chown ./cert files". Change the compose to user: 1000:1000 and the thing will start up and find the certs, but the local docker connection doesn't work. 

If you have to manually fiddle with the certificate files every 90 days when you renew, what's the point of auto renew and auto discovery?

**Comment by mablerf** [comment]
Also, when I did not mount my letscencrypt cert volume, and had the worker user: root, I was able to successfully have authentik outpost create the ldap container, but any attempt at using letsencrypt certificates all I was getting is root ca errors. I've fiddled with a lot of different configurations to resolve this issue, but currently up and working happily with the letsencrypt certificates was manually creating the LDAP outpost, as described here https://goauthentik.io/docs/outposts/manual-deploy-docker-compose#ldap-outpost.

```
ldap:
image: ghcr.io/goauthentik/ldap
networks:
  - authentik
ports:
  - 389:3389
  - 636:6636
environment:
  AUTHENTIK_HOST: https://authentik.yoursite.com:443
  AUTHENTIK_INSECURE: true
  AUTHENTIK_TOKEN: token-generated-by-authentik
  TIME_ZONE: America/New_York
  AUTHENTIK_DEBUG: true
volumes:
  - /etc/localtime:/etc/localtime
  - /etc/ssl/certs:/etc/ssl/certs # <-- this is for the root ca issue, use the hosts root CAs
  - /mnt/letsencrypt/live/yoursite.com:/certs/yoursite.com
  - /mnt/letsencrypt/archive/yoursite.com:/archive/yoursite.com
 ```

Using this in the Outpost Configuration. The take note of the container_image and object_naming_template
```
log_level: info
docker_labels: null
authentik_host: https://authentik.yoursite.com:443/
docker_network: authentik
container_image: authentik-ldap-1
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: ""
object_naming_template: authentik-%(name)-1
authentik_host_insecure: false
kubernetes_json_patches: null
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_ingress_class_name: null
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```
