### ISSUE TITLE
Grafana Redirect URI Error

### ISSUE THREAD

**Issue by Ingener74** [goauthentik/authentik#8673]
**Describe the bug**
Hi. I tried to connect Grafana to Authentik and I have a problem, "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)." 
I use [this](https://goauthentik.io/integrations/services/grafana/) instruction.

**To Reproduce**
My installation of Grafana. 
Docker compose for Grafana
```
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_DEFAULT_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_DEFAULT_PASSWORD
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    env_file:
      - .env
```
.env for Grafana
```
GF_AUTH_GENERIC_OAUTH_ENABLED=true
GF_AUTH_GENERIC_OAUTH_NAME=authentik
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=tU1tdZwzs62Hrm1TonnQLKS6FmRT8JL5gm9*****
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=OpFrGdo2Ia******** 
GF_AUTH_GENERIC_OAUTH_SCOPES="openid profile email"
GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.<here was my domain>/application/o/authorize/
GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.<here was my domain>/application/o/token/
GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.<here was my domain>/application/o/userinfo/
GF_AUTH_SIGNOUT_REDIRECT_URL=https://auth.<here was my domain>/application/o/grafana/end-session/
# Optionally enable auto-login (bypasses Grafana login screen)
GF_AUTH_OAUTH_AUTO_LOGIN=true
# Optionally map user groups to Grafana roles
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
```

**Expected behavior**
Authentik redirect to Grafana

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/3167594/6d68be90-8b52-40cd-9c61-c4320fe657f3)
![image](https://github.com/goauthentik/authentik/assets/3167594/d321b60c-3f13-4996-b49a-ccb3f30790ce)

**Version and Deployment (please complete the following information):**
-   my authentik version: 2024.2.1
-   Deployment: 
```
➜  homelab docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
➜  homelab docker compose version
Docker Compose version v2.21.0
```

**Comment by Ingener74** [comment]
Data from authentik_providers_oauth2_oauth2provider table in my postgresql instance
[authentik_providers_oauth2_oauth2provider.csv](https://github.com/goauthentik/authentik/files/14392995/authentik_providers_oauth2_oauth2provider.csv)

**Comment by alhazmy13** [comment]
same issue

**Comment by Ingener74** [comment]
@alhazmy13 thank you. Add GF_SERVER_ROOT_URL is a solution!

**Comment by excaliburzarau** [comment]
> I suspect that Grafana is being operated behind a reverse proxy. If that's the case, you should update the Grafana container by adding the following environment variable.
> 
> ```
>     GF_SERVER_ROOT_URL: "https://grafana.domain.com"
> ```
> 
> Additionally, if you encounter an infinite loop or receive an error indicating that Grafana cannot retrieve the token, please update the two environment variables listed below. Use the local IP address of Authentik instead of the public domain
> 
> ```
>     GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://127.0.0.1:380/application/o/token/"
>     GF_AUTH_GENERIC_OAUTH_API_URL: "http://127.0.0.1:380/application/o/userinfo/"
> ```

This solution worked for me. Thank you

**Comment by sutekisunday** [comment]
> I suspect that Grafana is being operated behind a reverse proxy. If that's the case, you should update the Grafana container by adding the following environment variable.
> 
> ```
>     GF_SERVER_ROOT_URL: "https://grafana.domain.com"
> ```

This has worked for me too. Thanks!

**Comment by gabrielcosi** [comment]
> I suspect that Grafana is being operated behind a reverse proxy. If that's the case, you should update the Grafana container by adding the following environment variable.
> 
> ```
>     GF_SERVER_ROOT_URL: "https://grafana.domain.com"
> ```
> 
> Additionally, if you encounter an infinite loop or receive an error indicating that Grafana cannot retrieve the token, please update the two environment variables listed below. Use the local IP address of Authentik instead of the public domain
> 
> ```
>     GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://127.0.0.1:380/application/o/token/"
>     GF_AUTH_GENERIC_OAUTH_API_URL: "http://127.0.0.1:380/application/o/userinfo/"
> ```

I am having the same issue but I am deploying both authentik and grafana with kubernetes. Adding the root_url causes an infinite loop and does not login at all. I have tried to replace the domain with the service but it doesn't work either.

I get a lot of `logger=authn.service t=2025-04-06T12:45:24.502387994Z level=warn msg="Failed to authenticate request" client=auth.client.session error="user token not found"`

My helm values:

```yaml
grafana.ini:
  server:
    root_url: https://grafana.<my_domain>
  analytics:
    check_for_updates: false
    check_for_plugin_updates: false
    reporting_enabled: false
  security:
    angular_support_enabled: true
    cookie_secure: true
  date_formats:
    use_browser_locale: true
  auth:
    signout_redirect_url: https://auth.<my_domain>/application/o/grafana/end-session/
    oauth_auto_login: false
  auth.generic_oauth:
    name: authentik
    enabled: true
    client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
    client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
    scopes: openid profile email
    auth_url: https://auth.<my_domain>/application/o/authorize/
    token_url: http://authentik-server.authentik.svc.cluster.local:80/application/o/token/
    api_url: http://authentik-server.authentik.svc.cluster.local:80/application/o/userinfo/
    role_attribute_path: contains(groups[*], 'Grafana Admins') && 'Admin' || 'Viewer'
```
