### ISSUE TITLE
Ldap Outpost restart loop after host reboot

### ISSUE THREAD

**Issue by Huber1** [goauthentik/authentik#8840]
**Describe the bug**
Every time i reboot my host, the ldap container is in a restart-loop until i do `docker compose down` and `docker compose up -d` again

**To Reproduce**
setup authentik with docker compose:
```yaml
---
version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.7}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.7}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

  authentik_ldap:
    image: ghcr.io/goauthentik/ldap
    # Optionally specify which networks the container should be
    # might be needed to reach the core authentik server
    # networks:
    #   - foo
    container_name: authentik_ldap
    depends_on:
      server:
        condition: service_healthy
    networks:
      - ldap
    ports:
      - 127.0.0.1:389:3389
      - 127.0.0.1:636:6636
    environment:
      AUTHENTIK_HOST: https://<myUrl>
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: <TOKEN>

volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  ldap:
    external: true
```

1. `docker compose up -d`
2. `sudo reboot now`
3. `docker ps`

**Expected behavior**
containers are like before reboot

**Logs**
output from `docker logs authentik_ldap`
[ldap.log](https://github.com/goauthentik/authentik/files/14531413/ldap.log)

**Version and Deployment (please complete the following information):**

-   authentik version: `2024.2.1`
-   Deployment: `docker-compose`

**Additional context**
This is pretty much the default docker-compose.yml file from the docs.
Only thing i modified is adding the ldap container to a network, so my application can reach the LDAP server internally (other compose file). My LDAP is not exposed to the internet.
Before rebooting, it workes as it should
I tried adding depends_on server, but this had no effect

**Comment by beamrod** [comment]
I am running into a very similar issue with the latest Authentik release (`2024.2.2`). I set up an LDAP outpost some time ago, and it worked flawlessly ever since. After updating to `2024.2.2`, the outpost is in a constant restart loop. 

However, there are some subtle differences in my deployment compared to OP:
- My LDAP outpost was deployed using the Docker integration via Authentik's web UI and not manually via entries in the `docker-compose.yml` file. 
- I noticed that after updating Authentik via Docker Compose (`2023.10.7` to `2024.2.2`), the LDAP outpost container was not updated to the latest release but remained at version `2023.10.7` (as shown in `docker ps -a`). 
- Stopping and starting the Docker Compose stack is not helping (I also tried to stop and restart the outpost container specifically). The LDAP container never reaches a healthy state and is constantly restarting.

**Comment by rissson** [comment]
The logs you provided seem to be normal. Do you have any more details about what happens when the outpost reboots? Does it just crash without any output or?

**Comment by BeryJu** [comment]
Can you try adding `restart: always` or `restart: unless-stopped` to the ldap container in your docker-compose config?

**Comment by Huber1** [comment]
Correct. The logs i posted is everything i get from the docker logs command.
I didn't get the issue after doing some steps:
1. updating authentik images to `2024.2.2`
2. adding `restart: unless-stopped`
3. removing `depends-on` in the ldap section
For reference, my `docker-compose.yml` now looks like this:

```yaml
version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.7}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.7}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

  authentik_ldap:
    image: ghcr.io/goauthentik/ldap:${AUTHENTIK_TAG:-latest}
    restart: unless-stopped
    container_name: authentik_ldap
    networks:
      - ldap
    ports:
      - 127.0.0.1:389:3389
      - 127.0.0.1:636:6636
    environment:
      AUTHENTIK_HOST: https://auth.huber.cloud
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: <TOKEN>
volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  ldap:
    external: true
```

my .env looks like this:
```env
AUTHENTIK_TAG=2024.2.2
PG_PASS=<PG_PASS>
AUTHENTIK_SECRET_KEY=<AUTHENTIK_SECRET_KEY>
AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL=true
```
My secrets are random strings

If I encounter this issue again, i'll give an update.
Thanks for the help
