### ISSUE TITLE
New Deployment: ERROR:  relation "authentik_tenants_tenant" does not exist at character 554

### ISSUE THREAD

**Issue by crltc** [goauthentik/authentik#8863]
**Describe the bug**
New deployment causes database errors, Authentik server and worker does not output errors. Authentik does not work.

**To Reproduce**
New Docker Compose deployment with Any version 

**Expected behavior**

**Logs**
```
2024-03-10 01:58:07.647 UTC [73] ERROR:  relation "authentik_tenants_tenant" does not exist at character 554
2024-03-10 01:58:07.647 UTC [73] STATEMENT:  SELECT "authentik_tenants_tenant"."tenant_uuid", "authentik_tenants_tenant"."schema_name", "authentik_tenants_tenant"."name", "authentik_tenants_tenant"."ready", "authentik_tenants_tenant"."avatars", "authentik_tenants_tenant"."default_user_change_name", "authentik_tenants_tenant"."default_user_change_email", "authentik_tenants_tenant"."default_user_change_username", "authentik_tenants_tenant"."event_retention", "authentik_tenants_tenant"."footer_links", "authentik_tenants_tenant"."gdpr_compliance", "authentik_tenants_tenant"."impersonation" FROM "authentik_tenants_tenant" WHERE "authentik_tenants_tenant"."ready"
```

```
2024-03-10 01:59:43.669 UTC [298] CONTEXT:  while updating tuple (0,125) in relation "authentik_flows_stage"
2024-03-10 01:59:43.669 UTC [298] STATEMENT:  UPDATE "authentik_flows_stage" SET "name" = 'default-password-change-write' WHERE "authentik_flows_stage"."stage_uuid" = '7f5e4402f83147e5a6a9f1c6342e4ec9'::uuid
2024-03-10 01:59:47.276 UTC [318] ERROR:  deadlock detected
2024-03-10 01:59:47.276 UTC [318] DETAIL:  Process 318 waits for ShareLock on transaction 2884; blocked by process 319.
	Process 319 waits for ShareLock on transaction 2887; blocked by process 318.
	Process 318: UPDATE "authentik_flows_stage" SET "name" = 'default-password-change-write' WHERE "authentik_flows_stage"."stage_uuid" = '7f5e4402f83147e5a6a9f1c6342e4ec9'::uuid
	Process 319: UPDATE "authentik_flows_stage" SET "name" = 'default-authentication-login' WHERE "authentik_flows_stage"."stage_uuid" = 'b737d524eba74177a2deb495d47ceba7'::uuid
```

**Version and Deployment (please complete the following information):**

-  Authentik version: 2024.2.2 (also tried 2024.2.1,2023.6,2022.12.1)
-  Postgres version: 16.2 (also tried 15.6, 12)
-  Deployment: [Docker via Nomad]

**Additional context**
I am not providing dedicated volume mounts for /certs /media /templates

**Comment by Meowcat285** [comment]
Same issue here when deploying

**Comment by rissson** [comment]
I just tried https://docs.goauthentik.io/docs/installation/docker-compose with postgres 16. I don't see any issue. Mind providing logs for the server and worker containers?

**Comment by crltc** [comment]
Postgres 16.2 & Authentik 2024.2.2

Authentik Environment Variables:
```
AUTHENTIK_SECRET_KEY=redacted
AUTHENTIK_REDIS__HOST=127.0.0.1
AUTHENTIK_REDIS__PORT=6379
AUTHENTIK_POSTGRESQL__HOST=127.0.0.1
AUTHENTIK_POSTGRESQL__PORT=5432
AUTHENTIK_POSTGRESQL__USER=authentik
AUTHENTIK_POSTGRESQL__NAME=authentik
AUTHENTIK_POSTGRESQL__PASSWORD=redacted
AUTHENTIK_ERROR_REPORTING__ENABLED=true
AUTHENTIK_LOG_LEVEL=debug
AUTHENTIK_PORT_HTTP=9000
AUTHENTIK_PORT_HTTPS=9443
```

Logs:
[postgres.txt](https://github.com/goauthentik/authentik/files/14565931/postgres.txt)
[server.txt](https://github.com/goauthentik/authentik/files/14565932/server.txt)
[worker.txt](https://github.com/goauthentik/authentik/files/14565933/worker.txt)

For troubleshooting, I will next try running this on bare docker rather than an orchestrator like Nomad.

**Comment by rissson** [comment]
I still am not able to replicate this. Would you mind providing the docker-compose.yml you're using?

**Comment by mmenajr** [comment]
> I still am not able to replicate this. Would you mind providing the docker-compose.yml you're using?

I am also seeing the same issue just now after performing an upgrade from 2023.10 to 2024.2.2. Not sure if the same error will be seen on a fresh install and this version did have some notes that there were some changes to how it uses postgres now.


```
Database requirement changes
authentik now uses PostgreSQL schemas other than public.

If you have a custom PostgreSQL deployment, please ensure that the authentik user is allowed to create schemas. Usually, if the authentik user is owner of the database, it already can.
```

I double checked the link you sent with instruction docs as my docker compose is set to use postgres 12, not 16, but the compose that the docs have you pull also still shows 12 as well.

Here is my compose for reference:
```
version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    container_name: authentik_postgres
    volumes:
      - /srv/authentik/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  redis:
    image: docker.io/library/redis:alpine
    container_name: authentik_redis
    command: --save 60 1 --loglevel warning
    volumes:
      - /srv/authentik/redis/data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-latest}
    container_name: authentik_server
    command: server
    volumes:
      - /srv/authentik/media:/media
      - /srv/authentik/templates:/templates
    ports:
      - 9000:9000
      - 9443:9443
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-latest}
    container_name: authentik_worker
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    # user: root
    volumes:
      - /srv/authentik/media:/media
      - /srv/authentik/certs:/certs
      - /srv/authentik/templates:/templates
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

volumes:
  database:
    driver: local
  redis:
    driver: local
```

**Comment by crltc** [comment]
To provide additional data points for troubleshooting, below is my docker-compose.yml that I tried on a bare docker install.

```
---
version: "3.4"
services:
  postgresql:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: redacted
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
  redis:
    image: docker.io/library/redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
  server:
    image: ghcr.io/goauthentik/server:2024.2.2
    restart: unless-stopped
    command: server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: redacted
      AUTHENTIK_SECRET_KEY: redacted
    ports:
      - "9000:9000"
      - "9443:9443"
  worker:
    image: ghcr.io/goauthentik/server:2024.2.2
    restart: unless-stopped
    command: worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: redacted
      AUTHENTIK_SECRET_KEY: redacted
    user: root
```
