### ISSUE TITLE
Forward Auth with Traefik showing Not Found Page

### ISSUE THREAD

**Issue by Jdplays** [goauthentik/authentik#8932]
``### Intro
I have been trying to setup Authentik to work with Traefik to authenticate users. I have followed a few guides but seem to keep hitting the same issue. I keep being shown a Not Found page that seems to have no css.

An example is vaultwarden. It works fine in Traefik by itself. However when i add this to its labels:
`- "traefik.http.routers.vaultwarden-secure.middleware=authentik@file"`
It gives this back
![image](https://github.com/goauthentik/authentik/assets/26013053/1602f71d-8a45-4f37-8787-cd73171204fb)

### Here is my setup

**Traefik version: 2.11.0**
**Authentik Version: 2024.2.2**

##### Traefik compose
``` yml
version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /nfs/traefik/data/traefik.yml:/traefik.yml:ro
      - /nfs/traefik/data/acme.json:/acme.json
      - /nfs/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.domain.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.local.domain.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.domain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.domain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[1].main=domain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.domain.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

##### Traefik config Middlewares
``` yml
middlewares:
    authentik:
      forwardauth:
        address: "http://authentik_server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```

##### Authentik Server compose
``` yml
server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    container_name: authentik_server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - /nfs/authentik/media:/media
      - /nfs/authentik/custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.entrypoints=http"
      - "traefik.http.routers.authentik.rule=Host(`auth.domain.com`)"
      - "traefik.http.middlewares.authentik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.authentik.middlewares=authentik-https-redirect"
      - "traefik.http.routers.authentik-secure.entrypoints=https"
      - "traefik.http.routers.authentik-secure.rule=Host(`auth.domain.com`)"
      - "traefik.http.routers.authentik-secure.tls=true"
      - "traefik.http.routers.authentik-secure.service=authentik"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      - "traefik.http.services.authentik-secure.loadbalancer.server.port=9443"
      - "traefik.docker.network=proxy"
```

##### Vaultwarden Compose
``` yml
version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /nfs/vaultwarden/data:/data
    networks:
      - proxy
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=http"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.domain.com`)"
      - "traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-https-redirect"
      - "traefik.http.routers.vaultwarden-secure.entrypoints=https"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`vaultwarden.domain.com`)"
      - "traefik.http.routers.vaultwarden-secure.tls=true"
      - "traefik.http.routers.vaultwarden-secure.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden-secure.middleware=authentik@file"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
```

If i go directly to `http://auth.domain.com:9000/outpost.goauthentik.io/auth/traefik` It also gives a not found page, but with css this time
![image](https://github.com/goauthentik/authentik/assets/26013053/5c221cb0-26a6-4d63-8fcd-ef93b3c577fb)

##### Application
![image](https://github.com/goauthentik/authentik/assets/26013053/6a4fff5e-be7c-4864-9a4e-3cfcfd157ec2)

##### Provider
![image](https://github.com/goauthentik/authentik/assets/26013053/164ab194-dc81-43be-8a3f-738f917619ce)

##### Outpost
![image](https://github.com/goauthentik/authentik/assets/26013053/fd332eb5-cdde-4f75-a7cd-6e717e8e6ab0)

I have been trying to fix this for the past few hours and have gotten no where. If someone knows why this is happening, any help would be appreciated.
Thanks in advance, James
