### ISSUE TITLE
Authentik and Traefik - Works, sometimes... very strange

### ISSUE THREAD

**Issue by tugdualenligne** [goauthentik/authentik#8934]
**Describe the bug**
I'm experimenting lots of issues with Authentik and Traefik (using Portaient to set it up)

Can someone share his working docker-compose, please? Mine is below but I have several issues:

1/ Authentic works fine and sometimes it is not accessible anymore, and I have to wait several hours before it works when restart the docker-compose

2/ Authentic works fine until I add Traefik labels into another container app so that Authentic can be middleware for authentication purposes. When I fire off the other container app, that app is no longer accessible, and Authentic appears to die

3/ my integration do local docker socket doesn't seem to work

**To Reproduce**
Add Traefik labels into another container app so that Authentic can be the middleware for authentication purposes. 
Then, when I fire off the other container app, that app is no longer accessible, and Authentic appears to die

**Expected behavior**
I shall be able to access the other application, or not, but at least Authentik shouldn't die

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: docker-compose

**Additional context**
My Docker compose

```
---
version: "3.9"
# version du 16/3/2024

services:
  postgresql:
    image: docker.io/library/postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database-authentik:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - stack.env
    networks:
      - authentik
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-authentik:/data
    networks:
      - authentik
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.2.2}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: ${AUTHENTIK_POSTGRESQL__HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    env_file:
      - stack.env
#    ports:
#      - "${COMPOSE_PORT_HTTP:-9005}:9005"
#      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    expose:
      - 9005
      - 9443
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authentik-rtr.rule=Host(`auth.$DOMAIN`)"
      - "traefik.http.routers.authentik-rtr.entrypoints=https"
      - "traefik.http.routers.authentik-rtr.tls=true"
      - "traefik.http.routers.authentik-rtr.tls.certresolver=du-plessis"
      ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)  
      - "traefik.http.routers.authentik-rtr-outpost.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.$DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-rtr-outpost.entrypoints=https"
      - "traefik.http.routers.authentik-rtr-outpost.tls=true"
      - "traefik.http.routers.authentik-rtr-outpost.tls.certresolver=du-plessis"
      ## HTTP Services
#      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
#      - "traefik.http.services.authentik-svc.loadBalancer.server.port=9005"
      ## essai depuis la config du Proxy
      - "traefik.http.middlewares.authentik.forwardauth.address=http://server/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version"
    depends_on:
      - postgresql
      - redis
    networks:
      - authentik
      - traefik_proxy
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.2.2}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
#    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-media:/media
      - authentik-certs:/certs
      - authentik-templates:/templates
    env_file:
      - stack.env
    depends_on:
      - postgresql
      - redis
    networks:
      - authentik
      - traefik_proxy
volumes:
  database-authentik:
    driver: local
  redis-authentik:
    driver: local
  authentik-media:
    driver: local
  authentik-certs:
    driver: local
  authentik-templates:
    driver: local
    
networks:
  authentik:
    internal: true
    name: authentik
  traefik_proxy:
    external: true
    name: traefik_proxy
```
