### ISSUE TITLE
Issues with Grafana

### ISSUE THREAD

**Issue by Spleenftw** [goauthentik/authentik#9004]
**Describe your question/**
I am following the authentik guide for grafana : https://docs.goauthentik.io/integrations/services/grafana/
I've properly created the application and the provider, modified my docker compose installation but still getting the issue of 
"Redirect URI Error
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)."\

What am i missing ?

**Relevant info**
Docker-compose file : 
```
version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik.hlb1.ovh"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "xxx"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "xxx"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.hlb1.ovh/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.hlb1.ovh/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.hlb1.ovh/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.hlb1.ovh/application/o/grafana/end-session/"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
    ports:
      - 3000:3000
    networks:
      network:
        ipv4_address: 172.23.0.201
    volumes:
      - grafana-volume:/var/lib/grafana
```

**Logs**
Grafana logs from the docker that may help :

```
logger=http.server t=2024-03-22T19:08:40.379496321Z level=error msg="Failed to parse user ID" error="identifier is not initialized"
logger=context userId=0 orgId=0 uname= t=2024-03-22T19:08:40.725441435Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.100.20.43 traceID=
logger=context userId=0 orgId=0 uname= t=2024-03-22T19:08:40.725498626Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.100.20.43 time_ms=0 duration=109.091µs size=102 referer= handler=/api/live/ws
logger=context userId=0 orgId=0 uname= t=2024-03-22T19:08:41.357404826Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.100.20.43 traceID=
logger=context userId=0 orgId=0 uname= t=2024-03-22T19:08:41.357466836Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.100.20.43 time_ms=0 duration=163.462µs size=102 referer= handler=/api/live/ws
logger=context userId=0 orgId=0 uname= t=2024-03-22T19:08:41.709263766Z level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=10.100.20.43 time_ms=0 duration=141.381µs size=307 referer=https://grafana.hlb1.ovh/login handler=/login/:name
logger=context userId=0 orgId=0 uname= t=2024-03-22T19:09:04.262248711Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=10.100.20.42 time_ms=0 duration=81.771µs size=29 referer= handler=/
logger=http.server t=2024-03-22T19:09:04.271275342Z level=error msg="Failed to parse user ID" error="identifier is not initialized"
 
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: docker-compose
