### ISSUE TITLE
Cookie error when using with the proxy container with forwardauth

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#910]
**Describe the bug**
Firefox gives me an error about wrong redirects when using it whit the proxy container. 

**To Reproduce**
1. Setting up a Authentik provider and application like PhotoPrism with dashboard.
2. Setting up the configuration with the containers an do an `up -d `command. 
3. Go the URL of the application.

**Expected behavior**
When setting up Authentik with the Authentik-proxy container, Firefox wont redirect to the right URL.

**Screenshots**
![app](https://user-images.githubusercontent.com/18529293/119124668-36c55d00-ba31-11eb-8b28-619a9f15605c.jpg)
![provider](https://user-images.githubusercontent.com/18529293/119124670-375df380-ba31-11eb-82a0-ad8253da5bbb.jpg)
![outpost](https://user-images.githubusercontent.com/18529293/119124671-375df380-ba31-11eb-8552-86df02f2e44a.jpg)

**Logs**

```
[2021/05/20 17:18:08] [logger.go:508] Error loading cookied session: cookie "authentik_proxy" not present, removing session
[2021/05/20 17:20:37] [logger.go:508] Error loading cookied session: cookie "authentik_proxy" not present, removing session
```

**Version and Deployment (please complete the following information):**
 - Authentik version: 2021.5.2
 - Deployment: Docker compose

**Additional context**

Looks like something is wrong with the headers? Can provides specific screenshots  when needed.

**Comment by BeryJu** [comment]
What domain does the outpost redirect you to? What have you configured in the proxy outpost? There was a bug that made it so when you changed either internal or external host in the proxy provider it wouldn't save correctly, thats fixed in 2021.5.3

**Comment by Akruidenberg** [comment]
Docker compose:

```
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2021.5.3
    hostname: authentik-proxy
    container_name: authentik-proxy
    restart: unless-stopped
    networks:
      - reverseproxy
    ports:
      - 4180:4180
      - 4443:4443
    environment:
      AUTHENTIK_HOST: https://authentik.$DOMAINNAME
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: 44ff92eaccb542e0876d21e80ee7d9dd
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.authentik-proxy-rtr.entrypoints: https
      traefik.http.routers.authentik-proxy-rtr.rule: Host(`authentik-proxy.$DOMAINNAME`) && PathPrefix(`/akprox/`)
      ## Middlewares
      traefik.http.middlewares.authentik-proxy-rtr.forwardauth.address: http://authentik-proxy:4180/akprox/auth?traefik
      traefik.http.middlewares.authentik-proxy-rtr.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik-proxy-rtr.forwardauth.authResponseHeaders: Set-Cookie,X-Auth-Username,X-Forwarded-Email,X-Forwarded-Preferred-Username,X-Forwarded-User
      ## HTTP Services
      traefik.http.routers.authentik-proxy-rtr.service: authentik-proxy-svc
      traefik.http.services.authentik-proxy-svc.loadbalancer.server.port: 4180     
      ## watchtower      
      com.centurylinklabs.watchtower.enable: "true"  

  photoprism:
    container_name: photoprism
    image: photoprism/photoprism
    restart: unless-stopped
    hostname: photoprism    
    env_file:
      - ./env/photoprism/photoprism.env
    networks:
      - reverseproxy
      - intern  
#    security_opt:
#      - no-new-privileges:true      
    environment:
      PUID: $PUID
      PGID: $PGID 
    volumes:
      - $ROOTDIR/foto:/photoprism/originals # [local path]:[container path]
      - $USERDIR/photoprism/Pictures/Import:/photoprism/import    # [local path]:[container path] (optional)
      - $USERDIR/photoprism/storage:/photoprism/storage     # Keep cache, settings and database   
    depends_on:
      - photoprism-mariadb      
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.photoprism-rtr.entrypoints: https
      traefik.http.routers.photoprism-rtr.rule: Host(`foto.$DOMAINNAME`)
      ## Middlewares
      traefik.http.routers.photoprism-rtr.middlewares: authentik-proxy-rtr@docker
      ## HTTP Services
      traefik.http.routers.photoprism-rtr.service: photoprism-svc
      traefik.http.services.photoprism-svc.loadbalancer.server.port: 2342
      ## watchtower      
      com.centurylinklabs.watchtower.enable: "true"     

```
First post will be updated with screenshots.
