### ISSUE TITLE
{"detail": "Request denied due to expired/invalid license.", "code": "denied_license"}

### ISSUE THREAD

**Issue by ruanbekker** [goauthentik/authentik#9292]
**Describe your question/**
I was trying to access Authentik as admin and I was returned with a error:

```
{"detail": "Request denied due to expired/invalid license.", "code": "denied_license"}
```

I believe this is due to multi-tenancy? I have followed https://docs.goauthentik.io/docs/advanced/tenancy and set `AUTHENTIK_TENANTS__ENABLED` to `false`. But that did not solve anything.

I would like to remove anything that is associated to enterprise so that I can access authentik's admin ui, but at the moment I cant. 

How do we go about getting out this issue?

**Relevant info**
- Chart version: `2024.2.2`
- Deployment: `helm`

**Screenshots**

<img width="635" alt="image" src="https://github.com/goauthentik/authentik/assets/567298/af1a6ad4-8631-4954-965b-d66cc4f85d07">

**Logs**

```bash
authentik-server-84dfd996f8-g7ntz server {"auth_via": "unauthenticated", "domain_url": "auth.x.x", "event": "Refusing request due to expired/invalid license", "host": "auth.x.x", "level": "warning", "logger": "authentik.enterprise.middleware", "pid": 43, "request_id": "1dad818b8e1a4b5cac4329ee733f5161", "schema_name": "public", "timestamp": "2024-04-16T16:35:42.334476"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: [ 2024.2.2 ]
-   Deployment: [ helm ]

**Additional context**

It might be a case that I was unaware that im using enterprise features, but I would like to disable it so that I can continue using it. Here is my helm values:

```yaml
authentik:
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - auth.x.x
      paths:
        - /
      pathType: Prefix
      tls:
        - secretName: x-x-x-tls
          hosts:
            - auth.x.x
      https: false
    env:
      - name: AUTHENTIK_TENANTS__ENABLED
        value: "false"

  authentik:
    log_level: info
    secret_key: "x"
    postgresql:
      host: "postgresql.databases.svc.cluster.local"
      name: "authentik_db"
      user: "postgres"
      password: "x"
      port: 5432
  postgresql:
    enabled: false
  redis:
    enabled: true
```
