### ISSUE TITLE
authentik outpost on different host

### ISSUE THREAD

**Issue by stephanschorer** [goauthentik/authentik#9399]
I have two servers with the following services
server1: authentik, nginx-proxy-manager, app1
server2: nginx-proxy-manager, authentik-outpost, app2

the servers are reachable like that:
server1: domain.com
server2: server2.domain.com

So I can access authentik on server1 with auth.domain.com

I want to use the authentik on server1 to authenticate the login to the app2 on server2.
I tried to deploy a authentik proxy to server2 with the token from authentik service on server1. That container is running fine.
```
version: "3.5"

networks:
  services_default:
    external: true
    name: services_default

services:
  authentik-outpost:
    image: ghcr.io/goauthentik/proxy
    container_name: authentik-outpost
    # Optionally specify which networks the container should be
    # might be needed to reach the core authentik server
    # networks:
    #   - foo
    #ports:
    #  - 9000:9000
    #  - 9443:9443
    environment:
      AUTHENTIK_HOST: https://auth.domain.com
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: 1X492
      # Starting with 2021.9, you can optionally set this too
      # when authentik_host for internal communication doesn't match the public URL
      # AUTHENTIK_HOST_BROWSER: https://auth.domain.com
    networks:
      - services_default
```

Now I create a provider in authentik on server1 like this:
type: Proxy
External host: app2.server2.domain.com
Internal host: http://app2:port

And then assign that provider to an app and to the outpost..

The container authentik-outpost on server2 is in the same network (services_default) as the app2 on server2, so they can reach each other!

On server2:
But if I then change nginx-proxy-manager to forward the traffic on app2.server2.domain.com to the container "authentik-outpost" I just get 502 Bad Gateway if I try to access: app2.server2.domain.com

Am I missing something?!

Please help me :)

Cheers
Stephan
