### ISSUE TITLE
Q: Using Postgres V16 in docker-compose instead of V12

### ISSUE THREAD

**Issue by 4d62ext** [goauthentik/authentik#9628]
I noticed in the docker-compose.yml file that the Postgres image is set to version 12. Is there any specific reason why a newer version isn't recommended in the Docker Compose file? Considering that [version 12 will reach its end of life in six months](https://endoflife.date/postgresql), would it be wise to create the database on version 16 or attempt to upgrade the current one? Also, how does this decision impact security?

**Comment by BeryJu** [comment]
The main reason why we haven't updated the postgres tag is because the upgrade procedure for postgres is a lot more manual than it is for redis or mysql. There aren't any new postgres features required by authentik either, but we test in CI with 12, 15 and 16. We will probably upgrade in the future, after we have some docs on how to upgrade too

**Comment by BeryJu** [comment]
I dont think there's too much to gain there, although I don't have any numbers for performance, but for security especially since postgres isn't exposed to anything there shouldn't be any issues

**Comment by appiekap653** [comment]
> I dont think there's too much to gain there, although I don't have any numbers for performance, but for security especially since postgres isn't exposed to anything there shouldn't be any issues

I don't believe this is exactly true when using the default docker-compose file from: https://goauthentik.io/docker-compose.yml

There is no use of separated networks in the compose file where the network for the Postgres container is set to: `internal: true` like this:

```
networks:
  external:
    name: external
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

  internal:
    name: internal
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1
```

So the Postgres container will have access to the outside internet with the default docker-compose file and can be vulnerable to attacks.
