### ISSUE TITLE
Cannot sign_out of Forwadh auth (Single application)  

### ISSUE THREAD

**Issue by info-path** [goauthentik/authentik#9939]
**Describe the bug**
Single app login is fully functional, but I can't log out. This address:
`https://homepage.domain.com/outpost.goauthentik.io/sign_out`

Generates an error:
`Application error: a client-side exception has occurred (see the browser console for more information).`

WebConsole:
```
Uncaught (in promise) SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at l._storageChangeDispatcher (content.js:2:855976)
    at _storageChangeDispatcherCallback (content.js:2:855424)
onCopyContentscript.js:157 A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
toolbarContentscript.js:113 {"message":"A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received"}
```

Note: `The` [gethomepage](https://gethomepage.dev/latest/) application, which does not have integrated user authentication.

**Expected behavior**
Ordinary logout from the session

**Version and Deployment (please complete the following information):**
-   authentik version: [e.g. 2024.4.2]
-   Deployment: docker-compose
-   Traefik v3 (Docker) as reverse proxy 

**Traefik config**
```
http:
  routers:
    homepage-public:
      middlewares:
        - authentik
      rule: "Host(`homepage.domain.com`)"
      priority: 10
      tls:
        certResolver: cloudflare            
      service: homepage-public
    homepage-auth:
      rule: "Host(`homepage.domain.com`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      service: authentik
  
  services:
    authentik:
      loadBalancer:
        servers:
          - url: https://192.168.30.30:9443/outpost.goauthentik.io
    homepage-public:
      loadBalancer:
        servers:
          - url: http://192.168.30.111:3000 #
  middlewares:
    authentik:
      forwardAuth:
        address: http://192.168.30.30:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
What could be the problem?
